### ISSUE TITLE
Insert Text, lost focus

### ISSUE THREAD

**Issue by sstaub** [platformio/platformio-atom-ide-terminal#1]
When using the Insert Text function and you click with the  mouse outside the small input window,
you can't close it with ESC because you lost the focus. You must click on to the textfield! again to get the focus back.
It will be better when you can close the Insert Text window without having a focus on the textfield.
##

**Comment by ivankravets** [comment]
Thanks a lot for the report. We will fix it later. 

How is your general impression from this Terminal and PlatformIO IDE 1.0.0 ?

**Comment by sstaub** [comment]
I really like this IDE and also the new Terminal. It is a great help for working
with mbed and a very great work from you.
I tried also the new IDE with installer, wow. One thing that could be better is
the possibility to download the platforms (mbed, arduino …) directly after downloading
as an optional installation process or/and as a Menü, so that you can start directly offline.
The next killer feature, debugger???

sstaub

**Comment by ivankravets** [comment]
Thanks! :blush: 

> I tried also the new IDE with installer, wow. One thing that could be better is
> the possibility to download the platforms (mbed, arduino …) directly after downloading
> as an optional installation process or/and as a Menü, so that you can start directly offline.

Please open an issue for that in PlatformIO IDE repo

> The next killer feature, debugger???

You are reading our thoughts :smile_cat:
