### ISSUE TITLE
[FR] select with scroll then copy

### ISSUE THREAD

**Issue by farfromrefug** [platformio/platformio-atom-ide-terminal#10]
I really like your implementation and would like to use it with the atom-build package.
Now there is some little things i miss. 
The biggest thing i miss is the way of selecting text beyond the view area.
Either by selecting, moving the mouse up or down to start scrolling, or by clicking at one place, scroll, then use shift-click to select.
##

**Comment by clayms** [comment]
This would be great!

**Comment by clayms** [comment]
Based on:
https://github.com/platformio/platformio-atom-ide-terminal/blob/dcd4e41ea9939d84ce9b9526610a1b184c1f8dda/lib/view.coffee#L5

Would it be more of a enhancement to `term.js`  [project](https://github.com/chjj/term.js)?  However, that project's readme says "⚠️This project is no longer maintained ⚠️. For a maintained fork take a look at sourcelair/xterm.js." 

Or a feature enhancement of the `xterm.js` [project](https://github.com/xtermjs/xterm.js) ?

https://github.com/platformio/platformio-atom-ide-terminal/blob/dcd4e41ea9939d84ce9b9526610a1b184c1f8dda/lib/view.coffee#L37

https://github.com/platformio/platformio-atom-ide-terminal/blob/dcd4e41ea9939d84ce9b9526610a1b184c1f8dda/lib/view.coffee#L70

https://github.com/platformio/platformio-atom-ide-terminal/blob/dcd4e41ea9939d84ce9b9526610a1b184c1f8dda/lib/view.coffee#L137

... and more.

**Comment by farfromrefug** [comment]
@clayms i won't follow up on this. I don't use atom anymore
Sorry

**Comment by the-j0k3r** [comment]
This kinda works (YMMV) works since https://github.com/platformio/platformio-atom-ide-terminal/pull/525 was merged and OP no longer using Atom.

close?
