### ISSUE TITLE
Security Issue: Heur.AdvML.B

### ISSUE THREAD

**Issue by chrissng** [platformio/platformio-atom-ide-terminal#101]
One of the packages `pty.js` used in this package has a security issue that was flagged out by Symantec Endpoint Protection on my Windows system:

```
Category: Quarantine
Date & Time,Risk,Activity,Status,Recommended Action,Path - Filename
9/11/2016 4:54:36 PM,High,winpty-agent.exe (Heur.AdvML.B) detected by Auto-Protect,Quarantined,Resolved - No Action Required,c:\users\chrissng\.atom\packages\platformio-ide-terminal\node_modules\pty.js\build\release\winpty-agent.exe
```

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0 is using node-pty-prebuilt instead unmaintained and outdated pty.js
