### ISSUE TITLE
Mouse selection will not highlight in terminal

### ISSUE THREAD

**Issue by shrabok-surge** [platformio/platformio-atom-ide-terminal#102]
Whenever I try to select text to copy using the mouse it will not highlight the selection. You can still select the content and copy/paste. There is no indication of what has been selected.

OSX 10.11.6
Atom 1.11.2
Platformio-ide-terminal 2.2.1

**Comment by yelfathi** [comment]
I have a similar issue where I defined a selection background-color and the colour coded in styles.less is not the same colour rendered in the terminal.

**Comment by alsGitHub270** [comment]
I have the same issue.  Doesn't matter the theme I use, I cannot highlight anything in the terminal, especially for copy/pasting.  Nothing gets highlighted, nothing gets copied.

Mac Sierra 10.12.6
Atom  1.22.1  x64
Platform-ide-terminal 2.7.0

**Comment by ddellamico** [comment]
+1

**Comment by liamdkane** [comment]
Has anyone found a solution for this?

**Comment by shrabok-surge** [comment]
@liamdkane 

I ended up overwriting the config file for solarized-dark.less with my own color scheme since no one really resolved this.

If you go to Settings -> Packages -> patformio-ide-terminal (click on package) and below see "View Code"

It will open another project and I change the file under:
platformio-ide-terminal
- styles
  - themes
    solarized-dark.less

and I paste in this color scheme
```
.solarized-dark {
  background-color: #1d1f21;
  color: #708284;

  ::selection {
    background-color: #8f7799;
  }

  .terminal-cursor {
    background-color: #819090;
  }
}
```

This fix needs to be done after every upgrade to that package though.
These are some custom color schemes I came up with after experimenting, but they are not solarized colors and i'm not sure what they should be.

**Comment by shrabok-surge** [comment]
Also I did some more messing around, and found `background-color: #252931;` is a close match to the editor window and makes the terminal feel alot like the atom dark theme which is what I was attempting to accomplish with my settings.

**Comment by shrabok-surge** [comment]
Also tried to fix the actual solarized colors and this is as close as I got to a "solarized-dark" solution:
```
.solarized-dark {
  background-color: #042029;
  color: #708284;

  ::selection {
    background-color: #839496;
  }

  .terminal-cursor {
    background-color: #819090;
  }
}
```

**Comment by alsGitHub270** [comment]
Neither had an effect.  And I tried various different themes.

**Comment by shrabok-surge** [comment]
I ended up fixing both the solarized-dark and one-dark themes as per the merged PR associated with this ticket. I'm going to close this ticket.

**Comment by shrabok-surge** [comment]
@alsGitHub270 whats not taking effect. If you are referring to manually modifying the themes, you need to modify the theme you selected. You also need to save and quit all running atom instances so the changes take effect on next start.

**Comment by chrismcband** [comment]
This was also not working for me, but I think I found the issue. I have the Nuclide package installed. When this is enabled text selection doesn't work in the terminal. When I disable Nuclide, mouse selection in the terminal works again.

**Comment by vincent-young-1701** [comment]
I'm also having the issue of mouse selection not working when Nuclide is installed.  Anyone found a workaround?

**Comment by chrismcband** [comment]
@vincent-young-1701 not really a workaround, but I started using the nuclide-terminal. I didn't realise they had one in the package. It's not as nice and it doesn't have a button to start it but it does work and more importantly text selection works in it. Use CMD-shift-p and search for terminal and you'll spot it.

**Comment by verswu** [comment]
+1 on mouse selection not working with Nuclide.

**Comment by fabien88** [comment]
will fix the problem if you have nuclide installed:
`rm -r ~/.atom/packages/nuclide/pkg/nuclide-terminal`  then restart atom 

Edit: with the new version of nuclide (0.299.0) it's now `mv ~/.atom/packages/nuclide/modules/atom-ide-ui/pkg/atom-ide-terminal/styles/nuclide-terminal-view.less ~/.atom/packages/nuclide/modules/atom-ide-ui/pkg/atom-ide-terminal/styles/nuclide-terminal-view.less.old`

**Comment by shantdashjian** [comment]
In my case it was the ink package. I disabled it and selection in the terminal worked as expected.

**Comment by KevCaz** [comment]
Had the same issue, disabling `ink` worked for me (Debian 9 / Atom 1.2.3 / Ink 0.8.2 / Plaformio 2.8.0 for the records).

**Comment by khaledalyawad** [comment]
I don't have the nuclide-terminal I have atom-ide-ui installed. And my selection highlight wasn't working, I have platformio-atom-ide-terminal installed

My solution was:

I went the atom-ide-ui/modules/atom-ide-ui/pkg/ and I deleted the atom-ide-terminal folder 

then restarted Atom 

Worked for me!

**Comment by Buchtanen** [comment]
just disable terminal feature under atom-ide-ui
