### ISSUE TITLE
Issue inserting multi-line code from editor

### ISSUE THREAD

**Issue by EisenRa** [platformio/platformio-atom-ide-terminal#1024]
- [x] I have reset Atom to defaults prior to submitting report.
- [ ] I have not reset Atom to defaults prior to submitting report.
### Description

The 'insert-selected-text' command is inserting a newline between each line of code, meaning I can't run multi-lined code (separated by '\') from the editor. I also get the same issue when copy-pasting multi-line code from the editor into the terminal too.

### Steps to reproduce

```
echo hi \
ho \
hum
```

**Expected behavior:** 
`hi ho hu`

**Actual behavior:** 
```
>hi
>
>ho \
>
ho: command not found
> hu
hu: command not found
>
```

**Reproduces how often:**  Every time

### Versions

```
> atom --version
1.58.0
```
```
> apm --version
2.6.2
```
OS name and version: Windows 10
Platformio-ide-terminal version: 2.10.1

**Comment by UziTech** [comment]
This package is no longer maintained. Please uninstall platformio-ide-terminal and install either [terminus](https://atom.io/packages/terminus) or [x-terminal](https://atom.io/packages/x-terminal)
