### ISSUE TITLE
LSOpenURLsWithRole() failed for the application /Applications/Atom.app with error -10810

### ISSUE THREAD

**Issue by jbrodriguez** [platformio/platformio-atom-ide-terminal#103]
I'm getting this error after updgrading to the latest version ...

I have the following script to assist in git-plus dealings
```bash
#!/usr/bin/env bash

# Get the location of the file to edit from Git.
FILE_TO_EDIT="$1"

# If the file we're editing is a commit message, we can assume Atom is set up
# to insert the magic token when the editor closes. Otherwise, we need to let
# Atom tell Git when it is done.
#
if [[ $(basename "$FILE_TO_EDIT") == "COMMIT_EDITMSG" || $(basename "$FILE_TO_EDIT") == "git-rebase-todo" ]]
then
  # Tell Atom to open the file in an existing window.
  atom "$FILE_TO_EDIT"

  # Wait for Atom to write the magic marker - ##ATOM EDIT COMPLETE## - to signal
  # that the editor has been closed.
  #
  tail -f "$FILE_TO_EDIT" | while read LOGLINE
  do
    [[ "$LOGLINE" == "##ATOM EDIT COMPLETE##" ]] && pkill -P $$ tail
  done

else
  # Tell Atom to open the file in a new window and report when it is finished.
  atom --wait "$FILE_TO_EDIT"
fi
```

platformio was working fine before the upgrade

**Comment by mikebelanger** [comment]
I am having the same issue -- also had the problem when upgrading to latest Atom version (v.1.12.2), on latest OS X (10.12.1).  Steps to reproduce:
1.  Launch Atom and in the menu, Go `Atom` >> `Install Shell Commands`. 
2.  Open a new platformio-atom-ide-terminal window, and enter `atom`.  I get the following error:

`LSOpenURLsWithRole() failed for the application /Applications/Atom.app with error -10810.`

My hunch is there's a permissions issue occurring.  If I run `sudo atom`, atom launches perfectly fine within this terminal emulator.

**Comment by drorata** [comment]
I have the same problem. Cannot run `atom` from `platformio-atom-ide`; getting `LSOpenURLsWithRole() failed for the application /Applications/Atom.app with error -10810.`

**Comment by malikshubham827** [comment]
@jbrodriguez Do you know the version number in which this update was pushed? Maybe we could use the previous version and get our work done.

@mikebelanger  I tried using 
`sudo atom hello.html` 
but I got two windows running at the same time and these two errors too:
![screen shot 2016-12-05 at 1 48 58 pm](https://cloud.githubusercontent.com/assets/13511528/20878011/4d1e5c0c-baf2-11e6-8512-96533ea586f2.png)

**Comment by BenSjoberg** [comment]
It seems to work if you run `atom` with no environment variables defined. As a workaround, I put the following in my .bash_profile: `alias atom='env -i /usr/local/bin/atom'`
