### ISSUE TITLE
Settings button not present on Windows 7

### ISSUE THREAD

**Issue by alayek** [platformio/platformio-atom-ide-terminal#104]
Hi,

I am trying to override default shell with my Git Bash exe on Windows 7. But I am not seeing any button for settings where I can override the shell

![no_settings](https://cloud.githubusercontent.com/assets/5607371/20264968/4224ca48-aa94-11e6-8657-2f8315cf9d00.png)

Is this a known issue?

Here is my apm -v output
```bash
apm  1.12.9
npm  3.10.5
node 4.4.5
python 2.7.10
git 2.10.2.windows.1
visual studio
```

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0 is using node-pty-prebuilt instead unmaintained and outdated pty.js
