### ISSUE TITLE
Switch from code to terminal without toggling off and on

### ISSUE THREAD

**Issue by dgerosa** [platformio/platformio-atom-ide-terminal#107]
Hello,
I would like to switch from the code to the terminal with the keyboard, while keeping the terminal visibile.  Right now it looks to me one has to hit ctrl-` twice and toggle the terminal off and on again.
Thanks for your work, this package is great.
Davide

**Comment by laubblatt** [comment]
This feature would make Atom really useful!

**Comment by YujiShen** [comment]
Duplicate #62

**Comment by the-j0k3r** [comment]
`ctrl`+`alt`+`f` does it. or command platformio-ide-terminal:focus
