### ISSUE TITLE
macOS: Disable accent menu / enable repeat on similarly to text editor

### ISSUE THREAD

**Issue by skull-squadron** [platformio/platformio-atom-ide-terminal#109]
### Actual Behavior

- Hold <kbd>e</kbd>, get a character accent menu asking for which variant of `e`

![img](https://camo.githubusercontent.com/4e4aa24da4af8b553458b2b594d2c2cafd2809a7/687474703a2f2f636f6e74656e742e73637265656e636173742e636f6d2f75736572732f787a787a787a78782f666f6c646572732f4a696e672f6d656469612f36383164363661392d386464332d343931622d383031302d3838333134646438666462662f30303030303036332e706e67)

### Expected Behavior

- Hold <kbd>e</kbd>, `eeeeeeeeee`

### Impact

- It makes most text editors and interactive CLI apps very painful.

### Nonviable solutions

- Changing system defaults.

### Possible implementation notes

The text editor uses a webkit hack possibly by extending the selection but it maybe just be setting the focus back to the editor view, causing the accent menu to dismiss (it may flicker but it goes away).

It seems like this should be default behavior, but able to be set to the previous behavior.

- https://github.com/atom/atom/blob/master/src/selection.coffee
- https://github.com/atom/atom/blob/master/src/text-editor.coffee
- https://github.com/atom/atom/blob/master/src/text-editor-component.coffee

### Long-term (not) solutions

I've asked electron/chromium folks if they might consider a `-webkit-*` style property like `-webkit-character-accent-menu: none` to avoiding having to set any key event handlers.

**Comment by the-j0k3r** [comment]
I cant duplicate this in macOS Mojave 10.14.2 it works as intended and perfectly.
