### ISSUE TITLE
Atom does not update Git change highlighting when Git commands are issued from terminal

### ISSUE THREAD

**Issue by toasty-sunbeam** [platformio/platformio-atom-ide-terminal#115]
Hello! This is purely a cosmetic issue, but it bugs me every day. One of the reasons I love this addon is that it opens to the folder I'm already working in. There's no need to `cd` deep into my directory structure. Among other things, this makes it perfect for committing changes in Git. 

Unfortunately, when I do so, all of Atom's great change highlighting (both of line numbers and of files in the tree) does not update. I have to close and re-open each file before Atom will notice they've changed. Is there some way to "nudge" Atom after Git commands so it will notice that the status of the repository has changed?

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0.
These type issues all so far seem fixed with this release due to using node-pty-prebuilt instead unmaintained and outdated pty.js
