### ISSUE TITLE
resizing terminal does not work properly when ssh from terminal

### ISSUE THREAD

**Issue by jzthree** [platformio/platformio-atom-ide-terminal#116]
If I resize a terminal window after ssh login into another machine, the 'full-screen' programs like vi or top won't display properly. My setup is Windows + git shell. I haven't tested on other platforms so I don't know whether this problem is platform specific.

**Comment by 3ynm** [comment]
It happens to me too. I'm using Arch linux.

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0 is using node-pty-prebuilt instead unmaintained and outdated pty.js
