### ISSUE TITLE
PlatformIO: Terminal service is not registered.

### ISSUE THREAD

**Issue by upeshjindal** [platformio/platformio-atom-ide-terminal#117]
I cannot run terminal from PlatformIO while clicking the terminal button. There is this error that pops out. Screenshot attached.

Operating system: Ubuntu 16.04 LTS
Atom Version: 1.12.6
PlatformIO-IDE Version: 1.7.1, Core: 3.1.0
Platform-ide-terminal version: 2.2.2

I tried uninstalling platform-ide-terminal and installing again but it doesn't work.

![terminal error](https://cloud.githubusercontent.com/assets/13344598/20912393/9e3e5960-bb34-11e6-8beb-b394e4e2663e.png)

**Comment by ivankravets** [comment]
Please click on ⚙ icon and follow to Plugins section. Click on `Uninstall` button for PlatformIO IDE Terminal. Reinstall this package again using Atom package manager.

**Comment by upeshjindal** [comment]
I tried it just now. The issue still remains.

**Comment by alfredocdmiranda** [comment]
I am facing the same issue

**Comment by ivankravets** [comment]
Do you see `+` icon in a bottom status bar? Could you click on it? Does Terminal work?

**Comment by upeshjindal** [comment]
Hi Alfredo/Ivan,

I tried uninstalling and installing again today. Surprisingly, it worked. There is nothing different that I did except downloading the latest copy of platformio.

Upesh

**Comment by Fenix999** [comment]
I don't know if it wil help, but I had the same problem and I noticed that I got a bug icon on the bottom right corner pressed and there was a ploblem with the terminal "../bin/linux/x64.m49.node", and there was a option to rebuild that I did, then restarted atom and terminal now works.

**Comment by ivankravets** [comment]
@Fenix999 what is your OS?

**Comment by Fenix999** [comment]
Ubuntu 16.04

**Comment by ivankravets** [comment]
@Fenix999, please open `View > Developer > Developer Tools` and paste this in console `process.versions.modules`. Which version do you see?

**Comment by Fenix999** [comment]
Hi,

@ivankravets I get 49.

I can try to uninstall everything to see if I can replicate the problem.

This is my first install of atom and I just do it for fun, so sorry if I can't help much.

**Comment by ivankravets** [comment]
@Fenix999 how did you install Atom? using built-in OS package manager or from Atom's deb package?

**Comment by Fenix999** [comment]
@ivankravets  By adding the following repository add-apt-repository ppa:webupd8team/atom

**Comment by ivankravets** [comment]
Could you try official deb from https://github.com/atom/atom/releases/tag/v1.12.7 ?

**Comment by Fenix999** [comment]
The terminal now works, do you want me to do it just for test purposes? If yes, give me 1 hour.

**Comment by ivankravets** [comment]
Have you installed `gcc` before this issue?

**Comment by Fenix999** [comment]
Not that I'm aware.

**Comment by Fenix999** [comment]
@ivankravets I did like you suggested, using the official deb and it worked, the terminal worked first time.

any clues on the issue?

**Comment by danielbibit** [comment]
I'm having the exactly same issue. 
Os: Fedora 25 
Atom version: 1.12.7
Platformio: IDE 1.7.1 | Core 3.2.1

i tried unistalling platformio, atom, just the terminal, but nothing works... I'm sure i have gcc installed. Any ideas ?

**Comment by michaelkrone** [comment]
I faced the same issue. In the "Incompatible Packages" section, `platformio-ide-terminal` was listed as "Build for older versions of Atom" and offered a "Rebuild" button. After clicking "Rebuild" and reloading Atom it works.

**Comment by marble** [comment]
I could solve it for me in this way: https://github.com/platformio/platformio-atom-ide/issues/196#issuecomment-275931433

**Comment by cristianszwarc** [comment]
@michaelkrone thanks, same issue here, same solution, cheers

**Comment by sabatmonk** [comment]
I have the same problem (Terminal service is not registered) on a fresh install of platformIO on Atom 1.36. Running linux.

**Comment by the-j0k3r** [comment]
@sabatmonk Thank you for reaching out with that issue report.

This ticket is outdated, it has no information about the supposed issue, if you have platformio-ide installed remove it, if you have platformio-ide-terminal installed, uninstall it via apm and re-install it.

If issue persists, please reopen a new ticket, filling in all fields without exception and add as much information as possible to the extra information field. Things like saying Linux are very vague, we need actionable information to try duplicate issue.

Thank you.
