### ISSUE TITLE
package not respond after a period of time

### ISSUE THREAD

**Issue by cyjj** [platformio/platformio-atom-ide-terminal#118]
atom version:1.12.6
system:Mac osx
after I weak up my notebook from sleep, the package act wired and not respond soon. At first, I just can't hide one terminal, then I can't open previous one or new one. I don't find any error info. Plz help with this situation. It will be a trouble if I need to reboot every time.  THX for sharing this package again.

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0 is using node-pty-prebuilt instead unmaintained and outdated pty.js
