### ISSUE TITLE
Terminal hangs on open with Atom 1.7.0

### ISSUE THREAD

**Issue by ayan4m1** [platformio/platformio-atom-ide-terminal#12]
Environment is Windows 10 Home en-US. After upgrading to Atom 1.7.0, the Terminal window no longer functions as expected. Prior to the upgrade, I could open the terminal view from the PlatformIO dropdown or the icon in the toolbar. Now, the view opens and displays a bg color, but does not run a terminal and the Windows "wait cursor" appears whenever the mouse is over the terminal view.

**Comment by ayan4m1** [comment]
Haven't delved too deep into it, but try looking here?

https://github.com/platformio/platformio-atom-ide-terminal/blob/master/lib/process.coffee#L16

I bet _.omit does something funky with those keys.

**Comment by ivankravets** [comment]
1. Please install the latest Atom 1.7.0.
2. Apply this patch https://github.com/platformio/platformio-atom-ide/commit/2ef99acd3d5711d84ffac761747556bf4d357731 to `platformio-ide` package. Go to `c:\Users\**\.atom\packages\platformio-ide` and replace `/lib/main.js` file by https://raw.githubusercontent.com/platformio/platformio-atom-ide/develop/lib/main.js.
3. Restart Atom.

Does it work now?

**Comment by ayan4m1** [comment]
Doesn't appear to on my system. I manually patched platformio-ide main.js as you described which fixes Atom 1.7.0 (the indexOf init failure) - open the terminal and it still hangs in the same way.

EDIT: Starting to debug... `process.env.SystemRoot`

https://github.com/platformio/platformio-atom-ide-terminal/blob/master/lib/platformio-ide-terminal.coffee#L71

Dumping process.env at that point, I have `SYSTEMROOT: "C:\WINDOWS"`

**Comment by ivankravets** [comment]
I have the same problems...

**Comment by viktak** [comment]
Same here. Platformio starts OK, but the terminal/serial monitor freezes.

**Comment by ivankravets** [comment]
PlatformIO-IDE Terminal 2.0.4 has been released. Please update it.
