### ISSUE TITLE
question: copy selected text

### ISSUE THREAD

**Issue by ellerbrock** [platformio/platformio-atom-ide-terminal#123]
hi there,

first at all thanks for your great work, love your terminal!
i searching now quite a while and did not get any response on stackoverflow that why i ask you as developer directly (sorry for opening a issue for that). i miss one feature which makes me crazy.
i'm so used to the feature from iterm2 which copy the selected text to the clipboard.

is it possible to do this without rewriting your plugin?

i did not yet write plugins for atom so i'm not sure how i could get this done.
my first thinking was if there is something like a keyboard setting like:

```yaml
'.platformio-ide-terminal .xterm':
  'selection':  ...
```
if its not possible this way what would be the right way to implement such a feature?

atom have i guess all i need with:
- <https://atom.io/docs/api/v1.1.0/Clipboard>
- <https://atom.io/docs/api/v1.1.0/Selection>

what is the preferred way of implementing such a feature?
can i make a hook / extension for your terminal plugin or how to do it best?

thanks a lot 

cheers maik

**Comment by Barbayar** [comment]
Sent a PR for you, my friend.
https://github.com/platformio/platformio-atom-ide-terminal/pull/174

**Comment by ellerbrock** [comment]
very cool, looking forward to get this feature finally in atom too
