### ISSUE TITLE
insert selected text don't proceed to the next line when wraping

### ISSUE THREAD

**Issue by sdaza** [platformio/platformio-atom-ide-terminal#124]
When text is wrapped, the next line move of the insert-selected-text command (without selected text)  doesn't work. 

![](https://dl.dropboxusercontent.com/u/18116710/Screenshots/Screenshot_2016-12-14_10.24.30.png)

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0 is using node-pty-prebuilt instead unmaintained and outdated pty.js
