### ISSUE TITLE
classpath for java file execution

### ISSUE THREAD

**Issue by mohit-dhiman** [platformio/platformio-atom-ide-terminal#126]
i'm not able to set classpath variable through this terminal.
but the same command i'm using to set classpath is working just fine in windows command prompt.

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0.
These type issues all so far seem fixed with this release due to using node-pty-prebuilt instead unmaintained and outdated pty.js
