### ISSUE TITLE
Error trying to open files with atom command

### ISSUE THREAD

**Issue by jwerre** [platformio/platformio-atom-ide-terminal#128]
$ atom ~/.bashrc
    LSOpenURLsWithRole() failed for the application /Applications/Atom.app with error -10810.

**Comment by tobiasger** [comment]
I have the same problem. Exactly the same error message. Running on macOS Sierra 10.12.

**Comment by DamnedScholar** [comment]
I've opened an issue [on the Atom repo](https://github.com/atom/atom/issues/13624).
