### ISSUE TITLE
Atom Integrated Terminal does not behave the same as Windows CMD outside of Atom

### ISSUE THREAD

**Issue by kickthedragon** [platformio/platformio-atom-ide-terminal#135]
So this is a very strange error that's occurring for me.  The integrated terminal in atom does not behave the same way as CMD or windows PowerShell outside of Atom.

Background Info:  I'm developing a nodejs app with yeomen's angular-fullstack generator.  My work computer at home runs linux where this package works perfectly as expected.  But my workstation at work runs Windows 10 and figured this package would behave the same way.  I've also tried configuring the integrated platform ide terminal to test both the Windows Powershell and CMD to make sure the same error is reproduced and I can confirm the issue is whether or not the terminal being used is integrated in Atom or running separately.  

Problem:  When I run `gulp serve` or `npm install` with platform-ide configured to use CMD.exe or PowerShell.exe within atom, the command does not perform as expected.  If i run either command in their respective independent application / window (cmd.exe or plowershell.exe) the commands work perfectly (just as if I was in a linux bash).  But when I use your package within atom  and configured to use either shell,  `npm install` does not completely install all the modules (specifically non of the dev dependencies).  So I ran `npm install` in a separate cmd.exe which installed all the modules to see if this was the only issue, but when when I run `gulp serve` within the platform-ide terminal i get a syntax error saying `Unexpected token` and its highlighting `import express from express` .  This does not happen when i run `gulp serve` in a cmd.exe or windows powershell.exe independently, my nodejs app launches as expected.  

Let me know if theres any logs or anything else i can contribute to debug this.  Having a terminal within atom is highly convenient so if this is a quick fix i'd love to make sure i give you enough info to do it.  The package works perfectly on my linux box.

**Comment by isaklafleur** [comment]
Same error here...

Running for example ng new command it does not install all required modules in "node_modules"-folder. When I run it from the Windows 7 default Command Prompt it install them all.

**Comment by woffleloffle** [comment]
This could have something to do with #207.

**Comment by savovsky** [comment]
I've observed same error with 2.5.0 package when trying run express within Atom platformio terminal . 
``` terminal
events.js:160
      throw er; // Unhandled 'error' event
      ^
 
Error: listen EACCES $PORT
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at Server._listen2 (net.js:1249:19)
    at listen (net.js:1298:10)
    at Server.listen (net.js:1387:5)
    at Object.<anonymous> (C:\Projects\jira-stackedchart-plugin\app.js:74:24)
    at Module._compile (module.js:570:32)

    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:393:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:508:3
```
Outside Atom in console or powershell works just fine on Windows 7 and 10. It has nothing in common with busy port which is misleading from the stack trace.  It will be great if fixed because there might be other hidden side effects that decrease my confidence in using the terminal even though I find it very handy.

**Comment by Naikno** [comment]
I have a similar issue using powershell or cmd: when i try to exec any `atom` commands for example `atom --help` nothing happens , the same commands works in pshell or cmd outside platformio-terminal.
any suggestion?

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0.
These type issues all so far seem fixed with this release due to using node-pty-prebuilt instead unmaintained and outdated pty.js
