### ISSUE TITLE
Cannot type ctrl-\

### ISSUE THREAD

**Issue by ksmithbaylor** [platformio/platformio-atom-ide-terminal#137]
Great work with this project! This is so useful to me.

I use `ctrl-\` (control-backslash) as my tmux prefix, and I was hoping to run tmux inside this terminal. However, something seems to be blocking this specific control sequence (`\u001C`, or `FS`) from making it to the terminal emulator. Most other control sequences I tried worked fine.

It may be an issue with the underlying term.js or pty.js libraries, but if anyone has ideas on where to start debugging, it would be much appreciated.

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0 is using node-pty-prebuilt instead unmaintained and outdated pty.js
