### ISSUE TITLE
Theme Conflict with Fishshell?

### ISSUE THREAD

**Issue by MVSICA-FICTA** [platformio/platformio-atom-ide-terminal#139]
I've installed this terminal package for atom because terminal-plus no longer had a prompt. For my shell I'm using fishshell 2.4.0 and I can see the theme I choose via fish_config in the standard OSX terminal, yet in atom running the platformio-atom-ide-terminal I do not see the theme I picked with fish_config. Then there are the themes that come with platformio-atom-ide-terminal, which also do not seem to be working.

How can I get my terminal to be happy (getting properly themed) in atom?

**Comment by josiekre** [comment]
I also use fish and am having no luck applying the themes that come built-in.

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0 is using node-pty-prebuilt instead unmaintained and outdated pty.

Also platformio-ide-terminal themes cant be applied to open terminals, close terminal > apply theme > reopen.
