### ISSUE TITLE
Terminal doesn't start. Maybe Xorg related

### ISSUE THREAD

**Issue by jmscaramal** [platformio/platformio-atom-ide-terminal#14]
Recently, I've Installed Atom and Platformio-ide. Everything seems to work fine. However, when I try to start the terminal (+), I get the following message:

> /usr/lib/xorg-server/Xorg.wrap: Only console users are allowed to run the X server
> xinit: giving up
> xinit: unable to connect to X server: Connection refused
> xinit: server error
> Couldn't get a file descriptor referring to the console

I've already tried to create the /etc/X11/Xwrapper.config file with the "allowed_users=anybody" line. But still, the terminal doesn't launch. When I try with the Xwrapper.config file, seems like the startx command being executed, and a new session of xorg starts.  

I'm not sure if it is a platformio or my system problem. Anyway, any help would be appreciated.

[Enter steps to reproduce below:]

...
...
Atom Version: 1.7.1-1
System: linux 4.4.5-1-ARCH
Thrown From: platformio-ide package, v1.1.2

**Comment by jmscaramal** [comment]
Just did a fresh install of my Arch system and It worked like a charm!

**Comment by JatraMaya** [comment]
Ok, I recently encounter this bug, my solution is not as extreme as @jmscaramal the only thing I do is unchecked the `Login Shell` option it's as simple as that.

hope this will help other people that encounter the same bug.
