### ISSUE TITLE
ctrl-enter does not work

### ISSUE THREAD

**Issue by xigua5** [platformio/platformio-atom-ide-terminal#141]
my atom is 1.12.7
when i select the text 'ls' and press ctrl+enter.it does not work . just go to a new line in the editor

**Comment by AndyXD** [comment]
same issue for me

**Comment by ghost** [comment]
+1, though it seems that yet another fork is no longer maintained..

**Comment by davidrosson** [comment]
I had this issue also, but I fixed it by remapping my keybindings from 'ctrl-enter' to 'ctrl-alt-enter' in Atom's 'keymap.cson' file (Atom -> Keymap...):

```
'.platform-darwin atom-workspace':
  'ctrl-alt-enter': 'platformio-ide-terminal:insert-selected-text'
```

In my case, there was a keybinding conflict with a recently-installed package called "intentions 1.1.2" from "steelbrain" (the linter folks). I can't remember exactly, but I think this package was a new dependency when I recently updated my linter package (and that's also when 'ctrl-enter' stopped working). You can either creating a new keybinding like I did, or just disable the default keybindings for whichever package is causing the conflict. You can check 'Atom -> Preferences... -> Keybindings' to see which other package is using 'ctrl-enter' as a keybinding.

**Comment by atongsa** [comment]
i follow @davidrosson  advice ; get solved the pro;   thanks @davidrosson ;

and i am on linux ubuntu 16.04 ; my keymaps is below:
    '.platform-linux atom-workspace, .platform-win32 atom-workspace':
  'ctrl-alt-enter': 'platformio-ide-terminal:insert-selected-text'

**Comment by angiemarie** [comment]
This worked for me:
'atom-workspace atom-text-editor:not([mini])':
  'ctrl-alt-enter': 'platformio-ide-terminal:insert-selected-text'

**Comment by rammurti84** [comment]
nothing working for me

**Comment by symonty** [comment]
Created a PR, worked for me.
https://github.com/platformio/platformio-atom-ide-terminal/pull/534

**Comment by atongsa** [comment]
Ubuntu 18.04 LTS

edit keymap banding

```
# add platform-ide
'atom-workspace atom-text-editor:not([mini])':
  'ctrl-enter': 'platformio-ide-terminal:insert-selected-text'
```
