### ISSUE TITLE
Request: Jump to terminal with short command

### ISSUE THREAD

**Issue by tobiasger** [platformio/platformio-atom-ide-terminal#145]
I think it would be great if you could press a short command for just jumping to the terminal (if it's open) and making it focused. I can enter `ctrl + shift + ´`, but that will only toggle the terminal. So if I already have the terminal open, it will then close when I press `ctrl + shift + ´`.

I've tried to find this short command but I haven't found it. Please let me know if this is already existing.

**Comment by RomanADavis** [comment]
The best I've managed is just pressing ctrl + ` twice. It's a little slow, but if I was already a super efficient hacker I'd probably be using emacs.
