### ISSUE TITLE
Can't use Atom command from platformio-ide-terminal in atom

### ISSUE THREAD

**Issue by RomanADavis** [platformio/platformio-atom-ide-terminal#146]
Crossposted here: https://discuss.atom.io/t/opening-a-file-from-a-terminal-in-atom/38213

Not sure if this is on your end or Atom's. Would certainly be handy to be able to open and edit my powershell $profile instead of having to open a seprate powershell instance just to open the file.

**Comment by DamnedScholar** [comment]
I've opened an issue [on the Atom repo](https://github.com/atom/atom/issues/13624).

**Comment by jamespayne** [comment]
I have exactly the same problem. I'm getting this message:

    LSOpenURLsWithRole() failed for the application /Applications/Atom.app with error -10810.

On Mac OSX Sierra 10.12.2 (16C67). IIRC it did work a while ago. Look forward to a fix for this. Thanks!
