### ISSUE TITLE
Object.dirname is deprecated.

### ISSUE THREAD

**Issue by cameflow** [platformio/platformio-atom-ide-terminal#148]
Argument to `path.dirname` must be a string
```
Object.dirname (/Applications/Atom.app/Contents/Resources/app.asar/src/electron-shims.js:9:10)
<unknown> (/Users/Alex/.atom/packages/platformio-ide-terminal/lib/status-bar.coffee:236:59)
Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
<unknown> (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:348:27)
Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
```

**Comment by ghost** [comment]
Basically appears on any application specific page(tab) within atom that obviously is not part of any project.

**Comment by Fred-Barclay** [comment]
#129 should handle this. :)

**Comment by mancelee** [comment]
Object.dirname - C:\Users\Administrator\AppData\Local\atom\app-1.16.0\resources\app.asar\src\electron-shims.js:9:10
<unknown> - C:\Users\Administrator\.atom\packages\platformio-ide-terminal\lib\status-bar.coffee:241:59
Function.module.exports.Emitter.simpleDispatch - C:\Users\Administrator\AppData\Local\atom\app-1.16.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14
Emitter.emit - C:\Users\Administrator\AppData\Local\atom\app-1.16.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:141:28
<unknown> - C:\Users\Administrator\AppData\Local\atom\app-1.16.0\resources\app.asar\src\pane-container.js:348:27
Function.module.exports.Emitter.simpleDispatch - C:\Users\Administrator\AppData\Local\atom\app-1.16.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14

**Comment by WickedSik** [comment]
I still have the problem, I'm using version `2.5.3`

```
Object.dirname - /Applications/Atom.app/Contents/Resources/app/src/electron-shims.js:9:10
<unknown> - /Users/jurriendokter/.atom/packages/platformio-ide-terminal/lib/status-bar.coffee:241:59
Function.module.exports.Emitter.simpleDispatch - <embedded>:63093:20
Emitter.emit - <embedded>:63209:34
Workspace.didChangeActivePaneItemOnPaneContainer - <embedded>:22980:28
WorkspaceCenter.paneContainer.onDidChangeActivePaneItem - <embedded>:70934:20
```

**Comment by benphelps** [comment]
As @Fred-Barclay mentioned, there is a (now closed) pull request #129 that fixes this.  I've added more information to the request so hopefully they can reproduce this and get it fixed.

**Comment by ivankravets** [comment]
Could someone provide PR? Thanks!

**Comment by benphelps** [comment]
#129 is for this issue.
