### ISSUE TITLE
Can't open atom from within platformio terminal. LSOpenURLsWithRole error 10810.

### ISSUE THREAD

**Issue by AaronV** [platformio/platformio-atom-ide-terminal#150]
I have atom as my default git mergetool. When rebasing my code from the platformio terminal, there is an error. This happens when trying to run `atom` directly as well.

The error message is:
```
$ atom
LSOpenURLsWithRole() failed for the application /Applications/Atom.app with error -10810.
```

I am able to rebase and launch atom from the MacOS Terminal app.

Some googling suggests this is related to tmux and reattach-to-user-namespace. Trying the suggestions I've found so far has been unsuccessful with the platformio terminal. Any ideas with what's going on?

PS: I found this tread on the matter: https://github.com/atom/atom/issues/3093. However the solutions here don't seem to work for the platformio terminal.

**Comment by AaronV** [comment]
Finally found a solution. This comment: https://github.com/atom/atom/issues/3093#issuecomment-263667546 suggests adding an alias to the effect of `alias atom="open -a /Applications/Atom.app/Contents/MacOS/Atom"` which seems to have solved it in my case.

**Comment by roroland** [comment]
I have a similar problem, in my case if I try to run`git commit -v` inside platformio (I use Atom to manage all git commit messages) I then get the error.

Any ideas how to solve it ? Thanks
