### ISSUE TITLE
Missing theme from Terminal

### ISSUE THREAD

**Issue by mikeerickson** [platformio/platformio-atom-ide-terminal#156]
I am trying to apply the same "theme" that I use in Terminal, but it does not appear?

Is it possible to use `snazzy` in my case?

![image](https://cloud.githubusercontent.com/assets/183153/22407822/d437cb1e-e622-11e6-83a3-64bb03314f20.png)

**Comment by giovapanasiti** [comment]
Where did you find the option to customize the theme?

**Comment by mikeerickson** [comment]
@giovapanasiti which part are you referring to?

**Comment by giovapanasiti** [comment]
Within Atom I can't find where to sed the terminal colors. I did it via CSS and .bash_profile but I would love to change the appearence through atom

**Comment by Joseph-D-Bradshaw** [comment]
@mikeerickson I would too like to know about where you found the theme menu for the terminal; currently my font is huge and it's just black and white with windows powershell message. Would like to change it but not as clever as @giovapanasiti to change it myself

**Comment by mikeerickson** [comment]
@SoulSkirx I will get you this information in the morning.

**Comment by mikeerickson** [comment]
@SoulSkrix sorry for the name typo.  Replying on phone and it doesn't have name auto complete 😊

**Comment by mikeerickson** [comment]
@SoulSkrix OK, I am  ready to assist :-)

1. Select `Atom -> Preferences`

2. Select `Settings -> Install` (I just do this to easily find out if a package is installed)

3. Select `platformio-ide-terminal` to access plugin settings

![image](https://cloud.githubusercontent.com/assets/183153/22987041/6181c8e8-f362-11e6-88bd-f827ca8de374.png)

4. Select `Settings`

5. Scroll down to `Style` section

![image](https://cloud.githubusercontent.com/assets/183153/22987074/7d202d6a-f362-11e6-91e9-a4bd4d134a02.png)

6. See `Theme` option to select desired terminal theme

![image](https://cloud.githubusercontent.com/assets/183153/22987105/9149416e-f362-11e6-86c7-cfd7283ebdc4.png)

**Comment by mikeerickson** [comment]
@SoulSkrix 

Here is what it looks like when I activate terminal ( ``` ctrl-` ``` ) or in my case, I use ( `shift-cmd-t` ) as I have ( ``` ctrl-` ``` ) configured to toggle `iTerm`

**Comment by abelgraham** [comment]
I had this problem. What I did wrong was that I had missed the enum in platformio-ide-terminal.coffee that you must add your theme to. I used pull request #42 for reference.

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0 is using node-pty-prebuilt instead unmaintained and outdated pty.js
