### ISSUE TITLE
package.json file not parseable on install

### ISSUE THREAD

**Issue by Sean-Hendler** [platformio/platformio-atom-ide-terminal#159]
I get the following error message when trying to install the package

Tell the package author to fix their package.json file. JSON.parse

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\SEANH_~1\AppData\Local\Temp\apm-install-dir-11713-14172-pu491m\npm-debug.log

**Comment by ivankravets** [comment]
Try to upgrade to 2.4.0
