### ISSUE TITLE
Linter warnings overlap terminal

### ISSUE THREAD

**Issue by torkleyy** [platformio/platformio-atom-ide-terminal#160]
I'm using the `linter` package and when scrolling down the warning overlaps the terminal like this:

![screenshot from 2017-02-04 09-45-53](https://cloud.githubusercontent.com/assets/23152057/22617211/5682e310-eabf-11e6-9bf7-ce0914614363.png)

I don't know exactly whether this is an issue with this terminal or the linter package.

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0 is using node-pty-prebuilt instead unmaintained and outdated pty.js
