### ISSUE TITLE
can not type chinese  on MAC10.11.3

### ISSUE THREAD

**Issue by Jonathanliu525** [platformio/platformio-atom-ide-terminal#162]
As you see it，I have files named by  chinese
![image](https://cloud.githubusercontent.com/assets/15061884/22684491/91b41202-ed57-11e6-9488-41b05f1a8eee.png)

when I open the terminal, I see this
![image](https://cloud.githubusercontent.com/assets/15061884/22684563/ce838636-ed57-11e6-81de-9522892095c4.png)

then I change the setting by using'LANG="zh_CN.UTF-8"
![image](https://cloud.githubusercontent.com/assets/15061884/22684598/f1210ea2-ed57-11e6-99dc-bae02f3593f5.png)
then I can see the right chinese
![image](https://cloud.githubusercontent.com/assets/15061884/22684614/0be88ed6-ed58-11e6-824e-9895d740f6de.png)

**But I can not type chinese into the terminal**
Some thing like this can not be typed,please help me,thank you. Cause I have some folder named by chinese, you know I can\`t use `cd` to access the those folder
```
echo “你好，世界”
```

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0 is using node-pty-prebuilt instead unmaintained and outdated pty.js
