### ISSUE TITLE
Open on project folder breaks when projects are added through a symlink

### ISSUE THREAD

**Issue by FossPrime** [platformio/platformio-atom-ide-terminal#164]
# Steps to reproduce
1. add a project through a symlink
2. add another project through a symlink
3. open a file on project 1
4. open a terminal
4. open a file on project 2
4. open a terminal

# Expected results:
the working dir of the first term will be proj 1, and 2 for the second.

# Actual results
the working dir of the first term will be proj 1 resolved to it's non-symlink name. Term 2 will still be project one resolved to it's non-symlink name.

# Versions
I'm running Fedora, but any posix os should do.
Atom 1.12.6
platformio-ide-terminal 2.2.3

![screenshot from 2017-02-08 17-04-29](https://cloud.githubusercontent.com/assets/876076/22833341/2bc1b022-ef77-11e6-8e75-60d6845b9c76.png)

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0 is using node-pty-prebuilt instead unmaintained and outdated pty.js
