### ISSUE TITLE
Terminal does not function on 64bit version of Atom (Windows)

### ISSUE THREAD

**Issue by acampb311** [platformio/platformio-atom-ide-terminal#165]
I updated and then did a clean install of the 64 bit version of Atom this morning and discovered that the terminal does not function at all. It simply blinks the cursor. Returning to the 32 bit build causes the terminal to function again.

**Comment by joshuadavidson** [comment]
See issue as #155 and the pull request from zorn-v found at [here](https://github.com/platformio/pty.js/pull/1/commits/23b7af33855bebe9c776d4c8338eb6f7d3d88da5). Add those 3 files to the following directory: ~\.atom\packages\platformio-ide-terminal\node_modules\pty.js\bin\win32\

Obviously just a quick patch until it is officially fixed.

**Comment by ivankravets** [comment]
Please update `platformio-ide-terminal` to 2.2.3
