### ISSUE TITLE
Cannot insert custom text when no files are open

### ISSUE THREAD

**Issue by Spitfire1900** [platformio/platformio-atom-ide-terminal#168]
Problem:
If no files are open or only the "Setting View" is open submitting a "Insert Custom Text" command results in the text not being inserted.
Excepted Result: When no files are open or only the "Setting View" is open submitting a "Insert Custom Text" command submits the custom text.

**OS:** Windows 7 x64
**Atom version:** 1.14.1 x64
**platformio-ide-terminal version:** 2.2.3
**Installed Powershell version:** 2

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0 is using node-pty-prebuilt instead unmaintained and outdated pty.js
