### ISSUE TITLE
Command History Not Working on Windows

### ISSUE THREAD

**Issue by darylnak** [platformio/platformio-atom-ide-terminal#170]
I'm not sure if this is because bash is not fully implemented on Windows, but using the Up Arrow to get my command history does not work when using bash through PlatformIO.

**Comment by gh-code** [comment]
Same here. Tab key is not working too.

**Comment by bubthegreat** [comment]
Same issue here.  Looking into it to see if I can fix, but this is probably beyond what I know how to work on. :(

**Comment by thegregstengel** [comment]
any updates on this, I have the same issue.

**Comment by rpartha** [comment]
same.

**Comment by Galyean** [comment]
can try ctrl+p or other  key combination

**Comment by henryxparker** [comment]
It's not a problem with bash on windows, since the up and down commands work fine when bash is executed from powershell. Identical to issues #231 and #221

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0 is using node-pty-prebuilt instead unmaintained and outdated pty.js
