### ISSUE TITLE
process.env.SHELL is undefined for some cases on macOS

### ISSUE THREAD

**Issue by Fred-Barclay** [platformio/platformio-atom-ide-terminal#176]
Hey guys - just wanted to kick this issue and a (so far) suitable fix up to you from my fork.

Under some circumstances, `process.env.SHELL` in [lib/platformio-ide-terminal.coffee](https://github.com/platformio/platformio-atom-ide-terminal/blob/master/lib/platformio-ide-terminal.coffee#L77) isn't defined for macOS. This means that a user will be able to launch the terminal but will only see a blinking cursor, as in #167 #131 #105.

Our workaround is to fall back to /bin/bash for macOS users if and **only** if process.env.SHELL is undefined, by replacing line 77-78 with this:
```
            else
              process.env.SHELL || '/bin/bash'
```
More info is at https://github.com/Fred-Barclay/Termination/issues/30
Hope this helps!
Fred

**Comment by ivankravets** [comment]
Hi Fred,

Thank you! I've just released new version!

**Comment by Fred-Barclay** [comment]
You're welcome! Happy to help!

Kudos to @isaac-webb for noticing the problem and helping me test. :+1:

**Comment by ivankravets** [comment]
@Fred-Barclay @isaac-webb, the right solution for this issue is to set default shell in OS
* http://stackoverflow.com/questions/453236/how-to-set-my-default-shell-on-mac

This is rather a hook than a fix 😊

**Comment by isaac-webb** [comment]
@ivankravets I messed around with that procedure today and, for some reason, I think even if a default shell is configured, the `$SHELL` variable from the terminal doesn't get passed to Atom if you launch it normally through Launchpad, Spotlight, or the Dock.

However, I found that if you open a terminal and execute `atom` from there to launch the editor, `process.env.SHELL` is set correctly... Not sure why this might be happening, but wanted to share!

**Comment by Fred-Barclay** [comment]
> the $SHELL variable from the terminal doesn't get passed to Atom if you launch it normally through Launchpad, Spotlight, or the Dock.

> 

@ivankravets @isaac-webb Sounds like this might be worth bringing to the attention of the Atom devs. What do you think?
