### ISSUE TITLE
Terminal does not open in project folder

### ISSUE THREAD

**Issue by ghost** [platformio/platformio-atom-ide-terminal#178]
I am on Windows 10, Atom 1.14.3. The terminal opens at it's default root, not the project. I have tried powershell and cygwin. To be fair this is also happening on terminal-plus, but in terminal-plus the terminal is not even loading. It sounds like terminal-plus is broken on Win 10.

**Comment by Vasencheg** [comment]
The terminal opens at root folder. I am on Win 10 and msys2 bash.

**Comment by filviu** [comment]
Is there any environment variable that can be specified as a command line parameter to bash?

**Comment by Vasencheg** [comment]
I fix the issue by adding 'process.platform isnt 'win32'' in the lib/process.coffee file:

`if /zsh|bash/.test(shell) and args.indexOf('--login') == -1 and process.platform isnt 'win32'
    args.unshift '--login'`

The '--login' parameter is the source of the issue on Windows.

**Comment by ghost** [comment]
Windows Powershell now opens at the project folder, but Cygwin still opens at the root folder.

**Comment by Vasencheg** [comment]
Have you got any shell arguments in the "platformio-ide-terminal" settings?

**Comment by ghost** [comment]
No

**Comment by Vasencheg** [comment]
It's very strange.
Do you launch "CYGWIN_FOLDER\bin\bash.exe" instead of using 'cygwin.bat' from root folder.

**Comment by ghost** [comment]
I'm not sure what you mean by 'bash.bat' in the root folder. I have tried
C:\cygwin\Cygwin.bat, and C:/cygwin/bin/bash.exe, both of them take me to
the root.

**Comment by nrfowler** [comment]
I'm not sure what you mean by 'bash.bat' in the root folder. I have tried C:\cygwin\Cygwin.bat, and C:/cygwin/bin/bash.exe, both of them take me to the root.

**Comment by Vasencheg** [comment]
I mean 'C:\cygwin\Cygwin.bat'.
I have tried '/bin/bash.exe' and it works for me. I use msys2 a long time.
Maybe try msys2 instead of Cygwin, but perhaps the problem is deeper.

**Comment by Vasencheg** [comment]
Try this workaround. Put this lines of code in the  lib/process.coffee file:
 ```
 index = args.indexOf('--login')
 if  index != -1 and process.platform is 'win32'
    args.splice(index, 1)
```
https://gist.github.com/Vasencheg/0cc91bb12394f62e548d3292a86cc2ce

**Comment by ghost** [comment]
Tried that and it did not work. There might be something deeper. I think it
is how I have cygwin configured, actually.

**Comment by Vasencheg** [comment]
Maybe. I have tried Cygwin and Msys2 'bin/bash.exe' and it works.
