### ISSUE TITLE
Copy/paste not working

### ISSUE THREAD

**Issue by krabbypattified** [platformio/platformio-atom-ide-terminal#179]
Whenever I try to "copy something from" or "paste something into" the terminal it doesn't work and is pretty annoying.

I'm on a Mac OS X Sierra and Atom 1.14.3, if it matters.

**Comment by ivankravets** [comment]
Do you still have this problem with 2.4.0?

**Comment by krabbypattified** [comment]
I can copy now but I can't paste. I'm forced to click the keyboard icon and paste a command there.

**Comment by meditatingCybermind** [comment]
I'm also having this issue on 2.4.0 running atom 1.11.2

The keyboard icon also works for me, but that'd require an extra step in my workflow, so that's not really a permanent solution for me

**Comment by krabbypattified** [comment]
Simple fix: go to "Settings > Core > Packages With Keymaps Disabled" and remove "platformio-ide-terminal" from the list

**Comment by alioion21** [comment]
> Simple fix: go to "Settings > Core > Packages With Keymaps Disabled" and remove "platformio-ide-terminal" from the list

I went to settings then to core but found no Packages with keymaps or platformio ide terminal? I am stuck.
