### ISSUE TITLE
Feature Fixes

### ISSUE THREAD

**Issue by muhd-ali** [platformio/platformio-atom-ide-terminal#18]
Could you please fix the following in your package?
1) Place the close all icon away from the opened windows
2) The terminal won't start until I open a folder in atom. Let it start even if no folder is open.
3) When I adjust the height of one terminal, all other opened instances should update their height

These things had been addressed in the original terminal-plus and I am missing them in your fork.
##

**Comment by takeontom** [comment]
Just opened #21 to look at the terminal height issue. (didn't see this before I posted)

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0 is using node-pty-prebuilt instead unmaintained and outdated pty.js

if issues persist open a new ticket with required information.

Thx =)
