### ISSUE TITLE
plugin does not respect user hissize, all history get resize to 500

### ISSUE THREAD

**Issue by intijk** [platformio/platformio-atom-ide-terminal#180]
My hist size and file set to a very big value. 

Every time I open the terminal in atom, my histfile is shinked to 500 lines.

This is really annoying.

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0 is using node-pty-prebuilt instead unmaintained and outdated pty.js

if issues persist open a new ticket with required information.

Thx =)
