### ISSUE TITLE
Composite unicode duplicated with every other letter

### ISSUE THREAD

**Issue by YongHee-Kim** [platformio/platformio-atom-ide-terminal#182]
![korean](https://cloud.githubusercontent.com/assets/7087745/23386866/5d83f4ca-fd9c-11e6-8aa7-f866a34ac993.gif)
I 've typed `가..나..다..라` but every other letter is duplicated ->`가..나나..다..라라`
perhaps related to #140 ?

Any unicode works fine in here, so I don't have any problem with using your package 👍 Thanks!
![image](https://cloud.githubusercontent.com/assets/7087745/23386949/e805f5f8-fd9c-11e6-95d2-e7dabb28bfc2.png)

**Comment by darron1217** [comment]
I think this is an important problem.

It makes us hard to use this plugin... :(

**Comment by YongHee-Kim** [comment]
![image](https://user-images.githubusercontent.com/7087745/33875840-fa788744-df66-11e7-91fe-fa5b8d49ff36.png)
It seems fixed now.
