### ISSUE TITLE
Request: Disable animation

### ISSUE THREAD

**Issue by marcel0ll** [platformio/platformio-atom-ide-terminal#191]
Would it be possible to have an animation toggle button?

I really don't see the point of slowly opening and closing the console. I would prefer that the terminal would just appear instantly

**Comment by nanot1m** [comment]
This animation is a little laggy cause of animating top property instead of using transform. It's becomes annoying and having option to disable animation would be nice 👍

**Comment by marcel0ll** [comment]
There is a config called Animation Speed. 
Setting it to 0 does open and close the terminal without delay
