### ISSUE TITLE
2.5.0 not working

### ISSUE THREAD

**Issue by rickydazla** [platformio/platformio-atom-ide-terminal#192]
I just downloaded the latest update and now there are no icons in the bottom bar and "toggling" doesn't launch anything... dunt werk :(

**Comment by ivankravets** [comment]
1. OS
2. Atom

**Comment by rickydazla** [comment]
sry

1. macOS Sierra v10.12.3
2. Atom v1.15.0

**Comment by ivankravets** [comment]
View-> Developer-> Tools > Console. What do you see? 

Try uninstall/install package

**Comment by rickydazla** [comment]
Aha. I see an error with another package : ) https://github.com/morassman/tabasco/issues/9
