### ISSUE TITLE
Change Node version

### ISSUE THREAD

**Issue by alexmylonas** [platformio/platformio-atom-ide-terminal#193]
Hi there, 

Is there a way to change the default node version? As far as i can see is v4.4.7 and atom uses v4.4.5

**Comment by Oblik-Design** [comment]
just wanted to tell someone that , it is an incredible package !

**Comment by valeriik** [comment]
The same question...

**Comment by the-j0k3r** [comment]
Doesnt seem like applicable anymore, closing.
