### ISSUE TITLE
bash: update_terminal_cwd: command not found

### ISSUE THREAD

**Issue by ghost** [platformio/platformio-atom-ide-terminal#196]
<img width="433" alt="screen shot 2017-03-23 at 12 28 07 am" src="https://cloud.githubusercontent.com/assets/5118530/24236565/9aa7a322-0f5f-11e7-9a68-816d3df1bd15.png">

**Comment by cento** [comment]
Same problem, here.

OS: macOS Sierra
Shell: GNU bash, version 4.4.12(1)-release (x86_64-apple-darwin16.3.0)

**Comment by willthemoor** [comment]
`update_terminal_cwd` is a command specific to the Apple Terminal app. Not bash, not even iterm. 

This plugin does respect whatever you've exported as `PS1` (and `PS2`, etc) in your `.bash_rc` or `.profile` or whatever. Try http://ezprompt.net/ maybe?

**Comment by tf42src** [comment]
Sorry, is it my fault? How can I fix it? I am not aware of having done anything unusual to my terminal (or .bash_profile).

**Comment by sebastientaggart** [comment]
Is there any update on this?  It's happening to me in Atom terminal, but not in iterm or anywhere else.  Is there a workaround?

EDIT: fixed from https://apple.stackexchange.com/questions/139807/what-does-update-terminal-cwd-do-in-the-terminal-of-os-x by adding this to `~/.bash_profile`:

```
update_terminal_cwd() {
    # Identify the directory using a "file:" scheme URL,
    # including the host name to disambiguate local vs.
    # remote connections. Percent-escape spaces.
    local SEARCH=' '
    local REPLACE='%20'
    local PWD_URL="file://$HOSTNAME${PWD//$SEARCH/$REPLACE}"
    printf '\e]7;%s\a' "$PWD_URL"
}
```

**Comment by samabp** [comment]
@sebastientaggart This was the same issue I was experiencing in atom. Thanks for posting back here.

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0 is using node-pty-prebuilt instead unmaintained and outdated pty.js

if issues persist open a new ticket with required information.

Thx =)
