### ISSUE TITLE
Uncaught Error: channel closed

### ISSUE THREAD

**Issue by kandril** [platformio/platformio-atom-ide-terminal#2]
Enter steps to reproduce below:  1. ... 2. ... **Atom Version**: 1.5.3 **System**: Ubuntu 14.04.4 **Thrown From**:  platformio-ide-terminal  https://github.com/platformio/platformio-atom-ide-terminal  package, v2.0.2 ### Stack Trace Uncaught Error: channel closed     At events.js:141 Error: channel closed at ChildProcess.target.send  internal/child_process.js:509:16  at Task.module.exports.Task.send  /usr/share/atom/resources/app.asar/src/task.js:117:27  at PlatformIOTerminalView.module.exports.PlatformIOTerminalView.input  /home/<user>/.atom/packages/platformio-ide-terminal/lib/view.coffee:262:17  at Terminal. anonymous>  /home/<user>/.atom/packages/platformio-ide-terminal/lib/view.coffee:141:8  at Terminal.EventEmitter.emit  /home/<user>/.atom/packages/platformio-ide-terminal/node_modules/term.js/src/term.js:109:12  at Terminal.handler  /home/<user>/.atom/packages/platformio-ide-terminal/node_modules/term.js/src/term.js:3493:8  at Terminal.keyPress  /home/<user>/.atom/packages/platformio-ide-terminal/node_modules/term.js/src/term.js:3243:8  at HTMLDocument. anonymous>  /home/<user>/.atom/packages/platformio-ide-terminal/node_modules/term.js/src/term.js:608:29      ### Commands     -0:05.4.0 platformio-ide:maintenance.update-platformio  atom-text-editor.editor.is-focused      ### Config    json {}     ### Installed Packages    coffee # User autocomplete-clang, v0.8.9 build, v0.55.0 language-ini, v1.14.0 linter, v1.11.3 linter-gcc, v0.6.7 platformio-ide, v1.0.4 platformio-ide-terminal, v2.0.2 tool-bar, v0.2.1 # Dev No dev packages     
##

**Comment by ivankravets** [comment]
Do you have GCC installed in your system? Give me please an output of `gcc --version`.

**Comment by kandril** [comment]
As requested, the output of `gcc --version` on my system

```
gcc (Ubuntu 4.8.4-2ubuntu1~14.04.1) 4.8.4
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by ivankravets** [comment]
Does Terminal work if click on the icon (+) in the status bar (bottom) ?

**Comment by kandril** [comment]
It does.
![pio-terminal](https://cloud.githubusercontent.com/assets/7306882/13299351/198dfd58-db3b-11e5-86e4-93b02ecbcfb0.png)

**Comment by jasonc0** [comment]
See my new issue #246 - I entered a new issue because I am on windows and although the title of the error once stack trace is produced is similar, the issue is different. 

[Enter steps to reproduce:]

1. Open platformio terminal - winpty.x64.dll assert failed dialog pops up.  If I hit ignore I get the uncaught error: channel closed error.

Terminal input does not work, nor do any commands sent to the terminal through the API.  So therefore platformio core update and other built in features do not work.  I just get the assert failed VC++ error from winpty.x64.dll every time terminal opens up.
![image](https://cloud.githubusercontent.com/assets/23383748/26808026/25e7efc0-4a28-11e7-901e-c79d724d74e6.png)

**Atom**: 1.17.2 x64
**Electron**: 1.3.15
**OS**: Microsoft Windows 10 Enterprise Insider Preview
**Thrown From**: [platformio-ide-terminal](https://github.com/platformio/platformio-atom-ide-terminal) package 2.5.1


### Stack Trace

Uncaught Error: channel closed

```
At events.js:160

Error: channel closed
    at ChildProcess.target.send (internal/child_process.js:540:16)
    at Task.module.exports.Task.send (~/AppData/Local/atom/app-1.17.2/resources/app/src/task.js:119:1)
    at PlatformIOTerminalView.module.exports.PlatformIOTerminalView.input (/packages/platformio-ide-terminal/lib/view.coffee:264:17)
    at /packages/platformio-ide-terminal/lib/view.coffee:142:8)
    at Terminal.EventEmitter.emit (/packages/platformio-ide-terminal/node_modules/term.js/src/term.js:109:12)
    at Terminal.handler (/packages/platformio-ide-terminal/node_modules/term.js/src/term.js:3493:8)
    at /packages/platformio-ide-terminal/node_modules/term.js/src/term.js:3253:12
```

### Commands

```
     -8:06.2.0 build:toggle-panel (atom-pane.pane)
     -7:46.5.0 terminal-plus:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -7:01.8.0 core:backspace (input.hidden-input)
     -4:32.3.0 platformio-ide-terminal:toggle (div.package-detail.panels-item)
```

### Non-Core Packages

```
autocomplete-clang 0.11.3 
build 0.68.0 
busy 0.7.0 
file-icons 2.1.7 
intentions 1.1.2 
language-ini 1.19.0 
linter 2.1.4 
linter-gcc 0.7.1 
linter-ui-default 1.6.0 
minimap 4.28.2 
platformio-aia 0.0.5 
platformio-ide 2.0.0-beta.6 
platformio-ide-debugger 1.2.2 
platformio-ide-terminal 2.5.1 
tool-bar 1.1.0 
```

**Comment by DCToddM** [comment]
jasonc0 did you find a fix for your problem? I'm having the same problem on my windows 10 machine.

**Comment by mikivan1980** [comment]
I'm having the same problem on my windows 10 machine.

**Comment by jomikk** [comment]
I had the same problem on a Windows 10 machine!!!!
I'am update VS2017 add Visual C++ Redistributable for VS2015...

![update-vs2017-for-atom-arow](https://user-images.githubusercontent.com/20689565/27881381-15add046-61d1-11e7-88fa-26d43433c814.png)

Try installing Redistributable for VS2015...

And changed the setting to:
atom -> settings -> shell override -> C:\Windows\System32\cmd.exe

Last is important!!!!!!!!

**Comment by jasonc0** [comment]
I gave up, switched to Manjaro Linux.

**Comment by fliprutledge** [comment]
https://www.microsoft.com/en-us/download/confirmation.aspx?id=48145 fixes it on Win 10

**Comment by the-j0k3r** [comment]
@ivankravets please close no longer relevant
