### ISSUE TITLE
How can I change the color of the folders when listing them?

### ISSUE THREAD

**Issue by mairanteodoro** [platformio/platformio-atom-ide-terminal#20]
When using `ls`, I would like to change the default blue color of the folders to another custom color.
How can I do this?

**Comment by mairanteodoro** [comment]
Oh, well... nevermind.

**Comment by xiaodid** [comment]
after following this, I managed to add color in mac.
http://osxdaily.com/2012/02/21/add-color-to-the-terminal-in-mac-os-x/
