### ISSUE TITLE
zshrc profile not loaded

### ISSUE THREAD

**Issue by vire** [platformio/platformio-atom-ide-terminal#202]
When I open a terminal it does not load my `~/.zshrc` explicitly, i have to use *Auto Run Command* like `source ~/.zshrc`

OSX 10.11.6
Atom 1.15 x64

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0 is using node-pty-prebuilt instead unmaintained and outdated pty.js

if issues persist open a new ticket with required information.

Thx =)
