### ISSUE TITLE
CLI is affected when commands are edited on Windows

### ISSUE THREAD

**Issue by stevenventimiglia** [platformio/platformio-atom-ide-terminal#204]
Whenever a command is reworded, the terminal seems to lose track of where the cursor was at.  The issue is often seen when using arrow keys or backspace to insert edits into a command before sending it.  In some cases, it will seem as if you have edited a command but then an error will tell you that the command you saw was not returned correctly.

Ex. "git push origin master" + either arrow left to change the command or backspacing to retype the command as "git push -u origin master" can result in something similar to "git: 'pus' is not a git command."

**Comment by stevenventimiglia** [comment]
Forgot I created this issue in March.  Still continues to make this package useless on Windows 10 (using Git for Windows bash.)

Attached is a visual example of the issue that I recorded for reference.

[platformioerror.zip](https://github.com/platformio/platformio-atom-ide-terminal/files/1273012/platformioerror.zip)

**Comment by richiksc** [comment]
This issue gives me a lot of trouble... this is the only thing I need in platformio-ide-terminal and it will be on par with the Mintty Git bash

**Comment by stevenventimiglia** [comment]
@richiksc - Unfortunately, I've moved on to Visual Studio Code.  It seems to be managed a bit better than Atom, and includes it's own terminal with tabs, as well as options for other shells.  The extensions seem to be much more reliable as well without as much abandonment as I've experienced with many of the repos that Atom is dependent on (especially after the update they did a while back.)

I'm always game to come back to Atom, but that move will be determined once the broken packages I was using are no longer broken or there are proper replacements for them (over 6+).

**Comment by grig0ry** [comment]
@stevenventimiglia @richiksc 
Try disabling **Cursor Blink** option.

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0 is using node-pty-prebuilt instead unmaintained and outdated pty.js

if issues persist open a new ticket with required information.

Thx =)

**Comment by richiksc** [comment]
I've moved on to atom-ide-ui, developed by atom developers with its own built in terminal
