### ISSUE TITLE
yarn install and npm install does not install devDependencies

### ISSUE THREAD

**Issue by woffleloffle** [platformio/platformio-atom-ide-terminal#207]
> Off the bat.. I realise this isn't really a bug, but it confused me completely, until I realised what was happening.

With the following `package.json`:

```
{
  "name": "test",
  "main": "index.js",
  "scripts": {
    "start": "node ."
  },
  "devDependencies": {
    "babel-cli": "^6.24.0"
  }
}
```

Running `npm install`, `npm i`, `yarn` or `yarn install` in a console within Atom would not install anything in `node_modules`.
After a lot of searching, I ran the following in Atom:

```
$ echo $NODE_ENV
production
```

[This](https://github.com/yarnpkg/yarn/issues/1830) closed issue on `yarnpkg/yarn` explains why this is not a bug from npm/yarn's side. To paraphrase:

>Using the --production flag, or when the `NODE_ENV` environment variable is set to `production`, Yarn will not install any package listed in devDependencies

To install the `devDependencies`, I run `npm install` or `yarn install` from a console opened outside of Atom.

I thought I would let you guys know, perhaps there's an implementation fix from your side.

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0.
These type issues all so far seem fixed with this release due to using node-pty-prebuilt instead unmaintained and outdated pty.js

if issues persist open a new ticket with required information.

Thx =)
