### ISSUE TITLE
Cursors show incorrectly

### ISSUE THREAD

**Issue by ToSeven** [platformio/platformio-atom-ide-terminal#210]
![default](https://cloud.githubusercontent.com/assets/14891443/24834498/41ac17bc-1d1a-11e7-865f-9cf21982f765.PNG)
the display format is uncomfortable and how to solve this issue？

**Comment by HojinCho** [comment]
I am experiencing this as well, Windows 10, either on Powershell or on Command Prompt.
And I think it is somewhat related with Full-Width characters in CJK characters.

It seems as if the line length acknowledged by terminal is shorter than its actual length.
If what I type and stdout content does not contain any CJK characters (for my case, Korean), it does not behave as this. Each line gets shorter if I type more CJK letters.

**Comment by hsz1273327** [comment]
![image](https://cloud.githubusercontent.com/assets/7850148/26521953/3f0796b0-4328-11e7-8cf3-66991f64ef5f.png)
try this!

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0 is using node-pty-prebuilt instead unmaintained and outdated pty.js
