### ISSUE TITLE
unable to download

### ISSUE THREAD

**Issue by Fr33maan** [platformio/platformio-atom-ide-terminal#213]
Unable to download https://www.atom.io/api/packages/platformio-ide-terminal/versions/2.5.0/tarball: getaddrinfo ENOTFOUND codeload.github.com codeload.github.com:443

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0 is using node-pty-prebuilt instead unmaintained and outdated pty.js

if issues persist open a new ticket with required information.

Thx =)
