### ISSUE TITLE
open terminal steals focus after focusing atom

### ISSUE THREAD

**Issue by aiomaster** [platformio/platformio-atom-ide-terminal#219]
1. Open a terminal pane in atom which has the focus
2. select another window, so that atom loses focus.
3. click at atom window to get the focus back

Problem:
Immediately after selecting atom the terminal gets focused. It doesn't matter where the click was done.

Expected behaviour:
Only focus the terminal if the click was made somewhere at the terminal pane.
If the click was made in the editor pane the cursor position should not be touched and editor pane should be active.

**Comment by ivankravets** [comment]
Fixed in https://github.com/platformio/platformio-atom-ide-terminal/pull/251
