### ISSUE TITLE
Not able to use the key pad to navigate through the history on Windows with Ubuntu Shell.

### ISSUE THREAD

**Issue by haoalisterw** [platformio/platformio-atom-ide-terminal#221]

**Comment by henryxparker** [comment]
Identical issue to #231

**Comment by tofi86** [comment]
Works for me with current Windows 10 stable build and current Atom release. Just noting...

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0.
These type issues all so far seem fixed with this release due to using node-pty-prebuilt instead unmaintained and outdated pty.js
