### ISSUE TITLE
Improvement: Send multi-line commands to the shell without selecting the lines

### ISSUE THREAD

**Issue by hagl** [platformio/platformio-atom-ide-terminal#224]
I'm working with files that contain shell command that span multiple lines and are separated by empty lines. While I'm working on these statements I would like to send the current block to the shell without the need to select all the lines and thereby losing the current cursor position.

I have a working implementation that I could provide as a PR in case this feature would be interesting for others.

**Comment by the-j0k3r** [comment]
Thank you for your ticket, all features and fixes are now solely a user generated contribution.
So yes please do.
