### ISSUE TITLE
two simply bugs reporting

### ISSUE THREAD

**Issue by anpaul0615** [platformio/platformio-atom-ide-terminal#229]
I found two bugs, please read below cases.

case 1 : not working electron bug; when start electron application in "platformio-atom-ide-terminal"

case 2 : line-feed and carriage-return bug; when I'm trying command job (I guess when long string returned). see captured image.

(normally atom size)
![bug1](https://cloud.githubusercontent.com/assets/8488507/26275330/c07650be-3d98-11e7-8af3-3a45fffda1dd.PNG)

(maximum atom size)
![bug2](https://cloud.githubusercontent.com/assets/8488507/26275332/c5237830-3d98-11e7-915d-f8f9cd55448f.PNG)

**Comment by ivankravets** [comment]
Could you try v2.5.1 (just released)?

**Comment by anpaul0615** [comment]
yes I tried.
here are bug capture images about running electron with "platformio-atom-ide-terminal"

![bug1](https://cloud.githubusercontent.com/assets/8488507/26281346/17e0019c-3e2f-11e7-8054-472e8bff5257.PNG)

![bug2](https://cloud.githubusercontent.com/assets/8488507/26281347/1b07e088-3e2f-11e7-8e23-0cf7675f9bee.PNG)

![bug3](https://cloud.githubusercontent.com/assets/8488507/26281350/20255e56-3e2f-11e7-93f8-121c889d5c95.PNG)

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0 is using node-pty-prebuilt instead unmaintained and outdated pty.js

if issues persist open a new ticket with required information.

Thx =)
