### ISSUE TITLE
New version error

### ISSUE THREAD

**Issue by rafalschmidt97** [platformio/platformio-atom-ide-terminal#233]
Hi,
My application doesn't start after newest update. Whenever I use system terminal everything work fine. 

<img width="858" alt="screen shot 2017-05-23 at 16 01 00" src="https://cloud.githubusercontent.com/assets/14861637/26359380/9dba20d4-3fd5-11e7-89c5-22d2d17fa09e.png">

**Comment by cscouras** [comment]
I am experiencing this same error when attempting to start a development server for any app built with create-react-app.

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0 is using node-pty-prebuilt instead unmaintained and outdated pty.js

if issues persist open a new ticket with required information.

Thx =)
