### ISSUE TITLE
Custom text options do not properly escape paths

### ISSUE THREAD

**Issue by cj81499** [platformio/platformio-atom-ide-terminal#234]
I have a custom text command for "python3 $D$F"

When I run it, if the file is in a folder with a space in the name (ex: "Python Stuff"), it doesn't work, because $D sends it as "Python Stuff", rather than "Python\ Stuff", which is what it should be (the difference is the parenthesis.

To fix this, spaces in paths need to be replaced with a backslash and a space.

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0 is using node-pty-prebuilt instead unmaintained and outdated pty.js

if issues persist open a new ticket with required information.

Thx =)
