### ISSUE TITLE
Lose focus when close the terminal

### ISSUE THREAD

**Issue by L4zyy** [platformio/platformio-atom-ide-terminal#237]
I was trying to see some doc on my browser and continue to write some code on Atom.
    When I change back to Atom and close the terminal, it can't focus on the text field I was writing before. Instead, it focused on the little toolbar on the bottom of Atom. 

Then I manually open and close the terminal with the button on that toolbar, it happened again in the same way.
  I wonder if there are some ways to focus on text field that I'm using using keyboard only instead of mouse?

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0 is using node-pty-prebuilt instead unmaintained and outdated pty.js

if issues persist open a new ticket with required information.

I cannot reproduce issue in 2.9.0.

Thx =)
