### ISSUE TITLE
Atom package "platformio-ide-terminal" unresponsive. Black screen with no blinking cursor. 

### ISSUE THREAD

**Issue by dzewdu** [platformio/platformio-atom-ide-terminal#239]
Atom version 1.17.1, Windows 10, platformio 2.5.1

![git](https://cloud.githubusercontent.com/assets/22486297/26461938/b025bd96-4133-11e7-99e9-b8aee5bdf23c.PNG)

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0 is using node-pty-prebuilt instead unmaintained and outdated pty.js

if issues persist open a new ticket with required information.

Thx =)
