### ISSUE TITLE
Map terminals to  each file or folder didn't works in ATOM 1.17.0

### ISSUE THREAD

**Issue by seajean** [platformio/platformio-atom-ide-terminal#240]
After I update to ATOM 1.17.0, I found  `map terminals to  each file` didn't work anymore, terminal always open  the first project folder I added.

**Comment by ghost** [comment]
+1 for Atom 1.18. I have 10 tabs open (each with a different file) but no matter what tab I open, the terminal I opened first is visible in all tabs.

Edit: If I open a second terminal in a different tab, they do switch when I switch between tabs. But I thought the terminal would auto hide on tabs I do not open any terminal? Or is this intended?

**Comment by xerosanyam** [comment]
+1 for Atom 1.19

**Comment by matmichal** [comment]
+1 for Atom 1.23.3

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0 is using node-pty-prebuilt instead unmaintained and outdated pty.js
