### ISSUE TITLE
Tree view git integration colors not updating after `git commit`

### ISSUE THREAD

**Issue by mixelpixel** [platformio/platformio-atom-ide-terminal#242]
Thank you for an amazing tool. I use your package to quickly stage and push git commits from my local repository to GitHub all from within the Atom app (Yay!) After pushing a commit, however, the git integration color scheme in the project tree does not update to indicate the changed status of the file after a `git commit -m "msg"`. After a `git commit...` or a `git push` I can enter <kbd>⌘</kbd>+<kbd>`</kbd> to close the Terminal console and then <kbd>⌘</kbd>+<kbd>s</kbd> to "save" (?) the file and then the project tree colors will change to indicate the current updated status.

Is this extra step something which can be incorporated into the Platformio Atom IDE Terminal, or is this an issue with Atom? Thanks for a great tool. Apologies if this is the wrong place to address this kind of issue.

FWIW: macOS 10.12.5, Atom 1.17.2 x64, platformio-ide-terminal 2.5.1

**Comment by erictrometer** [comment]
I am experiencing the same issue

**Comment by the-j0k3r** [comment]
This is external issue and anything else in this project would need someone to submit a PR.
