### ISSUE TITLE
terminal unresponsive but with cursor blinking

### ISSUE THREAD

**Issue by mongrol** [platformio/platformio-atom-ide-terminal#244]
When running the terminal in Atom through any means (command, toolbar, or Serial monitor) the terminal window pops up with a blinking cursor in the top left. No text is printed either from the serial port, or by echo

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0 is using node-pty-prebuilt instead unmaintained and outdated pty.js
