### ISSUE TITLE
Opening new terminal in Win 10 causes winpty.x64.dll assert failed error

### ISSUE THREAD

**Issue by jasonc0** [platformio/platformio-atom-ide-terminal#246]
[Enter steps to reproduce:]

1. Open platformio terminal - winpty.x64.dll assert failed dialog pops up.  If I hit ignore I get the uncaught error: channel closed error - stack trace from that is below.

Terminal input does not work, nor do any commands sent to the terminal through the API.  So therefore platformio core update and other built in features do not work.  I just get the assert failed VC++ error from winpty.x64.dll every time terminal opens up.
![image](https://cloud.githubusercontent.com/assets/23383748/26808026/25e7efc0-4a28-11e7-901e-c79d724d74e6.png)

**Atom**: 1.17.2 x64
**Electron**: 1.3.15
**OS**: Microsoft Windows 10 Enterprise Insider Preview
**Thrown From**: [platformio-ide-terminal](https://github.com/platformio/platformio-atom-ide-terminal) package 2.5.1

### Stack Trace

Uncaught Error: channel closed

```
At events.js:160

Error: channel closed
    at ChildProcess.target.send (internal/child_process.js:540:16)
    at Task.module.exports.Task.send (~/AppData/Local/atom/app-1.17.2/resources/app/src/task.js:119:1)
    at PlatformIOTerminalView.module.exports.PlatformIOTerminalView.input (/packages/platformio-ide-terminal/lib/view.coffee:264:17)
    at /packages/platformio-ide-terminal/lib/view.coffee:142:8)
    at Terminal.EventEmitter.emit (/packages/platformio-ide-terminal/node_modules/term.js/src/term.js:109:12)
    at Terminal.handler (/packages/platformio-ide-terminal/node_modules/term.js/src/term.js:3493:8)
    at /packages/platformio-ide-terminal/node_modules/term.js/src/term.js:3253:12
```

### Commands

```
     -8:06.2.0 build:toggle-panel (atom-pane.pane)
     -7:46.5.0 terminal-plus:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -7:01.8.0 core:backspace (input.hidden-input)
     -4:32.3.0 platformio-ide-terminal:toggle (div.package-detail.panels-item)
```

### Non-Core Packages

```
autocomplete-clang 0.11.3 
build 0.68.0 
busy 0.7.0 
file-icons 2.1.7 
intentions 1.1.2 
language-ini 1.19.0 
linter 2.1.4 
linter-gcc 0.7.1 
linter-ui-default 1.6.0 
minimap 4.28.2 
platformio-aia 0.0.5 
platformio-ide 2.0.0-beta.6 
platformio-ide-debugger 1.2.2 
platformio-ide-terminal 2.5.1 
tool-bar 1.1.0 
```

**Comment by abbiekressner** [comment]
I am having the same problem. Have you figured out how to solve this?

**Comment by rebnik** [comment]
I got the same error and suspected the issue was caused by the Atom x64 version. I re-installed the Atom x32 with AtomSetup.exe and now it works fine.

**Comment by bzuidgeest** [comment]
from issue #297 I found removing C:\Users\username\.atom\packages\platformio-ide-terminal\node_modules\pty.js\build\Release\pty.node and restarting Atom to solve the problem.

**Comment by jasonc0** [comment]
Another user has reported that installing the VS2015 x64 redistributable package fixes this.  I haven't tried myself.
Link: https://www.microsoft.com/en-us/download/confirmation.aspx?id=48145

**Comment by bhupi99000** [comment]
Thanks @jasonc0 installing VS2015 x64 redistributable package worked for me.
Link: https://www.microsoft.com/en-us/download/confirmation.aspx?id=48145

**Comment by Kogoruhn** [comment]
Thanks to @jasonc0!
small fix of outdated links:
https://support.microsoft.com/ru-ru/help/2977003/the-latest-supported-visual-c-downloads

**Comment by ManuelZ** [comment]
I have tried all this and nothing works:

- Installed the VS2017 x64 redistributable while having Atom x64 and didn't worked.
- Installed Atom x86, and nothing
- Installed VS2017 x86 redistributable and nothing.

**Comment by jasonc0** [comment]
ThIs is still an issue? You should probably use VS Code. If you do want to use Atom the person above said that the Visual C++ 2015 redistributable fixed it, NOT 2017. Use the x64 version of both Atom and the redist.
https://www.microsoft.com/en-us/download/confirmation.aspx?id=48145

**Comment by ManuelZ** [comment]
2015 didn't allow me to install it, said another version was already installed.

**Comment by Kogoruhn** [comment]
@ManuelZ 
I rushed to conclusions: all vc-redist links were useless. And I abandoned this venture.
Today I install [ atom v1.34.0-beta0](https://github.com/atom/atom/releases/tag/v1.34.0-beta0) and YES! Terminal working!

**Comment by ManuelZ** [comment]
@Kogoruhn That's great, but did it continue working flawlessly? Because from time to time the terminal starts working for me (using v1.33) and then out of nowhere it stops opening and throws the same error.

**Comment by the-j0k3r** [comment]
duplicate of #604 #584 please post at#604
