### ISSUE TITLE
no terminal or + sign available 

### ISSUE THREAD

**Issue by almend** [platformio/platformio-atom-ide-terminal#247]
Terminal is installed but there is no "+" sign and no terminal available.

**Comment by FutoRicky** [comment]
Same issue, I see no terminal not + sign anywhere.

**Comment by rajalokan** [comment]
It would be more helpful if you provide details as well. Operating System, version of atom etc? 

I just installed on Ubuntu 16.04 and works for me.

**Comment by FutoRicky** [comment]
@rajalokan I'm running OSX 10.11.6 and atom version: 1.18.0

**Comment by kenold** [comment]
I had the same issue. Windows 10, Atom 1.18.01 x64.
I disabled the Terminal+ package, restarted Atom. Enabled the package, restarted Atom and nothing worked. It only worked after I uninstalled and re-installed the package

**Comment by dmcna005** [comment]
I am having the same issue as above. I am using mac sierra 10.12.5 and atom version 1.16.0.

**Comment by FutoRicky** [comment]
Anything on this? I was very used to having the terminal on my editor, now I'm getting frustrated it isn't working.

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0 is using node-pty-prebuilt instead unmaintained and outdated pty.js

if issues persist open a new ticket with required information.

Thx =)
