### ISSUE TITLE
Utilize Docks (Atom 1.18 have docks )

### ISSUE THREAD

**Issue by v3ss0n** [platformio/platformio-atom-ide-terminal#256]
Would be nice if we can utlize dock feature of atom.

**Comment by nocksock** [comment]
Agreed! But there's already an issue for that: https://github.com/platformio/platformio-atom-ide-terminal/issues/256

**Comment by v3ss0n** [comment]
https://github.com/platformio/platformio-atom-ide-terminal/issues/256 is my issue ..

**Comment by v3ss0n** [comment]
#230 i found.

**Comment by nocksock** [comment]
Whoops. Copy Paste fail. :)
