### ISSUE TITLE
Auto-activate virtualenv for Python environments

### ISSUE THREAD

**Issue by redeemefy** [platformio/platformio-atom-ide-terminal#257]
I can't find in the settings how to auto-activate the `virtualenv`. Normally you open a terminal window, cd to your project path, activate `virtualenv`, and then open your editor from current path. Your editor should open in the current editor, which atom does, but when I (cnrt+\`) the terminal window open inside atom but the `virtualenv` is not active.

Would be nice if the package can detect if a `virtualenv` directory exists looking first project root and then a path to a centralize folder where all `virtualenvs` lives, and then activate the appropriate env for that particular project.

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0 is using node-pty-prebuilt instead unmaintained and outdated pty.js

**Comment by Saladin1812** [comment]
This issue still persists in 2022 :)

**Comment by UziTech** [comment]
This package is no longer maintained. Please uninstall platformio-ide-terminal and install [x-terminal](https://atom.io/packages/x-terminal)
