### ISSUE TITLE
python packages not found

### ISSUE THREAD

**Issue by atsteich** [platformio/platformio-atom-ide-terminal#260]
running a .py script from within IDE Terminal gives Error that multiple python packages are not found, while running the script in linux console works fine. 
running the .py script with full path: /usr/bin/python works fine, but I can't find an option to set this path for standard usage in the IDE Terminal
Use Atom 1.18.0, Platform IO installed with package manager.

**Comment by mateorico** [comment]
Same problem!

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0.
These type issues all so far seem fixed with this release due to using node-pty-prebuilt instead unmaintained and outdated pty.js
