### ISSUE TITLE
Insert Text is executing the line after insert

### ISSUE THREAD

**Issue by Radivarig** [platformio/platformio-atom-ide-terminal#261]
Whenever I use Insert Text it appends the text to existing text and executes the line. I'd expect it to just insert the text.

Using Atom on Windows 10 with bash.exe shell override

**Comment by Radivarig** [comment]
In case this is intended functionality, it would be great to have a second button to just insert without execution.

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0 is using node-pty-prebuilt instead unmaintained and outdated pty.js
