### ISSUE TITLE
Makefile output appears slowly at first

### ISSUE THREAD

**Issue by kravlost** [platformio/platformio-atom-ide-terminal#263]
When running a Make command in the terminal, the first output lines appear very slowly then the final lines appear in a rush. In a Windows command prompt the Make output appears at an even speed.

Edit: The program can be running on an attached device several seconds before the command appears to complete in the terminal.

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0 is using node-pty-prebuilt instead unmaintained and outdated pty.js
