### ISSUE TITLE
Bottom atom bar is misplaced when terminal content reaches its end

### ISSUE THREAD

**Issue by zecarrera** [platformio/platformio-atom-ide-terminal#267]
**Steps:**
1- Open terminal
2- Maximize it
3- do any command that makes you reach bottom of the page

**Expected:**
3 - Content is properly displayed

**Actual:**
3 - Bottom Atom menu bar is displayed in the middle of the content

**Extra info:**
- Running on MAC
- Atom version 1.18.0
**Screenshot:**
<img width="1411" alt="screen shot 2017-06-29 at 11 27 57" src="https://user-images.githubusercontent.com/4092515/27683557-47dc50dc-5cbe-11e7-8e61-0400f73bdb93.png">

**Comment by mikebelanger** [comment]
Can confirm, with same steps zecarrera.

**Comment by gkid** [comment]
Duplicate of
https://github.com/platformio/platformio-atom-ide-terminal/issues/227

**Comment by the-j0k3r** [comment]
Fixed in #369
