### ISSUE TITLE
cannot download 

### ISSUE THREAD

**Issue by snaqviApps** [platformio/platformio-atom-ide-terminal#269]
when click 'install' from atom -> settings to install it, get the following big list of errors:

------------------------------------------------------------------
Installing “platformio-ide-terminal@2.5.1” failed.Hide output…

> pty.js@0.3.0 install /tmp/apm-install-dir-11761-27084-r546cc.7xuemkuik9/node_modules/platformio-ide-terminal/node_modules/pty.js
> node scripts/install.js

/tmp/apm-install-dir-11761-27084-r546cc.7xuemkuik9
└── (empty)

module.js:471
    throw err;
    ^

Error: Cannot find module '/tmp/apm-install-dir-11761-27084-r546cc.7xuemkuik9/node_modules/platformio-ide-terminal/node_modules/pty.js/scripts/install.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
npm WARN enoent ENOENT: no such file or directory, open '/tmp/apm-install-dir-11761-27084-r546cc.7xuemkuik9/package.json'
npm WARN apm-install-dir-11761-27084-r546cc.7xuemkuik9 No description
npm WARN apm-install-dir-11761-27084-r546cc.7xuemkuik9 No repository field.
npm WARN apm-install-dir-11761-27084-r546cc.7xuemkuik9 No README data
npm WARN apm-install-dir-11761-27084-r546cc.7xuemkuik9 No license field.
npm ERR! Linux 4.4.0-81-generic
npm ERR! argv "/opt/atom/resources/app/apm/bin/node" "/opt/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/hamza/.atom/.apm/.apmrc" "--userconfig" "/home/hamza/.atom/.apmrc" "install" "/tmp/d-11761-27084-1j3eicz.a99ck2csor/package.tgz" "--runtime=electron" "--target=1.3.15" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! pty.js@0.3.0 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pty.js@0.3.0 install script 'node scripts/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pty.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pty.js
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pty.js
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/apm-install-dir-11761-27084-r546cc.7xuemkuik9/npm-debug.log
npm ERR! code 1
------------------------------------------------------------------

**Comment by snaqviApps** [comment]
more: I have this configuration:
---------------------------------------

-->:/usr/share/applications$ npm -v
**5.0.3**

--> :/usr/share/applications$ apm -v
apm  1.18.1
**npm  3.10.10**
node 6.9.5 x64
python 3.6.1
git 2.7.4

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0 is using node-pty-prebuilt instead unmaintained and outdated pty.js
