### ISSUE TITLE
I cannot write anything on my the terminal. It is showing up, but I cannot write anything on it

### ISSUE THREAD

**Issue by sapnavats** [platformio/platformio-atom-ide-terminal#270]
I installed this package on atom and opened it but i cannot write anything on it. I checked the installed package on the setting, there I found out that the package hasn't been installed completely. So then I tried uninstalling it so I could install it again but the package cannot be uninstalled for some reason.

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0.
These type issues all so far seem fixed with this release due to using node-pty-prebuilt instead unmaintained and outdated pty.js
