### ISSUE TITLE
Not fully functional with node and webpack commands

### ISSUE THREAD

**Issue by xsh2047** [platformio/platformio-atom-ide-terminal#271]
![image](https://user-images.githubusercontent.com/10691031/27813232-21556122-603a-11e7-8de4-6008c8cf2b73.png)
When running webpack it throws the error displayed above. However with a regular command prompt or git bash, everything works fine.

**Comment by entozoon** [comment]
Are you running the command from the same directory in both situations? #sanityCheck

**Comment by xsh2047** [comment]
Yeah, it only works if i run webpack from an external terminal and then webpack within that terminal.

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0.
These type issues all so far seem fixed with this release due to using node-pty-prebuilt instead unmaintained and outdated pty.js
