### ISSUE TITLE
The cursor does not become inline when closing (minimizing) once after opening the terminal and reopening it

### ISSUE THREAD

**Issue by kiiiit** [platformio/platformio-atom-ide-terminal#274]
Once the terminal is opened by a shortcut or icon click once, the cursor is displayed on the terminal and it becomes inline and you can type the command, but once you minimize the terminal with the shortcut command or icon click and reopen it, it will appear in the terminal Command can not be entered without cursor being displayed. When you click on the terminal display part, the cursor is displayed and it becomes in-line state and command input is possible. I am glad if you cure it because it is my favorite plugin.

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0 is using node-pty-prebuilt instead unmaintained and outdated pty.js
