### ISSUE TITLE
Terminal icon in the atom footer not loading the terminal

### ISSUE THREAD

**Issue by lotusms** [platformio/platformio-atom-ide-terminal#279]
The latest update caused the icon in the atom footer to crash. It doesn't load the icon or anything else in the footer. The Terminal doesn't launch from the toolbar either. Reverting to `apm install platformio-ide-terminal@2.5.2` brought it back. 

Can you look into this so I can update to latest again?

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0 is using node-pty-prebuilt instead unmaintained and outdated pty.js
