### ISSUE TITLE
can't use npm command in the terminal platform.

### ISSUE THREAD

**Issue by fqyjames** [platformio/platformio-atom-ide-terminal#282]
can this problem be fixed?

**Comment by andersdigital** [comment]
What appears to be happening? I can run npm commands just fine. Are you getting errors?

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0.
These type issues all so far seem fixed with this release due to using node-pty-prebuilt instead unmaintained and outdated pty.js
