### ISSUE TITLE
keyboard shortcut for toggle not working on right side

### ISSUE THREAD

**Issue by paulbmouton** [platformio/platformio-atom-ide-terminal#284]
I'm trying to do cmd+alt+F to toggle between my terminal and open pane, which works, not all the time, but if it does, it works more often using the _left_ command and alt instead of the right. Not sure why this happens.

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0 is using node-pty-prebuilt instead unmaintained and outdated pty.js
