### ISSUE TITLE
hi platfommio-atom-ide-terminal dev~~ i report issue

### ISSUE THREAD

**Issue by JinSung-Hwang** [platformio/platformio-atom-ide-terminal#286]
hi im korean dev
i use korean(utf-8) in platformio-atom-ide-terminal

if i write korean in platformio-atom-ide-terminal , text is writed two times in platformio-atom-ide-terminal

example
i want to write '가나다라'(abcd) but now issue is writed '가나나다라라'(abbcdd)

i used font 'D2Coding' , 'monaco'  and 'monospaced font' but i have this issue

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0 is using node-pty-prebuilt instead unmaintained and outdated pty.js
