### ISSUE TITLE
at-symbol (@) not recognized

### ISSUE THREAD

**Issue by felixholub** [platformio/platformio-atom-ide-terminal#288]
If I open cmd.exe I can use the at-sign, which is alt+q on my German keyboard. Once I start up Cmder as explained in issue #272, alt+q does not produce any output, while for example alt+0 still produces }. If I open Cmder standalone, I do not have this issue.

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0 is using node-pty-prebuilt instead unmaintained and outdated pty.js
