### ISSUE TITLE
getting errors while using terminal

### ISSUE THREAD

**Issue by benjo11111** [platformio/platformio-atom-ide-terminal#293]
when i load terminal it gives me below errors.
```
bash: error importing function definition for `scl'
/bin/sh: scl: line 1: syntax error: unexpected end of file
/bin/sh: error importing function definition for `scl'
/bin/sh: module: line 1: syntax error: unexpected end of file
/bin/sh: error importing function definition for `module'
/bin/sh: scl: line 1: syntax error: unexpected end of file
/bin/sh: error importing function definition for `scl'
/bin/sh: module: line 1: syntax error: unexpected end of file
/bin/sh: error importing function definition for `module'
/bin/sh: scl: line 1: syntax error: unexpected end of file
/bin/sh: error importing function definition for `scl'
/bin/sh: module: line 1: syntax error: unexpected end of file
/bin/sh: error importing function definition for `module'
```

OS : FEDORA 26
ATOM : 1.18.0-0.1

**Comment by zwolfe21** [comment]
I have this exact error as well. 

OS: Fedora 26
Atom: 1.18.0

**Comment by zwolfe21** [comment]
Hmm... This does not appear if atom is launched via terminal. Only occurs (for me) if launched from Gnome

**Comment by HerX121** [comment]
This problem is a user misconfiguration in Fedora, try the solution of @cnicodeme (https://github.com/AtomLinter/linter-flake8/issues/165)

For all others that have the same issue here, and are using Fedora, the solution is simple :

1.  Remove scl-utils : `sudo dnf remove scl-utils`. Don't worry, it's not useful on Fedora (it's more RHEL related)
2.  Reboot, and you won't have the problem again. **This is important**, if you don't reboot, nothing will change. (Don't ask me why!)

**Comment by alexfornuto** [comment]
I'm on Fedora 27, and removed `scl-utils` + reboot to solve some but not all of the lines coming up on a new terminal.

For anyone else who gets here first via Google with additional errors, see [this issue comment](https://github.com/platformio/platformio-atom-ide-terminal/issues/120#issuecomment-274756065) for the other half of the solution.

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0 is using node-pty-prebuilt instead unmaintained and outdated pty.js

**Comment by alexfornuto** [comment]
....Wat? Please review and add structure to the comment above, to increase clarity.

**Comment by the-j0k3r** [comment]
@alexfornuto see https://github.com/platformio/platformio-atom-ide-terminal/commit/f64888d6d134f7e06bbb13a762dfd45335e8a4ba

Its a considerable change in the application, this project no longer uses pty.js, any previous reports are invalid against node-pty-prebuilt version which start at platfomio-ide-terminal v2.9.0.
pty.js is an obsolete unmaintained project, its not suitable as a stable dependency and was quite buggy, node-pty-prebuilt is current and under active development, its more stable and reliable which results in a more robust application..

If platfomio-ide-terminal v2.9.0 doesnt fix the issue, a **new** report with the requested/required information should be opened.

If this is not clear enough, state clearly what your doubts are, simply asking for clarity isnt clear enough to what exactly your doubt(s) are.

**Comment by alexfornuto** [comment]
@the-j0k3r thanks, that clears up my confusion.

For reference, my issue wasn't with the technical decisions made. Your sentence simply lacked the form (punctuation, etc) required to convey the information. Now I understand, and if and when I use Atom again and hit an issue with the newer versions I will open a new issue.
