### ISSUE TITLE
unknown bin

### ISSUE THREAD

**Issue by gmcmenimen** [platformio/platformio-atom-ide-terminal#298]
Some installed packages could not be loaded because they contain native modules that were compiled for an earlier version of Atom.
 
Cannot find module '/Users/gregmcmenimen/.atom/packages/platformio-ide-terminal/node_modules/pty.js/bin'

**Comment by ivankravets** [comment]
https://github.com/platformio/platformio-atom-ide-terminal/releases/tag/v2.5.5
