### ISSUE TITLE
[SOLVED] Blank after latest update

### ISSUE THREAD

**Issue by barayuda** [platformio/platformio-atom-ide-terminal#301]
SOLVED
---

Hello, friend, I got the solution for this.
1. Uninstall platformio-ide-terminal in Atom 1.18.0
2. Update Atom 1.18.0 to 1.19.0
3. Install again platformio-ide-terminal
4. Rebuild package (click rebuild button in top right)
5. Done. 💯 

---

![image](https://user-images.githubusercontent.com/520463/29113089-9ed9d330-7d22-11e7-8a4f-d751b6ebaf94.png)

Hi platformio team, got this issue after latest update in my Atom 1.18.0 x64 Windows 10

**Comment by barayuda** [comment]
Sorry, I think the solution in #299
I will trying that first to rebuild

**Comment by barayuda** [comment]
After tried to rebuild, uninstall and install again, still get the blank issue like screenshot before. 
Please, need help to fix this. Thank you.

**Comment by barayuda** [comment]
SOLVED:

Hello friend, I got solution for this.
1. Uninstall platformio-ide-terminal in Atom 1.18.0
2. Update Atom 1.18.0 to 1.19.0
3. Install again platformio-ide-terminal
4. Rebuild package (click rebuild button in top right)
5. Done. 💯

**Comment by ivankravets** [comment]
Thanks! https://github.com/platformio/platformio-atom-ide-terminal/issues/297
