### ISSUE TITLE
Terminal appears but doesnt accept any text

### ISSUE THREAD

**Issue by JeevanJB** [platformio/platformio-atom-ide-terminal#303]
Hello,
Things were working well till 2.5.4 version, now when I updated it to 2.5.5, terminal appears blank.
Previously I had default appearance of my Django project in it.
Please help to resolve the issue. The issue is higlighted in yellow box within attachment
![issue](https://user-images.githubusercontent.com/30318221/29118186-89b4e548-7d1e-11e7-839a-a6d7e8dc8519.png)

**Comment by ivankravets** [comment]
https://github.com/platformio/platformio-atom-ide-terminal/issues/297
