### ISSUE TITLE
Upgraded to 2.5.5 and now platformio-atom-ide-terminal no longer works

### ISSUE THREAD

**Issue by indianabeck** [platformio/platformio-atom-ide-terminal#304]
Upgraded to 2.5.5 and now platformio-atom-ide-terminal no longer works. The + and - no longer show on the bar at the bottom of the screen and "new terminal" does nothing from the menu bar.

Atom 1.19.0 x64 Windows 10

**Comment by indianabeck** [comment]
untitled
Incompatible Packages
Some installed packages could not be loaded because they contain native modules that were compiled for an earlier version of Atom.Rebuild Packages
Package Settings
platformio-ide-terminal 2.5.5

bin@unknown – Cannot find module 'C:\Users\dbeck\.atom\packages\platformio-ide-terminal\node_modules\pty.js\bin'
bin@unknown – Cannot find module 'C:\Users\dbeck\.atom\packages\platformio-ide-terminal\node_modules\pty.js\bin'
bin@unknown – Cannot find module 'C:\Users\dbeck\.atom\packages\platformio-ide-terminal\node_modules\pty.js\bin'
bin@unknown – Cannot find module 'C:\Users\dbeck\.atom\packages\platformio-ide-terminal\node_modules\pty.js\bin'
bin@unknown – Cannot find module 'C:\Users\dbeck\.atom\packages\platformio-ide-terminal\node_modules\pty.js\bin'
bin@unknown – Cannot find module 'C:\Users\dbeck\.atom\packages\platformio-ide-terminal\node_modules\pty.js\bin'
bin@unknown – Cannot find module 'C:\Users\dbeck\.atom\packages\platformio-ide-terminal\node_modules\pty.js\bin'
bin@unknown – Cannot find module 'C:\Users\dbeck\.atom\packages\platformio-ide-terminal\node_modules\pty.js\bin'

**Comment by indianabeck** [comment]
I rebuilt the package and now it works.

**Comment by JeevanJB** [comment]
Hi Indianabeck
I am facing the same issue.
Can you pls tell the exact steps to resolve the issue

**Comment by indianabeck** [comment]
At the bottom right of Atom you should see a red bug.  Click it and you will see the errors listed above and a "rebuild" button.  Click Rebuild and then restart.

**Comment by insight1111** [comment]
Hello, indianabeck!
I am facing same issue, too. And you save me! very thank you.
my probrem was fixed.

**Comment by ivankravets** [comment]
Thanks! See https://github.com/platformio/platformio-atom-ide-terminal/issues/297#issuecomment-321260637

**Comment by JeevanJB** [comment]
Hello Indianbeck,
Thanks for the solution provided, issue resolved

**Comment by ivankravets** [comment]
https://github.com/platformio/platformio-atom-ide-terminal/issues/297
