### ISSUE TITLE
Open terminal on the right/left of the screen

### ISSUE THREAD

**Issue by finferflu** [platformio/platformio-atom-ide-terminal#306]
I'm wondering if it's possible to have the terminal pop up from the sides, rather than from the bottom, given that the horizontal screen estate tends to be more abundant than the vertical one. Any thoughts?

Thanks!

**Comment by vmasrani** [comment]
Second this!

**Comment by ezequielm** [comment]
+1

**Comment by dbeja** [comment]
+1

**Comment by AdnanHodzic** [comment]
This request has been open for awhile now, are there any updates?

**Comment by MarMun** [comment]
+1

**Comment by dorian-marchal** [comment]
In `terminal-plus`, you can drag'n'drop the terminal to the tab bar. It's broken in `platformio-atom-ide-terminal`.

**Comment by the-j0k3r** [comment]
dupe of https://github.com/platformio/platformio-atom-ide-terminal/issues/198
