### ISSUE TITLE
teminal install but not opening up

### ISSUE THREAD

**Issue by prashant2796** [platformio/platformio-atom-ide-terminal#307]
I have installed platformio IDE terminal for atom but I am not able to open it. Seems to be some issue with it.

**Comment by soundslikeinfo** [comment]
Started happening to me too and I am on Atom 1.19 when the problem began

**Comment by gangwarily** [comment]
It seems to be an issue with the toggle keyboard shortcut. Using `ALT + SHIFT + T` to open a new Terminal tab and going Packages -> platformio-ide-terminal -> Toggle also works.

**Comment by soundslikeinfo** [comment]
> bin@unknown – Cannot find module '/Users/greg/.atom/packages/platformio-ide-terminal/node_modules/pty.js/bin'
bin@unknown – Cannot find module '/Users/greg/.atom/packages/platformio-ide-terminal/node_modules/pty.js/bin'
bin@unknown – Cannot find module '/Users/greg/.atom/packages/platformio-ide-terminal/node_modules/pty.js/bin'
bin@unknown – Cannot find module '/Users/greg/.atom/packages/platformio-ide-terminal/node_modules/pty.js/bin'
bin@unknown – Cannot find module '/Users/greg/.atom/packages/platformio-ide-terminal/node_modules/pty.js/bin'
bin@unknown – Cannot find module '/Users/greg/.atom/packages/platformio-ide-terminal/node_modules/pty.js/bin'
bin@unknown – Cannot find module '/Users/greg/.atom/packages/platformio-ide-terminal/node_modules/pty.js/bin'
bin@unknown – Cannot find module '/Users/greg/.atom/packages/platformio-ide-terminal/node_modules/pty.js/bin'

**Comment by mikeerickson** [comment]
I receive a bug issue (in the status bar) which provides.  This started happening when I upgraded to Atom 1.19 (as others have reported).  Accessing from menu item does not work

![image](https://user-images.githubusercontent.com/183153/29136431-159bf182-7cf2-11e7-8c60-4de5d9192165.png)

**Comment by soundslikeinfo** [comment]
@mike Hit the **Rebuild Packages** and everything is fixed!

**Comment by mikeerickson** [comment]
@graphicagenda Yep, just tried that and all is good now :-)

**Comment by barayuda** [comment]
Sorry @graphicagenda ~~I did it, but still can't open up~~ Solved 😄  #301

**Comment by Zhythero** [comment]
Thanks @graphicagenda, that  solved my problem.
Isn't it time to close this issue?

**Comment by ivankravets** [comment]
https://github.com/platformio/platformio-atom-ide-terminal/issues/297
