### ISSUE TITLE
"Some installed packages could not be loaded because they contain native modules that were compiled for an earlier version of Atom."

### ISSUE THREAD

**Issue by ghost** [platformio/platformio-atom-ide-terminal#308]
bin@unknown – Cannot find module 'C:\Users\Zel\.atom\packages\platformio-ide-terminal\node_modules\pty.js\bin'
bin@unknown – Cannot find module 'C:\Users\Zel\.atom\packages\platformio-ide-terminal\node_modules\pty.js\bin'
bin@unknown – Cannot find module 'C:\Users\Zel\.atom\packages\platformio-ide-terminal\node_modules\pty.js\bin'
bin@unknown – Cannot find module 'C:\Users\Zel\.atom\packages\platformio-ide-terminal\node_modules\pty.js\bin'
bin@unknown – Cannot find module 'C:\Users\Zel\.atom\packages\platformio-ide-terminal\node_modules\pty.js\bin'
bin@unknown – Cannot find module 'C:\Users\Zel\.atom\packages\platformio-ide-terminal\node_modules\pty.js\bin'
bin@unknown – Cannot find module 'C:\Users\Zel\.atom\packages\platformio-ide-terminal\node_modules\pty.js\bin'
bin@unknown – Cannot find module 'C:\Users\Zel\.atom\packages\platformio-ide-terminal\node_modules\pty.js\bin'

**Comment by quanru** [comment]
+1 atom 1.19.0 x64 mac

**Comment by Zhythero** [comment]
@sawyerwatts duplicate of #307, the fix is also there.

**Comment by ivankravets** [comment]
https://github.com/platformio/platformio-atom-ide-terminal/issues/297
