### ISSUE TITLE
Feature request: Be able to persist terminals across relaunches

### ISSUE THREAD

**Issue by fiso** [platformio/platformio-atom-ide-terminal#309]
Whenever I restart Atom, I need to start a couple of new terminals in the correct working directories, and then set their colors and names, before starting the processes I want running in them. I'd love to be able to tag a terminal as "sticky", so that it will automatically reopen when I relaunch Atom, and remember its color, name and cwd.

**Comment by aaronovz1** [comment]
Another neat feature on this would be if the terminal could persist its environment too.

**Comment by the-j0k3r** [comment]
dulicate of #91
