### ISSUE TITLE
Cannot open terminal

### ISSUE THREAD

**Issue by skortela** [platformio/platformio-atom-ide-terminal#310]
Terminal stopped working!
When tryed to open terminal I got following error message:
  PlatformIO: Terminal service is not registered.
  Make sure that "platformio-ide-terminal" package is installed and activated.

I have tryed uninstalling & reinstalling whole atom & platformio & platformio-ide-terminal.
Environment Win10.

**Comment by ivankravets** [comment]
See https://github.com/platformio/platformio-atom-ide-terminal/issues/297
