### ISSUE TITLE
Uncaught Error: channel closed

### ISSUE THREAD

**Issue by ghost** [platformio/platformio-atom-ide-terminal#312]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.0 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Home
**Thrown From**: [platformio-ide-terminal](https://github.com/platformio/platformio-atom-ide-terminal) package 2.5.5

### Stack Trace

Uncaught Error: channel closed

```
At events.js:160

Error: channel closed
    at ChildProcess.target.send (internal/child_process.js:548:16)
    at Task.module.exports.Task.send (~/AppData/Local/atom/app-1.19.0/resources/app/src/task.js:113:33)
    at PlatformIOTerminalView.module.exports.PlatformIOTerminalView.input (/packages/platformio-ide-terminal/lib/view.coffee:264:17)
    at /packages/platformio-ide-terminal/lib/view.coffee:142:8)
    at Terminal.EventEmitter.emit (/packages/platformio-ide-terminal/node_modules/term.js/src/term.js:109:12)
    at Terminal.handler (/packages/platformio-ide-terminal/node_modules/term.js/src/term.js:3493:8)
    at /packages/platformio-ide-terminal/node_modules/term.js/src/term.js:3253:12
```

### Commands

```
     -3:07.2.0 core:copy (span.syntax--keyword.syntax--control.syntax--repeat.syntax--python)
  2x -3:03.4.0 platformio-ide-terminal:paste (textarea.)
```

### Non-Core Packages

```
platformio-ide-terminal 2.5.5 
```

**Comment by MarcoNiemann** [comment]
+1 

Get the same error with `Atom 1.19.0 x64` on a `Windows 8.1 x64` computer.

**Comment by EswarJ** [comment]
+1

**Comment by mlewk** [comment]
My terminal doesnt even show up anymore after I updated

**Comment by mak633** [comment]
I have the same problem

**Comment by ayunus** [comment]
Same here. I re-installed Atom and this same error came. Anyone know hot to solve this?

**Comment by Bobthebully** [comment]
+1
Same error, Anyone got help?

**Comment by rasw** [comment]
Hi Everyone

Both the serial monitor and terminal are crashing with the following c++ error

Assertion failed!

Program: ...minal\node_modules\pty.js\build\Release\winpty.dll
File: ..\..\..\deps\winpty\libwinpty\winpty.cc
Line: 148

Expression: pathExists(ret)

-------------------------------------------------------------
Exported trace below

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.2 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Home
**Thrown From**: [platformio-ide-terminal](https://github.com/platformio/platformio-atom-ide-terminal) package 2.5.5


### Stack Trace

Uncaught Error: channel closed

```
At events.js:160

Error: channel closed
    at ChildProcess.target.send (internal/child_process.js:548:16)
    at Task.module.exports.Task.send (~/AppData/Local/atom/app-1.19.2/resources/app/src/task.js:113:33)
    at PlatformIOTerminalView.module.exports.PlatformIOTerminalView.input (/packages/platformio-ide-terminal/lib/view.coffee:264:17)
    at /packages/platformio-ide-terminal/lib/view.coffee:142:8)
    at Terminal.EventEmitter.emit (/packages/build/node_modules/term.js/src/term.js:109:12)
    at Terminal.handler (/packages/build/node_modules/term.js/src/term.js:3493:8)
    at /packages/build/node_modules/term.js/src/term.js:3253:12
```

### Commands

```
     -2:24.8.0 platformio-ide:maintenance.serial-monitor (input.hidden-input)
     -1:19.3.0 platformio-ide:maintenance.open-terminal (atom-workspace.workspace.scrollbars-visible-always.theme-one-light-syntax.theme-atom-light-ui)
```

### Non-Core Packages

```
autocomplete-clang 0.11.3 
build 0.68.0 
busy 0.7.0 
file-icons 2.1.11 
intentions 1.1.5 
language-ini 1.19.0 
linter 2.2.0 
linter-gcc 0.7.1 
linter-ui-default 1.6.7 
minimap 4.29.6 
platformio-ide 2.0.0-beta.8 
platformio-ide-debugger 1.2.3 
platformio-ide-terminal 2.5.5 
tool-bar 1.1.0 
```

**Comment by elicutler** [comment]
+1

**Comment by the-j0k3r** [comment]
@elicutler your +1 to a bug report of an ancient bug report is welcome but this needs to be reproduced with current Atom 1.28.0 and platformio-ide-terminal 2.8.3 and if it still an issue a detailed report updated with full information would be nice.

**Comment by elicutler** [comment]
@the-j0k3r Sorry, I am new to Github; I am using Atom 1.28.0 and platformio-ide-terminal 2.8.3. My computer is running Windows 10. When I try to open a terminal I first get a Microsoft Visual C++ Runtime Library error:

![image](https://user-images.githubusercontent.com/28848755/41944707-06dc453e-795e-11e8-80bc-fa41d15f96e0.png)

If I retry or ignore the error and then attempt to type in the terminal Window, I get the following error message:
`Uncaught channel closed
events.js:183
Hide Stack Trace
Error [ERR_IPC_CHANNEL_CLOSED]: channel closed
    at ChildProcess.target.send (internal/child_process.js:588:16)
    at Task.module.exports.Task.send (C:\Users\cutle\AppData\Local\atom\app-1.28.0\resources\app\src\task.js:113:33)
    at PlatformIOTerminalView.module.exports.PlatformIOTerminalView.input (file:///C:/Users/cutle/.atom/packages/platformio-ide-terminal/lib/view.coffee:271:17)
    at Terminal.<anonymous> (file:///C:/Users/cutle/.atom/packages/platformio-ide-terminal/lib/view.coffee:149:8)
    at Terminal.EventEmitter.emit (C:\Users\cutle\.atom\packages\platformio-ide-terminal\node_modules\term.js\src\term.js:109:12)
    at Terminal.handler (C:\Users\cutle\.atom\packages\platformio-ide-terminal\node_modules\term.js\src\term.js:3493:8)
    at C:\Users\cutle\.atom\packages\platformio-ide-terminal\node_modules\term.js\src\term.js:3253:12`

UPDATE: Actually, I was trying to reproduce the error a second time, and funnily enough, this time no error occurred and I was able to access the terminal, even though yesterday the error persisted after multiple attempts. But I just tried a couple more times and the error has not yet resurfaced. So, at least for now the issue seems to have resolved itself.

**Comment by the-j0k3r** [comment]
> @the-j0k3r Sorry, I am new to Github

Its fine, dont worry about it.

> UPDATE: Actually, I was trying to reproduce the error a second time, and funnily enough, this time no error occurred

This is what  I suspected, Im glad your error is gone and that by magic things have solved itself.

@ivankravets this ticket served its purpose IMO, it should be closed along with other tickets older than 6 months because anything this old is likely to be irrelevant in newer Atom + platformio-ide-terminal

**Comment by elicutler** [comment]
@the-j0k3r The error actually came back again and persisted for a while even as I tried to close and open new terminals, restart Atom, etc. What *seemed* to make it go away for a second time was to first open my terminal normally from Windows, and then open the terminal through Atom. But I'm not confident that this is actually what fixed it.

**Comment by the-j0k3r** [comment]
This is highly unusual.

I feel tempted to ask for more details about your system and Atom installation even your Atom config.cson. If youre not famialir here is the basics.

The config.cson holds configuration for Atom and related addons(packages) Its has no sensitive information but check it for your piece of mind, unfortunately when you try other packages and later uninstall them, they leave behind their config entries, some even leave files in the Atom install directory .
Theoretically, they shouldn't interfere with other packages, but Ive learned that theories are just that, theories and in practice weird things happen.

First. I think you should open a new ticket with this information and leave this dead ticket die a normal death.

So please provide:

* a screenshot of your Atom install directory.
* a screenshot of you packages directory located at <username>\.atom\packages

something like.
![capture](https://user-images.githubusercontent.com/31389848/41950390-db18fb94-79bd-11e8-96d5-4b995e971579.PNG)

From an external console/terminal **not inside** Atom run.

* the output of `apm -v`
* the output of `atom -v`

Details about your OS version/type.

If you keep experiencing these issues the real only choice is to try isolate the culprit, sometimes some addons interfere with other addons.

Follow this https://flight-manual.atom.io/hacking-atom/sections/debugging/#reset-to-factory-defaults

Essentially you 

1. FIRST create  a backup directory of your existent Atom directory so you can revert to it after debugging is done 
2. then start with a fresh Atom , as if you just installed it.
3. Then you install platformio-ide-terminal 2.8.3 and see if you still get issues.

If you working and everything still behaves OK and no more issues persist you start installing previous non core packages one by one, and at each step see which (if any) causes this issue.

Sorry for this long thing but the errors you posted dont really help.

**Comment by the-j0k3r** [comment]
@ivankravets please close, no longer relevant
