### ISSUE TITLE
platformio-atom-ide-terminal installed but doesn't work

### ISSUE THREAD

**Issue by spoonmanchen** [platformio/platformio-atom-ide-terminal#313]
Today I first install AtomSetup-x64.exe on My windows 64-bit machine
When I try to install "platformio-atom-ide-terminal", it works well without errors 
However, no icon in the leftlower corner was found and the package menu is grey.
![image](https://user-images.githubusercontent.com/11889533/29200696-f722e24e-7e89-11e7-9cc3-d63f61de75fd.png)
Plus: Terminal Plus can't be installed too which show 
`Failed to install terminal-plus because Git was not found.

The terminal-plus package has module dependencies that cannot be installed without Git.

You need to install Git and add it to your path environment variable in order to install this package.

You can install Git by downloading, installing, and launching GitHub for Windows: https://windows.github.com

Run apm -v after installing Git to see what version has been detected.`

**Comment by paulcarroty** [comment]
https://github.com/platformio/platformio-atom-ide-terminal/issues/297

**Comment by ivankravets** [comment]
https://github.com/platformio/platformio-atom-ide-terminal/issues/297
