### ISSUE TITLE
platformio Some installed packages could not be loaded because they contain native modules that were compiled for an earlier version of Atom.

### ISSUE THREAD

**Issue by ohpoop** [platformio/platformio-atom-ide-terminal#314]
When I open atom in dev mode (to write python code), i keep getting a bug that says "some installed packages could not be loaded becuase they contain native modules that were compiled for an earlier version of atom." I clicked on rebuild packages which happened successfully. When I reload atom, the same error comes up again. Then the error started happening in non-dev mode but uninstalling/re-installing platformio-ide-terminal fixed that. However, the problem seems to be persistent with dev mode. I get the following error repeated 8 times.

platformio-ide-terminal 2.5.5
bin@unknown – Cannot find module 'C:\Users\xx\.atom\packages\platformio-ide-terminal\node_modules\pty.js\bin'

I'm running atom 1.19.0

I checked to make sure that this "bin" folder actually exists.

I poked around in atom and found this but it wasn't helpful to me.
C:\Users\xx\AppData\Local\atom\app-1.19.0\resources\app\node_modules\react-dom\lib\ReactDOM.js:73 Download the React DevTools and use an HTTP server (instead of a file: URL) for a better development experience: https://fb.me/react-devtools
C:\Users\xx\AppData\Local\atom\app-1.19.0\resources\app\node_modules\react\lib\lowPriorityWarni…:40 Warning: Accessing PropTypes via the main React package is deprecated, and will be removed in  React v16.0. Use the latest available v15.* prop-types package from npm instead. For info on usage, compatibility, migration and more, see https://fb.me/prop-types-docs
printWarning @ C:\Users\xx\AppData\Local\atom\app-1.19.0\resources\app\node_modules\react\lib\lowPriorityWarni…:40
tree-view.coffee:69 IntersectionObserver.observe(target): target element is not a descendant of root.
TreeView @ tree-view.coffee:69
package.coffee:548 Failed to require the main module of 'platformio-ide-terminal' because it requires one or more incompatible native modules (bin, bin, bin, bin, bin, bin, bin, bin).
Run `apm rebuild` in the package directory and restart Atom to resolve.
module.exports.Package.requireMainModule @ package.coffee:548

I googled and again didn't find anything. I would appreciate help with fixing this. Also, i'm a newbie so i could use some pointers on how to identify and fix such problems myself in the future without seeking help! Also, what more information should I provide to help you diagnose (doesn't seem like I've provided enough info but not sure what else to provide).

**Comment by ivankravets** [comment]
https://github.com/platformio/platformio-atom-ide-terminal/issues/297
