### ISSUE TITLE
PlatformIO IDE Terminal V2.5.5 dev mode error, Atom 1.19 

### ISSUE THREAD

**Issue by arvindmuthu** [platformio/platformio-atom-ide-terminal#315]
Its is working fine before three days...after the update...dev mode not working crashes the platformIO-IDE-terminal
Tried all possibilities, even complete uninstall atom and reinstalled but still the same
Below are the error
<img width="797" alt="screen shot 2017-08-11 at 11 59 12 pm" src="https://user-images.githubusercontent.com/18085535/29227889-21541c88-7ef1-11e7-9c33-8e239d3aedfd.png">

**Comment by arvindmuthu** [comment]
Tried the solution given in the previous post 
Open atom
Upgrade Atom to v1.19
Click on the red bug on the right side of the statusbar
Move your mouse cursor on the error message which states that "some packages were build for a previous version of atom" to the right corner -> a button will appear to rebuild packages
Press on the newly appearing button
Reload atom
Uninstall platformio-ide-terminal package
Install platformio-ide-terminal package

But still not working...it was working fine before the last update....
Is there any option to rollback the version ????

**Comment by ivankravets** [comment]
https://github.com/platformio/platformio-atom-ide-terminal/issues/297
