### ISSUE TITLE
Can't get terminal window to show up Atom 1.19.0 Windows 7

### ISSUE THREAD

**Issue by piningforfjords** [platformio/platformio-atom-ide-terminal#316]
Used this extension before and it worked great.  Tried to install in on a new setup/new computer and no matter what I do in terms of opening instances I can't get the terminal to show up.  This is on a laptop so the screen resolution cold play some role (1366x78).

**Comment by khoa-io** [comment]
This happens not only in Windows 7 but also in Linux. I updated Atom to 1.19.0 and terminal didn't show up anymore.

**Comment by khoa-io** [comment]
It is solved when I rebuilt package inside atom following instructions from https://github.com/platformio/platformio-atom-ide-terminal/issues/297.

**Comment by piningforfjords** [comment]
Thanks very much for the very quick help.  Worked like a charm.

**Comment by ivankravets** [comment]
https://github.com/platformio/platformio-atom-ide-terminal/issues/297
