### ISSUE TITLE
fail to install packages in atom windows

### ISSUE THREAD

**Issue by YoucefBnm** [platformio/platformio-atom-ide-terminal#317]
Installing “platformio-ide-terminal@2.5.5” failed.
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open 'C:\Users\.\AppData\Local\Temp\d-117713-4736-5kfg51.vxgulyp66r\package.tgz'
at Error (native)

**Comment by ivankravets** [comment]
https://github.com/platformio/platformio-atom-ide-terminal/issues/297
