### ISSUE TITLE
Some installed packages could not be loaded because they contain native modules that were compiled for an earlier version of Atom.

### ISSUE THREAD

**Issue by ghost** [platformio/platformio-atom-ide-terminal#318]
Cannot find module '/Users/user-name/.atom/packages/platformio-ide-terminal/node_modules/pty.js/bin'

**Comment by arvindmuthu** [comment]
Same here!

**Comment by kirontoo** [comment]
This issue is solve by following the instructions in #297

**Comment by ivankravets** [comment]
https://github.com/platformio/platformio-atom-ide-terminal/issues/297
