### ISSUE TITLE
terminal icon with a plus sign at the bottom left disappeared and reinstalling doesn't help

### ISSUE THREAD

**Issue by bogomazov** [platformio/platformio-atom-ide-terminal#321]
<img width="1096" alt="screen shot 2017-08-14 at 12 36 56 pm" src="https://user-images.githubusercontent.com/6625496/29266397-4ca34492-80ed-11e7-90f8-3693184f644b.png">
<img width="480" alt="screen shot 2017-08-14 at 12 38 01 pm" src="https://user-images.githubusercontent.com/6625496/29266444-785906bc-80ed-11e7-9ff1-00052a3c7bb1.png">

**Comment by ivankravets** [comment]
https://github.com/platformio/platformio-atom-ide-terminal/issues/297
