### ISSUE TITLE
platformio incompatible with Atom version 1.19.0

### ISSUE THREAD

**Issue by alsGitHub270** [platformio/platformio-atom-ide-terminal#322]
I've uninstalled and re-installed several times with no success.
![screen shot 2017-08-14 at 2 06 53 pm](https://user-images.githubusercontent.com/23367180/29284808-24ab9a0e-80fa-11e7-8dad-b1aae3cb490e.png)

Please help.
aadolfsen@yahoo.com

**Comment by objectkit** [comment]
see #297

**Comment by ivankravets** [comment]
https://github.com/platformio/platformio-atom-ide-terminal/issues/297
