### ISSUE TITLE
platformio-ide-terminal + Atom 2.5.5 doesn't work

### ISSUE THREAD

**Issue by ankitchadha** [platformio/platformio-atom-ide-terminal#323]
Fresh installation: 2.5.5 + Atom 1.91.64 on a Mac. After installing platformio-ide-terminal, I see errors saying:

Some installed packages could not be loaded because they contain native modules that were compiled for an earlier version of Atom.Rebuild Packages

platformio-ide-terminal 2.5.5

bin@unknown – Cannot find module '/Users/achadha/.atom/packages/platformio-ide-terminal/node_modules/pty.js/bin'
bin@unknown – Cannot find module '/Users/achadha/.atom/packages/platformio-ide-terminal/node_modules/pty.js/bin'
bin@unknown – Cannot find module '/Users/achadha/.atom/packages/platformio-ide-terminal/node_modules/pty.js/bin'
bin@unknown – Cannot find module '/Users/achadha/.atom/packages/platformio-ide-terminal/node_modules/pty.js/bin'
bin@unknown – Cannot find module '/Users/achadha/.atom/packages/platformio-ide-terminal/node_modules/pty.js/bin'
bin@unknown – Cannot find module '/Users/achadha/.atom/packages/platformio-ide-terminal/node_modules/pty.js/bin'
bin@unknown – Cannot find module '/Users/achadha/.atom/packages/platformio-ide-terminal/node_modules/pty.js/bin'
bin@unknown – Cannot find module '/Users/achadha/.atom/packages/platformio-ide-terminal/node_modules/pty.js/bin'

Rebuilding packages (using the 'rebuild package' button does not help)

**Comment by acanturgut** [comment]
Please solve this issue 👍

**Comment by ivankravets** [comment]
https://github.com/platformio/platformio-atom-ide-terminal/issues/297

**Comment by ankitchadha** [comment]
I have a MAC (El Capitan), and I tried the steps mentioned in the 'solution' section. When I rebuild, uninstall-and-reinstall platformio-ide-terminal, I still get the same error:

Some installed packages could not be loaded because they contain native modules that were compiled for an earlier version of Atom.

bin@unknown – Cannot find module '/Users/achadha/.atom/packages/platformio-ide-terminal/node_modules/pty.js/bin'
bin@unknown – Cannot find module '/Users/achadha/.atom/packages/platformio-ide-terminal/node_modules/pty.js/bin'
bin@unknown – Cannot find module '/Users/achadha/.atom/packages/platformio-ide-terminal/node_modules/pty.js/bin'
bin@unknown – Cannot find module '/Users/achadha/.atom/packages/platformio-ide-terminal/node_modules/pty.js/bin'
bin@unknown – Cannot find module '/Users/achadha/.atom/packages/platformio-ide-terminal/node_modules/pty.js/bin'
bin@unknown – Cannot find module '/Users/achadha/.atom/packages/platformio-ide-terminal/node_modules/pty.js/bin'
bin@unknown – Cannot find module '/Users/achadha/.atom/packages/platformio-ide-terminal/node_modules/pty.js/bin'
bin@unknown – Cannot find module '/Users/achadha/.atom/packages/platformio-ide-terminal/node_modules/pty.js/bin'
