### ISSUE TITLE
white space related error

### ISSUE THREAD

**Issue by jacknlliu** [platformio/platformio-atom-ide-terminal#324]
I type the following command in this terminal,
```sh
echo "export test_var="Hello""   >  test.sh
```
then I  use `cat` on it, 
```sh
$ cat test.sh

export test_var=Hello
``` 

then I copy this output use right mouse, and paste to the terminal, then replay it. But I got the followoing errors
```
$ export test_var=Hello
bash: export test_var=Hello: command not found...
```
And then I delete the space between `export` and `test_var`, and re-type a space, then it works correctly.

It's amazing!

I use Atom 1.19.0 with platform-ide-terminal 2.5.5.

**Comment by contentfree** [comment]
The space that's being printed / converted to a non-breaking space for some strange reason which, when you paste it and try to run it, fails because the non-breaking space isn't a space and therefore not treated as a separator. 

#365 duplicates this.

**Comment by the-j0k3r** [comment]
Please retest with platformio-atom-ide-terminal 2.9.0
