### ISSUE TITLE
Version 2.5.5 not working in atom 1.18.0 !!?

### ISSUE THREAD

**Issue by zunsakai** [platformio/platformio-atom-ide-terminal#333]
![29107754-f9adfad0-7cdb-11e7-9aa5-9fec71c4c460](https://user-images.githubusercontent.com/8158019/29453844-487bcf9c-8435-11e7-8fdd-4608bfd99b0f.png)
What problem ?

**Comment by zunsakai** [comment]
after "apm rebuild" =>
![image](https://user-images.githubusercontent.com/8158019/29453960-aeac9328-8435-11e7-965b-10d2e9bb3f64.png)
just a black screen ..., no type, no one, ...

**Comment by ivankravets** [comment]
https://github.com/platformio/platformio-atom-ide-terminal/issues/297
