### ISSUE TITLE
Failed to delete platformio-ide-terminal: EPERM: operation not permitted

### ISSUE THREAD

**Issue by arinaspb** [platformio/platformio-atom-ide-terminal#335]
Can't uninstall on atom 1.19.0 ... local administrator, still getting permission issue... why is that?

`C:\WINDOWS\system32>apm uninstall platformio-ide-terminal
Uninstalling platformio-ide-terminal failed
Failed to delete platformio-ide-terminal: EPERM: operation not permitted, lstat 'C:\Users\username\.atom\packages\platformio-ide-terminal\node_modules\pty.js\bin\win32\x64_m53\winpty-agent.exe'

C:\WINDOWS\system32>date
The current date is: 19-Aug-17`

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0 is using node-pty-prebuilt instead unmaintained and outdated pty.js
