### ISSUE TITLE
[help] ATOM trouble with installation

### ISSUE THREAD

**Issue by cerberlink** [platformio/platformio-atom-ide-terminal#336]
I cannot install the terminal into the atom. The Atom has 1.19.2 version on my iMac. Can you explain? Thank you very much
<img width="1610" alt="screen shot 2017-08-19 at 4 06 27 am" src="https://user-images.githubusercontent.com/11153290/29486131-f89e694e-8493-11e7-8629-8f486f27efa9.png">

**Comment by evle** [comment]
I got the same problem but now it works.
Try to rebuild the package and restart atom

**Comment by cerberlink** [comment]
Evle, I did try to rebuild the package and restart the atom but It still appears the same problem.

**Comment by ivankravets** [comment]
https://github.com/platformio/platformio-atom-ide-terminal/issues/297
