### ISSUE TITLE
not working for me error related to path

### ISSUE THREAD

**Issue by 2rohityadav** [platformio/platformio-atom-ide-terminal#340]
not working for me please have look the screenshot.
Somebody help me out.
<img width="1047" alt="terminalide" src="https://user-images.githubusercontent.com/21152844/29575305-b594e240-8781-11e7-8262-cdecb0b79389.png">

**Comment by morenoh149** [comment]
how did you produce this stacktrace? I too am having issues launching the terminal

**Comment by 2rohityadav** [comment]
@morenoh149  In the atom hit=>   ctrl+shift+i

**Comment by morenoh149** [comment]
that doesn't open the console for me. I also used `cmd+.` to see the key binding and `ctrl+shift+I` isn't mapped.

**Comment by 2rohityadav** [comment]
@morenoh149 Try these few fixes may be it will help you.
-- Try the same combination `Ctrl+Shift+I` two times.
-- Also try another combination  `Ctrl+Alt+I`
-- If you are using Mac try this `Cmd+Opt+I`
-- For linux try this  `ctrl-shift-I`

**Comment by morenoh149** [comment]
cmd+Opt+I on mac 👍

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0 is using node-pty-prebuilt instead unmaintained and outdated pty.js
