### ISSUE TITLE
I can not use the command to install the package via node

### ISSUE THREAD

**Issue by chenxu-javascript** [platformio/platformio-atom-ide-terminal#343]
My system environment is windows10
Now there is a problem I can not use the package installed through npm command.
But as the installation of the command to the global can use such as npm, git and so on.
As long as there is no set to the global variable can not call

**Comment by chenxu-javascript** [comment]
![tim 20170823180215](https://user-images.githubusercontent.com/16332458/29610619-57b1ce3e-882d-11e7-949f-722f9f1c32a1.png)

**Comment by chenxu-javascript** [comment]
![tim 20170823180243](https://user-images.githubusercontent.com/16332458/29610630-64ffc74e-882d-11e7-8f94-b449b4f72374.png)

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0.
These type issues all so far seem fixed with this release due to using node-pty-prebuilt instead unmaintained and outdated pty.js
