### ISSUE TITLE
terminal icon is still missing

### ISSUE THREAD

**Issue by MelindaHasselbring** [platformio/platformio-atom-ide-terminal#344]
I'm running 1.19.3x64 on a Mac on Yosemite 10.10.5, platformio-ide-terminal 2.2.5, the terminal icon is still missing.

**Comment by ivankravets** [comment]
https://github.com/platformio/platformio-atom-ide-terminal/issues/297

**Comment by MelindaHasselbring** [comment]
@ivankravets 
Hello Ivan,
First of all, thank you for your time for supporting this platform.  I really appreciate it.

Second,  I would like to comment on  [SOLVED] PlatformIO IDE Terminal does not work with Atom 1.19 #297.  Is this really a solution to my issue or is it a work around?  

You labeled  #297 as solved and closed all the duplicate issues yet when people install Atom, the terminal does not work because the "+" icon is missing or whatever behavior related to that.  This is very confusing to the users in general because when you labeled it "solved" I would expect that the issue has been resolved and will not require further action on my side anymore (meaning, I don't need to reload, uninstall and reinstall Atom again).  And since I installed a higher version, 1.9.03, I would expect the app should just work as it is without further action by the users.  However, since it required further action,  the steps given in #297 is simply a workaround.  Labeling it as "solved" prompts users to reopen or resubmit the same issue again because the original issue still persists.

If you intend to fix this issue, as I imagine you would because having the terminal within the IDE is such a great feature, you may wanna consider replacing the word "SOLVED" to a more appropriate one to prevent people from logging duplicate issues.

Have a wonderful day.

With all respect and appreciation,
Melinda
