### ISSUE TITLE
Atom "pulled up" when trigger Fullscreen while executing specific command

### ISSUE THREAD

**Issue by mmn6d6d6e** [platformio/platformio-atom-ide-terminal#346]
## How to Replicate
1. New terminal (make sure it's not fullscreen)
2. Execute `composer global update -vvv`
3. Click `fullcsreen`
4. Whole atom pulled up as in screenshot:

![image](https://user-images.githubusercontent.com/19344000/29653389-c4b27a46-88d3-11e7-9908-170464355ddf.png)

## System Specification

- Windows 8.1 x64 & Windows 10 x64
- Atom 1.19.3 x64

## Installed Packages

- atom-beautify@0.30.5
- autoclose-html@0.23.0
- busy-signal@1.4.3
- change-case@0.6.5
- clipboard-plus@0.5.1
- color-picker@2.2.5
- docblockr@0.11.0
- file-icons@2.1.11
- git-time-machine@1.5.9
- intentions@1.1.5
- linter@2.2.0
- linter-csslint@1.3.4
- linter-jshint@3.1.5
- linter-php@1.4.0
- linter-sass-lint@1.7.4
- linter-tidy@2.3.1
- linter-ui-default@1.6.7
- markdown-pdf@1.5.4
- minimap@4.29.6
- minimap-find-and-replace@4.5.2
- minimap-git-diff@4.3.1
- minimap-linter@2.0.2
- minimap-selection@4.5.0
- monokai@0.24.0
- platformio-ide-terminal@2.5.5
- project-manager@3.3.5
- remote-sync@4.1.5
- rest-client@1.3.1
- semanticolor@3.5.4
- sync-settings@0.8.2

**Comment by composerinteralia** [comment]
Yeah I am getting this too. I am able to reproduce it consistently by going into fullscreen and running any command that has a lot of output. The output causes `atom-panel-container` to overflow `atom-workspace-axis`. When you clear the terminal output the styling looks right again.

**Comment by composerinteralia** [comment]
Played around with this for a little bit. There seems to be a problem with `lib/view.coffee` line 183. Things looked more reasonable when I changed `@maxHeight = @prevHeight + $('.item-views').height()` to `@maxHeight = $('.item-views').height() - 50`, but I'm not yet confident enough with what is going on there to make a PR.

**Comment by onebree** [comment]
Can confirm this happens on Mac 10.12.6 with Atom 1.19.3. A related/duplicate issue: https://github.com/platformio/platformio-atom-ide-terminal/issues/267

**Comment by the-j0k3r** [comment]
Fixed a log time ago in https://github.com/platformio/platformio-atom-ide-terminal/commit/4c3f7a1717d2f8a2c8b928592195a5ad51718217
