### ISSUE TITLE
Page up, down, home, end keys don't work in PlatformIO Run compilation output

### ISSUE THREAD

**Issue by cosmikwolf** [platformio/platformio-atom-ide-terminal#35]
Page up, down, home, end keys don't work in PlatformIO Run compilation output.

I am using Atom 1.7.4 and the latest PlatformIO IDE Terminal 2.0.9

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0 is using node-pty-prebuilt instead unmaintained and outdated pty.js
