### ISSUE TITLE
custom text shortcut 

### ISSUE THREAD

**Issue by DeanKamali** [platformio/platformio-atom-ide-terminal#352]
Hello 

I have setup a custom text, but its a daunting task to open up the command palette overtime then type `ide custom`and then select text 1 

Any idea how I can possible create a command line shortcut to point to custom text #1 for example?

**Comment by DeanKamali** [comment]
I just figured it out 

Add the following to `keymap.cson` also can be access via `Preferences -> keybindings -> find "your keymap file" `

```
'.platform-darwin atom-workspace':
  'cmd-b': 'platformio-ide-terminal:insert-custom-text-1'
```

**Comment by RahimGit-dev** [comment]
I attempted to do this but it did not work, any help would be appreciated.
