### ISSUE TITLE
Platformio Ide Terminal doesn't work when put on vertical mode!

### ISSUE THREAD

**Issue by j1yoo** [platformio/platformio-atom-ide-terminal#356]
Love the package, I want to use it in vertical mode.

Please fix this asap! :)

**Comment by yangwao** [comment]
I'm just thinking the same, I can look on it later and play with styles.

**Comment by dorian-marchal** [comment]
In `terminal-plus`, you can drag'n'drop the terminal to the tab bar. It's broken in `platformio-atom-ide-terminal`.

**Comment by the-j0k3r** [comment]
See feature request https://github.com/platformio/platformio-atom-ide-terminal/issues/230
