### ISSUE TITLE
Own status bar for terminal

### ISSUE THREAD

**Issue by jesusvpct** [platformio/platformio-atom-ide-terminal#36]
I've seen on the screenshots that the terminal has its own status bar, but on my Atom version (1.7.4 and Windows 7) it's integrated with the status bar of Atom.

This is a problem for me, because when using with other packages, and when I open a file with a large path, the terminal icons are hidden, and it would be nice to have its own status bar, over the Atom status bar like the screenshots. In fact, when I had terminal-plus, it had their own status bar.

Thanks.

**Comment by skylize** [comment]
I absolutely agree with the new design decision to use the built-in status bar.

However the filename issue is real problem. The terminal needs to reserve the minimum required space and not be pushed off the screen by filenames.
