### ISSUE TITLE
Terminal does not show in tab

### ISSUE THREAD

**Issue by crubier** [platformio/platformio-atom-ide-terminal#361]
Hi, this is probably a CSS issue... On Mac OS, with any theme, I have the same problem: The terminal does not show when it is in a tab:

<img width="1916" alt="screen shot 2017-09-10 at 14 38 39" src="https://user-images.githubusercontent.com/2954572/30249158-0932fd70-9636-11e7-98a3-e4573535cf89.png">

**Comment by cj4luv** [comment]
I have same problem

**Comment by RodrigoHamuy** [comment]
Same problem here. It will be great to be able to move it to a tab and then to the right side of the editor (where the Git panels are).

**Comment by crubier** [comment]
bump !

**Comment by the-j0k3r** [comment]
Please retest with pplatformio-atom-ide-terminal 2.9.0

**Comment by lacostenycoder** [comment]
I'm late here but I'm still having this issue...

**Comment by the-j0k3r** [comment]
Use https://github.com/bus-stop/x-terminal

**Comment by lacostenycoder** [comment]
@the-j0k3r thank you! It works!
