### ISSUE TITLE
Copy paste terminal commands

### ISSUE THREAD

**Issue by ghost** [platformio/platformio-atom-ide-terminal#365]
When I copy and paste a command from the atom terminal to a GNOME terminal, spaces are turned into non-breaking space, which are not recognised as separators.

**Comment by contentfree** [comment]
I'm experiencing this on macOS as well... very strange.

**Comment by Michael-Stevens-27** [comment]
The only short-term solution I can suggest is replacing all of the non-breaking spaces with regular spaces by pressing "Ctrl-f" then copying and pasting the non-breaking space into the find bar, finding all, and replacing with a regular space. 
This has worked for me.

**Comment by ruifortes** [comment]
I just came to check about this problem that I came across quite some time ago .
I've had some headaches debugging scripts with this freaking non-breaking space.
I've installed [highlight-bad-chars](https://atom.io/packages/highlight-bad-chars) package to prevent forgetting about it.

**Comment by xinst** [comment]
https://github.com/platformio/platformio-atom-ide-terminal/issues/512

maybe can help you

**Comment by the-j0k3r** [comment]
Selection has been fixed, also please retest with platformio-ide-terminal 2.9.0
