### ISSUE TITLE
pio is unable to start in terminal

### ISSUE THREAD

**Issue by SRGDamia1** [platformio/platformio-atom-ide-terminal#366]
I'm getting the error "pkg_resources.DistributionNotFound: The 'platformio==3.5.0a9' distribution was not found and is required by the application"

**Comment by SRGDamia1** [comment]
Oh.  It works if I manually call "platformio" but using "pio" fails.

**Comment by ivankravets** [comment]
Just remove `%HOME_DIR%/.platformio/penv` folder and restart IDE.
