### ISSUE TITLE
How to use `alt + f` or `alt +b` replace `commond + left` or `commond + right`?

### ISSUE THREAD

**Issue by yi-ge** [platformio/platformio-atom-ide-terminal#367]
⌘←: Send Hex Codes: 0x01
⌘→: Send Hex Codes: 0x05

Send Hex Code:
alt + f: 0x1b 0x1b 0x5b 0x43
alt + b: 0x1b 0x1b 0x5b 0x44

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0 is using node-pty-prebuilt instead unmaintained and outdated pty.js
