### ISSUE TITLE
Uncaught TypeError: Cannot read property 'element' of undefined

### ISSUE THREAD

**Issue by squix78** [platformio/platformio-atom-ide-terminal#37]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.7.4
**System**: Mac OS X 10.11.3
**Thrown From**: [platformio-ide-terminal](https://github.com/platformio/platformio-atom-ide-terminal) package, v2.0.10
### Stack Trace

Uncaught TypeError: Cannot read property 'element' of undefined

```
At /Users/deichhor/.atom/packages/platformio-ide-terminal/lib/view.coffee:395

TypeError: Cannot read property 'element' of undefined
    at PlatformIOTerminalView.module.exports.PlatformIOTerminalView.adjustHeight (/Users/deichhor/.atom/packages/platformio-ide-terminal/lib/view.coffee:395:16)
    at PlatformIOTerminalView.module.exports.PlatformIOTerminalView.maximize (/Users/deichhor/.atom/packages/platformio-ide-terminal/lib/view.coffee:195:8)
    at HTMLButtonElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:220:36)
    at HTMLButtonElement.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLButtonElement.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```
### Commands

```
     -2:33.3.0 core:move-right (atom-text-editor.editor.is-focused.autocomplete-active)
     -2:31.5.0 core:save (atom-text-editor.editor.is-focused)
     -2:21 platformio-ide:target:upload (atom-text-editor.editor)
     -2:21 platformio-ide:target:upload-/Users/deichhor/git/esp8266-nfc (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-base16-tomorrow-light-theme.theme-one-light-ui)
     -2:03.3.0 platformio-ide:target:upload (atom-text-editor.editor)
     -2:03.3.0 platformio-ide:target:upload-/Users/deichhor/git/esp8266-nfc (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-base16-tomorrow-light-theme.theme-one-light-ui)
     -0:44.9.0 core:copy (atom-text-editor.editor.is-focused)
     -0:43.4.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:43 core:paste (atom-text-editor.editor.is-focused)
     -0:37.6.0 core:cut (atom-text-editor.editor.is-focused)
     -0:36.5.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:36.1.0 core:paste (atom-text-editor.editor.is-focused)
  7x -0:34.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:18 core:move-up (atom-text-editor.editor.is-focused)
  3x -0:17.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:09.1.0 core:save (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-light-ui",
      "base16-tomorrow-light-theme"
    ]
  },
  "platformio-ide-terminal": {
    "core": {},
    "style": {}
  }
}
```
### Installed Packages

``` coffee
# User
autocomplete-clang, v0.9.3
build, v0.64.0
language-ini, v1.16.0
linter, v1.11.4
linter-gcc, v0.6.14
platformio-ide, v1.2.2
platformio-ide-terminal, v2.0.10
tool-bar, v0.4.0

# Dev
No dev packages
```

Actually the core problem is that serial consoles keep dying and stacking up until they consume much of the space. When clicking on the fullscreen icon the above error appears. Here is a picture of the consoles which cannot be removed anymore. Only closing the window helps...
![screenshot 2016-05-31 15 14 14](https://cloud.githubusercontent.com/assets/716822/15675460/6a879216-2742-11e6-8162-1a8c97a37e60.png)

**Comment by ivankravets** [comment]
Do you have the same problem with default dark theme?

**Comment by spicajames** [comment]
Having same problem with One Dark theme, switching to Atom Dark and problem is there too.

**Comment by glumb** [comment]
![bildschirmfoto 2016-08-13 um 18 23 19](https://cloud.githubusercontent.com/assets/3062564/17644326/1c4d15d2-6183-11e6-89b4-d9e9174b08aa.png)
I'm having the same issue. This is kind of annoying, because I have to restart Atom every few minutes because I can not see any code due to empty terminals taking up all space.

I think the issue occurs when an Arduino upload fails.

**Comment by hwacookie** [comment]
Same problem here.

**Comment by ivankravets** [comment]
Do you use latest Atom and all packages are updated?

**Comment by vinodsr** [comment]
I am also facing the same issue . Using atom 1.11.2

**Comment by ivankravets** [comment]
Guys, please update to the latest Atom 1.12 and the latest PlatformIO IDE Terminal 2.2.2.

If you still have problems, please report here your OS.

**Comment by hwacookie** [comment]
IDE 1.6.0 | CLI 3.1.0
Atom packages are all up-to-date, however, Atom itself was rather old (1.8.0, ooops!), so this could very well be the reason for the problems. I'll try a while with the new 1.12.1, and report back.

**Comment by j-holub** [comment]
The Problem still remains with Atom version **1.12.7** on MacOS Sierra.

**Comment by bcanustundag** [comment]
IDE 1.7.1 | Core 3.2.1
also suffer from the same problem.

**Comment by ivankravets** [comment]
Could someone explain me how to reproduce this issue?

**Comment by dansmith65** [comment]
Atom 1.12.9
IDE: 1.7.1
CLI: 3.2.1

@ivankravets steps to reproduce:

I start the serial monitor, then while the serial monitor is connected I upload new firmware. Once uploaded, the serial monitor opens again, but it leaves one extra console at the bottom of the screen which cant be closed.

**Comment by kalsan** [comment]
Still occurs as @dansmith65 reported on Jan 6
```
atom 1.14.4
PIO 3.2.1
```

**Comment by ivankravets** [comment]
Does it occur each time?

**Comment by kalsan** [comment]
Once the bar is there, yes. Click the button that says "Normal", the error occurs. Pressing the two buttons right of it has no effect.

**Comment by mrkaroshi** [comment]
Same problem here, this is actually the cause of the python CPU usage issue I reported.

**Comment by manugildev** [comment]
Same problem in here.

OS: macOS Sierra
Atom: 1.15.0
Platformio-ide-terminal: 2.5
 
I dont know when it happens but I think is when an upload fails, and it only happens sometimes. 

<img width="1280" alt="screen shot 2017-03-30 at 14 04 52" src="https://cloud.githubusercontent.com/assets/13288771/24503324/e617829e-1551-11e7-97e5-b1cc05b1df8f.png">

You can click to close it only in the open ones. But the ones that are collapsed the close button does not work, and "Close All tabs" neither. You just need to restart everytime and it is a little bit annoying. I have update today atom and platform ide and the error is still there.

**Comment by ivankravets** [comment]
Thanks! I've just created separated issue in PIO IDE repository https://github.com/platformio/platformio-atom-ide/issues/302

Will try to fix it before final PIO IDE 2.0 release.

Please sorry.

**Comment by kibitan** [comment]
I get the same problem in here.  is it already solved or do you know the solution?

**Comment by spicajames** [comment]
@kibitan if you have evidence of this error with the updated software please post it to https://github.com/platformio/platformio-atom-ide/issues/302

**Comment by LividJava** [comment]
Setting the default panel height to an unsupported value appears to produce this issue. Atom live updating the values as i was typing them in lagged a bit and i ended up screwing the value and opened a new terminal without verifying my settings and i now have a stuck terminal.

**Comment by the-j0k3r** [comment]
Retest with 2.9.0 as it makes this report is now obsolete.
