### ISSUE TITLE
npm start is not relative to root

### ISSUE THREAD

**Issue by mikeRozen** [platformio/platformio-atom-ide-terminal#371]
Hi, 
I am a new to web development.
Versions:
npm version         3.10.10
node version         6.9.1
webpack version   3.6.0
running `npm start` from your terminal produce the following error:
`./src/components/Init.js
Module not found: Can't resolve 'helpers/localProfile' in 'C:\Users\......\project\src\components'`
The error is obvious its try to pick up a file according current file path BUT 'helpers/localProfile'  is in different directory.
I can fix it by adding '../' to the import but then I will need to change it in the whole project.
If I run `npm start` in windows shell everything works as expected. 
I tried several solutions like setting `NODE_PATH = src/` in the` .env` file but it didn't work.
I am not sure if this issue related to package or to some Atom configurations.
I will really appreciate your help regarding this issue.

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0.
These type issues all so far seem fixed with this release due to using node-pty-prebuilt instead unmaintained and outdated pty.js
