### ISSUE TITLE
Unable to install package. 

### ISSUE THREAD

**Issue by ayadav55** [platformio/platformio-atom-ide-terminal#372]
Below are the details of error message I am getting while installing package in windows 10 :
gyp info it worked if it ends with ok
gyp info using node-gyp@3.4.0
gyp info using node@6.9.5 | win32 | x64
gyp http GET https://atom.io/download/electron/v1.6.9/iojs-v1.6.9.tar.gz
gyp http 200 https://atom.io/download/electron/v1.6.9/iojs-v1.6.9.tar.gz
gyp http GET https://atom.io/download/electron/v1.6.9/SHASUMS256.txt
gyp http GET https://atom.io/download/electron/v1.6.9/win-x64/iojs.lib
gyp http GET https://atom.io/download/electron/v1.6.9/win-x86/iojs.lib
gyp http 200 https://atom.io/download/electron/v1.6.9/win-x64/iojs.lib
gyp http 200 https://atom.io/download/electron/v1.6.9/SHASUMS256.txt
gyp WARN install got an error, rolling back install
gyp ERR! install error
gyp ERR! stack Error: read ECONNRESET
gyp ERR! stack     at exports._errnoException (util.js:1022:11)
gyp ERR! stack     at TLSWrap.onread (net.js:569:26)
gyp ERR! System Windows_NT 10.0.10240
gyp ERR! command "C:\\Users\\***Username***\\AppData\\Local\\atom\\app-1.20.1\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\***Username***\\AppData\\Local\\atom\\app-1.20.1\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js" "install" "--runtime=electron" "--target=1.6.9" "--dist-url=https://atom.io/download/electron" "--arch=x64" "--ensure"
gyp ERR! cwd C:\Users\***Username***\.atom
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok

**Comment by ghost** [comment]
I have encountered the same problem, but i'm mac.

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0 is using node-pty-prebuilt instead unmaintained and outdated pty.js
