### ISSUE TITLE
Two deprecated error messages after trying to do simple 2 ** 3 function

### ISSUE THREAD

**Issue by ghost** [platformio/platformio-atom-ide-terminal#374]
![imag0227](https://user-images.githubusercontent.com/32286505/30842258-0961abc8-a24f-11e7-95cf-c555254d7289.jpg)
![imag0229](https://user-images.githubusercontent.com/32286505/30842259-0963834e-a24f-11e7-891d-fcc1dcd419d8.jpg)
![imag0230](https://user-images.githubusercontent.com/32286505/30842260-0963b828-a24f-11e7-8dfd-d8863ad4880f.jpg)

**Comment by the-j0k3r** [comment]
Fixed as far as I can tell
