### ISSUE TITLE
Atom platformio-atom-ide-terminal gives error 

### ISSUE THREAD

**Issue by MaisnamNSingh** [platformio/platformio-atom-ide-terminal#378]
While opening the terminal gives error with a popup window assertion error
![atom](https://user-images.githubusercontent.com/31078371/31061376-4ffe6532-a73e-11e7-838d-2a24473a7b61.png)

**Comment by felix9ia** [comment]
open Atom by admin?

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0.
These type issues all so far seem fixed with this release due to using node-pty-prebuilt instead unmaintained and outdated pty.js
