### ISSUE TITLE
Remember Terminals Open Per Project?

### ISSUE THREAD

**Issue by andrewcartwright1** [platformio/platformio-atom-ide-terminal#379]
Hey,

Is it possible to remember what terminals were open on a per project basis? Currently whenever I close and reopen my project I have to reopen 3 - 5 terminals to point at different directories.

It would be nice if when I clicked "Reopen Project" the terminals that were open with this project previously get reopened 😃

**Comment by guiguan** [comment]
Yes, please add this feature
