### ISSUE TITLE
When using the atom command I get Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by sdserage** [platformio/platformio-atom-ide-terminal#380]
Recently I reinstalled ubuntu 16.04 on my laptop as well as atom and the platformio-atom-ide-terminal package since they are super awesome. I was disappointed to discover that when I used the atom command from the platformio-atom-ide-terminal terminal I got a segmentation fault (core dumped) message. I thought this was strange since I had used this package before with no issues. I originally thought that atom itself had the issue but I confirmed that I can run the command fine from the regular terminal, it only produces the error when I run it from platformio-atom-ide-terminal. I know it should work since I used it all the time before. Any help would be appreciated. Feel free to ask me for any additional information that I should provide, I'm still fairly new at using Atom.

**Comment by zisheng-ai** [comment]
same issues

**Comment by zisheng-ai** [comment]
@ivankravets please fix  it，thanks

**Comment by zisheng-ai** [comment]
![2017-11-02_093459](https://user-images.githubusercontent.com/13204332/32306543-f7bb1424-bfb6-11e7-9f35-197ee526c9eb.png)

**Comment by zisheng-ai** [comment]
![segmentation-fault](https://user-images.githubusercontent.com/13204332/32368270-2c05724c-c0c0-11e7-8314-1c9f6478d4ae.png)
set this environment variable can solve this problem.

**Comment by the-j0k3r** [comment]
Please retest with platformio-atom-ide-terminal 2.9.0
