### ISSUE TITLE
Can't cut & paste nor highlight nor search in terminal window

### ISSUE THREAD

**Issue by ssilverman** [platformio/platformio-atom-ide-terminal#385]
These features are missing and are required for smooth development. This goes for the serial monitor and build windows especially.
platformio-ide-terminal 2.7.0, Atom 1.21.0, PlatformIO Core 3.5.0a16.

**Comment by the-j0k3r** [comment]
Cut and paste and selection work just fine, search is the only one left and thats a duplicate of https://github.com/platformio/platformio-atom-ide-terminal/issues/121
