### ISSUE TITLE
npm install Exits Without Executing

### ISSUE THREAD

**Issue by deeshrestha** [platformio/platformio-atom-ide-terminal#391]
When I try to execute `npm install` on my Laravel project, it exits without executing it.

**Comment by Ajedi32** [comment]
Possibly related to #277

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0.
These type issues all so far seem fixed with this release due to using node-pty-prebuilt instead unmaintained and outdated pty.js
