### ISSUE TITLE
on windows, using ipython, bracket problem

### ISSUE THREAD

**Issue by safavieh** [platformio/platformio-atom-ide-terminal#393]
Hi,

I'm having this problem on windows when I use ipython.

When I type some expressions that have brackets ()[]{}, when I move the cursor backward, it messes up the expression and it is not readable anymore. It happens when it tries to show the matching bracket. 

I have attached some images to show it more precisely.

It only happens when I use platformio-ide-terminal, not when I use ipython directly from shell outside Atom. I have checked this with "windows power shell" and "cmd", no difference.

Initial:
![0](https://user-images.githubusercontent.com/22679129/31664210-df407868-b344-11e7-84a9-f0c9b603bf78.png)

moving back the cursor:
![1](https://user-images.githubusercontent.com/22679129/31664255-0cfeed66-b345-11e7-875e-89c2ad44eeef.png)

moving back and forth the cursor a few times:
![2](https://user-images.githubusercontent.com/22679129/31664276-1be85740-b345-11e7-92ca-ed5c5c1b0f41.png)

PS. It doesn't happen always. usually, after a while, it starts to mess-up

Thanks

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0.
These type issues all so far seem fixed with this release due to using node-pty-prebuilt instead unmaintained and outdated pty.js
