### ISSUE TITLE
Plaformio IDE Terminal

### ISSUE THREAD

**Issue by ghost** [platformio/platformio-atom-ide-terminal#394]
Hello, 

Recently I installed Python IDE terminal in my atom to run python. Everything seems fine but I can only use the default command prompt which is like that: 

For, **print ("Hello World")** code
the output instantly disappeared & don't want for keyboard key press. 

I searched many places but didn't find, how to connect it to the python cmd. 
So, can anyone face the same problem?
If yes, then how could you solve it?

Thanks in advance.

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0.
These type issues all so far seem fixed with this release due to using node-pty-prebuilt instead unmaintained and outdated pty.js
