### ISSUE TITLE
Django runserver command won't run

### ISSUE THREAD

**Issue by Rezwanul-Haque** [platformio/platformio-atom-ide-terminal#395]
I try to run the command
python manage.py runserver (django devlopment)

![image](https://user-images.githubusercontent.com/22642254/31921609-19f2e46c-b892-11e7-85cc-376de982760b.png)

but the server won't run....

What should i do....

Thanks in advance....

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0 is using node-pty-prebuilt instead unmaintained and outdated pty.js

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0.
These type issues all so far seem fixed with this release due to using node-pty-prebuilt instead unmaintained and outdated pty.js

**Comment by Rezwanul-Haque** [comment]
> Please retest again with platformio-atom-ide-terminal 2.9.0.
> These type issues all so far seem fixed with this release due to using node-pty-prebuilt instead unmaintained and outdated pty.js

Yes, thanks for answering it's already been fixed and now I'm using it at full speed.

**Comment by the-j0k3r** [comment]
Thank you for coming back to us with that information. =)
