### ISSUE TITLE
Executing custom text command causes cursor in editor to move down

### ISSUE THREAD

**Issue by moxley** [platformio/platformio-atom-ide-terminal#396]
I set up custom text commands so that I can run them with a keystroke while I'm editing a file and they'll post the custom command to the terminal. However, when I execute any of my custom commands from within the editor pane, it causes the cursor in the editor pane to move down one row, as if I had pressed the down arrow key.

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0 is using node-pty-prebuilt instead unmaintained and outdated pty.js
