### ISSUE TITLE
"How do you want to open this file?."

### ISSUE THREAD

**Issue by jbcoulter** [platformio/platformio-atom-ide-terminal#397]
I installed Platformio for the first time yesterday.
I cant for the life of me find out how to get a module to run in the platformio terminal.

When I type 'node step2' (the name of the javascript file I wanted to run) into Windows 10 Command Prompt, I can run the module no problem.
But when trying to use your terminal in Atom I get **"How do you want to open this file?."**

I am running
Windows 10 Home 64 bit 
Atom 1.21 x64
PlatformIO

Both Atom and PlatformIO were re-installed today hoping to fix it just by in-installing and then re-installing.
I also cant access PlatformIO home via the home link from PlatformIO's drop down menu in Atom.
It just shows the circle moving around with nothing loading.

jbc

**Comment by jbcoulter** [comment]
From what I've read, Visual Studio released an update that could help Windows users with the Clang installation issue-  **LLVM** failed during installation. 
The installation error I got was; "Failed to find MSBuild toolsets directory. MSVC integration install failed.

This post from Aug. has me installing Visual Basic's 2017 Oct. update.
[https://developercommunity.visualstudio.com/content/problem/25618/visual-studio-2017-template-issues.html](url)

I'll update all here when its done (big install).

**Comment by jbcoulter** [comment]
LLVM and Clang is installed. That's the good. The bad is when trying to run a javascript in PlatformIO windows asks me what prog to use to run the file.
The Ugly= me crying.

Anyone with a solution is greatly appreciated!!!

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0.
These type issues all so far seem fixed with this release due to using node-pty-prebuilt instead unmaintained and outdated pty.js
