### ISSUE TITLE
On Arduino (Leonardo ETH) Serial Monitor stops after uplaoding 

### ISSUE THREAD

**Issue by sstaub** [platformio/platformio-atom-ide-terminal#4]
After uploading an arduino sketch the serial monitor stops working. He doesn't reconnect?
In the moment I must close the monitor and open again.
![serial](https://cloud.githubusercontent.com/assets/6450325/13674477/ebaa17b0-e6dd-11e5-929a-9b2b3d41552d.png)

**Comment by ivankravets** [comment]
1. Do you mean this issue? https://github.com/platformio/platformio-atom-ide/issues/45
2. Try to close all Terminal (red close icon on the status bar)
3. Try reconnect your device to Mac/or even change USB ports.

**Comment by sstaub** [comment]
1. The bug is different to platformio/platformio-atom-ide#45, because the upload is ok. The message comes up in the moment when starting uploading.
2. / 3. no changes

**Comment by ivankravets** [comment]
Did it work before?

**Comment by sstaub** [comment]
Good questions, i think it works with the classic terminal (on OS X). But I don't know with the
new build-in terminal, because in the last time i worked with mbed.

**Comment by ivankravets** [comment]
Does Serial Monitor work with mbed board?

**Comment by sstaub** [comment]
Yes, with mbed the serial monitor works like expected.

**Comment by ivankravets** [comment]
@sstaub Please contact me@ikravets.com with TeamViewer ID and Pass for the session.

**Comment by ivankravets** [comment]
Fixed in PlatformIO IDE 1.1.0
