### ISSUE TITLE
Doesn't recognize shortcut alt gr+0 ( azerty ) and acts strangely

### ISSUE THREAD

**Issue by LaurelineP** [platformio/platformio-atom-ide-terminal#405]
Hi there, I've been experiencing some issues .
For exemple i'm a connecting to heroku via the terminal : 
first: I try to add @ with alt gr + 0 (@ touche combined with alt gr)  and then this @ is not recognize from times to times( it has worked once ) ; then I found another way .....
second : i did a mistake on my passwprd and wanted to delete the character ... and my del touch was not recognize as a delete key but as a character...
Is there a way cause it is quite anoying ?

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0 is using node-pty-prebuilt instead unmaintained and outdated pty.js
