### ISSUE TITLE
Feature request: add a scroll-bar to terminal

### ISSUE THREAD

**Issue by fusion809** [platformio/platformio-atom-ide-terminal#41]
Hi,

I think it'd help navigating the `platformio-ide-terminal` windows if a scroll-bar was added to it, similar to the scroll bar of `tree-view`. 

Thanks for your time,
Brenton

**Comment by MechCoder** [comment]
Seconded, I would like scrolling support as well.

**Comment by ZCLMK** [comment]
ctrl + arrow (up or down) allows you to scroll up or down !

**Comment by the-j0k3r** [comment]
duplicate of #9
