### ISSUE TITLE
Custom Keybinding for focus not working properly

### ISSUE THREAD

**Issue by jpagarcia** [platformio/platformio-atom-ide-terminal#411]
I replaced the **ctrl-alt-f** shortcut for focus with **ctrl-t**. It focuses properly on the terminal but doesn't go back to the editor when I use the custom keybinding again. I don't have this problem when using the default keybinding.

**Comment by jpagarcia** [comment]
Also, when I focus on the terminal using the mouse or leave atom while focus is on the terminal, default shortcut **ctrl-alt-f** does not work anymore

**Comment by dtroydev** [comment]
My Issue #421 is related to yours

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0 is using node-pty-prebuilt instead unmaintained and outdated pty.js

**Comment by allefeld** [comment]
I have the same problem, but regarding `platformio-ide-terminal:toggle`. I configured

```
# toggle terminal with F4 like in Dolphin
'.platform-linux atom-workspace, .platform-win32 atom-workspace':
  'F4': 'platformio-ide-terminal:toggle'
```

Activating the terminal via "F4" works just fine, but if the terminal has the keyboard focus, pressing "F4" again does not minimize it.

Atom 1.14.0 on Linux, platformio-ide-terminal 2.10.0

**Comment by the-j0k3r** [comment]
Please resubmit a new ticket filling in all issue template fields.

Apologies in advance for any inconvenience this may cause.
