### ISSUE TITLE
The terminal will pull up.. but no content.. 

### ISSUE THREAD

**Issue by travishorne03** [platformio/platformio-atom-ide-terminal#417]
The terminal will pull up.. but no content..

**Comment by richiksc** [comment]
We need some more info:

Which version of Atom are you on?
Which version of PlatformIO IDE Terminal?
Which OS and which version?
What is your shell set to in the package settings?

**Comment by travishorne03** [comment]
I deleted the built in terminal. I deleted and readded yours.. now its working perfectly.


Thanks,
Travis Horne980.328.3109
-------- Original message --------From: Richik SC <notifications@github.com> Date: 12/6/17  9:47 AM  (GMT-05:00) To: platformio/platformio-atom-ide-terminal <platformio-atom-ide-terminal@noreply.github.com> Cc: Travis Horne <travis.horne03@gmail.com>, Author <author@noreply.github.com> Subject: Re: [platformio/platformio-atom-ide-terminal] The terminal will pull
  up.. but no content.. (#417) 
We need some more info:
Which version of Atom are you on?

Which version of PlatformIO IDE Terminal?

Which OS and which version?

What is your shell set to in the package settings?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/platformio/platformio-atom-ide-terminal","title":"platformio/platformio-atom-ide-terminal","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/platformio/platformio-atom-ide-terminal"}},"updates":{"snippets":[{"icon":"PERSON","message":"@richiksc in #417: We need some more info:\r\n\r\nWhich version of Atom are you on?\r\nWhich version of PlatformIO IDE Terminal?\r\nWhich OS and which version?\r\nWhat is your shell set to in the package settings?"}],"action":{"name":"View Issue","url":"https://github.com/platformio/platformio-atom-ide-terminal/issues/417#issuecomment-349661018"}}}

**Comment by the-j0k3r** [comment]
Solved then.
