### ISSUE TITLE
Cursor Focus Lost

### ISSUE THREAD

**Issue by dtroydev** [platformio/platformio-atom-ide-terminal#421]
Hi,

Problem: Editor Cursor can not regain focus after switching applications.
Environment: I have Atom 1.22.0 x64 on Mac running platform-ide-terminal 2.7.0

Steps to Reproduce:
1) In Atom, Start an Editor Window Editing Some File
2) Enable Terminal (Control-BackTick)
3) Test that Switching Cursor Back and Forth between Editor and Terminal Works (Command-Alt-F a few times). Leave cursor in Terminal
4) Switch To Another Application (Command-Tab)
5) Switch Back to Atom (Command-Tab)
6) Now It is not possible to regain focus in Editor (ie. Command-Alt-F no longer works)

**Comment by zachthemystic** [comment]
I have this issue too. When the outside application closes the only way to get focus back on the editor is to either click on it with the mouse, or press Ctrl-0 twice go to the tree view and then back to the editor. I'm not an expert, but somehow Ctrl-0 still works. Whatever Ctrl-0 does, maybe the fix can do that?

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0.
These type issues all so far seem fixed with this release due to using node-pty-prebuilt instead unmaintained and outdated pty.js
