### ISSUE TITLE
PSReadline issue

### ISSUE THREAD

**Issue by collins73** [platformio/platformio-atom-ide-terminal#423]
Cannot load PSReadline module. Console is running without PSReadline.

Any ideas or fixes for this problem?

**Comment by collins73** [comment]
I still cannot resolve this issue.. I will use my command prompt that came with computer

**Comment by the-j0k3r** [comment]
duplicate of https://github.com/platformio/platformio-atom-ide-terminal/issues/64 which also has a solution.
