### ISSUE TITLE
text highlighting invisible

### ISSUE THREAD

**Issue by smiller171** [platformio/platformio-atom-ide-terminal#432]
Text highlighting is not visible when using solarized-dark theme. This does not affect other themes.

Edit: appears this was fixed by #424 Is it possible to cut a bugfix release to fix this?

**Comment by eyaleizenberg** [comment]
same here

**Comment by the-j0k3r** [comment]
Thx =)This was fixed by #424 

if issues persist open a new ticket with required information.
