### ISSUE TITLE
Close Terminal on Exit stopped working.

### ISSUE THREAD

**Issue by CodeBrotha** [platformio/platformio-atom-ide-terminal#436]
Recently I have noticed that the "Close Terminal on Exit" setting no longer works. Even though I have it selected the Terminal no longer closes after typing exit and pressing return.

**Comment by the-j0k3r** [comment]
This is working perfectly with 2.9.0

Please retest again with platformio-atom-ide-terminal 2.9.0 is using node-pty-prebuilt instead unmaintained and outdated pty.js

if issues persist open a new ticket with required information.

Thx =)

**Comment by CodeBrotha** [comment]
Thank you!
