### ISSUE TITLE
Powershell does not inherit Window's enviroment variables

### ISSUE THREAD

**Issue by nicholascgilpin** [platformio/platformio-atom-ide-terminal#437]
Problem:
I installed the Yarn package manager and could use it from powershell when powershell was started from outside of Atom. However, when starting powershell from inside Atom using platformio-atom-ide-terminal, the enviroment variables that allow access to Yarn had changed and I couldn't use Yarn.

Steps to reproduce:
Run powershell from the start menu
In powershell run the following command to see the path variable:
`Get-Item Env:Path`
Now, open Atom and click the + button to open a new ide-terminal (powershell)
Enter the same command as before
On my system, the Path string has been replaced with:
"C:\Windows C:\Windows C:\Windows C:\Windows C:\Windows C:\Windows"

Temporary Solution:
Run the following script from the newly opened powershell instance:
`foreach($level in "Machine","User") {
   [Environment]::GetEnvironmentVariables($level).GetEnumerator() | % {
      # For Path variables, append the new values, if they're not already in there
      if($_.Name -match 'Path$') { 
         $_.Value = ($((Get-Content "Env:$($_.Name)") + ";$($_.Value)") -split ';' | Select -unique) -join ';'
      }
      $_
   } | Set-Content -Path { "Env:$($_.Name)" }
}`
[Script by Jaykul from Stackoverflow](https://stackoverflow.com/questions/14381650/how-to-update-windows-powershell-session-environment-variables-from-registry)

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0 is using node-pty-prebuilt instead unmaintained and outdated pty.js

if issues persist open a new ticket with required information.

Thx =)
