### ISSUE TITLE
Unable to open a terminal

### ISSUE THREAD

**Issue by prawin777** [platformio/platformio-atom-ide-terminal#439]
![image](https://user-images.githubusercontent.com/20386413/34281609-cb03f646-e68d-11e7-827f-8cf85de33a7b.png)

**Comment by JayWhite2357** [comment]
Having the same issue

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0 is using node-pty-prebuilt instead unmaintained and outdated pty.js

if issues persist open a new ticket with required information.

Thx =)
