### ISSUE TITLE
Always show error

### ISSUE THREAD

**Issue by okprogrammer** [platformio/platformio-atom-ide-terminal#441]
when I installed that terminal first day it won't work but second day it started to work. I really became happy.But second suddenly stop working.My problem face by many people.I think either you terminal is not working or atom text editor not support ur terminal

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0 is using node-pty-prebuilt instead unmaintained and outdated pty.js

if issues persist open a new ticket with required information.

Thx =)
