### ISSUE TITLE
The compatibility of Chinese is not very good (对中文的兼容性不太好)

### ISSUE THREAD

**Issue by jiangshantao** [platformio/platformio-atom-ide-terminal#442]
<img width="259" alt="2017-12-30 11 42 55" src="https://user-images.githubusercontent.com/25195806/34455497-6bfd93b6-edbb-11e7-8672-818392752654.png">

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0 is using node-pty-prebuilt instead unmaintained and outdated pty.js

if issues persist open a new ticket with required information.

Thx =)
