### ISSUE TITLE
Please, edit name of Package in the menu

### ISSUE THREAD

**Issue by ardubit** [platformio/platformio-atom-ide-terminal#443]
![2017-12-31 13 48 05](https://user-images.githubusercontent.com/6237239/34461402-5a67aabc-ee31-11e7-9755-996ae61bc044.png)

Everything working good, thank you. However, the name of "platformio-ide-terminal" in the menu making some visual style dissonance with others packages. Please edit it to "Platformio IDE Terminal" or "Platformio Terminal". I edit it each time after updates, can't live without harmony.

**Comment by the-j0k3r** [comment]
Thank you for your ticket, all features and fixes are now solely a user generated contribution.

**Comment by the-j0k3r** [comment]
Please see https://github.com/platformio/platformio-atom-ide-terminal/pull/648#issuecomment-462057412

**Comment by the-j0k3r** [comment]
This has been fixed in https://github.com/bus-stop/terminus
