### ISSUE TITLE
Platformio IDE Terminal does not work with Atom 1.23.1

### ISSUE THREAD

**Issue by 2rohityadav** [platformio/platformio-atom-ide-terminal#444]
Got the some kind of issue.
platformio 2.8.0 on Atom 1.23.1, Windows 10
Already tried to reinstall the package.

<img width="1096" alt="atom" src="https://user-images.githubusercontent.com/21152844/34473459-f1790fb4-ef98-11e7-9538-fe6d6787a7b3.png">

**Comment by nitiz143** [comment]
same there please provide the solution as soon as possible

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0 is using node-pty-prebuilt instead unmaintained and outdated pty.js

if issues persist open a new ticket with required information.

Thx =)
