### ISSUE TITLE
Any chance we can get this to work in Docks?

### ISSUE THREAD

**Issue by bgarrant** [platformio/platformio-atom-ide-terminal#446]
Any chance we can get this to work in Docks? It would be great if it was just next to the normal Diagnostics tab when open.

![screen shot 2018-01-08 at 2 40 18 pm](https://user-images.githubusercontent.com/2436728/34688963-e23c014e-f481-11e7-907d-94864697a09f.png)

**Comment by ChristinWhite** [comment]
Came here to ask just this, it would be great addition! There's at least one other terminal package that works in a dock but there's no comparison.

**Comment by the-j0k3r** [comment]
There is a request already see https://github.com/platformio/platformio-atom-ide-terminal/issues/230
