### ISSUE TITLE
Atom and PlatformIO don't work together anymore????

### ISSUE THREAD

**Issue by beegee-tokyo** [platformio/platformio-atom-ide-terminal#448]
Over the last days PlatformIO and Atom don't like each other anymore.

It started with the same error as
[Uncaught TypeError: Cannot read property 'runCommandInNewTerminal' of undefined](https://github.com/platformio/platformio-atom-ide-terminal/issues/398)
and same error as
[Platformio IDE Terminal does not work with Atom 1.23.1](https://github.com/platformio/platformio-atom-ide-terminal/issues/444)
and got worse today when I try to hit the build button I get
```log
Failed to build.
Status 'Build: PIO Upload' is already set
Hide Stack Trace
Error: Status 'Build: PIO Upload' is already set
    at Registry.statusAdd (file:///C:/Users/beegee/.atom/packages/busy-signal/lib/registry.js:50:13)
    at file:///C:/Users/beegee/.atom/packages/busy-signal/lib/registry.js:31:12
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\beegee\AppData\Local\atom\app-1.23.2\resources\app\node_modules\event-kit\lib\emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (C:\Users\beegee\AppData\Local\atom\app-1.23.2\resources\app\node_modules\event-kit\lib\emitter.js:141:34)
    at Provider.add (file:///C:/Users/beegee/.atom/packages/busy-signal/lib/provider.js:21:18)
    at file:///C:/Users/beegee/.atom/packages/build/lib/build.js:127:46
```
and to make it worse, since today when I try to flash over USB/Serial I get at the end of the compilation (when it should start to upload
```log
...
Checking program size
text       data     bss     dec     hex filename
384010     9368   32488  425866   67f8a .pioenvs\huzzah\firmware.elf
"esptool" -eo "C:\Users\beegee\.platformio\packages\framework-arduinoespressif8266\bootloaders\eboot\eboot.elf" -bo .pioenvs\huzzah\firmware.bin -bm qio -bf 40 -bz 4M -bs .text -bp 4096 -ec -eo .pioenvs\huzzah\firmware.elf -bs .irom0.text -bs .text -bs .data -bs .rodata -bc -ec
MethodWrapper(["upload"], [".pioenvs\huzzah\firmware.bin"])
Auto-detected: COM2
esptool -vv -cd nodemcu -cb 115200 -cp "COM2" -p 8266 --auth= -cf .pioenvs\huzzah\firmware.bin
esptool v0.4.9 - (c) 2014 Ch. Klippel <ck@atelier-klippel.de>
setting board to nodemcu
setting baudrate from 115200 to 115200
setting port from COM1 to COM2
*** [upload] Error -1
```

Switched to Visual Studio Code for now as there at least the building and terminal functions work.
Flashing over USB/Serial is not possible there as well (same error message).

Flashing over USB/Serial is possible from Arduino IDE. And the COM port is working, I get debug and log messages over it. The COM port is not occupied by any other program. And the error message is quite strange: ** [upload] Error -1 **

I tried already a new installation of Atom and PlatformIO and the platforms, but the problems are not going away. Is there any way to go back to an older version of Atom? I have the feeling it started with some updates of Atom, but I am not sure.

**Comment by the-j0k3r** [comment]
Please retest with platformio-ide-terminal 2.9.0

**Comment by beegee-tokyo** [comment]
Sorry for not closing this. Moved on to msvc with platformio long time ago.
