### ISSUE TITLE
cannot change background colour

### ISSUE THREAD

**Issue by andersfylling** [platformio/platformio-atom-ide-terminal#451]
Running the latest atom and platformio, I can't seem to alter the background for some reason. It stays pitch black.

Chanigng the background field in the less field yielded no changes even when restarting atom. Changing the black colour from the package GUI settings, only affected the text.

I really need a more detailed doc for the json settings. Where can I find this?
Tbh, being able to set the colours to the same as your terminal, would be great!

**Comment by the-j0k3r** [comment]
Depends what theme you have set in platformio-atom-ide-terminal settings.

If using say [one dark ](https://github.com/platformio/platformio-atom-ide-terminal/blob/master/styles/themes/one-dark.less)and wanted to chnage the background you would add this to the Atom stylesheet.

```css
.one-dark {
  background-color: #353535 !mportant;
}
```

But note, any color changes dont apply to ANY/ALL open terminals, close them and re-open them to see changes.

Also applicable read https://github.com/platformio/platformio-atom-ide-terminal/issues/578#issuecomment-407666169
