### ISSUE TITLE
Backspace problem

### ISSUE THREAD

**Issue by ghost** [platformio/platformio-atom-ide-terminal#454]
Windows 10.
While holding backspace it makes sometimes spaces so I can't delete the whole command.
When it stops the text is still visible but in real its gone.
![abc](https://user-images.githubusercontent.com/35633932/35341819-d8deec72-0126-11e8-812f-9d57a58aab46.PNG)

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0.
These type issues all so far seem fixed with this release due to using node-pty-prebuilt instead unmaintained and outdated pty.js

if issues persist open a new ticket with required information.

Thx =)
