### ISSUE TITLE
Custom terminal not running?

### ISSUE THREAD

**Issue by cloudbluedigital** [platformio/platformio-atom-ide-terminal#455]
Hi Guys,

On my windows I am usually using a custom console: http://cmder.net/ 

However from this package when I try to run it, it doesn't work I get a blank console. Powershell console etc, do work normally. Is there anything wrong with it?

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0 is using node-pty-prebuilt instead unmaintained and outdated pty.js

if issues persist open a new ticket with required information.

Thx =)
