### ISSUE TITLE
Blinking Cursor

### ISSUE THREAD

**Issue by CarterRichard** [platformio/platformio-atom-ide-terminal#456]
After installing and reinstalling the package multiple times I still run into the same issue. As soon as I open the terminal (using the plus icon on bottom left of screen since shortcut doesn't work) the terminal pops up but I cant interact with it unless closing it. The cursor will just blink but it wont load anything and I cant type anything. I have tried looking online regarding the issue but apart from uninstall and reinstall I cant seem to find a solution. I am trying to run python programs using the terminal as my end goal.

**Comment by the-j0k3r** [comment]
try with platformio-atom-ide-terminal 2.9.0

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0 is using node-pty-prebuilt instead unmaintained and outdated pty.js

if issues persist open a new ticket with required information.

Thx =)
