### ISSUE TITLE
text selection cursor fails to appear when opening file using "atom filename.txt" command

### ISSUE THREAD

**Issue by mmore500** [platformio/platformio-atom-ide-terminal#46]
When I open a new file (or an existing file) in the Atom editor using the "atom filename.txt" command, there is no cursor in the atom text editing pane after I hide the terminal with the ctrl-`command. This is not an issue once I have the file open and use the ctrl-` command to toggle, only immediately after opening a new or existing file with the "atom filename.txt" command from the patformio-atom-ide-terminal. This is very annoying as I have to click in the atom window (or toggle the finder) to get a cursor to show up so I can type in my newly opened file. I do not experience this issue when using the "atom filename.txt" command from the OSX standalone terminal (i.e. the new file shows up with a cursor ready for me to type with and I do not have to click in the window). Thanks.

**Comment by the-j0k3r** [comment]
Should be fixed with 2.9.0
