### ISSUE TITLE
The terminal font has a shadow or 3D effect.

### ISSUE THREAD

**Issue by kingjacob** [platformio/platformio-atom-ide-terminal#460]
<img width="634" alt="screen shot 2018-02-07 at 11 17 38 pm" src="https://user-images.githubusercontent.com/806312/35960133-59426a2e-0c5d-11e8-9e6e-c5ba9ef45b74.png">

**Comment by shiny-eel** [comment]
**EDIT - HOTFIX**
This was annoying me as well, but I found a way to remove the text shadow.

1. Go into atom's stylesheet `styles.less`
2. add the following:

```css
.platformio-ide-terminal .xterm {
    text-shadow: none;
}
```

[This is the corresponding *terminal-plus* issue](https://github.com/jeremyramin/terminal-plus/issues/124)


------
I also have this issue.
Atom: `1.27.0`
platformio-ide-terminal: `2.8.1`
Machine: Macbook Pro w High Sierra

**Comment by the-j0k3r** [comment]
@ivankravets this was already fixed in #535 please close
