### ISSUE TITLE
Just a blinking Cursor after atom 1.25.0 beta2 update

### ISSUE THREAD

**Issue by sudwebd** [platformio/platformio-atom-ide-terminal#466]
After I updated to atom 25.0 beta2, the terminal just shows a blinking cursor and is not working.
I tried both rebuilding the package for the newer version and also reinstalling the package, but none of the strategies worked

**Comment by robaerospace** [comment]
Can confirm the same on 1.25.0-beta2

**Comment by ElecTreeFrying** [comment]
same here.. need help

Error: ` Error: Cannot find module 'C:\Users\John James Ermitaño\.atom\packages\platformio-ide-terminal\node_modules\pty.js\bin\win32\x64_m54\pty.node'`

> Cannot find module 'C:\Users\John James Ermitaño\.atom\packages\platformio-ide-terminal\node_modules\pty.js\bin\win32\x64_m54\pty.node' Error: Cannot find module 'C:\Users\John James Ermitaño\.atom\packages\platformio-ide-terminal\node_modules\pty.js\bin\win32\x64_m54\pty.node'

Error: `Object {errno: -4058, code: "ENOENT", syscall: "lstat", path: "C:\Users\John James Ermitaño\.atom\packages\tokama…ode_modules\pty.js\bin\win32\x64_m54\pty.node.bak"}`

Error: `handler is not defined ReferenceError: handler is not defined`

Warning: `events.js:106 Cannot find module '..\build\Release\pty.node'`

![53 only](https://user-images.githubusercontent.com/19801459/36930084-0fad048e-1ed5-11e8-8350-d186ad5012da.PNG)

it says no x64_m54. I tried this

![added](https://user-images.githubusercontent.com/19801459/36930086-16ee4b72-1ed5-11e8-8b6a-9c6cc6ef015d.PNG)

Please help how to change `NODE_MODULE_VERSION` to 54 . Already tried `npm rebuild` and `npm install` still the same.

Error: `Error: The module '\\?\C:\Users\John James ErmitaÃ±o\.atom\packages\platformio-ide-terminal\node_modules\pty.js\bin\win32\x64_m54\pty.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 53. This version of Node.js requires
NODE_MODULE_VERSION 54. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`).`

> The module '\\?\C:\Users\John James ErmitaÃ±o\.atom\packages\platformio-ide-terminal\node_modules\pty.js\bin\win32\x64_m54\pty.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 53. This version of Node.js requires
NODE_MODULE_VERSION 54. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`). Error: The module '\\?\C:\Users\John James ErmitaÃ±o\.atom\packages\platformio-ide-terminal\node_modules\pty.js\bin\win32\x64_m54\pty.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 53. This version of Node.js requires
NODE_MODULE_VERSION 54. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`).

Error: `handler is not defined ReferenceError: handler is not defined`

Warning: `events.js:106 Cannot find module '..\build\Release\pty.node'`

Blinking..
![blinking](https://user-images.githubusercontent.com/19801459/36930166-8aa88cf2-1ed6-11e8-8ad7-7a5e8b7c8af8.PNG)

`atom -v`
Atom: 1.25.0-beta2
Electron: 1.7.11
Chrome: 58.0.3029.110
Node: 7.9.0

`apm -v`
apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.25.0-beta2
python
git 2.16.2.windows.1
visual studio

`node -v`
v9.7.1

**Comment by ravirawat89** [comment]
Serial monitor and platform io terminal not working after atom 1.25.0 update, just showing blank screen with blinking cursor. i tried to uninstall and reinstall platform io terminal but still facing same problem.

**Comment by danielstefaniak** [comment]
Same issue here: atim 1.25.0 and platformio-ide-terminal 2.8.0. Only blinking cursor in the terminal. Reinstalled both applications but again tge same issue.

**Comment by danielstefaniak** [comment]
Same issue here: atom 1.25.0 and platformio-ide-terminal 2.8.0. Only blinking cursor in the terminal. Reinstalled both applications but again the same issue. However, it works when installing the previous atom version.

**Comment by osidon** [comment]
There a work around to this?

**Comment by abrarwali** [comment]
Same problem here.....Any Solutions ??

**Comment by arnoks** [comment]
I have got the same problem.  Just upgraded to 1.25.0 and re-installed the platform-ide-terminal 

1.25.0\resources\app.asar\src\compile-cache.js:235:23)
(anonymous) @ <embedded>:75431
(anonymous) @ <embedded>:75505
module.exports.Emitter.simpleDispatch @ <embedded>:66262
module.exports.Emitter.emit @ <embedded>:66378
(anonymous) @ <embedded>:75457
emitTwo @ events.js:106
emit @ events.js:194
process.nextTick @ internal/child_process.js:766
_combinedTickCallback @ internal/process/next_tick.js:73
_tickCallback @ internal/process/next_tick.js:104
events.js:106 handler is not defined ReferenceError: handler is not defined
    at process.<anonymous> (C:\Users\xxxxx\AppData\Local\atom\app-1.25.0\resources\app.asar\src\task-bootstrap.js:51:20)
    at emitTwo (events.js:106:13)
    at process.emit (events.js:194:7)
    at process.nextTick (internal/child_process.js:766:12)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)

**Comment by danielstefaniak** [comment]
As long as there is no "official solution" you can download and install 1.24 and stop automated updates. Worked fine for me after having the same issue on 1.25.0.

**Comment by pietropatelli** [comment]
version 2.8.1 solves the issue, see #477

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0 is using node-pty-prebuilt instead unmaintained and outdated pty.js

if issues persist open a new ticket with required information.

Thx =)
