### ISSUE TITLE
Not able to select text from terminal window

### ISSUE THREAD

**Issue by kkbhav** [platformio/platformio-atom-ide-terminal#467]
I am not able to select text from terminal to copy it to another place. I don't know if this is a bug or a feature implementation.

Thanks

**Comment by esparkman** [comment]
Updated:
Same issue here.
Atom Version: 1.25.0
platformio-atom-ide-termianl: 2.8.1

**Comment by galblank** [comment]
same here
Atom: 1x25 64bit
platformio-atom-ide-termianl: 2.8.1

**Comment by kkbhav** [comment]
@ivankravets Any solution for this issue?

**Comment by galblank** [comment]
Nope, and it's very frustrating

**Comment by esparkman** [comment]
I've gone back to VSCode for the time being.

**Comment by AfflatusX** [comment]
I am having same problem :(

It works on some of my computers, not others.

**Comment by AfflatusX** [comment]
looks like it has been resolved before: https://github.com/platformio/platformio-atom-ide-terminal/issues/102

**Comment by kkbhav** [comment]
Yes. I tested out solutions mentioned in #102 and it worked for me, it was caused because of nuclide package. So the main issue that needs to resolved is how to make this terminal compatible with others plugins.

We can close this issue if others can also find their solution from #102 and move the discussion to that thread.

**Comment by rajatjindal** [comment]
it didn't worked for me. I cant select the text anymore  on terminals, which is so annoying :(

**Comment by xinst** [comment]
@rajatjindal 
this is work for me https://github.com/platformio/platformio-atom-ide-terminal/issues/512
"
I have the same issue!
I solve this issue by disabling a feature of atom-ide-ui.
Go to Settings->packages->atom-ide-ui and expand the Enabled Features, then find the Enable terminal option and set to Never enabled. Now you can select and copy text in the platformio-atom-ide-terminal.
"

**Comment by the-j0k3r** [comment]
This has been fixed

Please retest again with platformio-atom-ide-terminal 2.9.0.
These type issues all so far seem fixed with this release due to using node-pty-prebuilt instead unmaintained and outdated pty.js

if issues persist open a new ticket with required information.

Thx =)
