### ISSUE TITLE
bash: npm: command not found

### ISSUE THREAD

**Issue by srcwhitaker** [platformio/platformio-atom-ide-terminal#468]
See video https://www.useloom.com/share/e4f45e3d51e84e9896e109f6e6507555 In my terminal outside of ATOM works fine, but that defeats the purpose of using this package.

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0.
These type issues all so far seem fixed with this release due to using node-pty-prebuilt instead unmaintained and outdated pty.js

if issues persist open a new ticket with required information.

Thx =)
