### ISSUE TITLE
Install @ionic/app-scripts and typescript won't work in platformio

### ISSUE THREAD

**Issue by MaverickWarlock** [platformio/platformio-atom-ide-terminal#469]
I found this problem accidentally when trying to install @ionic/app-scripts and typescript using npm i @ionic/app-scripts -D (same for typescript).

Using platformio terminal, the installation won't result in successful installation, but using windows command prompt directly will result in successful installation of @ionic/app-scripts and typescript.

At first I thought maybe because platformio is using windows powershell, but actually when using powershell to install @ionic/app-scripts and typescript, the result is still successful.

As you can see in attachment below
![image](https://user-images.githubusercontent.com/17490926/37072389-bafa2544-21f3-11e8-90df-f739e730b071.png)
This is when using platformio terminal

![image](https://user-images.githubusercontent.com/17490926/37072472-576d3a60-21f4-11e8-9c39-5073c7c6372d.png)
And this is when using windows command prompt

And same thing is happening here in attachment below also
![image](https://user-images.githubusercontent.com/17490926/37072619-152748e8-21f5-11e8-8a09-d68ff16af254.png)
Even more peculiar things happen in @ionic/app-scripts package installation

![image](https://user-images.githubusercontent.com/17490926/37072748-960cd978-21f5-11e8-8e5c-9d888a14730e.png)
![image](https://user-images.githubusercontent.com/17490926/37072755-9de6ba7e-21f5-11e8-963a-8801bc19d003.png)
While using windows command prompt, it works perfectly

Hope there'll a solution to this as I starting to love platformio terminal already

**Comment by MaverickWarlock** [comment]
because there's no answer at all here, I think it's time to move on.
I tried to use yarn and for now it solved my problem.

**Comment by descodifica** [comment]
I encountered a similar problem with VueJS and solved it in the following way, try:

Add in Auto Run Command of the Platformio Ide Terminal settings:

$env:NODE_ENV="development"
