### ISSUE TITLE
Mac High Sierra, Swiss German Keyboard: cannot use [], \, {} and other keys

### ISSUE THREAD

**Issue by bleikera** [platformio/platformio-atom-ide-terminal#472]
Hi, 
I cannot use any of the keys that are accessed via ALT in the terminal.

This concerns for example #, [, ], |, {, }, and \

Whenever trying to use one of those, the row beginning turns into a (args: int), e.g.
(args: 5) 

in Atom, the characters are working properly, but in the terminal, they do not behave correctly.

Any tips on how to fix that?

my system:

Atom 1.24.1
platform-ide-terminal 2.8.0
Mac OS High Sierra 10.13.3
Swiss German Keyboard

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0 is using node-pty-prebuilt instead unmaintained and outdated pty.js

if issues persist open a new ticket with required information.

Thx =)
