### ISSUE TITLE
command prompt and text become invisible (after running php artisan command)

### ISSUE THREAD

**Issue by TomRosenbloom** [platformio/platformio-atom-ide-terminal#473]
I'm using Atom for Laravel development. When I open a new terminal window the command prompt is present and correct, e.g. C:\xampp\htdocs\projectname> but when I run any artisan command from the command line e.g. 'php artisan help', the command prompt becomes invisible, leaving just the blinking cursor, in the position where it would be at the end of the line. If I type in further commands this text will also be invisible though the command will be executed. Interestingly, if I type an erroneous command like 'php artisan foo', producing an error message, the command prompt will re-appear following the error message, and then remain visible for any subsequent legitimate commands. But then if I close and re-open the terminal window the problem returns.

I've tried uninstalling/re-installing, and changing settings - different shell, different theme, all to no avail.

Can anyone reproduce this problem and/or suggest a fix?

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0 is using node-pty-prebuilt instead unmaintained and outdated pty.js

if issues persist open a new ticket with required information.

Thx =)
