### ISSUE TITLE
Easy way to remove/hide the status-bar?

### ISSUE THREAD

**Issue by leseb** [platformio/platformio-atom-ide-terminal#474]
Thanks for the great work, the terminal does the job perfectly.

I was wondering if there was a way to hide the status bar?
I don't use the icons on that bar and I never resize it anyway.

I tried to hack around it, by removing the status-bar.coffee but some sort of cache might persist because this doesn't do anything.

Thanks in advance for your help.

**Comment by the-j0k3r** [comment]
If I understand you correctly, the Status bar is part of Atom, you can hide by adding the following to its stylesheet.

```css
.footer {
    display: none !important;
}
```
![danger](https://user-images.githubusercontent.com/31389848/52416884-ee493600-2aea-11e9-8d51-2f10a01c59d5.gif)

If thats not it please add more information on which are youre trying to hide.

**Comment by leseb** [comment]
I meant the bar from the terminal, the one that shows a keyboard icon etc. In your example, the bar above your "Windows PowerShell" word.

Thanks.

**Comment by the-j0k3r** [comment]
Ah that has already been answered here #580

**Comment by leseb** [comment]
Thanks
