### ISSUE TITLE
Backspace and updating error

### ISSUE THREAD

**Issue by Matterny** [platformio/platformio-atom-ide-terminal#475]
So, I am running a windows 10 system, and have the bash ubuntu feature installed and enabled. I have configured platformio-atom-ide-terminal to automatically launch this bash instead of powershell, since I am mostly using bash commands and mostly need to use linux. 
Now, The specific issue is two-fold. When I compile and run a program using the default g++,  entering text into a cin statement gives a ^H instead of removing the character. In addition, when the program is supposed to clear the screen, using system("clear"), it only works after I start typing in the next cin statement, almost like its not automatically updating. These are technically 2 issues, however I suspect that when 1 is cured, the other will be cured as well. 
A nice feature that may be somewhat related is that when I compile using the same command in this or in bash, in this I get more error information, especially relating to segfaults. 
Running everything with the command: g++ <File>;./a.out

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0 is using node-pty-prebuilt instead unmaintained and outdated pty.js

if issues persist open a new ticket with required information.

Thx =)
