### ISSUE TITLE
Broken in Atom 25.0

### ISSUE THREAD

**Issue by crcdng** [platformio/platformio-atom-ide-terminal#477]
Blinking Cursor, no prompt shown. This is for multiple platforms, see also #476, #466

**Comment by c5-tommy** [comment]
I ran into this issue today, I saw a small red bug icon in the bottom right of the editor.  When I clicked on it I was taken to a screen that showed the ide-terminal package needed to be rebuilt.  I clicked the Rebuild package button and everything is working properly now

**Comment by apovall** [comment]
I have the same issue, but no red bug icon as @tbuzelli-c5 describes. Tried running `apm rebuild` (everything as well as platformio-ide-terminal). Get message of successful rebuild but still same issue of the blank terminal. Any idea on how to get said package to rebuild, if not using `apm rebuild` ?

Temporary workaround is to roll back to 1.24.1 (which _does_ work, have just tried it) until I see this has actually been fixed.

**Comment by deloosem** [comment]
I have this issue too. Blinking cursor and nothing else. I tested the terminal from the arduino IDE and it outputs fine. In atom nothing. I hope it will be fixed.

Right now I use the arduino Terminal side by side with platformIO

**Comment by ivankravets** [comment]
@atom has updated Electron to the new version, as result, we need to rebuild binaries for the different platforms. We are working on that and the new version of this terminal will be released soon.

**Comment by Kogoruhn** [comment]
U can use earlier version of atom, simply for work continue
f.e. https://github.com/atom/atom/tree/v1.24.1

**Comment by pjv** [comment]
uninstalled + reinstalled current version = works for me.

**Comment by ivankravets** [comment]
@pjv what is your OS? Are here Windows users?

**Comment by CrispyCrafter** [comment]
@pjv  @ivankravets  Tried to uninstall/re-install on Mac OS 10.13.3 (High Sierra).  Can confirm does not work. Oh well, will just have to bash it for a while until the patch.

**Comment by ivankravets** [comment]
All binaries are ready and work except Windows. Could some provide here binaries for Windows? I'll explain how to compile PTY.JS

**Comment by pjv** [comment]
Sorry - MacOS 10.13.3 / Atom 1.25.0.

Wasn't working for me after the 1.25.0 update. All I did was uninstall and then immediately re-install and it worked.

**Comment by aldahick** [comment]
@ivankravets Send instructions - I'll see if I can get it done.

**Comment by ivankravets** [comment]
New version 2.8.1 is out! Please upgrade!

**Comment by ivankravets** [comment]
@aldahick does 2.8.1 work for you?

Guys, please confirm here that it works now. thanks!

**Comment by ojbg** [comment]
Awesome! working on windows 10 x64

**Comment by aldahick** [comment]
Yep, it works for me @ivankravets. Thanks!

**Comment by ivankravets** [comment]
Great!

Have a nice weekend!

**Comment by CrispyCrafter** [comment]
@ivankravets Yes sir thank you!

**Comment by ivankravets** [comment]
Thank you, @valeros for the Windows binaries! 😊

**Comment by roddypratt** [comment]
Awesome. Works for me on Win 10.  Thanks for the fast response!

**Comment by apovall** [comment]
Upgraded to 2.8.1, works perfectly. Thanks @ivankravets.

**Comment by ritou11** [comment]
2.8.1 works perfectly for me. Thank you @ivankravets !

**Comment by sergioplacanica** [comment]
@ivankravets  2.8.1 on windows here, doesn't work :(

**Comment by OsBlaineOra** [comment]
@ivankravets I'm using 2.8.1 on Windows 7 and I only have the blinking cursor.  I've un-installed and re-installed platformio-atom-ide-terminal, still not working.

**Comment by NicoLaval** [comment]
@ivankravets 2.8.1 doesn't seem to fix on Windows 7 :(

**Comment by underdpt** [comment]
Hi. I'm on Windows 10 Pro version 1709 and it's not working: only shows a blinking cursor. 
Tried to reinstall, uninstall and install again with no luck.

**Comment by rhkina** [comment]
@ivankravets Not working for me: Windows 7, Atom 1.25.0, platformio 2.8.1,  :(

**Comment by tangmediauk** [comment]
Still broken for me on Windows 10, Atom 1.25.0, platformio 2.8.1. Tried uninstalling and reinstalling.
