### ISSUE TITLE
Blank terminal window on Atom 1.25.0

### ISSUE THREAD

**Issue by adityamahapatra** [platformio/platformio-atom-ide-terminal#478]
Hi,

I installed platformio on Atom 1.21.1 and it worked fine. Then I went on to update Atom to version 1.25 and ever since, I have been getting a blank terminal with a blinking cursor.

![platformio](https://user-images.githubusercontent.com/24292999/37496498-ddb23108-28d8-11e8-8569-3a21ac62ee59.JPG)

**Comment by tidydevv** [comment]
yes also experiencing this issue

**Comment by KevinKulp** [comment]
Same here, I've tried uninstalling > restarting atom > reinstalling, no luck.

**Comment by ohri-anurag** [comment]
Same issue, reinstalling the package did not help.

**Comment by adityamahapatra** [comment]
Just to check, I tried uninstalling this, installed terminal-plus (of which, this is a fork). That is giving the same issue as well.

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-atom-ide-terminal/issues/477
