### ISSUE TITLE
platformio-atom-ide-terminal 2.8.0 blank on Atom 1.25.0 x64 (OS Windows 10 x64)

### ISSUE THREAD

**Issue by rikynurdiana** [platformio/platformio-atom-ide-terminal#479]
after i update atom version to 1.25.0 then platformio-atom-ide-terminal 2.8.0 gone blank. i use windows 10 x64. need your help please.
![blank](https://user-images.githubusercontent.com/6265650/37504223-8a30f3ac-290f-11e8-8f01-59982ca17431.PNG)

**Comment by chulit** [comment]
same issues

**Comment by roddypratt** [comment]
Duplicate of #478

**Comment by vidsav** [comment]
same here

**Comment by kelvin8773** [comment]
Hi, I got the same issues while I am at( **MacOS 10.13.3**), I tried to reinstall the package or even (**Atom 1.25.0 x64**) , both doesn't work. 

And I actually remember it was like that even right before I update (**Atom 1.24.0 x64**) to **1.25.0**, I thought it is update issue and turn out it is sth else.

![screen shot 2018-03-16 at 4 55 41 pm](https://user-images.githubusercontent.com/15091317/37511889-64d6b656-293b-11e8-9387-3121f26d1b30.png)

![screen shot 2018-03-16 at 4 56 50 pm](https://user-images.githubusercontent.com/15091317/37511848-4332003c-293b-11e8-85c8-fa1ed4946f9f.png)

**Comment by alex-muci** [comment]
+1

**Comment by theGhostJW** [comment]
+1

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-atom-ide-terminal/issues/477

**Comment by rhkina** [comment]
+1
