### ISSUE TITLE
ATOM 1.25.0 on OSX 10.12.6 -PlatformIO: Terminal service is not registered.

### ISSUE THREAD

**Issue by juergenschubert** [platformio/platformio-atom-ide-terminal#480]
Folks,
my Atom is telling me:
Make sure that "platformio-ide-terminal" package is installed and activated.
I am using the platformio-ide-terminal 2.8.0 and had no issues so far. But today I got this error. I installed the platformio-ide-terminal and reinstalled it but seams not to solve this problem

**Comment by ivankravets** [comment]
https://github.com/platformio/platformio-atom-ide-terminal/issues/477
