### ISSUE TITLE
Platformio terminal wouldn't start (after the last update of Atom)

### ISSUE THREAD

**Issue by webEquipage** [platformio/platformio-atom-ide-terminal#481]
Hello there!

I have 
![image](https://user-images.githubusercontent.com/29765165/37515898-4f8d8d04-2947-11e8-8ac3-cf01265d6eaf.png) 
and 
![image](https://user-images.githubusercontent.com/29765165/37515908-607b1028-2947-11e8-95f7-56d6e6e1b88f.png)

After I start the terminal, it's totally black, with blinking cursor.
![image](https://user-images.githubusercontent.com/29765165/37515977-a26196f6-2947-11e8-9b8d-49dc93e4be69.png)

I've tried to re-install the terminal, it didn't help. 

I haven't noticed the moment when the terminal changed its native behavior, but it happened today, within the last few hours. Any help?

Thanks,

Dmitry

**Comment by ivankravets** [comment]
https://github.com/platformio/platformio-atom-ide-terminal/issues/477

**Comment by webEquipage** [comment]
Thanks! After release of the 
![image](https://user-images.githubusercontent.com/29765165/37550380-0c8c82c8-29c7-11e8-8fed-438b9811438d.png)
things are back to normal
