### ISSUE TITLE
Not working, Just blinking cursor, no prompt shown.

### ISSUE THREAD

**Issue by sangamsyabil** [platformio/platformio-atom-ide-terminal#483]
I wasn't using terminal a while, now not working. I tried uninstalling and installing. I am using Atom 1.25.0 

![capture](https://user-images.githubusercontent.com/25291216/37524101-398c52e4-28ff-11e8-8729-e92e75e65d37.JPG)

**Comment by digomes87** [comment]
this issue https://github.com/platformio/platformio-atom-ide-terminal/issues/482 is the same Dude

**Comment by roddypratt** [comment]
Duplicate of #477

**Comment by sangamsyabil** [comment]
How to downgrade the atom? 
useful link to a process is appreciated.

**Comment by kushalj001** [comment]
+1

**Comment by kushalj001** [comment]
platformio terminal ide suddenly stopped working on atom . Uninstalled and installed again both the package and atom.
no luck. 
on atom 1.25

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-atom-ide-terminal/issues/477#issuecomment-373765626
