### ISSUE TITLE
terminal and serial monitor have stopped working after today's platformio update

### ISSUE THREAD

**Issue by Hristo05** [platformio/platformio-atom-ide-terminal#485]
terminal and serial monitor have stopped working after today's platformio update. Can't see any error message nor advice anywhere.
Tried to uninstall and reinstall, no luck.
Still works perfectly with Arduino IDE.

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-atom-ide-terminal/issues/477#issuecomment-373765626
