### ISSUE TITLE
Terminal shows only flashing cursor

### ISSUE THREAD

**Issue by tarunnsharma** [platformio/platformio-atom-ide-terminal#486]
The terminal shows up but I am not able type in it . Do I have change environment variable ?The python programs run with IDLE but not with ATOM as the terminal is not working properly.

**Comment by ccheau** [comment]
Update your package

**Comment by tarunnsharma** [comment]
every package is updated

**Comment by DrGonzoIII** [comment]
I have the same issue.

**Comment by ravi198715** [comment]
same issue cursor keeps flashing . uninstalling , installing, updating nothing works

**Comment by AlexKutkanych** [comment]
I had the same issue, deleting, installing and relaunching Atom helped me

**Comment by tobkum** [comment]
Same issue here, the workaround by @AlexKutkanych didn't work for me

**Comment by alexis-valois** [comment]
I have the same issue. I suspect it may be due to the lastest Atom version 1.25.0 not beeing compatible with the plugin : my coworker and I started to have the issue right after an automatic update of Atom. At home, I still use 1.24 and the plugin works correctly.

**Comment by rhkina** [comment]
Same issue: Windows 7 (64 bits), Atom 1.25.0

**Comment by jksnow** [comment]
Same issue, blank terminal, just flashing cursor

**Comment by bcichonski** [comment]
![image](https://user-images.githubusercontent.com/3934559/38100100-b308988a-337c-11e8-972b-0b6dfcc1327f.png)

Win10 x64

First error message translated to english is "%1 is not valid win32 application"

**Comment by rafaelm01** [comment]
I downgrade Atom to version 1.24 and it fixed the problem.

**Comment by the-j0k3r** [comment]
Works fine here.

Windows 10 64bit 1709 16299.371
Atom 64bit 1.26.0
Platform-ide-terminal 2.8.1

```
$ atom --version
v7.9.0
```

```
$ apm --version

apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.26.0
python 3.5.2
git 2.17.0.windows.1
visual studio
```
![capture](https://user-images.githubusercontent.com/31389848/39189339-ea5dc204-47c9-11e8-9bf1-99c263cd89f4.PNG)

![test2](https://user-images.githubusercontent.com/31389848/39190350-57a09772-47cc-11e8-8060-74a0558bf039.gif)

**Comment by the-j0k3r** [comment]
to anyone monitoring this.

Is this still an issue with Atom 1.28.0 and platformio-ide-terminal 2.8.3?

**Comment by rhkina** [comment]
Decided to use VSCode.

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0.
These type issues all so far seem fixed with this release due to using node-pty-prebuilt instead unmaintained and outdated pty.js
