### ISSUE TITLE
Terminal is not starting

### ISSUE THREAD

**Issue by pkgajulapalli** [platformio/platformio-atom-ide-terminal#489]
When I restarted atom, it showed the following error.

> Some installed packages could not be loaded because they contain native modules that were compiled for an earlier version of Atom.
> 
> 
> `pty.js@0.3.0` – Cannot find module `'/Users/username/.atom/packages/platformio-ide-terminal/node_modules/pty.js/bin/darwin/x64_m54/pty.node'`

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0.
These type issues all so far seem fixed with this release due to using node-pty-prebuilt instead unmaintained and outdated pty.js
