### ISSUE TITLE
New release 2.8.1 renders a empty terminal

### ISSUE THREAD

**Issue by lotusms** [platformio/platformio-atom-ide-terminal#490]
I've tried uninstalling it and re-installing it. I also changed the version to 2.8.0 and nothing seems to work

![platformio-terminal](https://user-images.githubusercontent.com/6147772/37660717-6a2043f2-2c29-11e8-8990-0f571593bef6.png)

**Comment by NicoLaval** [comment]
@ivankravets 2.8.1 doesn't seem to fix on Windows 7 #477

**Comment by Clano** [comment]
Yes, for me its not working on windows 7, any sugestion?

**Comment by roddypratt** [comment]
@Clano Use the Atom "View/Developer Tools" menu and see what's showing in the console. That would help to understand why the fix isn't working for you.

**Comment by AndrewMoore10** [comment]
Here is the console error I'm getting:
```
%1 is not a valid Win32 application.
\\?\C:\Users\***\.atom\packages\platformio-ide-terminal\node_modules\pty.js\bin\win32\ia32_m54\pty.node Error: %1 is not a valid Win32 application.
\\?\C:\Users\***\.atom\packages\platformio-ide-terminal\node_modules\pty.js\bin\win32\ia32_m54\pty.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:488:32)
...
```

**Comment by marianolop22** [comment]
Hi! win7m platformio-ide-terminal 2.8.1 and atom 1.25.0 ia32 not working, please! some solution!

**Comment by lotusms** [comment]
You may keep this open for the other devs still having problems. I, unfortunately, couldn't wait and changed to Visual Studio Code. No problems there. Not to say anything bad about atom and its extensions. It was good to me for a very long time. Signing out of this thread. Good luck!

**Comment by roddypratt** [comment]
@AndrewMoore10 Are you using 32-bit or 64-bit Windows? looks like it's trying to find a 32-bit module. On my system, that folder contains pty.node.bak but not pty.node, while the x64_mXX folders  contain pty.node. You *could* try renaming that pty.node.bak to pty.node in that folder? No warranty expressed or implied :)

**Comment by marianolop22** [comment]
@roddypratt Hi! i'm using  win32, for now, installed visual code.  Can you give me the entire path of the route?

**Comment by roddypratt** [comment]
@marianolop22 Look here.
` C:\Users\***\.atom\packages\platformio-ide-terminal\node_modules\pty.js\bin\win32\ia32_m54\pty.node`

**Comment by marianolop22** [comment]
@roddypratt i've got theese files pty.node.bak, winpty.dll, winpty-agent.exe

**Comment by marianolop22** [comment]
rename it, but still is not working

**Comment by AndrewMoore10** [comment]
I installed x64 and its working now. Thanks @roddypratt!

**Comment by eihabovich** [comment]
@AndrewMoore10 Can you share the steps?

**Comment by ghost** [comment]
@lotusms The latest release by @ivankravets fixes the problem.
[platformio-atom-ide-terminal v2.8.3](https://github.com/platformio/platformio-atom-ide-terminal/releases/tag/v2.8.3)

![ido-terminal](https://user-images.githubusercontent.com/40354438/41809790-bd04100c-76f3-11e8-8449-d245bc0e4dc9.png)

**Comment by ivankravets** [comment]
Please upgrade to the latest version
