### ISSUE TITLE
Why this is not working?

### ISSUE THREAD

**Issue by ghost** [platformio/platformio-atom-ide-terminal#493]
First time when i install this works , but now why is not working?

Please repair this

I'm using Windows 10

Thank you,
Cristy

**Comment by ivankravets** [comment]
Try to uninstall and install again

**Comment by lisabi** [comment]
Having same issues here.
![screenshot 2](https://user-images.githubusercontent.com/13150516/37837327-3a7f03c0-2eb5-11e8-9678-b90af970857c.png)

**Comment by ghost** [comment]
Same issue here.

Win7 x64
Atom v1.25.0 ia32
Package v2.8.1

Tried to uninstall and reinstall it, not working more

**Comment by rubik16x16** [comment]
Same issue here.

Win8 x64
Atom v1.25.0 
Package v2.8.1

Tried to uninstall and reinstall it.

**Comment by ghost** [comment]
When if this will be updated again?

[Sorry bad english.]
