### ISSUE TITLE
Update 2.8.1 Failed to Install

### ISSUE THREAD

**Issue by DFYT42** [platformio/platformio-atom-ide-terminal#495]
Updating to “platformio-ide-terminal@2.8.1” failed.Hide output…
C:\Users\ADMINI~1\AppData\Local\Temp\apm-install-dir-118225-6912-5dnaso.5cfy3krzfr
`-- (empty)

npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\ADMINI~1\AppData\Local\Temp\apm-install-dir-118225-6912-5dnaso.5cfy3krzfr\package.json'
npm WARN apm-install-dir-118225-6912-5dnaso.5cfy3krzfr No description
npm WARN apm-install-dir-118225-6912-5dnaso.5cfy3krzfr No repository field.
npm WARN apm-install-dir-118225-6912-5dnaso.5cfy3krzfr No README data
npm WARN apm-install-dir-118225-6912-5dnaso.5cfy3krzfr No license field.
npm ERR! Windows_NT 10.0.16299
npm ERR! argv "C:\\Users\\Administrator\\AppData\\Local\\atom\\app-1.25.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Administrator\\AppData\\Local\\atom\\app-1.25.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\Administrator\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\Administrator\\.atom\\.apmrc" "install" "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\d-118225-6912-1msgxss.lxwtu4bo6r\\package.tgz" "--runtime=electron" "--target=1.7.11" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! path C:\Users\ADMINI~1\AppData\Local\Temp\apm-install-dir-118225-6912-5dnaso.5cfy3krzfr\node_modules\.staging\extend-a7b51336
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall rename

npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\ADMINI~1\AppData\Local\Temp\apm-install-dir-118225-6912-5dnaso.5cfy3krzfr\node_modules\.staging\extend-a7b51336' -> 'C:\Users\ADMINI~1\AppData\Local\Temp\apm-install-dir-118225-6912-5dnaso.5cfy3krzfr\node_modules\platformio-ide-terminal\node_modules\extend'
npm ERR!     at destStatted (C:\Users\Administrator\AppData\Local\atom\app-1.25.0\resources\app\apm\node_modules\npm\lib\install\action\finalize.js:25:7)
npm ERR!     at C:\Users\Administrator\AppData\Local\atom\app-1.25.0\resources\app\apm\node_modules\npm\node_modules\graceful-fs\polyfills.js:264:29
npm ERR!     at FSReqWrap.oncomplete (fs.js:123:15)
npm ERR! 
npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\ADMINI~1\AppData\Local\Temp\apm-install-dir-118225-6912-5dnaso.5cfy3krzfr\node_modules\.staging\extend-a7b51336' -> 'C:\Users\ADMINI~1\AppData\Local\Temp\apm-install-dir-118225-6912-5dnaso.5cfy3krzfr\node_modules\platformio-ide-terminal\node_modules\extend'
npm ERR!     at Error (native)
npm ERR!  { Error: EPERM: operation not permitted, rename 'C:\Users\ADMINI~1\AppData\Local\Temp\apm-install-dir-118225-6912-5dnaso.5cfy3krzfr\node_modules\.staging\extend-a7b51336' -> 'C:\Users\ADMINI~1\AppData\Local\Temp\apm-install-dir-118225-6912-5dnaso.5cfy3krzfr\node_modules\platformio-ide-terminal\node_modules\extend'
npm ERR!     at destStatted (C:\Users\Administrator\AppData\Local\atom\app-1.25.0\resources\app\apm\node_modules\npm\lib\install\action\finalize.js:25:7)
npm ERR!     at C:\Users\Administrator\AppData\Local\atom\app-1.25.0\resources\app\apm\node_modules\npm\node_modules\graceful-fs\polyfills.js:264:29
npm ERR!     at FSReqWrap.oncomplete (fs.js:123:15)
npm ERR! 
npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\ADMINI~1\AppData\Local\Temp\apm-install-dir-118225-6912-5dnaso.5cfy3krzfr\node_modules\.staging\extend-a7b51336' -> 'C:\Users\ADMINI~1\AppData\Local\Temp\apm-install-dir-118225-6912-5dnaso.5cfy3krzfr\node_modules\platformio-ide-terminal\node_modules\extend'
npm ERR!     at Error (native) parent: 'platformio-ide-terminal' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\ADMINI~1\AppData\Local\Temp\apm-install-dir-118225-6912-5dnaso.5cfy3krzfr\npm-debug.log
npm ERR! code 1

**Comment by DFYT42** [comment]
Yes, this is a repeat to #477. However, I'm on Windows 10 Enterprise & terminal was simply blinking screen.  I attempted to update, uninstall, and reinstall 2.8.1 and back to 1.2.5...all to no avail. tried running as admin & regular user...

**Comment by the-j0k3r** [comment]
@DFYT42 is this still an issue with 2.8.3?

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0.
These type issues all so far seem fixed with this release due to using node-pty-prebuilt instead unmaintained and outdated pty.js
