### ISSUE TITLE
backspace does not delete all of the text

### ISSUE THREAD

**Issue by clayms** [platformio/platformio-atom-ide-terminal#498]
When using git-bash as the terminal in Windows, the backspace key does not delete all of the text.  It leaves a the first 2 to 10 characters on the screen.  If you press enter, nothing gets ran, so apparently there is actually nothing there, but the shell shows visual 'ghost' of the text that was there.   This only happens with git-bash in Atom.

Windows 10 Enterprise x64
Atom 1.25.0 x64
platformio-atom-ide-terminal 2.8.1
git version 2.14.3.windows.1

Shell Override  -  C:\Program Files\Git\bin\bash.exe

**Comment by clayms** [comment]
Duplicate: https://github.com/platformio/platformio-atom-ide-terminal/issues/108

**Comment by kumkumy2** [comment]
Backspace is not working properly and also forward and backward arrows are not working properly. Can anyone suggest me if this issue has been resolved?
