### ISSUE TITLE
Terminal error: execvp(3) failed.: No such file or directory

### ISSUE THREAD

**Issue by ogail** [platformio/platformio-atom-ide-terminal#5]
Hi,
I am using PlatformIO on mac os x El-Capitan, when I click on the + for open a new terminal session I get error `execvp(3) failed.: No such file or directory`. I have searched online and it says that I need to install java and I've verified java exists by `java --version`, would appreciate help.

I have tried build and upload to Arduino and they worked perfectly.

<img width="1440" alt="screen shot 2016-03-11 at 9 54 06 pm" src="https://cloud.githubusercontent.com/assets/1034045/13720349/39c0f404-e7d4-11e5-9c30-2a2ad6ed7a64.png">
##

**Comment by ogail** [comment]
Found the solution! Atom 2 must be opened with `sudo` from terminal to avoid this problem. If there is a better way please advise, otherwise feel free to close the issue.

**Comment by dmytrokyrychuk** [comment]
Does this occur when you click `+` exclusively, or does this also occur when you open a Serial Monitor?

**Comment by simonmittag** [comment]
I'm experiencing this as well now. With or without sudo when launching with "+". Edit: in my case, the bash executable path was pointing to a wrong location. Now fixed.

**Comment by ivankravets** [comment]
@ogail what is your default shell? Please set valid shell https://kb.iu.edu/d/benf

**Comment by whitfin** [comment]
Had the same problem as @ogail (only worked with sudo), but I added a Shell Override in the settings and now all is good.

**Comment by DanielApt** [comment]
I am having this issue as well.

I have Java installed and am opening it via `sudo`. Still no luck. Any help?

It currently is using `/bin/false` as the shell instance. @simonmittag what did you do?

**Comment by DanielApt** [comment]
Worked for me by setting it the Shell instance to `/bin/bash`

For a list of valid shells, run `cat /etc/shells` in your terminal.

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0.

These type issues all so far seem fixed with this release since [f64888d](https://github.com/platformio/platformio-atom-ide-terminal/commit/f64888d6d134f7e06bbb13a762dfd45335e8a4ba) switching to the currently actively maintained node-pty-prebuilt instead unmaintained and outdated pty.js.

This is good news for stability and compatibility.

if issues persist, please open a new ticket with requested information.

Thx =)

**Comment by ijunaid8989** [comment]
having the same issue at the moment with lastest verison.

**Comment by the-j0k3r** [comment]
me too reports with no details, good luck.

Will lock to prevent such reports.

@ijunaid8989 open a new issue providing ALL the information, if you ommit anything requested it will be closed.
