### ISSUE TITLE
Can't type into the terminal

### ISSUE THREAD

**Issue by pablosutton** [platformio/platformio-atom-ide-terminal#500]
Using Windows 10. Installed platformio a while ago. Tried it today and all I get is cursor. When I try to type nothing happens. I updated platformio and restarted Atom but it still doesn't work.

**Comment by the-j0k3r** [comment]
works fine here

Windows 10 64bit 1709 16299.371
Atom 64bit 1.26.0
Platform-ide-terminal 2.8.1

```
$ atom --version
v7.9.0
```

```
$ apm --version

apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.26.0
python 3.5.2
git 2.17.0.windows.1
visual studio
```
![capture](https://user-images.githubusercontent.com/31389848/39189339-ea5dc204-47c9-11e8-9bf1-99c263cd89f4.PNG)

![test2](https://user-images.githubusercontent.com/31389848/39190200-fd7c3c1a-47cb-11e8-8e09-9890532eee61.gif)

**Comment by LEEDOGEGG** [comment]
Hi,I also meet this problem today.
The console shows "events.js:106  Cannot find module '..\build\Release\pty.node''
And I try to install pty.node using npm command but failed.

**Comment by the-j0k3r** [comment]
Try to uninstall and reinstall platformio-atom-ide-terminal 

IDK, but  it doesnt make sense that it works for some people and not others.

In any case this project is no longer maintained.

**Comment by the-j0k3r** [comment]
@ people monitoring this, is this still an issue with platformio-ide-terminal 2.8.3?

**Comment by LEEDOGEGG** [comment]
Thanks for your reply.I finally solved it by reinstalling  atom.

2018-07-11 

18818224651 



发件人：the-j0k3r <notifications@github.com>
发送时间：2018-07-05 22:15
主题：Re: [platformio/platformio-atom-ide-terminal] Can't type into the terminal (#500)
收件人："platformio/platformio-atom-ide-terminal"<platformio-atom-ide-terminal@noreply.github.com>
抄送："LEEDOGEGG"<18818224651@163.com>,"Comment"<comment@noreply.github.com>

@ people monitoring this, is this still an issue with platformio-ide-terminal 2.8.3?

**Comment by the-j0k3r** [comment]
@LEEDOGEGG Im glad its working for you now. I suspect half the issues reported are Atom profiles gone wild.

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0 is using node-pty-prebuilt instead unmaintained and outdated pty.js

**Comment by gopeshkh1** [comment]
Terminal is not working . Using Ubuntu 18.04. Tried reinstalling platformio but it does seem to work. All I get is cursor. When I try to type nothing happens. I restarted Atom too, but it still doesn't work.
Platformio-ide-terminal version - 2.10.0

**Comment by the-j0k3r** [comment]
@gopeshkh1 see and read https://github.com/platformio/platformio-atom-ide-terminal/issues/668#issuecomment-633130699
