### ISSUE TITLE
wont start

### ISSUE THREAD

**Issue by dmolpa** [platformio/platformio-atom-ide-terminal#501]
I see only blinking cursor. Can't input a thing and command prompt wont start. Reinstalled Atom and platformio terminal.
![capture](https://user-images.githubusercontent.com/37658654/38213831-f3c9b144-36c2-11e8-96c4-90ffbd877c3e.JPG)

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0 these type issue all so far seem fixed with this release due to using node-pty-prebuilt instead unmaintained and outdated pty.js
