### ISSUE TITLE
Terminal panels behave very strange

### ISSUE THREAD

**Issue by clayms** [platformio/platformio-atom-ide-terminal#503]
Terminal panels start to behave very strange when the [atom-html-preview](https://github.com/harmsk/atom-html-preview) package is active.

Not sure who has the problem here, but the html-preview continues to work just fine, and the terminal panels are what start to misbehave.

**Comment by the-j0k3r** [comment]
I cant say I notice this issue but...

Please retest again with platformio-atom-ide-terminal 2.9.0 is using node-pty-prebuilt instead unmaintained and outdated pty.js
