### ISSUE TITLE
Win10 Atom "Editor is not responding" upon Exit after using integrated console

### ISSUE THREAD

**Issue by mixelpixel** [platformio/platformio-atom-ide-terminal#505]
Atom v1.25.0
Platformio-IDE-Terminal v2.8.1
Win10 Home 10.0.16299, x64-based PC

Issue: After using the integrated console, when I close the Atom Editor through the top right `X` button, or File>>>Exit, the Atom application freezes:
![screen shot 2018-04-04 at 7 31 33 am](https://user-images.githubusercontent.com/18152993/38306152-9aaa18da-37dd-11e8-9a87-22445cf0c698.png)

I have the integrated console pointed towards the GitBash executable in the Shell Override settings:
`C:\Program Files\Git\usr\bin\bash.exe`

Using the integrated console, when I exit the app - having entered console commands then closed the integrated console (or left it active) - Atom freezes. As little as a `git status` and it freezes.

Of note, if I merely open the integrated console, let the prompt load, but do not enter anything, I can exit cleanly.

Using the GitBash console by itself with a git repository open in the Atom text editor, and the platformio-ide-terminal **disabled**, I am unable to reproduce this behavior and Atom otherwise exits and operates as expected.

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0 is now using node-pty-prebuilt instead unmaintained and outdated pty.js
