### ISSUE TITLE
I am having nuclide on top of atom. seems like I'm unable to copy(or paste) any text/commands inside terminal

### ISSUE THREAD

**Issue by karingula** [platformio/platformio-atom-ide-terminal#506]
If this is already solved please direct me to the solution. Any hints or solutions are appreciated.

Thanks,

**Comment by xinst** [comment]
I have the same issue!
I solve this issue by disabling a feature of atom-ide-ui.
Go to Settings->packages->atom-ide-ui and expand the Enabled Features, then find the Enable terminal option and set to Never enabled. Now you can select and copy text in the platformio-atom-ide-terminal.

https://github.com/platformio/platformio-atom-ide-terminal/issues/512
