### ISSUE TITLE
Terminal Not Responding in Atom

### ISSUE THREAD

**Issue by Georjay** [platformio/platformio-atom-ide-terminal#508]
Whenever I open my terminal in atom, it only shows an empty console and the cursor blinking. It also does not respond to anything I type. Please help!!!!

![untitled](https://user-images.githubusercontent.com/21058007/38553114-26fbc9b4-3cb6-11e8-9863-2aa06945fd2a.png)

**Comment by cacondie** [comment]
I'm having this issue as well

**Comment by miklik72** [comment]
I've solved this problem by upgrade Atom to 64bit version.

**Comment by OsBlaineOra** [comment]
I upgraded Atom to 64bit version and it's still not working.

**Comment by at9924** [comment]
Would like to reported that I experienced the same issue after updating my Atom editor 64-bit (intentionally set to manual update) to version 1.25.1; prior to the update, it was working fine.

**Comment by at9924** [comment]
Hi everyone.... I got mine working now (Atom 64-bit v.1.25.1 running Windows 8.1).

Here's what I did:
1. Go to **File** -> **Settings** -> **Packages**.
2. In the **Installed Packages** window/page, look for the '**_platformio-ide-terminal_**' package by scrolling down the list of installed packages.
3. Once found, click the **Uninstall** button.
4. After uninstalling the package successfully, close or exit the Atom editor.
5. Restart the Windows operating system.
6. After logging in back to Windows, launch the Atom editor.
7. Go to **File** -> **Settings** -> **Install**.
8. In the **Install Packages** window/page, type '**_platformio-ide-terminal_**' on the text box, followed by pressing **Enter** key.
9. Once the '**_platformio-ide-terminal_**' package is found, click the **Install** button.

After successfully installing the package, it should be working back as it was before. 

However, would like to note that this 'solution' has not been tested on Atom editors (of the same version) running on Linux or OS X operating systems.

Hope this helps.

**Comment by Georjay** [comment]
Thanks for the input @atx900 and @miklik72 

However, I noticed a few things whiles trying to get platformio-ide-terminal to work.
I would usually open a project in the Atom editor using the default windows command prompt (cmd) using the "atom ." command (without the quotes).
Each time I do that and launch the platform-ide-terminal in Atom, it only shows an empty console with the blinking cursor.
So I decided to open the Atom editor directly and when I opened the platformio-ide-terminal in Atom, it works.

Kindly let me know if this helps.
![untitled1](https://user-images.githubusercontent.com/21058007/38615869-148e9778-3d8a-11e8-88f9-948bccee3fa4.png)

**Comment by at9924** [comment]
Glad to be of help, @Georjay 

Tested the command-line recommendation on another Windows computer (a backup dev machine running same the OS and Atom editor versions) that experienced the same platformio-ide-terminal issue.

As advised, ran the "**atom .**" command (w/o the quotes) via default Windows command prompt from inside a project directory/folder. 

![atom-testfix-01](https://user-images.githubusercontent.com/16277149/38622598-17e640be-3dd6-11e8-930f-c385dbe45003.jpg)

It successfully launched the Atom editor and loads the project folder but the platformio-ide-terminal displayed an empty console with a blinking cursor.

![atom-recommendation](https://user-images.githubusercontent.com/16277149/38622522-ef390c14-3dd5-11e8-89cb-9b51800d384e.jpg)

Haven't implemented the 9-steps fix posted earlier so as not to 'contaminate' the Atom editor while finding a much better (and shorter) solution.

**Comment by Georjay** [comment]
Yeah, so I'd encourage anyone who is facing the challenge of an empty console and a blinking cursor to simply open their Atom editor directly (from the desktop). Thanks.

**Comment by OsBlaineOra** [comment]
I almost always run my editor from the icon on the desktop or taskbar.

This does not work for me.

**Comment by gethimG99** [comment]
Thanks

**Comment by Georjay** [comment]
Guys, i also installed Nodejs (https://nodejs.org/en/download/) at some point. You could also try. 
**Note:** I sincerely can't tell if it had any impact on getting the terminal to work.

**Comment by rhkina** [comment]
Hi, guys, platformio is finally working fine for me on Windows 7 with the latest Atom version (1.26.1 x64)!

**Comment by gearskullguy** [comment]
I'm using the latest Atom version 64-bit on Windows 7, just added Git Bash to Settings > Shell Override (pasted in C:\Program Files\Git\bin\git.exe, with or without quotes), and just get the blinking cursor. The program runs just fine when run from command-line or double-clicked in Windows Explorer.

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0 which since [f64888d](https://github.com/platformio/platformio-atom-ide-terminal/commit/f64888d6d134f7e06bbb13a762dfd45335e8a4ba) is using node-pty-prebuilt instead unmaintained and outdated pty.js. This is good news for stability and compatibility.

if issues persist, please open a new ticket with requested information.

Thx =)

**Comment by 12xman** [comment]
Hi guys,

I have the same issue on platformio-atom-ide-terminal 2.9.1, and i have done all the above mentioned cases but still get the issue. Please help...

![image](https://user-images.githubusercontent.com/46105745/53701392-6e6e6d00-3e05-11e9-853a-58ee489d2852.png)

**Comment by the-j0k3r** [comment]
@12xman 

please open a new issue and fill in all template details, not leaving anything out and adding full screenshots or (preferably) gif captures and relevant portions of the config files for atom.

Thanks.

**Comment by xavalex** [comment]
I have had the same issue for quite some time, having done the 9 steps above again and again... I am using the windows terminal at the moment which is of much more ponderous.

I have also tried launching Atom from the cmd window. Same issue.
![blinking_window](https://user-images.githubusercontent.com/16002532/56131037-52bac280-5f7e-11e9-8e44-d8e95a4194de.png)

Platformio-ide-terminal is only package I have installed . 
![installed](https://user-images.githubusercontent.com/16002532/56131099-7a118f80-5f7e-11e9-8b5e-22bf1a1e3f8b.JPG)

I have also uninstalled Atom completely and re-installed. Still the same issue.

I am using Windows 10 Home. Curiously, the platformio terminal opened without issue for a long time. This might be a case of some kind of update that went wrong.

**Comment by the-j0k3r** [comment]
@xavalex

You are using WIndows 10 1809 right? If so set your terminal to bash, see https://github.com/platformio/platformio-atom-ide-terminal/issues/668#issuecomment-482838020

I advise you also read the post above.

Also, this issue is for an outdated version of platformio-ide terminal, if you still have an issue after this, reopen a new ticket.

Thank you.

**Comment by sikapreneur** [comment]
> Hi everyone.... I got mine working now (Atom 64-bit v.1.25.1 running Windows 8.1).
> 
> Here's what I did:
> 
> 1. Go to **File** -> **Settings** -> **Packages**.
> 2. In the **Installed Packages** window/page, look for the '**_platformio-ide-terminal_**' package by scrolling down the list of installed packages.
> 3. Once found, click the **Uninstall** button.
> 4. After uninstalling the package successfully, close or exit the Atom editor.
> 5. Restart the Windows operating system.
> 6. After logging in back to Windows, launch the Atom editor.
> 7. Go to **File** -> **Settings** -> **Install**.
> 8. In the **Install Packages** window/page, type '**_platformio-ide-terminal_**' on the text box, followed by pressing **Enter** key.
> 9. Once the '**_platformio-ide-terminal_**' package is found, click the **Install** button.
> 
> After successfully installing the package, it should be working back as it was before.
> 
> However, would like to note that this 'solution' has not been tested on Atom editors (of the same version) running on Linux or OS X operating systems.
> 
> Hope this helps.

This worked for me. I uninstalled platformio-ide-terminal and installed again. Just that. I didn't restart the pc

**Comment by the-j0k3r** [comment]
This is outdated and solution already exists in other topic.
