### ISSUE TITLE
NPM can't see any of my global modules while using this terminal

### ISSUE THREAD

**Issue by bakana808** [platformio/platformio-atom-ide-terminal#51]
Using git bash for this package, running `npm list -g` gives me an empty list:

![](http://i.imgur.com/nTJUSpn.png)

Here it is again using PowerShell:

![](http://i.imgur.com/q22w8ZO.png)

Outside of Atom it works fine (notice how it's looking in the same exact directory):

![](http://i.imgur.com/mQ1790j.png)

This might be related to #15 since I did notice the `NODE_ENV` variable being overwritten by Atom, though I have no idea if that is the problem.

But for the record, running just `npm list` works fine for seeing local node packages.

**Comment by dmccollough** [comment]
I'm having the same issue as well, when I do a npm install it immediately returns to the prompt and does nothing. If I open a PowerShell window as administrator and change to the same directory and do a npm install everything works fine.

**Comment by ChiefORZ** [comment]
+1

**Comment by vejin** [comment]
+1

**Comment by black-snow** [comment]
Yup, same here. This is rendering the whole terminal useless for me. Even `npm i` fails.

**Comment by konstantinfickel** [comment]
For me `npm i` failed using this terminal, too - it seemed to work finde, but just skipped random packages.

**Comment by HayDegha0917** [comment]
On Windows at least, NODE_PATH is set to the Atom path. That is what messes things up.

**Comment by chefhoobajoob** [comment]
+1

Same here - NODE_ENV is also set to 'production' in shell instances on Windows

**Comment by efaryna** [comment]
you can run `$env:NODE_ENV="development"` in the terminal if using windows Powershell
or `set NODE_ENV=development` in windows command prompt
or insert one of those commands (depending on your shell) into the "auto run command" in settings as quick fix.
This same issue occurs with other terminal packages for Atom. I think it might be something in Atom.

**Comment by the-j0k3r** [comment]
fixed with 2.9.0
