### ISSUE TITLE
It does not work with atom 1.25.1

### ISSUE THREAD

**Issue by EnlightonOcean** [platformio/platformio-atom-ide-terminal#511]
![error](https://user-images.githubusercontent.com/12697571/38786347-57e922b8-40f5-11e8-92a6-8589e388983d.png)

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0 these type issue all so far seem fixed with this release due to using node-pty-prebuilt instead unmaintained and outdated pty.js
