### ISSUE TITLE
I can not select the text in the terminal and copy it

### ISSUE THREAD

**Issue by kiiiit** [platformio/platformio-atom-ide-terminal#512]
# Environment

## os
macOS High Sierra
10.13.4

## Atom version
1.26.0 x 64

## platformio-ide-terminal version
2.8.1

# Overview

It is not possible to select texts such as logs displayed in the terminal with the mouse.

For example, if you want to move to a specific commit place with `git log`, you can not copy the commit ID, so you must train your memorization skills ....

Although it is not certain, I feel I can not use it since I updated Atom-ide's package to the latest one.

I am glad if it resolves.

**Comment by crcdng** [comment]
<img width="556" alt="screenshot" src="https://user-images.githubusercontent.com/830492/39085628-67713234-457d-11e8-964e-c7acc7e87ae2.png">

**Comment by ameenross** [comment]
> Although it is not certain, I feel I can not use it since I updated Atom-ide's package to the latest one.

Funny, I'm experiencing the same problem and it did start after an update of atom-ide-ui. Does this terminal package rely on something from atom-ide-ui?

**Comment by kiiiit** [comment]
@i3games 
@ameenross 
Thank you both.
Certainly stopped "atom - ide - ui", it became possible to select normally.

However, I will expect that the bug will be resolved because the function of atom-ide is considerably impaired ...

**Comment by gholami-mohammad** [comment]
I have the same issue!
I solve this issue by disabling a feature of atom-ide-ui.
Go to Settings->packages->atom-ide-ui and expand the `Enabled Features`, then find the `Enable terminal` option and set to `Never enabled`. Now you can select and copy text in the `platformio-atom-ide-terminal`.

**Comment by kiiiit** [comment]
@m6devin 
CC: @ameenross 
CC: @ivankravets 
CC: @i3games 

You are the best!
Thank you very much.

I will close this problem
