### ISSUE TITLE
the bottom of terminal will be covered by the Atom status bar (Atom 1.26.0 x64)

### ISSUE THREAD

**Issue by xinst** [platformio/platformio-atom-ide-terminal#513]
the 2.8.1 - PlatformIO in the Atom version:1.26.0 x64 mac 
the bottom of terminal will be covered by the Atom status bar

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0

**Comment by xinst** [comment]
> Please retest again with platformio-atom-ide-terminal 2.9.0

Thanks and It seems ok
