### ISSUE TITLE
terminal don't allow to write 

### ISSUE THREAD

**Issue by abdullahkhalid092** [platformio/platformio-atom-ide-terminal#515]
not working on 32bit  system

**Comment by the-j0k3r** [comment]
Try to uninstall and reinstall the platformio-atom-ide-terminal again, if that doesnt work get another terminal -> read https://github.com/platformio/platformio-atom-ide-terminal/issues/514#issuecomment-384241678

**Comment by the-j0k3r** [comment]
duplicate of #500

**Comment by the-j0k3r** [comment]
@ivankravets please close this is a duplicate marked as above
