### ISSUE TITLE
error with 'vue create app'

### ISSUE THREAD

**Issue by BeatScherrer** [platformio/platformio-atom-ide-terminal#519]
if you run the vue-cli command 'vue create app' and proceed the instructions there are some dependencies which are missing when trying to run the dev server 'npm run dev'. Trying the same commands in cmder works as expected.

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0 these type issue all so far seem fixed with this release due to using node-pty-prebuilt instead unmaintained and outdated pty.js
