### ISSUE TITLE
not initialized!!

### ISSUE THREAD

**Issue by SP046767** [platformio/platformio-atom-ide-terminal#521]
not getting initialized on startup

**Comment by the-j0k3r** [comment]
try to uninstall and install the platformio-atom-ide-terminal again.

If youre interested also read https://github.com/platformio/platformio-atom-ide-terminal/issues/514#issuecomment-384241678

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0
