### ISSUE TITLE
Copy and Paste?

### ISSUE THREAD

**Issue by compostbrain** [platformio/platformio-atom-ide-terminal#523]
I thought I used to be able to copy/paste using the mouse to select text in the terminal. Now this feature seems to be disabled.  I can do this in iterm which is the terminal I use outside of Atom. Is there a setting for this or way to enable?

**Comment by TimothyMDean** [comment]
I am having this same problem. Text selection, copy, and paste used to work in the terminal. Sometime recently it stopped working.

**Comment by mattpilott** [comment]
I have this also, it's quite annoying

**Comment by mattpilott** [comment]
https://github.com/platformio/platformio-atom-ide-terminal/pull/525

**Comment by mattpilott** [comment]
Also, if you want to patch this yourself short term you can add the following the to atom stylesheet

```
.platformio-ide-terminal.terminal-view .xterm > .terminal > div {
    user-select: text;
    -ms-user-select: text;
    -webkit-user-select: text;
}
```

**Comment by Ewocker** [comment]
Great! Thanks @matt3224 .

**Comment by rajatjindal** [comment]
fixed the issue for me. thanks @matt3224

**Comment by compostbrain** [comment]
Thanks!

**Comment by the-j0k3r** [comment]
Read this https://github.com/platformio/platformio-atom-ide-terminal/issues/514#issuecomment-384241678

All I have to say is this project needs a new maintainer, else PR's or not we are stuffed.

> Also, if you want to patch this yourself short term you can add the following the to atom stylesheet

That is long term realistically speaking, but thanks for not being as cynical as me :)

@matt3224  thanks for workaround and PR, no other pr's have been merged/reviewed in an ice age.

**Comment by the-j0k3r** [comment]
@ivankravets this was fixed in https://github.com/platformio/platformio-atom-ide-terminal/commit/ec07fd7d6f3ac0af22aa045be916de1b3ce043a0 please close.
