### ISSUE TITLE
Gulp behaves differently with this plugin :(

### ISSUE THREAD

**Issue by AlexMachin1997** [platformio/platformio-atom-ide-terminal#526]
Hey everyone,

I'm a little puzzle as to why my gulp system works through the standard OS's command line , but when using this plugin it runs and rebuilds tasks, but the changes are shown in the session.

However, when i manually restarted nodemon the changes were injected into the session, weird. I'm super confused and this is annoying as hell.

I think this is a plugin problem as it works fine in every other terminal i have., but not with platfromio atom-ide-terminal.

Cheers

**Comment by the-j0k3r** [comment]
Read this https://github.com/platformio/platformio-atom-ide-terminal/issues/514#issuecomment-384241678
