### ISSUE TITLE
Using Hyper2 as a terminal?

### ISSUE THREAD

**Issue by andrewcartwright1** [platformio/platformio-atom-ide-terminal#527]
Hi,

I've been trying to use Hyper 2 as a terminal, but whenever I open the terminal its just blank with a flashing text cursor.

Looking at the atom dev tools show's a missing file error? But it looks to be doing that when it is defaulted to powershell.

I'm using:
- Windows 10 x64 Build 17134
- Atom 1.26.1 x64
- platformio-atom-ide-terminal 2.8.1
- Hyper 2

My shell override path is: C:\Users\<Username>\AppData\Local\hyper\Hyper.exe, and I have no other settings configured.

Was wondering if anyone else had any luck using this shell?

**Comment by takumiabe** [comment]
platformio-atom-ide-terminal needs the SHELL to work, not the terminal emulator.

sh, bash, zsh, etc.. are SHELL.
but, I think Hyper 2 is a terminal emulator.

At Windows, cmd.exe is shell and terminal. It is confusable...

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0 is using node-pty-prebuilt instead unmaintained and outdated pty.js
