### ISSUE TITLE
terminal won't toggle off or hide

### ISSUE THREAD

**Issue by archaeojsc** [platformio/platformio-atom-ide-terminal#529]
Using Atom 1.26.1 x64, platformio-ide-terminal 2.8.1, and gitbash. After latest Atom update, the terminal won't toggle to hidden anymore. No errors generated, just stays open unless I close the terminal completely. 

Any ideas why?

**Comment by the-j0k3r** [comment]
No, but you could try to uninstall and reinstall the platformio-atom-ide-terminal.

Also read this https://github.com/platformio/platformio-atom-ide-terminal/issues/514#issuecomment-384241678

**Comment by the-j0k3r** [comment]
@archaeojsc is this still an issue with platformio-ide-terminal 2.8.3 and atom 1.28.0?

**Comment by archaeojsc** [comment]
2.8.3 and 1.28 x64 (Windows)

If there is only one center dock open it now hides correctly, but not if there are two (e.g. editor and preview side-by-side). It will toggle full/normal mode, but hiding doesn't work. It will start to close, but "bounce" right back to open unless the terminal is closed.

Tried uninstall/reinstall, but no change.

**Comment by the-j0k3r** [comment]
Atom 1.23? I doubt this is a reason, but I cant duplicate your issue.

**Comment by archaeojsc** [comment]
Sorry... typo. Atom 1.28 x64.

I'm mostly using atom for markdown editing, so often have an editor window up with a pandoc preview (markdown-preview-plus v3.3.2)... side-by-side with both in a center dock... treeview and minimap in left dock... and have the terminal in a bottom dock to run pandoc or latex commands with git bash. Sometimes git in the right dock, though that doesn't seem to affect the terminal.

If there is more than one pane visible in the center dock area, the terminal pane won't hide. Multiple tabs in the same center dock pane are fine, but not two visible panes.

**Comment by the-j0k3r** [comment]
Can you post a screenshot of when it works and when it doesnt? I think I understand your issue and will try to see if I can duplicate.

Will return later.

**Comment by the-j0k3r** [comment]
![popover](https://user-images.githubusercontent.com/31389848/42566746-7978cdc2-84ff-11e8-87b9-e5601bd09e1b.gif)

If this is what you mean, it works fine here.

**Comment by archaeojsc** [comment]
What happens when you try to hide it (down-arrow to the left), rather than closing the terminal?

**Comment by the-j0k3r** [comment]
Everything works here, no matter what I press, it responds as expected.
![popover](https://user-images.githubusercontent.com/31389848/42644373-5c60b80e-85f3-11e8-8e7d-777659972c52.gif)

**Comment by the-j0k3r** [comment]
I think you should try with a fresh Atom profile just in case your existing one has something odd going on.

**Comment by the-j0k3r** [comment]
@archaeojsc A possibility is to follow this portion https://flight-manual.atom.io/hacking-atom/sections/debugging/#reset-to-factory-defaults

Try to follow these steps after trying the step above to backup/reset Atom.

1.  Make sure you upgrade to latest atom 1.29.0 Then install platformio-ide-terminal 2.8.4
 1. try to duplicate.

Also try to ensure that issue is not being caused by some conflict with another Non-core package.

1.   Install your Non-Core packages one at a time, testing to duplicate issue in between each non core package install

Failing that, this issue is not duplicable. My guess is something on your local install is causing issue by conflict with platformio-ide-terminal.

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0 these type issue all so far seem fixed with this release due to using node-pty-prebuilt instead unmaintained and outdated pty.js
