### ISSUE TITLE
I type too fast for the terminal :-(

### ISSUE THREAD

**Issue by mathuin** [platformio/platformio-atom-ide-terminal#530]
If I type a command, like say `ls -al`, into my terminal and hit return, something strange happens.

```
jmt@nala:~$ ls -
alls: cannot access '-': No such file or directory
jmt@nala:~$ al
```

I wonder if somehow the return keystroke has some kind of higher priority and interrupts whatever keys are in the buffer to be added to the terminal.

It's pretty easy to reproduce, just type really fast. :-)

**Comment by the-j0k3r** [comment]
Read this https://github.com/platformio/platformio-atom-ide-terminal/issues/514#issuecomment-384241678

Its really sad... but your solutions are:

Suggestion 1 type slower 
Suggestion 2  fork the project

I can only do 1.

**Comment by mathuin** [comment]
@the-j0k3r thanks for the pointer!  Suggestion 3 would be to find an alternative solution which is actively maintained and which provides terminal support.  Any recommendations?

**Comment by the-j0k3r** [comment]
There is no 3rd option imho, good luck with that.

A possible 3rd option would be to fork this project as a non JS dev (project manager type thing) + add the fixes/prs hanging dry, then, try convince a few past contributors to join the team on a no obligation clause and hope that generates interest from some competent devs in the short term to continue slowly chugging along.

Or something of that sort, else, find some terminal that works and currently developed/maintained and has basic features you need.

Or move to Vscode and abandon atom. Atom btw has plans to add a terminal but the person responding claimed out right they wouldn't maintain it.

**Comment by mathuin** [comment]
95% of the time I spend in Atom I have an xterm or two open in the correct directories, so I have functional workarounds.

**Comment by the-j0k3r** [comment]
Well there is that, but honestly, ho much does that suck? Switching between windows is a workflow killer.

**Comment by mathuin** [comment]
It's not integrated the way `M-x shell` is within Emacs, that's true, but for my biggest current project, compilation takes between 3-15 seconds depending on the changes I'm making, so window switching isn't my biggest pain point.

**Comment by the-j0k3r** [comment]
In my case if push comes to shove that will have to be the direction to go, but the reason I started using atom is to do as much as possible eliminating a dozen programs for one.

For me thats going backwards to my old setup which also worked but sucked ass. No thanks, Ill Dump atom for a better option, the choice for me to use atom was to have a better more efficient way built into something Atom in this case.

tbh Im not too hot on supporting yet another Microsoft nonsense, but VScode is starting to look mighty good.

**Comment by the-j0k3r** [comment]
There is 1 maintained project, termination https://github.com/Fred-Barclay/Termination but its somewhat like going back in time to terminal-plus and mmm, well you be the judge.

The others are all unmaintained afaik, 900 million terminal projects 899 million are terminally terminal terminated. :+1:

**Comment by mathuin** [comment]
Alas, termination has the same defect from typing too quickly. :-(  It also uses a little extra screen real estate for its terminal windows, so I think I'm going to go back to platformio's terminal, and close this issue.
