### ISSUE TITLE
No show console

### ISSUE THREAD

**Issue by patriciopujos** [platformio/platformio-atom-ide-terminal#531]
Error: Cannot find module 'C:\Users\Patricio\.atom\packages\atom-ide-ui\node_modules\nuclide-prebuilt-libs\pty\build\pty-v0.1.4-electron-v1.7-win32-ia32\pty.node'

**Comment by the-j0k3r** [comment]
uninstall platformio-atom-ide-terminal and reinstall

**Comment by the-j0k3r** [comment]
@patriciopujos is this still a problem with 2.8.3?

**Comment by the-j0k3r** [comment]
@ivankravets this is not related to platformio-ide-termnal please close.

@patriciopujos feel free to report issue to atom-ide-ui https://github.com/facebook-atom/atom-ide-ui/issues
