### ISSUE TITLE
Run cmder outside atom

### ISSUE THREAD

**Issue by SeasonCCC** [platformio/platformio-atom-ide-terminal#532]
If i want to run cmder outside atom based on the current folder, what should i do ?

**Comment by the-j0k3r** [comment]
@SeasonCCC Hello and apologies for late reply, can you please explain what youre trying to achieve exactly, what is cmder?

**Comment by the-j0k3r** [comment]
Actually this has been answered in https://github.com/platformio/platformio-atom-ide-terminal/issues/272

Marking as duplicate and closing.

Thanks.
