### ISSUE TITLE
platformio-ide-terminal

### ISSUE THREAD

**Issue by MDGMDG** [platformio/platformio-atom-ide-terminal#533]
platformio-ide-terminal does not work, the panel shows a black area,but can't enter any text on it.

My OS is Windows 7,and my Atom version 1.27.0

Thanks for your help

MDGMDG

**Comment by ANUJ-07** [comment]
Same issue

**Comment by bccrayton** [comment]
same issue but I'm on MacOS Sierra and Atom version 1.27.0

**Comment by moremorenoadan** [comment]
Just the same for me.

Win 10. Atom 1.27.1

Thanx!

**Comment by the-j0k3r** [comment]
Uninstall and reinstall, it works.

**Comment by moremorenoadan** [comment]
It was the first thing I did: uninstall & install again, but it doesn't work.

**Comment by the-j0k3r** [comment]
Good luck then, this is no longer developed.

**Comment by deepankarbaruah** [comment]
Platformio-ide-terminal does not work, the panel shows a black area,but can't enter any text on it.
Windows 7,and Atom version 1.27.1

**Comment by the-j0k3r** [comment]
@MDGMDG @moremorenoadan is this still an issue with Atom 1.28.0 and platformio-ide-terminal 2.8.3?

**Comment by the-j0k3r** [comment]
also this is a duplicate of #500 

@ivankravets please add a duplicate label and if possible a feedback requested label, pending feedback maybe closed at your discretion.
