### ISSUE TITLE
Unable to select text.

### ISSUE THREAD

**Issue by trusktr** [platformio/platformio-atom-ide-terminal#538]
How do we select text in the terminal, in order to copy it? When I try, it does not select anything.

**Comment by the-j0k3r** [comment]
Please <s>look</s> skate around the open issues.

See https://github.com/platformio/platformio-atom-ide-terminal/issues/523#issuecomment-386700780

also this project is no longer developed.

**Comment by the-j0k3r** [comment]
@ivankravets this has been fixed in https://github.com/platformio/platformio-atom-ide-terminal/commit/ec07fd7d6f3ac0af22aa045be916de1b3ce043a0, please close.
