### ISSUE TITLE
https://www.atom.io/api/packages/platformio-ide-terminal

### ISSUE THREAD

**Issue by 1nf0t3ch** [platformio/platformio-atom-ide-terminal#539]
Unable to download https://www.atom.io/api/packages/platformio-ide-terminal/versions/2.8.1/tarball: self signed certificate in certificate chain

**Comment by the-j0k3r** [comment]
This is outdated anyway (2.8.1), try to disable firewall and try again with 2.8.3

Im also unable to duplicate this issue.

**Comment by the-j0k3r** [comment]
Newer ticket more relevant https://github.com/platformio/platformio-atom-ide-terminal/issues/577

@ivankravets I think this can be closed as an old duplicate. Also I chalk this down to Firewall/Amtivirus being too selective see https://github.com/platformio/platformio-atom-ide-terminal/issues/565 which fixed this type issue himself.

**Comment by the-j0k3r** [comment]
Test with newer atom, issue should be fixed in atom.
