### ISSUE TITLE
cant type on platformio-ide-terminal

### ISSUE THREAD

**Issue by amritanshusingh1997** [platformio/platformio-atom-ide-terminal#540]
i have installed platformio ide terminal package but I cat type on it

**Comment by pdbartsch** [comment]
Same problem here and doesn't show working directory.  I'm on Windows 10 using Atom 1.27.2

**Comment by the-j0k3r** [comment]
duplicate of https://github.com/platformio/platformio-atom-ide-terminal/issues/500

also this project is no longer developed, the maintaner said they would maintain existing features for newer atom but they have done nothing in months and months to address any issues that are related to it.

FYI it works here

**Comment by the-j0k3r** [comment]
@ivankravets please add a duplicate label, close at your discretion.
