### ISSUE TITLE
Platformio-atom-ide-terminal is not working properly

### ISSUE THREAD

**Issue by ghost** [platformio/platformio-atom-ide-terminal#544]
Hi, the platformio-atom-ide-terminal is not working. I wrote python and it was saying:
python : The term 'python' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ python
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (python:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by the-j0k3r** [comment]
Read https://github.com/platformio/platformio-atom-ide-terminal/issues/543

If uninstalling and reinstalling does fix it, oh well.

**Comment by the-j0k3r** [comment]
@ivankravets please close the OP is no longer existing
