### ISSUE TITLE
Terminal not working with npm

### ISSUE THREAD

**Issue by mbkupfer** [platformio/platformio-atom-ide-terminal#546]
When I run the command `npm ls`  command

I get the following output

```
PS C:\Users\mkupfer\Desktop\web-dev-sandbox\test-webpack> npm ls
test-webpack@1.0.0 C:\Users\mkupfer\Desktop\web-dev-sandbox\test-webpack
`-- (empty)
```

but in the GIT bash:

```

mkupfer@MKUPFER18 MINGW64 /c/Users/mkupfer/Desktop/web-dev-sandbox/test-webpack
$ npm ls
test-webpack@1.0.0 C:\Users\mkupfer\Desktop\web-dev-sandbox\test-webpack
+-- webpack@4.12.0
| +-- @webassemblyjs/ast@1.5.12
| | +-- @webassemblyjs/helper-module-context@1.5.12 deduped
| | +-- @webassemblyjs/helper-wasm-bytecode@1.5.12
| | +-- @webassemblyjs/wast-parser@1.5.12
| | | +-- @webassemblyjs/ast@1.5.12 deduped
| | | +-- @webassemblyjs/floating-point-hex-parser@1
.....
.....
.....
```

Any chance someone knows what is causing this?

**Comment by assmdx** [comment]
me too.. when I use 'npm install' or 'npm run',it doesn't works,however when I try this in windows cmd ,it works.

**Comment by the-j0k3r** [comment]
I can confirm this as an issue. 

Even running `atom -v`  from withing platformio-ide-termnal outputs only `v8.9.3` while running externally yields a definitive complete listing. See below.
```
C:\Users\Joker> atom -v

Atom    : 1.29.0
Electron: 2.0.5
Chrome  : 61.0.3163.100
Node    : 8.9.3

C:\Users\Joker> apm -v

apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.29.0
python 3.5.2
git 2.18.0.windows.1
visual studio
```

Platformio-ide-terminal 2.8.4

The problem here is #543 But I would wait until https://github.com/platformio/platformio-atom-ide-terminal/pull/585 is merged

If that doesnt fix it someone needs to submit a fix.

**Comment by Lonniebiz** [comment]
I'm trying platformio-ide-terminal for the first time. I'm getting this:

npm -v
The program 'npm' is currently not installed. You can install it by typing:
sudo apt install npm

Yet, it is already installed and works from other terminals not embedded in Atom.

**Comment by cw00dw0rd** [comment]
Experiencing the same. Acts as if NPM isn't installed but definitely is installed externally. Ubuntu 18 here

**Comment by Lonniebiz** [comment]
I'm on Ubuntu 16.04 and never got this figured out. Maybe has something to do with the way I've already installed npm before ever wanting this package.

Here's how I install it:
sudo apt-get install curl git

### Make sure there is a .bashrc file in your home directory, if not do this command:
touch ~/.bashrc

### Go here:
### https://github.com/creationix/nvm
### to get the latest command nvm install script. This *was* the latest:
wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash

### Now install latest version of node via nvm:
nvm install 10.14.2

### 10.11.0 was latest on 2018-01-08
### Set version 10.11.0 as default verison to use (not necessary on fresh install):
nvm use 10.14.2

**Comment by the-j0k3r** [comment]
I can confirm 2.9.0 fixes this issue + #630

@ivankravets please pin this issue and can close until newer information provided. thx

**Comment by calebhaye** [comment]
This is still an issue running `v2.10.1`

**Comment by UziTech** [comment]
This package is no longer maintained. Please uninstall platformio-ide-terminal and install either [terminus](https://atom.io/packages/terminus) or [x-terminal](https://atom.io/packages/x-terminal)

**Comment by ivankravets** [comment]
@calebhaye what is your OS? Do you use the latest version of Atom? It should work without any issues.

**Comment by ChristopherIndrawan** [comment]
I was having the same issue, but then i just run atom as administrator, and it works. Idk if that's the problem with you all but that's the fix for my case. My teminal is Platformio-ide-terminal
