### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by spac30** [platformio/platformio-atom-ide-terminal#549]
when i  open terminal in atom it will not open current directory for run file.

**Comment by the-j0k3r** [comment]
You select open folder or open file from File menu.

![capture](https://user-images.githubusercontent.com/31389848/41502721-b155ab2a-71b8-11e8-8f7a-00e053d0a912.PNG)

Also platformIO-IDE-terminal package (from atom packages section and select map terminal to, also the working directory portions.

See
![pio-file-folder](https://user-images.githubusercontent.com/31389848/41503116-0031b6bc-71c3-11e8-8376-c50a573b64e1.gif)

**Comment by spac30** [comment]
Thank you! but its not working.

**Comment by the-j0k3r** [comment]
Then explain exactly what you're trying to do, try to press some more keys on the keyboard to form more words so as to explain yourself better.

**Comment by the-j0k3r** [comment]
Closing for lack of information
