### ISSUE TITLE
https://github.com/fusion809/terminal-fusion is successor of this?

### ISSUE THREAD

**Issue by v3ss0n** [platformio/platformio-atom-ide-terminal#55]
I am not sure this project stopped and https://github.com/fusion809/terminal-fusion is the successor so asking.

**Comment by ivankravets** [comment]
There is no major difference between this fork and @fusion809. The only one difference is that this package works everywhere and has some issues with very specific Linux distros, where the @fusion809's package worka only with Linux. See changes:
- https://github.com/platformio/platformio-atom-ide-terminal/commit/9ac54fbc398ee155286371af1fcef69a71d8d13e
- https://github.com/fusion809/pty.js/commit/a00fc7916795546148f822950582b7f8f7aaedb8

I answered before, see my answer here https://github.com/chjj/pty.js/pull/159#issuecomment-223926975

**Comment by v3ss0n** [comment]
sorry we are confused which one to choose. thanks.

**Comment by ivankravets** [comment]
@v3ss0n what is your OS?

**Comment by v3ss0n** [comment]
linux , some of the team uses windows for frontend dev.

**Comment by ivankravets** [comment]
What is your distributive? Do you have problem with platformio-terminal package?

**Comment by v3ss0n** [comment]
no , not at all , platformio works fine. just seeing two and not sure what to choose. and would like to know if platformio is still in development .

**Comment by ivankravets** [comment]
Of course, PlatformIO is in development :) We highly recommend to use our packages and update them if a new version is available.
