### ISSUE TITLE
add windows WSL, git bash and bash as terminals

### ISSUE THREAD

**Issue by bobbymac** [platformio/platformio-atom-ide-terminal#552]
Would be really cool if you added a few if/else statements  ##for windows wsl-bridge, git-bash, windows bash.

**Comment by the-j0k3r** [comment]
See https://github.com/platformio/platformio-atom-ide-terminal/pull/66 that would do it, but alas its 2 years old and not going anywhere.

**Comment by the-j0k3r** [comment]
xterm.js would very much solve this instead of using the old term.js which is 100% unmaintained.

**Comment by the-j0k3r** [comment]
duplicate of https://github.com/platformio/platformio-atom-ide-terminal/issues/435
