### ISSUE TITLE
Support for Atom 1.28.0 Windows

### ISSUE THREAD

**Issue by darron1217** [platformio/platformio-atom-ide-terminal#555]
It stopped working after upgrading Atom from `1.27.2` to `1.28.0` on Windows

How can we fix this bug?

![image](https://user-images.githubusercontent.com/8064923/41752698-0d302b06-7604-11e8-8dc3-cbfecb2f1c06.png)

**Comment by the-j0k3r** [comment]
Thats it, Atom 1.28.0 has electron 2.0 I wonder if that's it, in any case, Im now for the first time not able to make pio-ide-terminal work with atom any longer.

```
$ apm -v

apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.28.0
python 3.5.2
git 2.17.1.windows.2
visual studio

$ atom -v

Atom    : 1.28.0
Electron: 2.0.3
Chrome  : 61.0.3163.100
Node    : 8.9.3

Platformio-ide-terminal 2.8.2
```

@ivankravets When you said you would keep this package working for current atom versions was this true or will you just label this as PR welcome?

Goodbye my old friend platformio-ide-terminal rest in piece :coffin: :skull: :tulip:  :dove: :peace_symbol:

**Comment by darron1217** [comment]
Here's my console log
```log
commitCommentContainer_item.graphql.js:112 Cannot find module '..\build\Release\pty.node'
(anonymous) @ commitCommentContainer_item.graphql.js:112
(anonymous) @ commitCommentContainer_item.graphql.js:112
module.exports.Emitter.simpleDispatch @ commitCommentContainer_item.graphql.js:112
module.exports.Emitter.emit @ commitCommentContainer_item.graphql.js:112
(anonymous) @ commitCommentContainer_item.graphql.js:112
emitTwo @ events.js:126
emit @ events.js:214
emit @ internal/child_process.js:772
_combinedTickCallback @ internal/process/next_tick.js:141
_tickCallback @ internal/process/next_tick.js:180
commitCommentContainer_item.graphql.js:112 {errno: -4058, code: "ENOENT", syscall: "lstat", path: "C:\Users\user\.atom\packages\platformio-ide-termin…ode_modules\pty.js\bin\win32\x64_m57\pty.node.bak"}code: "ENOENT"errno: -4058path: "C:\Users\user\.atom\packages\platformio-ide-terminal\node_modules\pty.js\bin\win32\x64_m57\pty.node.bak"syscall: "lstat"__proto__: Object
(anonymous) @ commitCommentContainer_item.graphql.js:112
(anonymous) @ commitCommentContainer_item.graphql.js:112
module.exports.Emitter.simpleDispatch @ commitCommentContainer_item.graphql.js:112
module.exports.Emitter.emit @ commitCommentContainer_item.graphql.js:112
(anonymous) @ commitCommentContainer_item.graphql.js:112
emitTwo @ events.js:126
emit @ events.js:214
emit @ internal/child_process.js:772
_combinedTickCallback @ internal/process/next_tick.js:141
_tickCallback @ internal/process/next_tick.js:180
commitCommentContainer_item.graphql.js:112 Cannot find module 'C:\Users\user\.atom\packages\platformio-ide-terminal\node_modules\pty.js\bin\win32\x64_m57\pty.node' Error: Cannot find module 'C:\Users\user\.atom\packages\platformio-ide-terminal\node_modules\pty.js\bin\win32\x64_m57\pty.node'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:473:25)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\user\.atom\packages\platformio-ide-terminal\node_modules\pty.js\lib\pty.js:27:9)
    at Object.<anonymous> (C:\Users\user\.atom\packages\platformio-ide-terminal\node_modules\pty.js\lib\pty.js:487:3)
    at Module._compile (module.js:642:30)
    at Object.value [as .js] (C:\Users\user\AppData\Local\atom\app-1.28.0\resources\app.asar\src\compile-cache.js:235:23)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\user\.atom\packages\platformio-ide-terminal\node_modules\pty.js\lib\pty_win.js:10:20)
    at Object.<anonymous> (C:\Users\user\.atom\packages\platformio-ide-terminal\node_modules\pty.js\lib\pty_win.js:410:3)
    at Module._compile (module.js:642:30)
    at Object.value [as .js] (C:\Users\user\AppData\Local\atom\app-1.28.0\resources\app.asar\src\compile-cache.js:235:23)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\user\.atom\packages\platformio-ide-terminal\node_modules\pty.js\index.js:2:18)
    at Object.<anonymous> (C:\Users\user\.atom\packages\platformio-ide-terminal\node_modules\pty.js\index.js:4:3)
    at Module._compile (module.js:642:30)
    at Object.value [as .js] (C:\Users\user\AppData\Local\atom\app-1.28.0\resources\app.asar\src\compile-cache.js:235:23)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
(anonymous) @ commitCommentContainer_item.graphql.js:112
(anonymous) @ commitCommentContainer_item.graphql.js:112
module.exports.Emitter.simpleDispatch @ commitCommentContainer_item.graphql.js:112
module.exports.Emitter.emit @ commitCommentContainer_item.graphql.js:112
(anonymous) @ commitCommentContainer_item.graphql.js:112
emitTwo @ events.js:126
emit @ events.js:214
emit @ internal/child_process.js:772
_combinedTickCallback @ internal/process/next_tick.js:141
_tickCallback @ internal/process/next_tick.js:180
commitCommentContainer_item.graphql.js:112 handler is not defined ReferenceError: handler is not defined
    at process.<anonymous> (C:\Users\user\AppData\Local\atom\app-1.28.0\resources\app.asar\src\task-bootstrap.js:51:20)
    at emitTwo (events.js:126:13)
    at process.emit (events.js:214:7)
    at emit (internal/child_process.js:772:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
(anonymous) @ commitCommentContainer_item.graphql.js:112
(anonymous) @ commitCommentContainer_item.graphql.js:112
module.exports.Emitter.simpleDispatch @ commitCommentContainer_item.graphql.js:112
module.exports.Emitter.emit @ commitCommentContainer_item.graphql.js:112
(anonymous) @ commitCommentContainer_item.graphql.js:112
emitTwo @ events.js:126
emit @ events.js:214
emit @ internal/child_process.js:772
_combinedTickCallback @ internal/process/next_tick.js:141
_tickCallback @ internal/process/next_tick.js:180
```

**Comment by darron1217** [comment]
Problem seems related to [platformio/pty.js](https://github.com/platformio/pty.js) repo.
The pty.js repo does not contains `m57` binary. (Latest is `m54`)

@ivankravets I don't have much knowledge about it, is it possible to change [platformio/pty.js](https://github.com/platformio/pty.js) dependency into [Microsoft/node-pty](https://github.com/Microsoft/node-pty)?

There's an example of node-pty implement [amejia1/atom-xterm](https://github.com/amejia1/atom-xterm)

**Comment by the-j0k3r** [comment]
@darron1217 this is a longer conversation but see...https://github.com/platformio/platformio-atom-ide-terminal/pull/551

**Comment by darron1217** [comment]
@the-j0k3r Thanks, I should have checked the PR first :)

**Comment by the-j0k3r** [comment]
Well lets see what comes out of it and if it cures this, atm Im back to using a standalone terminal outside which sucks, but hey.

**Comment by ivankravets** [comment]
We need new PTY.JS/m57 binary for Windows. Please make PR to https://github.com/platformio/pty.js/pulls

See example: https://github.com/platformio/pty.js/pull/2

P.S: macOS & Linux users, please uninstall and install this extension. Should work for you now.

**Comment by zorn-v** [comment]
https://github.com/platformio/pty.js/pull/3

**Comment by zorn-v** [comment]
Terminal from facebook (atom-ide-ui) does not work also 😋

**Comment by zorn-v** [comment]
@the-j0k3r 
> Goodbye my old friend platformio-ide-terminal rest in piece

Are you know terminal better ?

**Comment by the-j0k3r** [comment]
> Are you know terminal better ?

This is a bit broken English :), do you mean, do I know any better terminals other than pio-ide-terminal?

If so my answer is, OF COURSE NOT, they are all broken and dont integrate as well as  pio-ide-terminal

**Comment by ivankravets** [comment]
`platformio-ide-terminal` v2.8.3 is out with a support for Atom 1.28!

Thank you so much, @zorn-v and @cocoaine for the binaries for Mac/Windows.

**Comment by the-j0k3r** [comment]
@ivankravets thanks I guess, soon we can have node-pty-prebuilt as soon as all binaries are available it should solve many issues.

@zorn-v thanks for providing the bins.

**Comment by zorn-v** [comment]
>This is a bit broken English

Yep, but is it does matters if you understand me ?

>  I guess, soon we can have node-pty-prebuilt as soon as all binaries are available it should solve many issues.

I guess soon we have problems (I think) as `pty.node` does not builded in node v10

**Comment by the-j0k3r** [comment]
> Yep, but is it does matters if you understand me ?

I guessed :) as long as if I make the wrong guess you aren't upset, then no, it doesn't matter one little sausage.

>I guess soon we have problems (I think) as pty.node does not builded in node v10

The answer to that was provided by @daviwil 

> @daviwil replied an hour ago
... I only needed to  bump to Node 10 in general to deal with the changes they've made to how  native modules get built.  Apparently you can't build native modules for  Node 10 with version 9 or below
--

thanks again @zorn-v its appreciated now can use pio again, all the kittens and babies are safe once again.

**Comment by darron1217** [comment]
Thanks everyone :)
I felt this repo is very active and healthy

Thanks for this fancy package @ivankravets 👍

**Comment by zorn-v** [comment]
> thanks again @zorn-v its appreciated now can use pio again, all the kittens and babies are safe once again

What is "pio" (i don't know) but I kill kitties and eat babies for breakfast.
Mediocre troll of you.

Anyway if in MY atom breaks terminal, I find (or write code myself) how to fix it...

**Comment by zorn-v** [comment]
BTW (abbr of by the way)
FUCK YOU  @the-j0k3r
