### ISSUE TITLE
blank terminal

### ISSUE THREAD

**Issue by dimaskpz** [platformio/platformio-atom-ide-terminal#557]

**Comment by Yannny** [comment]
There is a new update v2.8.3 that should fix the bug.

**Comment by the-j0k3r** [comment]
Thank you for your detailed and exhaustive bug report.

This is a duplicate of https://github.com/platformio/platformio-atom-ide-terminal/issues/555

@ivankravets please close :)

**Comment by dimaskpz** [comment]
thankyou
