### ISSUE TITLE
A problem with reinstalling or updating

### ISSUE THREAD

**Issue by hsaltan** [platformio/platformio-atom-ide-terminal#565]
**When I try to update or reinstall the platformio-ide-terminal 2.8.3, I get the below error:**

gyp info it worked if it ends with ok
gyp info using node-gyp@3.4.0
gyp info using node@6.9.5 | darwin | x64
gyp http GET https://atom.io/download/electron/v2.0.3/iojs-v2.0.3.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! install error 
gyp ERR! stack Error: self signed certificate in certificate chain
gyp ERR! stack     at Error (native)
gyp ERR! stack     at TLSSocket.<anonymous> (_tls_wrap.js:1079:38)
gyp ERR! stack     at emitNone (events.js:86:13)
gyp ERR! stack     at TLSSocket.emit (events.js:185:7)
gyp ERR! stack     at TLSSocket._finishInit (_tls_wrap.js:603:8)
gyp ERR! stack     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:433:38)
gyp ERR! System Darwin 17.6.0
gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/node-gyp/bin/node-gyp.js" "install" "--runtime=electron" "--target=2.0.3" "--dist-url=https://atom.io/download/electron" "--arch=x64" "--ensure"
gyp ERR! cwd /Users/hasanserdaraltan/.atom
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 

**What can I do about it?**

**Comment by ghost** [comment]
im trying to install it for the first time and i get the same error, hopefully someone notices and helps.

**Comment by hsaltan** [comment]
I fixed it. Firewall or antivirus can hinder the installation. Better to turn it off first temporarily before the installation.

**Comment by the-j0k3r** [comment]
Fell free to close issue.

**Comment by the-j0k3r** [comment]
@ivankravets issue was solved please close.
