### ISSUE TITLE
ide not working

### ISSUE THREAD

**Issue by saurot123** [platformio/platformio-atom-ide-terminal#566]
my atom ide was working properly before installing platformio terminal package after installation  suddenly  atom ide don't respond and closed automatically. i reinstalled atom but same problem occur..

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0.
These type issues all so far seem fixed with this release due to using node-pty-prebuilt instead unmaintained and outdated pty.js

if issues persist open a new ticket with required information.

Thx =)
