### ISSUE TITLE
command problem

### ISSUE THREAD

**Issue by kingdom84521** [platformio/platformio-atom-ide-terminal#567]
if i entered "cls" it will lag sometimes, until i press another button.
although "clear" command will do the same thing and won't lag at all, but i still tend to use "cls" more.

**Comment by kingdom84521** [comment]
correction: command "clear" will lag, too

**Comment by the-j0k3r** [comment]
This sounds to me like too much going on in Atom rather than the terminal.

Backup your current Atom profile and try to reproduce with a fresh Atom profile.

**Comment by the-j0k3r** [comment]
Last try @kingdom84521 please follow https://flight-manual.atom.io/hacking-atom/sections/debugging/#reset-to-factory-defaults

Then reinstall platformio-ide-terminal with Atom 1.29.0 (latest stable at time of writing this) 

Then retry to duplicate.

Note: I cant duplicate this.

**Comment by the-j0k3r** [comment]
Should be fixed by 2.9.0 release. retry and let us know.
