### ISSUE TITLE
terminal not working .!

### ISSUE THREAD

**Issue by bhupesh07** [platformio/platformio-atom-ide-terminal#570]
it is blinking but not able to type anything .! not even showing anything on it . I am not able to do anything on it please help me out asap

**Comment by the-j0k3r** [comment]
Atom version?
Platformio-ide-terminal version?

Would you press some more keys on your keyboard to describe the stages/steps what you did until you noticed this?

**Comment by bhupesh07** [comment]
i have pressed every single key i can .. but it is not working .. tell me
what to do , i have tried uninstalling as well but it also didn't work..

**Comment by the-j0k3r** [comment]
There is not enough information for me to even guess.

Try type on a terminal outside Atom to run:

`apm uninstall platformio-ide-terminal`

wait until it completes then run

`apm install platformio-ide-terminal`

**Comment by the-j0k3r** [comment]
@ivankravets duplicate of #500 please close
