### ISSUE TITLE
Assertion Failed!  Windows10 Pro

### ISSUE THREAD

**Issue by dunkinman** [platformio/platformio-atom-ide-terminal#571]
I have been encountering an issue with my Windows10 Pro OS using platformio-ide-terminal.  After I reboot my PC and launch Atom, everything is fine until I click on the + sign on the lower left hand corner of the screen to launch a terminal.  When I do so, I receive the following error:

![atom4](https://user-images.githubusercontent.com/30054587/42539104-893fbf9a-845f-11e8-99bd-76bc19b346ee.PNG)

It used to be if I clicked retry, and then shutdown my terminal and then relaunched it, it would take me four times to recycle the terminal and then I would finally be prompted with a command prompt.  In the last couple of months or so this problem seems to be getting more annoying as it can take up to 12 different times until the error goes away and I see the command prompt.  I can only recreate this problem after a reboot.  If I shutdown the terminal and start it back up after I have gotten past this error it does not reoccur.  I am running the most current version of platformio-ide-terminal, 2.8.3 and I am also running the most recent version of Atom as well. 1.28.1.  My laptop is up to date with the most current patches.  Anyone else encountering this problem?  Any ideas on how to fix?

**Comment by the-j0k3r** [comment]
As Ive mentioned before, I cant duplicate your issue or 99% of the issues reported by various people here WIndows side in two separate WIndows 10 pro versions 1709/1803

Given you have previously described system crashes and random now it works now it doesnt in https://github.com/platformio/platformio-atom-ide-terminal/issues/499#issuecomment-403309719 etc My only suggestion to you is test this in a fresh install of OS in something like a virtual machine or a secondary partition/HDD on your PC.

Other than that, Im afraid I dont have any other feedback/suggestions.

**Comment by dunkinman** [comment]
Ok.  Will try a clean install and see what happens.  Sincerely appreciate your efforts.

**Comment by cenap** [comment]
My solution:
`cd c:\Users\<your-user-name-here>\.atom\packages\platformio-ide-terminal>`
`npm i node-pty-prebuilt`
Restart Atom

**Comment by the-j0k3r** [comment]
@cenap How would that work exactly? platforio-ide-terminal doesnt use node-pty-prebuilt

**Comment by cenap** [comment]
Please see https://github.com/platformio/platformio-atom-ide-terminal/issues/547

**Comment by the-j0k3r** [comment]
@cenap that hasnt been implemented yet

**Comment by dunkinman** [comment]
Coincidentally...an update for Atom came out today 1.28.2 x64. I updated Atom to 1.28.2 x64 and after rebooting my machine, only received the Assertion Error 1 time when I tried to launch the terminal. For fun, I rebooted my machine again and when I launched the terminal, I did NOT receive an error. For more fun, because it is Friday night...I rebooted my machine again...and did not receive the error after this reboot either. Can't say for certain it's fixed but it appears to be trending in the right direction.

**Comment by dunkinman** [comment]
Another update.  I had to reboot again to install another product, and this time, Atom did not come up at all!  I ultimately had to uninstall Atom and then reinstall it cleanly.  No Assertion Error after uninstall and clean install.  Running 1.28.2 x64.  Going to continue to monitor after system reboots until comfortable that this has been resolved.

**Comment by dunkinman** [comment]
Appears to be working well.  Uninstalling and then reinstalling Atom 1.28.2 x64 is what I did to resolve the problem.

**Comment by dunkinman** [comment]
Rebooted and tested again today.  No Assertion Errors.  Closing issue.  Uninstall and then reinstall of 1.28.2 x64 resolved this issue.

**Comment by dunkinman** [comment]
This problem resurfaced again this am.  I had to reboot and then got approximately 12 Assertion Errors before I was greeted with a command prompt.  For now, the workaround is to just keep clicking on retry and then open and close the terminal until you do not get the error message.

**Comment by dunkinman** [comment]
I rebooted again and then this problem did not surface.  It seems to be very sporadic now.  Sometimes it happens and sometimes it doesn't.

**Comment by the-j0k3r** [comment]
I still have serious doubts this is related to this package at all, but rather to some conflict with some other package or something you have installed OS side.

**Comment by dunkinman** [comment]
Not sure if it's unrelated or not.  If nothing else, future googlers will at least have a reference of what to do if they encounter a similar problem.  Going to close out for now as problem is not easily replicated.  I rebooted today and problem didn't occur upon starting Atom.  If nothing else, at least it's more sporadic now, it used to consistently be a problem every time a reboot would occur.  Now it's more random.

**Comment by codebibble** [comment]
@dunkinman: I have the same issue on mine... It works sometimes other times i have to hit retry multiple times and depending on my lucky number for the day it would bless me with command prompt after a few attempts!

**Comment by aufdenkampe** [comment]
Two different people I'm working with just had the same error, both when trying to run Terminal and also when trying to run Serial Monitor. Hitting retry multiple times seemed to have solved it for now (thanks for that tip @dunkinman!).

The error message looked slightly different.

![pastedimage-assertionfail](https://user-images.githubusercontent.com/5166036/49883881-2be65700-fdf9-11e8-8080-342a9d0026c1.png)


We'll keep you all posted if this error continues to haunt us.

**Comment by aufdenkampe** [comment]
A third person I'm working with had the same error when Installing PlatformIO for Atom for the first time today. One of the three got things to clear up by uninstalling Atom, rebooting, and reinstalling Atom and PlatformIO. The other two did not have such luck.

I think this issue should be reopened.

Is it possibly connected to https://github.com/platformio/platformio-atom-ide-terminal/issues/604?

**Comment by dunkinman** [comment]
This issue also continues to plague me.  Sometimes when I reboot I don't encounter this issue, but most of the time I do.  At one point I thought it was solved but it still appears regularly.  The work around is the same.  Continue to hit retry and then close the terminal and then relaunch it up to about 10 times and then I finally get a command prompt.

**Comment by MewPin97** [comment]
I have the same problem when I open atom, but my error message is different. Anyone can help? Thanks in advance.
- atom v1.33.0
- windows 10
Uninstall & reinstall does not work for me. 
![capture](https://user-images.githubusercontent.com/41229972/50213607-0e952800-03b9-11e9-8002-fb5099274fb6.PNG)

**Comment by dunkinman** [comment]
@MewPin97 Have you tried to click on the retry button and then open and close the terminal?  You might have to do this up to like 12 times...but then eventually in my case the error clears and I get a command prompt.

**Comment by the-j0k3r** [comment]
Duplicate of #613 @ivankravets pls close.

**Comment by the-j0k3r** [comment]
@dunkinman please open a new ticket, your issue as you have documented in this ticket is not reproducible 100% of the time, you restart/reboot and sometimes platformio-ide-terminal works.

Its of no help to you or anyone else trying to make sense or document of your issue in other reports.

You have made comments, here #499, and #636 and #650 just because of basic issue similarities and its not been helpful to your issue + they were already duplicate issues.

Once you have done that feel free to import your comments from the tickets (for your documentation purposes of the problem YOU experience) above including this one, I will be hiding all comments except ops as offtopic there in #650, because as already established previously here by yourself, your issue is not reproducible 100% of time, could be caused by literally anything, its an unknown at this time.

Please understand its impossible to determine what your issue is about from a support point of view.

Please provide all the information requested including screenshots, errors and logs.

Thx.
