### ISSUE TITLE
Unable to download https://www.atom.io/api/packages/platformio-ide-terminal/versions/2.8.3/tarball: self signed certificate in certificate chain

### ISSUE THREAD

**Issue by AashrithRV95** [platformio/platformio-atom-ide-terminal#577]
Trying to install the package platformio-ide-terminal on atom in the settings view.
I get the following error message.
Unable to download https://www.atom.io/api/packages/platformio-ide-terminal/versions/2.8.3/tarball: self signed certificate in certificate chain

**Comment by the-j0k3r** [comment]
read https://github.com/platformio/platformio-atom-ide-terminal/issues/565

**Comment by the-j0k3r** [comment]
@ivankravets this is duplicate please feel free to tag and close
