### ISSUE TITLE
iTerm2 build 3.0.4 doesn't show folder's name

### ISSUE THREAD

**Issue by mathbunnyru** [platformio/platformio-atom-ide-terminal#58]
I use platformio-atom-ide-terminal and iTerm2. 
When I'd installed a new version of iTerm2 (build 3.0.4), platformio-atom-ide-terminal started to show `sh-3.2$`instead of folder's name. Please, help me to fix it.

**Comment by ivankravets** [comment]
I also use this  iTerm2 (build 3.0.4) and don't have problems. Which shell do you use? I use Fish https://fishshell.com

**Comment by ivankravets** [comment]
See here how to check default shell http://www.cyberciti.biz/faq/howto-set-bash-as-your-default-shell/

**Comment by mathbunnyru** [comment]
@ivankravets when I type `which bash` the output is `/bin/bash`

**Comment by mathbunnyru** [comment]
@ivankravets installed the fishshell via homebrew, made it default. Now, iTerm2 and Terminal use the fishshell, platformio-atom-ide-terminal still uses `/bin/bash`

**Comment by ivankravets** [comment]
@mathbunnyru have you made it as default shell?

P.S: Fish is very COOOOL shell but is very SPECIFIC. Please be careful with it :)

**Comment by mathbunnyru** [comment]
@ivankravets yes. Restart helped. Thank you. I'll try to be careful and not to destroy the planet:)
