### ISSUE TITLE
cannot install in Windows 10 1803 in Atom 1.29.0

### ISSUE THREAD

**Issue by PankajAdiley** [platformio/platformio-atom-ide-terminal#583]
![screenshot 66](https://user-images.githubusercontent.com/30251478/43956372-8dff1fa6-9cc1-11e8-8e7e-f850809e6bae.png)

**Comment by the-j0k3r** [comment]
You can, it should work just fine, try this via external terminal.

`apm install platformio-ide-terminal`

or reinstalling via UI.

If that doesn't work and same issue occurs , I would suggest you complain to https://github.com/atom/fuzzaldrin the errors shown in that screenshot are from https://github.com/atom/fuzzaldrin not platformio-ide-terminal

Also when you report that bug to fuzzaldrin include the file it asks you to submit at end of log in screenshot.

Feel free to close this report, its nothing to do with platformio-ide-terminal.

Thanks.

**Comment by the-j0k3r** [comment]
@ivankravets this ticket is unrelated to platformio-ide-terminal but intead to https://github.com/atom/fuzzaldrin

Please close.
