### ISSUE TITLE
error when opening the platformio terminal

### ISSUE THREAD

**Issue by Akhmami** [platformio/platformio-atom-ide-terminal#584]
atom version 1.29.0
<img width="322" alt="pio" src="https://user-images.githubusercontent.com/23007437/43987769-6d4b1c58-9d50-11e8-8637-ad1f7f81a319.PNG">

**Comment by Akhmami** [comment]
how to solve it?

**Comment by the-j0k3r** [comment]
@Akhmami You could have added more information to your report, like what OS and OS version, you could have added helpful information like

output of: (on external terminal)

`apm ls`
`atom --version`
`apm --version` 

Also please provide.

OS type: What OS Are you using? 
OS version: What version is your OS?

> how to solve it?

A possibility be is to follow this portion https://flight-manual.atom.io/hacking-atom/sections/debugging/#reset-to-factory-defaults

This is caused by something in your setup or by a conflicting extension in Atom, else everyone would have this problem and thats not the case,  I for one dont see this issue.

Also please read #543

**Comment by driador** [comment]
Still an issue... Windows 10 Pro Version 1803 Build 17134.228
Clean install of Atom 1.30
Python 2.7 and 3.x installed

npm/apm/atom info:

Built-in Atom Packages (92)
 atom-dark-syntax@0.29.0
 atom-dark-ui@0.53.2
 atom-light-syntax@0.29.0
 atom-light-ui@0.46.2
 base16-tomorrow-dark-theme@1.5.0
 base16-tomorrow-light-theme@1.5.0
 one-dark-ui@1.12.4
 one-light-ui@1.12.4
 one-dark-syntax@1.8.4
 one-light-syntax@1.8.4
 solarized-dark-syntax@1.1.5
 solarized-light-syntax@1.1.5
 about@1.10.0
 archive-view@0.65.1
 autocomplete-atom-api@0.10.7
 autocomplete-css@0.17.5
 autocomplete-html@0.8.4
 autocomplete-plus@2.40.7
 autocomplete-snippets@1.12.0
 autoflow@0.29.4
 autosave@0.24.6
 background-tips@0.28.0
 bookmarks@0.45.1
 bracket-matcher@0.89.2
 command-palette@0.43.5
 dalek@0.2.2
 deprecation-cop@0.56.9
 dev-live-reload@0.48.1
 encoding-selector@0.23.9
 exception-reporting@0.43.1
 find-and-replace@0.215.12
 fuzzy-finder@1.8.2
 github@0.18.3
 git-diff@1.3.9
 go-to-line@0.33.0
 grammar-selector@0.50.1
 image-view@0.63.0
 incompatible-packages@0.27.3
 keybinding-resolver@0.38.2
 line-ending-selector@0.7.7
 link@0.31.4
 markdown-preview@0.159.20
 metrics@1.6.1
 notifications@0.70.5
 open-on-github@1.3.1
 package-generator@1.3.0
 settings-view@0.255.0
 snippets@1.3.3
 spell-check@0.74.0
 status-bar@1.8.15
 styleguide@0.49.11
 symbols-view@0.118.2
 tabs@0.109.2
 timecop@0.36.2
 tree-view@0.222.0
 update-package-dependencies@0.13.1
 welcome@0.36.6
 whitespace@0.37.6
 wrap-guide@0.40.3
 language-c@0.60.0
 language-clojure@0.22.7
 language-coffee-script@0.49.3
 language-csharp@1.0.4
 language-css@0.42.11
 language-gfm@0.90.5
 language-git@0.19.1
 language-go@0.46.0
 language-html@0.51.1
 language-hyperlink@0.16.3
 language-java@0.30.0
 language-javascript@0.129.1
 language-json@0.19.2
 language-less@0.34.2
 language-make@0.22.3
 language-mustache@0.14.5
 language-objective-c@0.15.1
 language-perl@0.38.1
 language-php@0.44.0
 language-property-list@0.9.1
 language-python@0.51.2
 language-ruby@0.72.2
 language-ruby-on-rails@0.25.3
 language-sass@0.62.0
 language-shellscript@0.27.0
 language-source@0.9.0
 language-sql@0.25.10
 language-text@0.7.4
 language-todo@0.29.4
 language-toml@0.18.2
 language-typescript@0.4.0
 language-xml@0.35.2
 language-yaml@0.32.0

Community Packages (1) C:\Users\reube\.atom\packages
 platformio-ide-terminal@2.8.4


Atom    : 1.30.0
Electron: 2.0.5
Chrome  : 61.0.3163.100
Node    : 8.9.3

apm  1.19.0
npm  3.10.10
node 6.9.5 x64

atom 1.30.0
python 

git 2.18.0.windows.1
visual studio

**Comment by Akhmami** [comment]
because the problem can't be solved, i switched to vscode.
waiting for a solution

**Comment by RobinBlomberg** [comment]
This is still an issue (on one of my laptops), and other terminal packages were likewise buggy or unusable. I can't do much work without a built-in terminal, so I'm giving VS Code a try.

**Comment by the-j0k3r** [comment]
@ivankravets  please close as duplicate of #604
