### ISSUE TITLE
error

### ISSUE THREAD

**Issue by sooqom** [platformio/platformio-atom-ide-terminal#587]
an error occurs every time i use the plat
its assertion failed..... line203 

i've tried to abort/debug/ignore
reinstall
nothing works
please help

**Comment by the-j0k3r** [comment]
This is a duplicate of https://github.com/platformio/platformio-atom-ide-terminal/issues/584

@ivankravets please close.

@sooqom reply to #554 with the information requested in https://github.com/platformio/platformio-atom-ide-terminal/issues/584#issuecomment-412271466
