### ISSUE TITLE
platformio-ide-terminal not working

### ISSUE THREAD

**Issue by JJjulle** [platformio/platformio-atom-ide-terminal#589]
latest version. Mac high sierra 10.13.6
It´s like the package haven´t been installed, the + that should be on the bottom of Atom isn´t showing up .

**Comment by billyjbryant** [comment]
I have this same issue on Sierra 10.12.6.  I used the terminal yesterday, shutdown, started it today and it looks like it isn't even loading.  Tried uninstall/reinstall of the package, nothing, loaded the debug console, no indication as to what fails.  Any ideas?

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0 is using node-pty-prebuilt instead unmaintained and outdated pty.js
