### ISSUE TITLE
unable to find the commands prompt

### ISSUE THREAD

**Issue by achyuthreddyi** [platformio/platformio-atom-ide-terminal#593]
![atomeror](https://user-images.githubusercontent.com/35003947/44617899-5c75a580-a889-11e8-80f7-871cb5eb561a.png)
![atomeror](https://user-images.githubusercontent.com/35003947/44617908-7d3dfb00-a889-11e8-9955-98ce89620916.png)

**Comment by the-j0k3r** [comment]
@ivankravets please close, this is duplicate of #584 

@achyuthreddyi please reply in #584 with information requested in https://github.com/platformio/platformio-atom-ide-terminal/issues/584#issuecomment-412271466

Also there is a suggestion about reseting atom, please follow that.
