### ISSUE TITLE
Cannot install platformio-ide-terminal

### ISSUE THREAD

**Issue by cwil290831** [platformio/platformio-atom-ide-terminal#595]
Hi, 
  I received the following notice when I tried to install the platformio-ide-terminal on my 2016 macbook air. 
Installing “platformio-ide-terminal@2.8.4” failed.Hide output…

npm ERR! Darwin 17.7.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/arthurwilliams/.atom/.apm/.apmrc" "--userconfig" "/Users/arthurwilliams/.atom/.apmrc" "install" "/private/var/folders/59/j2v1k0010gbbrqck7n5kllph0000gn/T/d-11881-9607-1aa1r7f.02j1ao47vi/package.tgz" "--runtime=electron" "--target=2.0.5" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10

npm ERR! Hostname/IP doesn't match certificate's altnames: "Host: registry.npmjs.org. is not in the cert's altnames: DNS:a.sni.fastly.net, DNS:a.sni.global-ssl.fastly.net"
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/59/j2v1k0010gbbrqck7n5kllph0000gn/T/apm-install-dir-11881-9607-1cnblc1.2t82d18aor/npm-debug.log

Please advise.

**Comment by Laputa1212** [comment]
hi Please try to install the npm-install package first and then install the platformio-ide-terminal. Good luck

**Comment by cwil290831** [comment]
This worked, thank you

**Comment by the-j0k3r** [comment]
@ivankravets solved, please close

**Comment by Delfikos** [comment]
Ok... good this worked.. thank you

**Comment by muhakmalfadh** [comment]
> hi Please try to install the npm-install package first and then install the platformio-ide-terminal. Good luck

i cannot instal npm-install too

**Comment by DanMowday** [comment]
It didnt work for me. i can install npm-install but i still have the same issue with platformio-ide-terminal not installing

**Comment by the-j0k3r** [comment]
@DanMowday 

This is a duplicate of #700 see https://github.com/platformio/platformio-atom-ide-terminal/issues/707#issuecomment-514634895 for a possible workaround
