### ISSUE TITLE
Cannot install Platformio-Ide-Terminal Package

### ISSUE THREAD

**Issue by LeaWeigand** [platformio/platformio-atom-ide-terminal#598]
Whenever I try to install the platformio-ide-terminal package, I get the following error messages:
Installing “platformio-ide-terminal@2.8.4” failed.Hide output…

> pty.js@0.3.0 install C:\cygwin64\tmp\apm-install-dir-11885-6896-rw3qhr.k0dp00ms4i\node_modules\platformio-ide-terminal\node_modules\pty.js
> node scripts/install.js

C:\cygwin64\tmp\apm-install-dir-11885-6896-rw3qhr.k0dp00ms4i
`-- (empty)

'node' is not recognized as an internal or external command,
operable program or batch file.
npm WARN enoent ENOENT: no such file or directory, open 'C:\cygwin64\tmp\apm-install-dir-11885-6896-rw3qhr.k0dp00ms4i\package.json'
npm WARN apm-install-dir-11885-6896-rw3qhr.k0dp00ms4i No description
npm WARN apm-install-dir-11885-6896-rw3qhr.k0dp00ms4i No repository field.
npm WARN apm-install-dir-11885-6896-rw3qhr.k0dp00ms4i No README data
npm WARN apm-install-dir-11885-6896-rw3qhr.k0dp00ms4i No license field.
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Users\\lweigand\\AppData\\Local\\atom\\app-1.30.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\lweigand\\AppData\\Local\\atom\\app-1.30.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\lweigand\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\lweigand\\.atom\\.apmrc" "install" "C:\\cygwin64\\tmp\\d-11885-6896-1vzyexe.lw4xn4gqfr\\package.tgz" "--runtime=electron" "--target=2.0.5" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! pty.js@0.3.0 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pty.js@0.3.0 install script 'node scripts/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pty.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pty.js
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pty.js
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\cygwin64\tmp\apm-install-dir-11885-6896-rw3qhr.k0dp00ms4i\npm-debug.log
npm ERR! code 1

I've seen that someone had a similar problem before but installing npm-install first did not solve the issue for me.

Thanks for any advice!

**Comment by taiftahmid** [comment]
someone please post a solution here. I am facing the same problem

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0 is using node-pty-prebuilt instead unmaintained and outdated pty.js
