### ISSUE TITLE
Arduino Mega 2560, no upload possible while Serialmonitor is open

### ISSUE THREAD

**Issue by sstaub** [platformio/platformio-atom-ide-terminal#6]
Using an Arduino Mega 2560, it is not possible to upload code while the Serialmonitor is open.
![mega timeout](https://cloud.githubusercontent.com/assets/6450325/13728407/6da64320-e917-11e5-82a3-fd3a58860507.png)

**Comment by dmytrokyrychuk** [comment]
This will be fixed very soon. Take a look at this issue: platformio/platformio-atom-ide/issues/45.
