### ISSUE TITLE
Fix Copy, Paste (Ctrl-C, Ctrl-V) on Windows

### ISSUE THREAD

**Issue by blogscot** [platformio/platformio-atom-ide-terminal#60]
Using _Ctrl-C_, _Ctrl-V_ on my Windows 10 box doesn't work as expected, however I note, it does work on Mac.

On Windows, pressing _Ctrl-C_ in the terminal does not update the clipboard, while Pressing _Ctrl-V_ displays '^V'. The word-around is use the menu options, but this becomes a drag after a while. It'd be great if this could be fixed.

Thanks, and keep up the great work!

**Comment by alereisan** [comment]
+1 same on Linux, please make Ctrl-Shift-C and Ctrl-Shift-V for copy pasting

**Comment by pelted** [comment]
I swear this was working on my Mac a while back but maybe that was terminal-plus which no longer works at all. But Cmd-C and Cmd-V are not working in macOS either.

**Comment by black-snow** [comment]
`Ctrl+C` is probably a bad idea for it'll send an interrupt but `Ctrl+Shift+C / V` sounds good. I'd say `alt` is better than shift (alt = alternative) but the keycombo seems harder to type.

**Comment by blcarson** [comment]
Same issue as @pelted - I swear it was working as early as a few weeks ago. Maybe an Atom update nuked it?

**Comment by blcarson** [comment]
Any progress on this?

**Comment by MatthiasPortzel** [comment]
@blcarson I know this sounds kind of stupid, but I had a an entire bug report written up before I thought to check this. Do you have keybindings enabled for the package? Turning keybindings on fixed the same problem for me. If that's not the problem, I would create a new issue, as this one's specifically referencing the fact that copy and paste aren't supported on Windows.

**Comment by BurakaKrishna** [comment]
i was experiencing the same problem when trying on windows 10.
@blcarson,@blogscot or anybody is it solved or has found any workaround for it ?

**Comment by AionDev** [comment]
I can't believe is so hard to find an easy fix for this issue. 

The most important feature for any terminal shell - after running the actual script - is to have keyboard shortcuts for copy and pasting. They are vital. 

I wouldn't use a terminal in the first place, i was not comfortable with the keyboard. Forcing me to use the mouse or menu drop-downs is against this hole terminal idea. It's a terminal shell or it's a UI ? ..
For copy and pasting `Ctrl+Swif+C`, `Ctr+V` works for me. 

Is there a technical limitation? What specific challenges we have in implementing this functionality? 
Thanks :)

**Comment by the-j0k3r** [comment]
This is fixed a while back and better with 2.9.0
