### ISSUE TITLE
New bug in atom 1.30

### ISSUE THREAD

**Issue by SeasonCCC** [platformio/platformio-atom-ide-terminal#600]
![_20180908203118](https://user-images.githubusercontent.com/9429680/45254159-2b779380-b3a6-11e8-8e43-9c298e6918aa.png)

windows 10、 atom version 1.30 and combine terminal with cmder

**Comment by the-j0k3r** [comment]
pls upgrade to 2.9.0 and if that doesnt fix it, disable cmder

@ivankravets pls close.
