### ISSUE TITLE
Showing blank screen after change from powershell to cmd

### ISSUE THREAD

**Issue by ghost** [platformio/platformio-atom-ide-terminal#601]
version 2.8.4 after changing the shell override from powershell to cmd its shows blank screen with cursor blinking.

Thanks
T Swaminathan

**Comment by codemonkee** [comment]
@swaminathant I ran into the same issue when switching from Windows PowerShell (default) to PowerShell Core. I didn't find any reports on that, but notice this one.

I also tried switching to cmd.exe with the same results. Blank screen with a blinking cursor.
Switched to just `"cmd.exe"` as it's in my path with the same results... then realized I was encapsulating the path to the executable with double quotes out of habit on Windows.

Removing the quotes I'm able to launch both `cmd.exe` and `pwsh.exe` without issue.

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0 is using node-pty-prebuilt instead unmaintained and outdated pty.js

Also ensure this isnt a path issue, this works fine without any issues. See https://github.com/platformio/platformio-atom-ide-terminal/issues/554#issuecomment-400678241 for how to setup this in a working manner.
