### ISSUE TITLE
Can't install any packages in atom 

### ISSUE THREAD

**Issue by adityagoyal222** [platformio/platformio-atom-ide-terminal#602]

**Comment by philippetheis** [comment]
Updating to “platformio-ide-terminal@2.8.4” failed.

> pty.js@0.3.0 install /private/var/folders/yt/748b99px6y5_8bxp2spxyc_h0000gn/T/apm-install-dir-118817-31024-rz0ter.vs5iuanhfr/node_modules/platformio-ide-terminal/node_modules/pty.js
> node scripts/install.js

/private/var/folders/yt/748b99px6y5_8bxp2spxyc_h0000gn/T/apm-install-dir-118817-31024-rz0ter.vs5iuanhfr
└── (empty)

/private/var/folders/yt/748b99px6y5_8bxp2spxyc_h0000gn/T/apm-install-dir-118817-31024-rz0ter.vs5iuanhfr
└── (empty)


npm WARN enoent ENOENT: no such file or directory, open '/private/var/folders/yt/748b99px6y5_8bxp2spxyc_h0000gn/T/apm-install-dir-118817-31024-rz0ter.vs5iuanhfr/package.json'
npm WARN apm-install-dir-118817-31024-rz0ter.vs5iuanhfr No description
npm WARN apm-install-dir-118817-31024-rz0ter.vs5iuanhfr No repository field.
npm WARN apm-install-dir-118817-31024-rz0ter.vs5iuanhfr No README data
npm WARN apm-install-dir-118817-31024-rz0ter.vs5iuanhfr No license field.
npm ERR! Darwin 17.7.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/philippetheis/.atom/.apm/.apmrc" "--userconfig" "/Users/philippetheis/.atom/.apmrc" "install" "/private/var/folders/yt/748b99px6y5_8bxp2spxyc_h0000gn/T/d-118817-31024-gguetq.h91vt5ipb9/package.tgz" "--runtime=electron" "--target=2.0.5" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! file sh
npm ERR! path sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn sh

npm ERR! pty.js@0.3.0 install: `node scripts/install.js`
npm ERR! spawn sh ENOENT
npm ERR! 
npm ERR! Failed at the pty.js@0.3.0 install script 'node scripts/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pty.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pty.js
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pty.js
npm ERR! There is likely additional logging output above.
npm WARN enoent ENOENT: no such file or directory, open '/private/var/folders/yt/748b99px6y5_8bxp2spxyc_h0000gn/T/apm-install-dir-118817-31024-rz0ter.vs5iuanhfr/package.json'
npm WARN apm-install-dir-118817-31024-rz0ter.vs5iuanhfr No description
npm WARN apm-install-dir-118817-31024-rz0ter.vs5iuanhfr No repository field.
npm WARN apm-install-dir-118817-31024-rz0ter.vs5iuanhfr No README data
npm WARN apm-install-dir-118817-31024-rz0ter.vs5iuanhfr No license field.
npm ERR! Darwin 17.7.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/philippetheis/.atom/.apm/.apmrc" "--userconfig" "/Users/philippetheis/.atom/.apmrc" "install" "/private/var/folders/yt/748b99px6y5_8bxp2spxyc_h0000gn/T/d-118817-31024-gguetq.h91vt5ipb9/package.tgz" "--runtime=electron" "--target=2.0.5" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! pty.js@0.3.0 install: `node scripts/install.js`
npm ERR! Exit status -2
npm ERR! 
npm ERR! Failed at the pty.js@0.3.0 install script 'node scripts/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pty.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pty.js
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pty.js
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/yt/748b99px6y5_8bxp2spxyc_h0000gn/T/apm-install-dir-118817-31024-rz0ter.vs5iuanhfr/npm-debug.log
npm ERR! code 1

**Comment by the-j0k3r** [comment]
try again with platformio-atom-ide-terminal 2.9.0 should be all fixed.
