### ISSUE TITLE
Can't get virtual environment to work

### ISSUE THREAD

**Issue by ggabunia** [platformio/platformio-atom-ide-terminal#603]
Hello. I'm using Latest version of Atom and Platformio on my new windows machine. On the previous machine everything worked fine - when I worked in python, I could easily create, activate, work in and deactivate virtual environments. But now it seems impossible: I still create them through platformio, but when I try to activate them (using "workon" command), nothing happens. Any suggestions?
Thanks in advance.

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0 is using node-pty-prebuilt instead unmaintained and outdated pty.js

if issues persist open a new ticket with required information.

Thx =)
