### ISSUE TITLE
Style terminal using Atom colors

### ISSUE THREAD

**Issue by Jomik** [platformio/platformio-atom-ide-terminal#605]
Is it possible to style the terminal using colors from Atom? I use gruvbox, which is not one of the supported themes.
I haven't looked into how the terminal is run, but I believe it should be possible to compile colors from Atom and send them to the terminal the same way you do with the themes at the moment.

**Comment by the-j0k3r** [comment]
HI @Jomik maybe you can expand/modify on https://github.com/platformio/platformio-atom-ide-terminal/pull/563#issuecomment-408830176 to do what youre tying to achieve, It should be possible to add whole themes based on that.
