### ISSUE TITLE
I am connecting to oracle database throught cmd and windows power shell but i can not on the atom terminal.

### ISSUE THREAD

**Issue by gtfMasterJohn** [platformio/platformio-atom-ide-terminal#606]
![untitled](https://user-images.githubusercontent.com/30161194/45919611-100c8e00-be66-11e8-8bd5-2d38e62b8de2.png)
![image](https://user-images.githubusercontent.com/30161194/45919587-a9877000-be65-11e8-909a-ff47e64dab93.png)
what is the difference if it is the same program. 

I restarted atom and reinstalled the terminal.

Thanks

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0 is using node-pty-prebuilt instead unmaintained and outdated pty.js

If issue persists open a new ticket with the required information.
