### ISSUE TITLE
Terminal Not Updating/Refreshing Text Correctly

### ISSUE THREAD

**Issue by travVT** [platformio/platformio-atom-ide-terminal#608]
First, I really like this package for Atom. The only issue I'm having is that the terminal doesn't update/refresh the command I typed in correctly. For instance, if I type 'some command goes here' into the terminal:

![image](https://user-images.githubusercontent.com/8258221/46209522-15e9ef80-c2fc-11e8-824c-9eb36ca55592.png)

And then try and delete the whole command that I just typed, using backspace, it doesn't fully delete it:

![image](https://user-images.githubusercontent.com/8258221/46209715-93adfb00-c2fc-11e8-9beb-8372db066dd8.png)

However, if I try and run another command it works perfectly, so there seems to be some type of update/refresh issue occurring. I'm hoping someone else has had the same issue and might be able to help?

Thanks!

**Comment by nikolaysalinder** [comment]
I have the same issue.

**Comment by the-j0k3r** [comment]
try again with platformio-atom-ide-terminal 2.9.0 should be all fixed.

**Comment by the-j0k3r** [comment]
Confirmed fixed with 2.9.0

**Comment by travVT** [comment]
This is working perfectly! Thank you. :)
