### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by itaiperi** [platformio/platformio-atom-ide-terminal#61]
Hey, I've got a little installation issue:

```
$ sudo apm install platformio-ide-terminal
Installing platformio-ide-terminal to /home/itai/.atom/packages ✗

> pty.js@0.3.0 install /tmp/apm-install-dir-116625-10224-1h2owyv/node_modules/platformio-ide-terminal/node_modules/pty.js
> node scripts/install.js



module.js:340
    throw err;
          ^
Error: Cannot find module '/tmp/apm-install-dir-116625-10224-1h2owyv/node_modules/platformio-ide-terminal/node_modules/pty.js/scripts/install.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3
npm ERR! Linux 4.4.0-21-generic
npm ERR! argv "/opt/atom/resources/app/apm/bin/node" "/opt/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/itai/.atom/.apm/.apmrc" "--userconfig" "/home/itai/.atom/.apmrc" "install" "/tmp/d-116625-10224-1k1b5vv/package.tgz" "--target=0.36.8" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! pty.js@0.3.0 install: `node scripts/install.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the pty.js@0.3.0 install script 'node scripts/install.js'.
npm ERR! This is most likely a problem with the pty.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls pty.js
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/apm-install-dir-116625-10224-1h2owyv/npm-debug.log
```

Tried also without the sudo, and then just got "undefined" as result.
Some info:
$ nodejs --version
v6.3.0
$ npm --version
3.10.3
$ atom --version
Atom    : 1.8.0
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1

**Comment by ivankravets** [comment]
Could you try this plugin (only for test)? https://github.com/platformio/platformio-atom-ide-terminal/issues/55

**Comment by itaiperi** [comment]
This is weird, I have no idea what I have done, but both are installing fine right now. Thanks anyways.

**Comment by ragmha** [comment]
### Not sure if it help anyone, I ran into this issue today:

Got it fixed (Not sure how 🙏 )  😄 , but these are the steps I did on my **MAC**:

- [ ] npm-cache clear
- [ ] brew update
- [ ] brew upgrade node
- [ ] npm install -g node-gyp (I was also missing the **node-gyp** too)
- [ ] apm install platformio-ide-terminal  🎉 

Works!  👊

**Comment by snaqviApps** [comment]
Hi 

I have very similar issue: 
Here is the system configuration (ubuntu 16.04):

$ **apm --version**
apm  1.18.1
**npm  3.10.10**
node 6.9.5 x64
python 2.7.12
git 2.7.4

:/opt/atom$ nodejs --version
v6.11.0

$ **npm --version
5.0.3**        <-----------------  Here is version number is different than what 'apm --version' command told above

**Error Output**:
--------------------- 
$ **sudo apm install platformio-ide-terminal**

Installing platformio-ide-terminal to /home/hamza/.atom/packages ✗

> pty.js@0.3.0 install /tmp/apm-install-dir-117524-14890-1s5tiqb.m9yh1l9pb9/node_modules/platformio-ide-terminal/node_modules/pty.js
> node scripts/install.js

/tmp/apm-install-dir-117524-14890-1s5tiqb.m9yh1l9pb9
└── (empty)


module.js:471
    throw err;
    ^

Error: Cannot find module '/tmp/apm-install-dir-117524-14890-1s5tiqb.m9yh1l9pb9/node_modules/platformio-ide-terminal/node_modules/pty.js/scripts/install.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
npm WARN enoent ENOENT: no such file or directory, open '/tmp/apm-install-dir-117524-14890-1s5tiqb.m9yh1l9pb9/package.json'
npm WARN apm-install-dir-117524-14890-1s5tiqb.m9yh1l9pb9 No description
npm WARN apm-install-dir-117524-14890-1s5tiqb.m9yh1l9pb9 No repository field.
npm WARN apm-install-dir-117524-14890-1s5tiqb.m9yh1l9pb9 No README data
npm WARN apm-install-dir-117524-14890-1s5tiqb.m9yh1l9pb9 No license field.
npm ERR! Linux 4.4.0-81-generic
npm ERR! argv "/opt/atom/resources/app/apm/bin/node" "/opt/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/hamza/.atom/.apm/.apmrc" "--userconfig" "/home/hamza/.atom/.apmrc" "install" "/tmp/d-117524-14890-1hvmzqo.fp9xh9qkt9/package.tgz" "--runtime=electron" "--target=1.3.15" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! pty.js@0.3.0 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pty.js@0.3.0 install script 'node scripts/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pty.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pty.js
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pty.js
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/apm-install-dir-117524-14890-1s5tiqb.m9yh1l9pb9/npm-debug.log
npm ERR! code 1

     ------------------

Thanks

**Comment by anuroopmjay** [comment]
anuroop@friday:~$ sudo apm install platformio-ide-terminal
Installing platformio-ide-terminal to /home/anuroop/.atom/packages ✗

> pty.js@0.3.0 install /tmp/apm-install-dir-117528-7646-199doeq.pz3nnx9a4i/node_modules/platformio-ide-terminal/node_modules/pty.js
> node scripts/install.js

/tmp/apm-install-dir-117528-7646-199doeq.pz3nnx9a4i
`-- (empty)


module.js:471
    throw err;
    ^

Error: Cannot find module '/tmp/apm-install-dir-117528-7646-199doeq.pz3nnx9a4i/node_modules/platformio-ide-terminal/node_modules/pty.js/scripts/install.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
npm WARN enoent ENOENT: no such file or directory, open '/tmp/apm-install-dir-117528-7646-199doeq.pz3nnx9a4i/package.json'
npm WARN apm-install-dir-117528-7646-199doeq.pz3nnx9a4i No description
npm WARN apm-install-dir-117528-7646-199doeq.pz3nnx9a4i No repository field.
npm WARN apm-install-dir-117528-7646-199doeq.pz3nnx9a4i No README data
npm WARN apm-install-dir-117528-7646-199doeq.pz3nnx9a4i No license field.
npm ERR! Linux 4.4.0-81-generic
npm ERR! argv "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/anuroop/.atom/.apm/.apmrc" "--userconfig" "/home/anuroop/.atom/.apmrc" "install" "/tmp/d-117528-7646-177rujc.wed9pphkt9/package.tgz" "--runtime=electron" "--target=1.3.15" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! pty.js@0.3.0 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pty.js@0.3.0 install script 'node scripts/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pty.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pty.js
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pty.js
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/apm-install-dir-117528-7646-199doeq.pz3nnx9a4i/npm-debug.log
npm ERR! code 1

**Comment by azumia-azu** [comment]
sudo apm install platformio-ide-terminal
Installing platformio-ide-terminal to /home/hitrel/.atom/packages ✗

> pty.js@0.3.0 install /tmp/apm-install-dir-118631-15277-1802x5v.r9ht2tvs4i/node_modules/platformio-ide-terminal/node_modules/pty.js
> node scripts/install.js

/tmp/apm-install-dir-118631-15277-1802x5v.r9ht2tvs4i
└── (empty)


module.js:471
    throw err;
    ^

Error: Cannot find module '/tmp/apm-install-dir-118631-15277-1802x5v.r9ht2tvs4i/node_modules/platformio-ide-terminal/node_modules/pty.js/scripts/install.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
npm WARN enoent ENOENT: no such file or directory, open '/tmp/apm-install-dir-118631-15277-1802x5v.r9ht2tvs4i/package.json'
npm WARN apm-install-dir-118631-15277-1802x5v.r9ht2tvs4i No description
npm WARN apm-install-dir-118631-15277-1802x5v.r9ht2tvs4i No repository field.
npm WARN apm-install-dir-118631-15277-1802x5v.r9ht2tvs4i No README data
npm WARN apm-install-dir-118631-15277-1802x5v.r9ht2tvs4i No license field.
npm ERR! Linux 4.15.0-29-generic
npm ERR! argv "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/hitrel/.atom/.apm/.apmrc" "--userconfig" "/home/hitrel/.atom/.apmrc" "install" "/tmp/d-118631-15277-1lb3vey.7xfuu40a4i/package.tgz" "--runtime=electron" "--target=2.0.5" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! pty.js@0.3.0 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pty.js@0.3.0 install script 'node scripts/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pty.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pty.js
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pty.js
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/apm-install-dir-118631-15277-1802x5v.r9ht2tvs4i/npm-debug.log
npm ERR! code 1

**Comment by Nicekor** [comment]
+1

**Comment by fabriciosobral** [comment]
+1
