### ISSUE TITLE
Error when clicking new terminal (After I installed Platformio-ide-terminal 2.8.4)

### ISSUE THREAD

**Issue by Sid4879** [platformio/platformio-atom-ide-terminal#611]
Details below, let me know if you need more information. Thank you in advance.

**Info**
Windows 10 Home x64
Installed Atom 1.31.1 x64
Installed Platformio-ide-terminal 2.8.4

**Steps causing the error**
After installing the Platformio, I clicked on the '+' (New terminal), I got the below error after few seconds and the Terminal screen is blank
![screenshot 2018-10-05 22 49 35](https://user-images.githubusercontent.com/39803373/46561761-fbfa6f00-c8f0-11e8-8ea1-783aa53b9a3a.png)
 

**Error msg**
![screenshot 2018-10-05 22 27 50](https://user-images.githubusercontent.com/39803373/46561518-ee90b500-c8ef-11e8-8202-31e010de54ac.png)

**Comment by jhollowe** [comment]
Look at issue #246 and try the solutions in there.

**Comment by jhollowe** [comment]
Confirmed still an issue in Atom 1.32.0 with platformio-ide-terminal 2.8.4

**Comment by the-j0k3r** [comment]
This is a duplicate of #613 and friends @ivankravets pls close
