### ISSUE TITLE
assertion failed!, atom 1.31.2 x64

### ISSUE THREAD

**Issue by pedelon** [platformio/platformio-atom-ide-terminal#613]
![image](https://user-images.githubusercontent.com/35803490/46873868-16ab7700-ce0e-11e8-98fa-f54453b7ac19.png)

**Comment by fvarno** [comment]
Same error here.

**Comment by jhollowe** [comment]
Look at issue #246 and try the solutions in there. Please also look through other issues from the same issue.  Issue #611 has the same error message.

**Comment by ManuelZ** [comment]
None of the solutions on the referred issues solved this problem for me.

**Comment by the-j0k3r** [comment]
Please update to 2.9.0

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0 is using node-pty-prebuilt instead unmaintained and outdated pty.js

**Comment by ManuelZ** [comment]
- Atom 1.33.1 ia32
- platformio-ide 2.3.1
- platformio-ide-terminal 2.9.0

When I open a new terminal, it doesn't appear, it looks like if it's loading, but nothing happens.

What can I do to give you some useful information?


![image](https://user-images.githubusercontent.com/115771/52526553-18842a80-2c88-11e9-80ad-151eb9b4ed35.png)

**Comment by the-j0k3r** [comment]
Please follow https://flight-manual.atom.io/hacking-atom/sections/debugging/#reset-to-factory-defaults

Dont forget to backup Attom profile before resetting it.

Then reinstall platformio-ide-terminal 2.9.0 via apm in a terminal with atom 1.34.0 and no platformio-ide 2.3.1

If it fails reopen a ticket and provide the requested information.

**Comment by ManuelZ** [comment]
Ok thanks, I just opened a new ticket because it still doesn't work.

https://github.com/platformio/platformio-atom-ide-terminal/issues/650
