### ISSUE TITLE
Can't open a terminal window 

### ISSUE THREAD

**Issue by zedin27** [platformio/platformio-atom-ide-terminal#614]
When I tried to open the terminal on my atom, I don't see the option to do it. I have the latest platformio-ide-terminal download and atom 1.23.3 in my working computer

Any suggestions on how to fix this?

EDIT: nvm, fixed 😅. This can be closed now

**Comment by guilhermevescovi** [comment]
Hi, how you solved it?

**Comment by zedin27** [comment]
It was an issue on my side because I was running a script to remind myself to drink water. My script runs when I open a new terminal. However, I'm not sure how that affects to the platformio-ide-terminal.

**Comment by the-j0k3r** [comment]
please update to 2.9.0 @ivankravets this is now invalid
