### ISSUE TITLE
atom command not running in powershell

### ISSUE THREAD

**Issue by franknavarro** [platformio/platformio-atom-ide-terminal#617]
When I try to run the atom command to open a new atom window in platformio nothing happens.
![2018-10-19_10-00-17](https://user-images.githubusercontent.com/7967480/47233030-55997980-d386-11e8-8689-ca7d1818cb3b.gif)

However when running the atom command in a powershell window outside of atom a new atom window is opened.
![2018-10-19_10-01-48](https://user-images.githubusercontent.com/7967480/47233036-5a5e2d80-d386-11e8-9082-47f5d08e06e0.gif)

**Comment by the-j0k3r** [comment]
this is duplicate of #546 and #630 @ivankravets pls close.

Also @franknavarro pls update to 2.9.0
