### ISSUE TITLE
Keyboard shortcut to switch between terminal & code editor

### ISSUE THREAD

**Issue by YujiShen** [platformio/platformio-atom-ide-terminal#62]
[#97](https://github.com/jeremyramin/terminal-plus/issues/97) for terminal-plus, seems not be implemented yet. I think this would be a very helpful feature.

**Comment by astrohsy** [comment]
I agree. I hope this feature will be added soon.

**Comment by MariuszDabrowski** [comment]
+1

**Comment by bklier** [comment]
+1

**Comment by sadhu89** [comment]
:+1

**Comment by osembedded** [comment]
Here is a simple example to make up your custom keyboard bindings to toggle between the editor and the terminal. Put this in your keymap.cson file

The following helps show/hide the terminal using Ctrl Dot as the keybinding

```
'.platform-darwin atom-workspace':
  'ctrl-.':'platformio-ide-terminal:toggle'
```

The following helps navigate between tabs within the terminal.

```
'.platformio-ide-terminal':
  'ctrl-cmd-p': 'platformio-ide-terminal:prev'
  'ctrl-cmd-n': 'platformio-ide-terminal:next'
```

See the attached screenshot for other commands you can customize.

<img width="785" alt="screen shot 2016-09-25 at 8 59 05 am" src="https://cloud.githubusercontent.com/assets/2177535/18816055/5cee825a-82fe-11e6-8d4a-9a1ea4471df1.png">

**Comment by osembedded** [comment]
Just realized, the above only helps with opening and closing the terminal and doesn't help with switching focus. But the above ^^^ can be used as a work around until we have real focus switch support in the ide terminal.

**Comment by jlerche** [comment]
Hacky way to toggle between terminal and active editor pane (wrote this for terminal plus, should be easy to adapt)

in init.coffee

```
atom.commands.add 'atom-workspace',
   'editor:focus-main', ->
       p = atom.workspace.getActivePane()
       term = null
       #p.activate()
       panels = atom.workspace.getBottomPanels()
       for pan in panels
           if pan.item.constructor.name == 'TerminalPlusView'
               term = pan.item
               break
        if term and p.focused isnt false
            term.focus()
        else if term and p.focused is false
            p.activate()
```

**Comment by laubblatt** [comment]
I am new to Atom, what of the above code of jlerche I should change?
What would be the key binding in the keymap.cson? 
Any help appreciated!

**Comment by cachance7** [comment]
@jlerche That was a great starting point. Here's how I ultimately adapted mine:

```coffeescript
 atom.packages.onDidActivatePackage (pack) ->
  if pack.name == 'platformio-ide-terminal'
    atom.commands.add 'atom-workspace',
      'editor:focus-main', ->
        p = atom.workspace.getActivePane()
        panels = atom.workspace.getBottomPanels()
        term = panels.find (pan) ->
          pan.item.constructor.name == 'PlatformIOTerminalView' and pan.visible
        if not term
          # Open a new terminal
          editor = atom.workspace.getActiveTextEditor()
          atom.commands.dispatch(atom.views.getView(editor), 'platformio-ide-terminal:new')
        else if term and p.focused isnt false
          term.item.focus()
        else if term and p.focused is false
          term.item.blur()  # Stops the terminal from blinking
          p.activate()
```
(Edit: updated to be specific about how this is loading)

@laubblatt You can use anything you want. Here's what I added to the end of `platformio-ide-terminal.cson` in order to use `ctrl-;` for my setup. 
```
'atom-workspace':
  'ctrl-;': 'editor:focus-main'
```

**Comment by laubblatt** [comment]
Hi Casey! great it works now for me - also the edit for the keymap.cson was very helpful!

**Comment by YujiShen** [comment]
Thanks for the comments of @jlerche @cachance7 and @laubblatt, I would like to summarize a working solution without change the code inside plugin.

1. Add the following code into Atom's Init Script `init.coffee`, you can open it from menu or command palette.
  ```coffee
   atom.packages.onDidActivatePackage (pack) ->
    if pack.name == 'platformio-ide-terminal'
      atom.commands.add 'atom-workspace',
        'editor:focus-main', ->
          p = atom.workspace.getActivePane()
          panels = atom.workspace.getBottomPanels()
          term = panels.find (pan) ->
            pan.item.constructor.name == 'PlatformIOTerminalView' and pan.visible
          if not term
            # Open a new terminal
            editor = atom.workspace.getActiveTextEditor()
            atom.commands.dispatch(atom.views.getView(editor), 'platformio-ide-terminal:new')
          else if term and p.focused isnt false
            term.item.focus()
          else if term and p.focused is false
            term.item.blur()  # Stops the terminal from blinking
            p.activate()
  ```
2. Add your keyboard shortcut into Atom's Keymap `keymap.cson`, you can also open it from menu or command palette. An example here, you can change to whatever combination you like.
  ```
  'atom-workspace':
    'ctrl-;': 'editor:focus-main'
  ```
3. Reload Atom and enjoy! 🎉

P.S. Anyone who knows how to integrate these into the plugin could make a pull request to free others from hacking like this.

**Comment by ivankravets** [comment]
@YujiShen, @jlerche,  @cachance7 and @laubblatt , could you provide PR for this issue? Thanks!

**Comment by hbrezak** [comment]
Hi! I have a question about the @YujiShen compact solution. I can't seem to get it to work properly. First two 'if's work fine, creating new terminal window if there is none and switching from text editor to terminal but if terminal is currently active window it doesn't switch back to text editor.

Any thoughts? Using Ubuntu 14.04 and atom 1.13.1 x64

UPDATE: discovered that above code won't work for me when using 'ctrl-something' shortcuts (clash with terminal commands?). Changing to 'alt-y' shortcut works perfectly.

**Comment by andreikoenig** [comment]
Hello, can someone help me with this solution?
I copied @YujiShen 's code but I am getting `Failed to load {path}/init.coffee` `pack is not defined`.
I am using platformio-ide-terminal 2.2
and in the script the name of the pack is platformio-ide-terminal. I dont understand why I am getting this error. 

I am using Atom 1.13.1
Thank you!

edited: to correct typo to avoid confusion

**Comment by hbrezak** [comment]
@andreikoenig where did you paste the code? That is a weird error since actual file is called init.coffee. Try pasting the code meant for init.coffee through atom interface, by going to Edit -> Init Script... then save, restart atom, give it a go

**Comment by andreikoenig** [comment]
@hbrezak , thanks for your reply! So sorry, that was a typo in my message above. I *did* paste it into the `init.coffee` through Atom.

Screenshot of my init.coffee file http://i.imgur.com/BBEusdx.png
This is the error http://i.imgur.com/rtR5L5g.png

any ideas? thank you so much for taking your time!

**Comment by andreikoenig** [comment]
Ugh, sorry had to delete my comment.
@hbrezak , thank you for taking your time to answer! It was a typo in my message above. I did paste it into the `init.coffee`.

here is my init.coffee screenshot http://i.imgur.com/TEPnkAZ.png
and here is the error I am getting when I reload Atom. http://i.imgur.com/P2KIy4h.png

Thank you!

**Comment by andreikoenig** [comment]
@hbrezak , I am using this plugin https://github.com/platformio/platformio-atom-ide-terminal

**Comment by hbrezak** [comment]
I believe line 16 of your init.coffee file was meant to be a comment but you forgot to put # before the word 'switch'

**Comment by andreikoenig** [comment]
@hbrezak , yes! I caught it after I posted the reply! (embarrassing). I updated my comment, please see updated screenshots above. That was not an issue. I made a mistake commenting that block back in to make a screenshot. :(

**Comment by hbrezak** [comment]
Okay,  something also went wrong with indentation during copy/paste, your line 18 is not properly indented and probably all the lines after it. Your problem should be resolved once you fix that

**Comment by andreikoenig** [comment]
@hbrezak , oh man, thank you so much! That was it. Double embarrassing. I have been coding in Ruby for about a year, and it is so weird when indentation matters, I never thought to check that! Thanks again!

**Comment by andreikoenig** [comment]
@hbrezak , is there anyway to reach out to you? I have one more question regarding this plugin (not related to this issue), and I dont want to clutter this thread.

**Comment by colin-kiegel** [comment]
Hm, the [PR #183](https://github.com/platformio/platformio-atom-ide-terminal/commit/5662b6a2136700226521e11d2ac6665e48646491) implemented a focus command
`'platformio-ide-terminal:focus': => @activeTerminal.focusTerminal()`

But that's missing the [_unfocus_ part](https://github.com/platformio/platformio-atom-ide-terminal/issues/62#issuecomment-263085500) which is equally important to toggle back to the last editor pane.

Could this issue be re-opened for the time being?

**Comment by pietrodn** [comment]
@colin-kiegel implemented un-focus in PR #218

**Comment by seiichi1101** [comment]
+1

**Comment by christianbueno1** [comment]
One alternative after close platformio-terminal is use the command ALT+\ (get focus of Tree View), then ALT+\ again (or Left Arrow key with one pane).
System: fedora 29 Workstation (Gnome desktop) , Linux.

**Comment by baogorek** [comment]
Hey I just got the switching to work. Had to use Alt in the key-sequence to for refocusing on main from the terminal:
```
  'ctrl-t': 'platformio-ide-terminal:focus'
  'ctrl-alt t': 'editor:focus-main'
```

**Comment by baogorek** [comment]
Nice workaround, @christianbueno1. Could have sworn I had this working with 
```
  'ctrl-t': 'platformio-ide-terminal:focus'
  'ctrl-alt t': 'editor:focus-main'
```
but when I went to check one more time before sending, it didn't work. Maybe I'm going crazy.

**Comment by the-j0k3r** [comment]
You cant remap existing keymaps

https://github.com/platformio/platformio-atom-ide-terminal/blob/f61084493ed48db11d2e54d39e01c1b88e693654/keymaps/platformio-ide-terminal.cson#L17

also see https://github.com/platformio/platformio-atom-ide-terminal/issues/807

**Comment by baogorek** [comment]
Thanks @the-j0k3r. I just noticed that ctrl-alt-f does indeed focus on the terminal and back to the editor as you repeatedly press it. My Ctrl+t keymap will also get me down to the terminal, just not back to the editor! I suppose I can live with ctrl-alt-f.
