### ISSUE TITLE
Terminal Not working

### ISSUE THREAD

**Issue by AdiPathak** [platformio/platformio-atom-ide-terminal#620]
Hey im trying to compile and run some code(in java) using Atom and i'm on a windows 10 64 bit machine. Every time I try and use the terminal this error pops up Assertion failed! Program: na'\node_modules\pty.js\bin\win32\x64_m57\pty.node. File..\src\win\pty.cc 
Line:203

Expression: pc !=nullptr 
For information on how your program can cause an assertion failure. see the visual C++ documentaiton on asserts. Then it prompts me if I would like to abort, retry, ignore.

Im on Version 1.32.0

**Comment by jhollowe** [comment]
Look at issue #246 and try the solutions in there. Please also look through other issues from the same issue.  Issue #613 has the same error message.

**Comment by the-j0k3r** [comment]
should be fixed now with 2.9.0

This issue now invalid with new node-pty-prebuilt in 2.9.0 @ivankravets pls close.
