### ISSUE TITLE
platformio-ide-terminal installation failed

### ISSUE THREAD

**Issue by ghost** [platformio/platformio-atom-ide-terminal#621]
Installing “platformio-ide-terminal@2.8.4” failed.Hide output…

> pty.js@0.3.0 install C:\Users\Guest_\AppData\Local\Temp\apm-install-dir-118926-6848-k8364b.7zw\node_modules\platformio-ide-terminal\node_modules\pty.js
> node scripts/install.js

npm WARN lifecycle npm is using C:\Users\Guest_\AppData\Local\atom\app-1.32.0\resources\app\apm\bin\node.exe but there is no node binary in the current PATH. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.
'node' is not recognized as an internal or external command,
operable program or batch file.
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\Guest_\AppData\Local\Temp\apm-install-dir-118926-6848-k8364b.7zw\package.json'
npm WARN apm-install-dir-118926-6848-k8364b.7zw No description
npm WARN apm-install-dir-118926-6848-k8364b.7zw No repository field.
npm WARN apm-install-dir-118926-6848-k8364b.7zw No README data
npm WARN apm-install-dir-118926-6848-k8364b.7zw No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pty.js@0.3.0 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pty.js@0.3.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Guest_\.atom\.apm\_logs\2018-10-26T18_11_13_166Z-debug.log

**Comment by the-j0k3r** [comment]
This is now invalid with new node-pty-prebuilt in 2.9.0 @ivankravets pls close.
