### ISSUE TITLE
Fails at start after installation into Atom ver 1.32

### ISSUE THREAD

**Issue by IgorTopalov** [platformio/platformio-atom-ide-terminal#622]
Environment:  Win 10 pro

Editor Atom 1.32

Once clicked in "+" sign displays pop-up window title as "MS Visual C++ Runtime library"
Error text
Assertion Failed
Program: ..node_modules\pty.js\bin\win32\x64_m57\pty.node
File:  .. src\win\pty.cc

Line: 203

Expression pc != nullptr

..

**Comment by jhollowe** [comment]
Look at issue #246 and try the solutions in there. Please also look through other issues from the same issue. Issue #620 has the exact same error message as you posted.

**Comment by the-j0k3r** [comment]
This is now invalid with new node-pty-prebuilt in 2.9.0 @ivankravets  pls close.
