### ISSUE TITLE
Assertion failed 

### ISSUE THREAD

**Issue by icmathad** [platformio/platformio-atom-ide-terminal#623]
I installed the platform io terminal and I changed the **"Shell override option ->"C:\Windows\System32\cmd.exe"** while opening the terminal I have faced the below issue  please help me 

<img width="960" alt="capture" src="https://user-images.githubusercontent.com/40857087/48042617-5dd81e00-e1a8-11e8-8625-d066b13b7dea.PNG">

**Comment by the-j0k3r** [comment]
Fixed with 2.9.0 @ivankravets please close.

And FYI this issue persists look a resetting atom.
