### ISSUE TITLE
Windows PowerShell / PowerShell Core breaks to prompt when typing too fast with -AsSecureString

### ISSUE THREAD

**Issue by codemonkee** [platformio/platformio-atom-ide-terminal#625]
When running

`Read-Host -AsSecureString` and typing input at a fast pace, or pasting in text. One or two asterisk will display, followed by the breaking back to prompt with the remainder of the text type out at the prompt.

This occurs when using Windows PowerShell through the platformio-atom-ide-terminal or directly in PowerShell launched separately.

I found this report which describes the issue https://github.com/PowerShell/PowerShell/issues/3511.

Installing PowerShell Core 6.1.x it appears to resolve the issue when launching pwsh.exe outside of Atom; however, the issue still remains after adjusting the Atom plug-in setting to launch PowerShell Core `C:\Program Files\PowerShell\6\pwsh.exe` instead of the default Windows PowerShell.

Would there be any arguments/attributes that could be set that would contribute to this behavior within platformio? (Everything else is default values)

**Comment by codemonkee** [comment]
Seems to be fixed by the legacy console issues described here https://docs.microsoft.com/en-us/previous-versions/orphan-topics/ws.11/mt427362(v=ws.11)#controlling-the-new-features

Setting **HKEY_CURRENT_USER/Console/ForceV2** to `0` (default 1)

    Windows Registry Editor Version 5.00

    [HKEY_CURRENT_USER\Console]
    "ForceV2"=dword:00000000

https://github.com/jeremyramin/terminal-plus/issues/15#issuecomment-144618245
https://github.com/platformio/platformio-atom-ide-terminal/pull/575

**Comment by the-j0k3r** [comment]
@ivankravets please pin this issue (pinning is on the right sidebar at bottom.)

@codemonkee please retest with 2.9.0.

**Comment by codemonkee** [comment]
I don't believe I retested this after 2.9.0 and have been running in legacy mode since. Recently I upgraded Windows 10 from 1703 to 1909 and ran into #780 resolved after disabling legacy console mode again. (Windows 10 1909, Atom 1.41.0, Platformio: 2.10.0)

After disabling legacy mode; I haven't replicated the original issue in this issue.
