### ISSUE TITLE
Error Install on Ubuntu 18.04

### ISSUE THREAD

**Issue by Cperbony** [platformio/platformio-atom-ide-terminal#629]
i've got this error trying install platformio-atom-ide-terminal on Atom in Ubuntu 18.04
Node and NPM already installed

apm install platformio-ide-terminal
Installing platformio-ide-terminal to /home/perboni/.atom/packages ✗

> pty.js@0.3.0 install /tmp/apm-install-dir-118111-24589-1777dca.8nk6/node_modules/platformio-ide-terminal/node_modules/pty.js
> node scripts/install.js

module.js:538
    throw err;
    ^

Error: Cannot find module '/tmp/apm-install-dir-118111-24589-1777dca.8nk6/node_modules/platformio-ide-terminal/node_modules/pty.js/scripts/install.js'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
npm WARN enoent ENOENT: no such file or directory, open '/tmp/apm-install-dir-118111-24589-1777dca.8nk6/package.json'
npm WARN apm-install-dir-118111-24589-1777dca.8nk6 No description
npm WARN apm-install-dir-118111-24589-1777dca.8nk6 No repository field.
npm WARN apm-install-dir-118111-24589-1777dca.8nk6 No README data
npm WARN apm-install-dir-118111-24589-1777dca.8nk6 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pty.js@0.3.0 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pty.js@0.3.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/perboni/.atom/.apm/_logs/2018-12-01T23_52_36_507Z-debug.log

Thks!

**Comment by Nicekor** [comment]
I have the same issue, can someone please help? Thanks

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0 which since [f64888d](https://github.com/platformio/platformio-atom-ide-terminal/commit/f64888d6d134f7e06bbb13a762dfd45335e8a4ba) is using node-pty-prebuilt instead unmaintained and outdated pty.js. This is good news for stability and compatibility.

if issues persist, please open a new ticket with requested information.

Thx =)

**Comment by jtyska** [comment]
Hey! 

I'm having the same issue, any good news about this? I'm using atom 1.37 and the apm install command for platformio-ide-terminal on ubuntu 18.04

**Comment by the-j0k3r** [comment]
Nothing we can do, we cant control apm or  atom, open a bug with apm.
