### ISSUE TITLE
Failed to load the platformio-ide-terminal package

### ISSUE THREAD

**Issue by kristsm** [platformio/platformio-atom-ide-terminal#63]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Microsoft Windows 10 Pro
**Thrown From**: [platformio-ide-terminal](https://github.com/platformio/platformio-atom-ide-terminal) package, v2.1.1
### Stack Trace

Failed to load the platformio-ide-terminal package

```
At 'themes/standard.less' wasn't found in C:\Users\krists\.atom\packages\platformio-ide-terminal\styles\themes.less:2:2

LessError: 'themes/standard.less' wasn't found
  at C:\Users\krists\.atom\packages\platformio-ide-terminal\styles\themes.less:2:2
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "autoHideMenuBar": true
  }
}
```
### Installed Packages

``` coffee
# User
autocomplete-clang, v0.9.4
build, v0.65.0
busy, v0.6.0
language-ini, v1.16.0
linter, v1.11.14
linter-gcc, v0.6.15
platformio-ide, v1.3.6
platformio-ide-terminal, v2.1.1
tool-bar, v1.0.0

# Dev
No dev packages
```

**Comment by ivankravets** [comment]
Could you try to remove " C:\Users\krists.atom\packages\platformio-ide-terminal" and restart Atom? It should be installed from the Atom registry

**Comment by nikhilweee** [comment]
I'm having the same issue. Reinstalling doesn't help. Neither does removing the package directory.
I had to manually copy files from the `themes` folder in this repo to the local installation.

**Comment by the-j0k3r** [comment]
this is now invalid with 2.9.0 out. @ivankravets pls close.
