### ISSUE TITLE
path behaves different from system-terminal (for anaconda)

### ISSUE THREAD

**Issue by birnstiel** [platformio/platformio-atom-ide-terminal#630]
The new anaconda installation does not just add itself in front of the path, instead it adds the following to the `.bash_profile` or `.profile` file:

```

# added by Anaconda3 5.3.1 installer
# >>> conda init >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$(CONDA_REPORT_ERRORS=false '/Users/username/anaconda3/bin/conda' shell.bash hook 2> /dev/null)"
if [ $? -eq 0 ]; then
    \eval "$__conda_setup"
else
    if [ -f "/Users/username/anaconda3/etc/profile.d/conda.sh" ]; then
        . "/Users/username/anaconda3/etc/profile.d/conda.sh"
        CONDA_CHANGEPS1=false conda activate base
    else
        \export PATH="/Users/username/anaconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda init <<<
```

If I run `which python` in the system terminal (I'm on macOS), I  get:

    /Users/username/anaconda3/bin/python

and for `which conda`, I get:

    /Users/birnstiel/anaconda3/bin/conda

However doing the same on the platformio terminal, it behaves differently. Then I get

    /usr/bin/python

and

    /Users/username/anaconda3/bin/conda

For some reason, the code that the anaconda installer added to my `.profile` (see above) does not prepend the `anaconda3/bin` directory to the `PATH`.

**Comment by Ruben9922** [comment]
I have the same issue.

**Comment by the-j0k3r** [comment]
This seems like same issue #546 just you discovered a different symptom.

**Comment by the-j0k3r** [comment]
I can confirm 2.9.0 fixes this issue + #546 

@ivankravets can close until newer information provided. thx

**Comment by gideonsimpson** [comment]
I'm having this problem on MacOS with version 2.9.4

**Comment by the-j0k3r** [comment]
@gideonsimpson please see https://github.com/platformio/platformio-atom-ide-terminal/issues/703 which has a solution posted in https://github.com/platformio/platformio-atom-ide-terminal/issues/703#issuecomment-504878005
