### ISSUE TITLE
Platformio-Ide-terminal Cursor jumps several lines on open

### ISSUE THREAD

**Issue by ghost** [platformio/platformio-atom-ide-terminal#631]
Cursor jumps 20 lines on opening a terminal and goes to the middle of the terminal/console. The cursor is red. The top lines and I quote 
"Windows Powershell
Copyright (C) Microsoft Corporation. All rights reserved." are separated from the cursor by 20 lines. This happens even with shell override settings option set to C:Windows\System32\cmd.exe. I have to press enter to get a "valid" line like "PS C:\Users\MyName>  Blinking_Red_Cursor"
I reset Powershell.exe and Cmd.exe configurations and preferences but to no effect.

It does not jump if I set shell override to ubuntu.exe (You know, the Linux environment for Windows). That "seems" to be working fine.
![platformio atom error](https://user-images.githubusercontent.com/33810534/50045594-1fcef380-009e-11e9-9492-371635922ec3.PNG)

I have Windows 10 with the October Update running. Atom x64 latest as of Dec-15-2018 (1.33 through installer).

![platformio atom error](https://user-images.githubusercontent.com/33810534/50045594-1fcef380-009e-11e9-9492-371635922ec3.PNG)

Any ideas why it is broken? It used to work just fine but I can't get previous versions of either Atom and/or PlatformioIdeTerminal combinations to work either.

Is Platformio-IDE-Terminal deprecated and no longer developed as I read somewhere in this thread space and in that case is there an alternative?

**Comment by the-j0k3r** [comment]
Please update to 2.9.0 its running like butter on a hot summer day. @ivankravets pls close 2.9.0 invalidates all previous reports of the sort
