### ISSUE TITLE
Terminal Blank, Not loading

### ISSUE THREAD

**Issue by 22Tango** [platformio/platformio-atom-ide-terminal#642]
![image](https://user-images.githubusercontent.com/43447807/52015719-9b4efd80-24b0-11e9-9c30-e4446bb069cc.png)
The terminal does not load. I recently upgraded to python 3 from 2. I have completely uninstalled platformio-ide-terminal and reinstalled. I've deleted the configs for it and tried again. I have current versions of atom and platformio-ide-terminal. I've also tried installing the pre-2.9.0 version of the terminal using "apm install..." and letting it auto upgrade. No success. 
[Windows 10 x64] 
Is this problem just occurring on my comp or are others dealing with this/have fixed this?

**Comment by 22Tango** [comment]
atom --version

Atom    : 1.34.0
Electron: 2.0.16
Chrome  : 61.0.3163.100
Node    : 8.9.3

apm --version

apm  2.1.3
npm  6.2.0
node 8.9.3 x64
atom 1.34.0
python 3.7.2
git 2.20.1.windows.1
visual studio

**Comment by the-j0k3r** [comment]
Hi and thx for report, try resetting atom to defaults and then reinstalling the terminal 2.9.0

**Comment by 22Tango** [comment]
Same problem with a fresh install of atom (deleted all atom files before reinstalling.) I also tried running atom as admin just in case it was a permissions problem. Same problem: a blank, grey popup.

**Comment by the-j0k3r** [comment]
Either downgrade platformio-ide-terminal to 2.8.4 if that worked for you or switch to vscode.

**Comment by rotcerid10** [comment]
how to downgrade it to previous version and also whatever the code I type in grey popup it returns the path address

**Comment by 22Tango** [comment]
Hey rotcerid10, to downgrade, uninstall it from atom, then type "apm install platformio-ide-terminal@<version>" into cmd with <version> replaced with whatever version you want. 
My problem was resolved today. I tried everything, nothing worked. Left Atom for vscode. Randomly opened Atom today with no new updates and the terminal worked. So. I don't know why it wouldn't load before, but it's fixed now :\

**Comment by the-j0k3r** [comment]
Glad its solved for you. @ivankravets pls close as its solved.

**Comment by TrySpace** [comment]
In my case when I tried uninstalling via the GUI, it didn't work, and on a terminal:

```
 apm uninstall platformio-atom-ide-terminal
Uninstalling platformio-atom-ide-terminal failed
Failed to delete platformio-atom-ide-terminal: No package.json found at 
C:\Users\xxx\.atom\packages\platformio-atom-ide-terminal\package.json
```

I manually removed the package folder, and reinstalled, then it worked again.

**Comment by the-j0k3r** [comment]
The actual issue is here https://github.com/platformio/platformio-atom-ide-terminal/issues/668
