### ISSUE TITLE
Fedora 29 Flatpak: Cannot access /usr/local.. user nfsnobody

### ISSUE THREAD

**Issue by LightAutumnMelancholy** [platformio/platformio-atom-ide-terminal#664]
- [ ] I have reset Atom to defaults prior to submitting report.
- [x] I have not reset Atom to defaults prior to submitting report.
- [x] I have reinstalled platformio-ide-terminal prior to submitting report.
### Description
Cannot find /usr/local.. after fresh install, from sh or bash.

### Steps to reproduce

0.) Fedora 29 Linux pc-local 4.20.10-200.fc29.x86_64 #1 x86_64 GNU/Linux:

[me@pc-local bin]$ flatpak list
Description                Application     Version Branch Arch   Origin  Installation
Atom - A hackable text ed… io.atom.Atom    1.34.0  stable x86_64 flathub system
Intel                      …rm.VAAPI.Intel         18.08  x86_64 flathub system
html5-codecs               …m.html5-codecs         18.08  x86_64 flathub system
Freedesktop.org Software … …reedesktop.Sdk         18.08  x86_64 flathub system
[jonathanwindham@jwindham-pc-local bin]$ 

1.) Freshly install ATOM from flatpak (using flathub.io) 
2.) Freshly install platform-io-ide-terminal
3.) Start terminal, and attempt 

**Expected behavior:**
To be able to access /usr/local

**Actual behavior:** 
Not found: bash-4.4$ cd /usr/local
bash: cd: /usr/local: No such file or directory
bash-4.4$

**Reproduces how often:**
100%

### Versions

```
> atom --version

bash-4.4$ atom --version
Atom    : 1.34.0
Electron: 2.0.16
Chrome  : 61.0.3163.100
Node    : 8.9.3
bash-4.4$

```
```
> apm --version
bash-4.4$ apm --version
apm  2.1.3
npm  6.2.0
node 8.9.3 x64
atom 1.34.0
python 2.7.15
git 2.20.1
bash-4.4$
```
OS name and version:
Platformio-ide-terminal version: 2.9.1

### Additional Information

![image](https://user-images.githubusercontent.com/24681993/53579393-77cab180-3b47-11e9-9e2a-ce5220375bc7.png)

**Comment by LightAutumnMelancholy** [comment]
Ooh, check this as shiz out:

platformio-ide-terminal:
![image](https://user-images.githubusercontent.com/24681993/53579111-fbd06980-3b46-11e9-8267-5dc9152bcfb0.png)



Gnome Terminal: 
![image](https://user-images.githubusercontent.com/24681993/53579269-418d3200-3b47-11e9-99c8-298df90a30cb.png)



This smells like packaging in flatpak for atom. Nfsnobody is usually seen during NFS

**Comment by LightAutumnMelancholy** [comment]
Dove through the atom.io flatpak setup; but I've never worked on it prior.
```
/var/lib/flatpak/app/io.atom.Atom/x86_64/stable/active
[user@pc-local active]$ ls -l
total 16
-rw-r--r-- 1 root root  315 Feb 25 12:31 deploy
drwxr-xr-x 4 root root 4096 Feb 25 12:31 export
drwxr-xr-x 5 root root 4096 Feb 25 12:31 files
-rw-r--r-- 2 root root  876 Dec 31  1969 metadata
```

In that file, Metadata:

![image](https://user-images.githubusercontent.com/24681993/53582941-89638780-3b4e-11e9-8525-8442b212106c.png)

So my searching lead me to this document:

http://docs.flatpak.org/en/latest/sandbox-permissions-reference.html#filesystem-permissions.

So I now believe that the manifest used for packaging atom, declares filesystem incompletely. 

If I am correct, then I believe that the pacakage maintainer for atom has not considered the use/requirement for RO, as according to the document. 

I don't know what you want to do with this info (if I'm correct, I'm not a packer of flat) maybe you can talk to the maintainers, etc.

```
I'm going to attempt a work around, of not using flatpak
```

**Comment by LightAutumnMelancholy** [comment]
I'm ready to call this a workaround. It's truly out of scope for your project. I'm leaving this here for posterity.

The version installed from atom.io

```
[user@pc-local AWS-VPC-Information]$ atom --version
Atom    : 1.34.0
Electron: 2.0.16
Chrome  : 61.0.3163.100
Node    : 8.9.3
[user@pc-local AWS-VPC-Information]$ apm --version
apm  2.1.3
npm  6.2.0
node 8.9.3 x64
atom 1.34.0
python 2.7.15
git 2.20.1
[user@pc-local AWS-VPC-Information]$

```

Installed via https://atom.io   rpm package

```
sudo dnf install ~/Downloads/atom.x86_64.rpm
```

You may wish to talk with the flatpak maintainer, otherwise your terminal emulator is a failure, and this also certainly affects many other packages.

**Comment by LightAutumnMelancholy** [comment]
Closing issue: This is out of scope for this project; it's an issue for the flatpak package maintainer team to sort out.

WORKAROUND: Remove flatpak version, and install and use via https://atom.io rpm package

**Comment by the-j0k3r** [comment]
Thanks.

**Comment by LightAutumnMelancholy** [comment]
@the-j0k3r  I got a reply back from the flatpak maintainer. 

https://github.com/flathub/io.atom.Atom/issues/39

Long story short: They cant/wont fix it; so platformio-ide-terminal can never work properly with the flatpak version of Atom.

**Comment by the-j0k3r** [comment]
So flatpak limitation, glad you came to that conclusion though and came back to us with valuable updates regarding issue. So again Thank you.

**Comment by ls-1N** [comment]
I don't nearly understand the issue here, but I landed here when searching solutions to my own unrelated problem of accessing `/usr/local` from inside a flatpak. Sorry if my solution isn't relevant to this specific problem, but I hope at least other unrelated people landing here will find help from this.

My pilgrimage ended with the understanding that Flatpak mounts `/etc` and `/usr` under `/var/run/host/`. So to access the `/usr/local` path of the host system from inside flatpakked software, you need to use the path `/var/run/host/usr/local`.

As described [here](https://stackoverflow.com/a/59666752/4335271) and in the last bullet point of [this](https://docs.flatpak.org/en/latest/sandbox-permissions.html#filesystem-access) section.

**Comment by grandmastergainz** [comment]
Hi

**Comment by jeremyduanewallace** [comment]
Welcome Guide
