### ISSUE TITLE
failed to install: 1 vulnerability requires manual review.

### ISSUE THREAD

**Issue by wanancat** [platformio/platformio-atom-ide-terminal#666]
- [x] I have reset Atom to defaults prior to submitting report.
- [ ] I have not reset Atom to defaults prior to submitting report.
### Description

I tried to install it by using npm install, but it seems failed. The Feedback is below.

I tried to install jquery it mentioned, same vulnerability.

I open Atom, and it shows an "Incompatible Packages". 

I try to rebuild packages but Rebuild Failed.

I would be really grateful if someone would like to help🙏
### Steps to reproduce

>cd ~/.atom/packages/
>git clone https://github.com/platformio/platformio-atom-ide-terminal.git
>cd platformio-atom-ide-terminal/
>npm install

```
> node-pty-prebuilt@0.7.6 install /Users/wanancat/.atom/packages/platformio-atom-ide-terminal/node_modules/node-pty-prebuilt
> prebuild-install || node scripts/install.js


> node-pty-prebuilt@0.7.6 postinstall /Users/wanancat/.atom/packages/platformio-atom-ide-terminal/node_modules/node-pty-prebuilt
> node scripts/post-install.js

npm notice created a lockfile as package-lock.json. You should commit this file.
added 85 packages from 49 contributors and audited 202 packages in 7.582s
found 1 high severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details
```
>npm audit fix
```
up to date in 0.644s
fixed 0 of 1 vulnerability in 202 scanned packages
  1 vulnerability required manual review and could not be updated
```
>npm audit
```
                       === npm audit security report ===                        
                                                                                
┌──────────────────────────────────────────────────────────────────────────────┐
│                                Manual Review                                 │
│            Some vulnerabilities require your attention to resolve            │
│                                                                              │
│         Visit https://go.npm.me/audit-guide for additional guidance          │
└──────────────────────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Cross-Site Scripting (XSS)                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ jquery                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=3.0.0                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ atom-space-pen-views                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ atom-space-pen-views > space-pen > jquery                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/328                       │
└───────────────┴──────────────────────────────────────────────────────────────┘
found 1 high severity vulnerability in 202 scanned packages
  1 vulnerability requires manual review. See the full report for details.
```
inside the Atom:
```
Some installed packages could not be loaded because they contain native modules that were compiled for an earlier version of Atom.
```
```
gyp info it worked if it ends with ok
gyp info using node-gyp@3.4.0
gyp info using node@8.9.3 | darwin | x64
gyp http GET https://atom.io/download/electron/v2.0.16/iojs-v2.0.16.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! install error 
gyp ERR! stack Error: connect ETIMEDOUT 52.203.66.95:443
gyp ERR! stack     at Object._errnoException (util.js:1024:11)
gyp ERR! stack     at _exceptionWithHostPort (util.js:1046:20)
gyp ERR! stack     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
gyp ERR! System Darwin 18.2.0
gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/node-gyp/bin/node-gyp.js" "install" "--runtime=electron" "--target=2.0.16" "--dist-url=https://atom.io/download/electron" "--arch=x64" "--ensure"
gyp ERR! cwd /Users/wanancat/.atom
gyp ERR! node -v v8.9.3
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
```

### Versions

```
> atom --version
Atom    : 1.34.0
Electron: 2.0.16
Chrome  : 61.0.3163.100
Node    : 8.9.3
```
```
> apm --version
apm  2.1.3
npm  6.2.0
node 8.9.3 x64
atom 1.34.0
python 2.7.10
git 2.18.0
```
OS name and version: macOS Mojave 10.14.1
Platformio-ide-terminal version: 2.9.1

**Comment by the-j0k3r** [comment]
Hello and thank you for your report.

Please follow (again) https://flight-manual.atom.io/hacking-atom/sections/debugging/#reset-to-factory-defaults

Then reinstall platformio-ide-terminal 2.9.1 via apm in aexternal terminal, if that fails,, reset atom and try installing via UI.. (make sure all atom/platformio folders are 100% gone..

That failing again is suspect and interesting that its macOS mojave issue (we have a few issues coming from macOS mojave), that said, we have no control over this or other project dependencies or `apm` which depends on ancient node-gyp 3.4.0 and gives users a few problems.

The real issue is the installer, try to look for issue with installer in macOS mojave
If you look at your error it fails in gyp with command `
gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/node-gyp/bin/node-gyp.js" "install" "--runtime=electron" "--target=2.0.16" "--dist-url=https://atom.io/download/electron" "--arch=x64" "--ensure"` That is Atom/apm related at very least.

In conclusion, this issue is really external to project, if anything try opening issues on the [apm repo](https://github.com/atom/apm/issues/new) or [node-gyp](https://github.com/nodejs/node-gyp/issues/new). looking at pre-existing issues that maybe related.

Another thing worth trying is virtualizating another OS and giving it a whirl again, I know its a long way around and unpractical but whatever works, right?

Or switch to vscode.

**Comment by wanancat** [comment]
@the-j0k3r Apm is not working well behind the wall of China, this also make installing via UI completely unusable, and that's another difficult and real problem.

 I check the [npm docs](https://docs.npmjs.com/auditing-package-dependencies-for-security-vulnerabilities#security-vulnerabilities-found-requiring-manual-review) and follow the step, and I may have found the possible problem?

[space-pen](https://github.com/atom-archive/space-pen) & [Atom-SpacePen-Views](https://github.com/atom/atom-space-pen-views) were deprecated and no longer maintained, and they are dependency of jQuery 2.14 with vulnerability ( jQuery remediate it in version 3.0.0).

Is there a way to fix them without using apm?

**Comment by the-j0k3r** [comment]
The issues you are seeing have nothing to do with either space-pen or Atom-space-pen-views and I would dare say nothing to do with jquery vulnerabilities.

If youre behind a firewall in china, try setting up atom to use a vpn or proxy, 

Failing that, you would need to manually grab all dependencies which is an insane task, I would even say next to impossible to grab (manually 1 by 1 ) all dependencies for Atom alone, never mind side projects, but if you did and they were in correct directories you would still need to use apm to install.

Best bet is the vpn route, look at apm/atom repos for anyone with similar issues and see if they have a solution, or open a ticket to ask the question there.

Here though thers nothing we can do about such issues.

**Comment by wanancat** [comment]
It may not related to this package, but I leaves my final solution for anyone who might click in this issue with the same trouble. Try to reinstall nodejs & npm, try using npm mirror & proxy, install this package in the UI again, and click rebuild package button in the UI. 

Anyway, it's really a great package that I need, thx for your help.:D

**Comment by the-j0k3r** [comment]
Added workaround label, glad you solved it in the end. =)
