### ISSUE TITLE
The "platformio-ide-terminal:insert-selected-text" is not working.

### ISSUE THREAD

**Issue by PedroAMBH** [platformio/platformio-atom-ide-terminal#67]
I installed the package but one of the features that must meter for mi is "insert-selected-text"  is not working.

I use "ctrl-enter" but it is not passing the code to the shell. 

I test it on windows 10 and 7.

**Comment by essicolo** [comment]
By default in atom,  `ctrl+enter` inserts a new line. To make `ctrl-enter` behave as expected, you could add this to keymap.cson

```
'atom-workspace atom-text-editor:not([mini])':
  'ctrl-enter': 'platformio-ide-terminal:insert-selected-text
```

**Comment by althritis** [comment]
If these are necessary changes, this should be documented. It can't be considered a 'feature' if it doesn't do this by default.

**Comment by sc268** [comment]
For mac users' reference:  

    'atom-workspace atom-text-editor:not([mini])':
    'cmd-enter': 'platformio-ide-terminal:insert-selected-text'

**Comment by dougwyu** [comment]
`ctrl-enter `to _insert-selected-text_ worked by default when i installed _platformio-ide-terminal_ on my mac. 

However, after I later installed the _linter-shellcheck_ package, `ctrl-enter` stopped working. So i followed these instructions and added the line to _keymap.cson_, and the `ctrl-enter` function was restored.  (I prefer `ctrl-enter` over `cmd-enter`, in my case).

by the way, when copying the above line, remove the newline between `([mini])':` and ` 'cmd-enter':`

Thank you!

**Comment by dougwyu** [comment]
i have now also successfully used this (to re-bind ctrl-enter) in the keymap.cson in Atom installed on Ubuntu 16 inside VirtualBox on macOS (whew!):

`'atom-workspace atom-text-editor:not([mini])': 'ctrl-enter': 'platformio-ide-terminal:insert-selected-text'`

**Comment by atongsa** [comment]
Ubuntu 18.04 LTS Atom solve the bug thanks all the guys above *-*

# change paltform ide key binding
'atom-workspace atom-text-editor:not([mini])':
  'ctrl-enter': 'platformio-ide-terminal:insert-selected-text'

**Comment by the-j0k3r** [comment]
thx for feedback @atongsa 

Related fix in this project https://github.com/platformio/platformio-atom-ide-terminal/commit/de2cc2efd88e5d14dbbb25bf9cdcd161c36f86a2 and cleanup https://github.com/platformio/platformio-atom-ide-terminal/commit/23343e8b06e3b56224c518d8c584f9af80f1e2d6
