### ISSUE TITLE
Is the keystroke for platformio-ide-terminal:new changed?

### ISSUE THREAD

**Issue by benpptung** [platformio/platformio-atom-ide-terminal#672]
I'm not sure if my memory is correct. I'm used to type `shift-cmd-t` to open the terminal, but apparently it is `alt-cmd-t` to open the terminal in the settings.

So, I"m asking if the keystroke was changed or not? Sorry, this is my fingers' memory, I really don't know why my fingers always type `shift-cmd-t`

Second question, if the above question is `no`, please ignore the following question.

I've changed the keystroke setting to `shift-cmd-t`, so I won't mess up while I need to open the terminal or close it. However, if this keystroke was changed, why? should I change it to `shift-cmd-t`?

Thank you :)

**Comment by the-j0k3r** [comment]
Thank you for reaching out.

A short answer is yes, the keymap in macOS apparently conflicted, and a PR was submitted by @navalkishore30 to address this. See commit https://github.com/platformio/platformio-atom-ide-terminal/commit/cb12f3127edb8364add8e53fe041aac5d28670fa

I think were open to improving on this as long as there's no conflicts with Atom. I will be testing out this in a couple of days.

**Comment by benpptung** [comment]
thank you  👍
