### ISSUE TITLE
Black screen with no reaction cursor, terminal not work.

### ISSUE THREAD

**Issue by VitaliyAT** [platformio/platformio-atom-ide-terminal#68]
# Temporary solution

See https://github.com/platformio/platformio-atom-ide-terminal/issues/68#issuecomment-260311524

--------

![screenshot 302](https://cloud.githubusercontent.com/assets/1639608/17654476/ecbbbc34-62bc-11e6-8ea0-33f0a1c526af.jpg)
Just single symbol of cursor and I can't type anything.

**Comment by piaoyidage** [comment]
me too.

**Comment by ivankravets** [comment]
What is your OS?

**Comment by piaoyidage** [comment]
OS: win7 64
when I tried terminal-plus, also the same problem.

**Comment by thacoon** [comment]
I also have the same issue, also same [issue with terminal-plus](https://github.com/jeremyramin/terminal-plus/issues/201)
I am running Arch Linux (64-bit, linux 4.7-1) and I am running Atom 1.9.8.
I have tried to rebuild the package: `apm rebuild platform-atom-Ide-terminal` and I also tried to reinstall node modules:

```
cd ~/.atom/packages/platformio-ide-terminal
rm -r node_modules/
npm install
```

These two were pointed out in a [terminal-plus issue](https://github.com/jeremyramin/terminal-plus/issues/201) both things worked for a few people.

One error I get is:

```
Cannot find module '../bin/linux/x64.m49.node' Error: Cannot find module '../bin/linux/x64.m49.node'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/raptor/.atom/packages/platformio-ide-terminal/node_modules/pty.js/lib/pty.js:18:9)
    at Module._compile (module.js:541:32)
    at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:208:21)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/raptor/.atom/packages/platformio-ide-terminal/node_modules/pty.js/index.js:2:18)
    at Module._compile (module.js:541:32)
    at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:208:21)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/raptor/.atom/packages/platformio-ide-terminal/lib/process.coffee:1:7)
    at Object.<anonymous> (/home/raptor/.atom/packages/platformio-ide-terminal/lib/process.coffee:1:1)
    at Module._compile (module.js:541:32)
    at Object.value [as .coffee] (/usr/lib/atom/src/compile-cache.js:208:21)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/atom/src/task-bootstrap.js:110:13)(anonymous function) @ task.js:52
task.js:52 Cannot read property 'bind' of null TypeError: Cannot read property 'bind' of null
    at process.<anonymous> (/usr/lib/atom/src/task-bootstrap.js:82:23)
    at emitTwo (events.js:106:13)
    at process.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:719:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)(anonymous function) @ task.js:52
```

**Comment by cars10** [comment]
Same for me on archlinux. I also tried this package because terminal-plus was not working, but no luck here either.

**Comment by ivankravets** [comment]
Please take a look at Know Issues here http://docs.platformio.org/en/latest/ide/atom.html#arch-linux-platformio-ide-terminal-issue

**Comment by cars10** [comment]
This has nothing to do with the terminal plugin, and it does not solve the issue.

**Comment by ivankravets** [comment]
Have you repeated all steps from the article above? Also, do you use Atom from Arch Linux package registry?

**Comment by cars10** [comment]
I tried to install the platformio package and reproduced the steps in the article - still no luck. Also the error messages have nothing to do with platformio, and https://github.com/jeremyramin/terminal-plus faces the same errors right now. ( #316, #321, #319, #317, ...)

**Comment by ivankravets** [comment]
See https://community.platformio.org/t/ide-upload-only-works-once-window-counter-doesnt-stop/621/10

**Comment by jashuang1130** [comment]
I'm having the same issue also. 
I'm currently using Atom ver. 1.9.9 and terminal-plus 0.14.5. I've installed npm-gyp and going into command prompt to change to "Use legacy console" and still encountering the same issue.

**Comment by ivankravets** [comment]
@jashuang1130 what is your OS?

**Comment by sidpagariya** [comment]
+1

**Comment by sidpagariya** [comment]
Having problems on macOS Sierra 10.12

**Comment by eazar001** [comment]
Yea, I can confirm that 2.2.0 does this as well. Just a black screen with a blinking cursor.

**Comment by m13253** [comment]
Solved on ArchLinux with version 2.2.0.
My Atom was 1.9.9, official binary.

**Comment by wluisi** [comment]
Upgrading to version 2.2.0 fixed this issue for me.

I'm running Mac OS El Capitan 10.11.6 and Atom 1.9.9

**Comment by sidpagariya** [comment]
Fixed for me too. macOS Sierra 10.12 Atom Dev

**Comment by cars10** [comment]
Arch with Atom 1.9.9 and platformio-atom-ide-terminal Version 2.2.0, still the same issue. Any hints?

**Comment by ivankravets** [comment]
@cars10 please check https://primalcortex.wordpress.com/2016/08/18/platformio/

**Comment by jashuang1130** [comment]
@ivankravets I'm currently using Windows 10

**Comment by ivankravets** [comment]
@jashuang1130 do you have special symbols in user name(system account)?

**Comment by jashuang1130** [comment]
@ivankravets  no i don't have any special symbols in user name

**Comment by eazar001** [comment]
That is strange. I'm on Arch Linux, and this package only works when i install `atom-editor-bin` from the AUR. Otherwise, if I use the official version, the cursor blink problem will persist.

**Comment by m13253** [comment]
> That is strange. I'm on Arch Linux, and this package only works when i install `atom-editor-bin` from the AUR. Otherwise, if I use the official version, the cursor blink problem will persist.

It is said that `[community]/atom` has many bugs. Unless you need to tweak the code, prefer `[aur]/atom-editor-bin`.

**Comment by NicholasDM** [comment]
I am using Arch Linux. As a few others have posted, the aur version solved my issue for this.

**Comment by ivankravets** [comment]
Should be fixed in the latest 2.2.1 version

**Comment by cars10** [comment]
Great! works for me now.

**Comment by eazar001** [comment]
This is strange, but I just noticed recently that the terminal no longer appears ... at all. I'm not sure when this occurred. Is there anyone on arch linux using `atom-editor-bin` that can confirm this?

**Comment by ppalladino** [comment]
I started to see the same issue above after I blew away my old manual install of node and brew installed nvm. I was able to resolve the problem by uninstalling and then reinstalling platformio-ide-terminal via atom package installer in Settings.

**Comment by ivankravets** [comment]
@eazar001 @ppalladino try to install `gcc` and totally uninstall PlatformIO IDE Terminal using Atom UI. Then, install it again from Atom UI package manager. Does it work now?

**Comment by ppalladino** [comment]
@ivankravets Yes, thanks.

**Comment by ivankravets** [comment]
Could you share somewhere archived `~/.atom/packages/platformio-ide-terminal/node_modules/pty.js/build/Release/pty.node` file? I'll add it to pre-compiled list. Thanks.

**Comment by ppalladino** [comment]
@ivankravets [pty.node.zip](https://github.com/platformio/platformio-atom-ide-terminal/files/589145/pty.node.zip)

**Comment by ivankravets** [comment]
@ppalladino what is a version of Atom?

**Comment by ppalladino** [comment]
@ivankravets 1.12.2

**Comment by eazar001** [comment]
@ivankravets @ppalladino Thanks, that worked perfectly for me.

**Comment by ivankravets** [comment]
Fixed in the latest release. If you still have problems, please

1. Install `gcc` 
2. Settings ⚙️ > Packages > Unisntall platofrmio-ide-terminal
3. Settings ⚙️ > Install > platformio-ide-terminal

**Comment by ChaplainsBud** [comment]
Atom opens my program on the top half of the screen, but I am not able to run it in the lower half using the terminal this package offers. I'm not aware of any reason why this is the case, especially since it worked once randomly. I have Windows 10 and am not sure why this is the case. 

Would you happen to know of another package I could run as an alternative? I think it may not be suited to Windows 10.

**Comment by nbeuchat** [comment]
I have the same issue as the original post. I only see the single symbol of cursor and I can't type anything.
I have:
- Atom 1.16.0 x64
- platform-ide-terminal 2.5.0
- Windows 10 Pro, 64-bits

Any suggestion?
