### ISSUE TITLE
Minimize the blank space

### ISSUE THREAD

**Issue by K-Sato1995** [platformio/platformio-atom-ide-terminal#681]
- [ ] I have reset Atom to defaults prior to submitting report.
- [x] I have not reset Atom to defaults prior to submitting report.

### Description
Would be cool if I could minimize the blank/setting part of the terminal.

I'm refering to this part in the image.

![image](https://user-images.githubusercontent.com/32632542/56268587-aec34980-612c-11e9-8fc6-ac59eafebdf3.png)

**Comment by the-j0k3r** [comment]
Hi @K-Sato1995 Thank you for reaching out with this query.

You may want to look at https://github.com/platformio/platformio-atom-ide-terminal/issues/580#issuecomment-408851262 which has inline answers that solve this query.

Thanks.

**Comment by K-Sato1995** [comment]
Awwwsome! Thank you @the-j0k3r !!!
