### ISSUE TITLE
Insert code to terminal problem with ^[

### ISSUE THREAD

**Issue by yiranweishen** [platformio/platformio-atom-ide-terminal#682]
- [ ] I have reset Atom to defaults prior to submitting report.
- [ ] I have not reset Atom to defaults prior to submitting report.
### Description

Have problems in text-editor and the Insert-text editor.

### Steps to reproduce

1.keymap bind
 'atom-text-editor':
   'ctrl-enter': 'platformio-ide-terminal:insert-selected-text'
2.write code  'a=5'
3.send it to the terminal

**Expected behavior:** 
a=5

**Actual behavior:** 
a=5
^[

**Reproduces how often:** 
1000% percent
![atomproblem](https://user-images.githubusercontent.com/49714033/56275798-fc8f8000-6133-11e9-91ac-ad50ac1d6845.png)

### Versions

```
> atom --version
2.1.3
```
```
> apm --version
1.36.0
```
OS name and version: Windows 10
Platformio-ide-terminal version: 2.9.1

### Additional Information

All I send with ‘^[" whatever I send.

**Comment by yiranweishen** [comment]
> * [ ]  I have reset Atom to defaults prior to submitting report.
> * [ ]  I have not reset Atom to defaults prior to submitting report.
> 
> ### Description
> ### Steps to reproduce
> 1.keymap bind
> 'atom-text-editor':
> 'ctrl-enter': 'platformio-ide-terminal:insert-selected-text'
> 2.write code 'a=5'
> 3.send it to the terminal
> 
> **Expected behavior:** 
> a=5
> 
> **Actual behavior:** 
> a=5
> ^[
> 
> **Reproduces how often:** 
> 1000% percent
> ![atomproblem](https://user-images.githubusercontent.com/49714033/56275798-fc8f8000-6133-11e9-91ac-ad50ac1d6845.png)
> 
> ### Versions
> ```
> > atom --version
> ```
> ```
> > apm --version
> ```
> OS name and version:Windows 10
> Platformio-ide-terminal version:2.9.1
> 
> ### Additional Information

**Comment by the-j0k3r** [comment]
Thank you for reaching out with this bug report.

You are getting this reply because the issue template was not filled in its entirety, overwritten,  or some portions were partially left out.

This issue template contains important information to be able to provide any kind of support, and will help us triage or reproduce the issue. Without reproduction no workaround or fix can normally be derived...

Copy and paste the template located at https://raw.githubusercontent.com/platformio/platformio-atom-ide-terminal/master/.github/ISSUE_TEMPLATE.md and fill in all fields. Logs / Errors / other information should be added at the bottom in the Notes portion of the [issue template](https://raw.githubusercontent.com/platformio/platformio-atom-ide-terminal/master/.github/ISSUE_TEMPLATE.md).

Tickets without this information may be closed and labeled invalid at our discretion.

Thank you for your understanding.

**Comment by yiranweishen** [comment]
> * [ ]  I have reset Atom to defaults prior to submitting report.
> * [ ]  I have not reset Atom to defaults prior to submitting report.
> 
> ### Description
> ### Steps to reproduce
> 1.keymap bind
> 'atom-text-editor':
> 'ctrl-enter': 'platformio-ide-terminal:insert-selected-text'
> 2.write code 'a=5'
> 3.send it to the terminal
> 
> **Expected behavior:** 
> a=5
> 
> **Actual behavior:** 
> a=5
> ^[
> 
> **Reproduces how often:** 
> 1000% percent
> ![atomproblem](https://user-images.githubusercontent.com/49714033/56275798-fc8f8000-6133-11e9-91ac-ad50ac1d6845.png)
> 
> ### Versions
> ```
> > atom --version
> ```
> ```
> > apm --version
> ```
> OS name and version:
> Platformio-ide-terminal version:
> 
> ### Additional Information

**Comment by the-j0k3r** [comment]
Youre clearly having trouble here, re-posting the same info is not OK., please edit your post like so

![generic](https://user-images.githubusercontent.com/31389848/56277882-75c3ae80-6105-11e9-8b48-e9f43eacff7e.gif)

Then complete all sections and full steps including screenshots and what files youre editing etc.

Thank you for your understanding.

**Comment by the-j0k3r** [comment]
Also works fine here.

![generic](https://user-images.githubusercontent.com/31389848/56278173-14500f80-6106-11e9-8d09-6e2a9a4a01f1.gif)

**Comment by yiranweishen** [comment]
Nope! it has the same problems here!




------------------ 原始邮件 ------------------
发件人: "the-j0k3r"<notifications@github.com>; 
发送时间: 2019年4月17日(星期三) 下午5:44
收件人: "platformio/platformio-atom-ide-terminal"<platformio-atom-ide-terminal@noreply.github.com>; 
抄送: "春繁先生"<478698139@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [platformio/platformio-atom-ide-terminal] Insert code to terminalproblem with ^[ (#682)




Also works fine here.

**Comment by the-j0k3r** [comment]
Hello again, Ive no idea what exactly you are doing, thereis not enough information provided in order for me to try to duplicate the issue exactly, **Ive tried, it works here**, and without knowing specifics which you omitted doesn't help me to help you.

Fell free to edit your main post and add more information, and at that time, Ill have another look. But at this time, there's nothing further I can contribute.

Thank you for your understanding.

**Comment by yiranweishen** [comment]
> Hello again, Ive no idea what exactly you are doing, thereis not enough information provided in order for me to try to duplicate the issue exactly, **Ive tried, it works here**, and without knowing specifics which you omitted doesn't help me to help you.
> 
> Fell free to edit your main post and add more information, and at that time, Ill have another look. But at this time, there's nothing further I can contribute.
> 
> Thank you for your understanding.

![problems](https://user-images.githubusercontent.com/49714033/56280958-fa322380-613d-11e9-818f-1f10f50ec99c.gif)
My problem just act like this.

**Comment by yiranweishen** [comment]
> Hello again, Ive no idea what exactly you are doing, thereis not enough information provided in order for me to try to duplicate the issue exactly, **Ive tried, it works here**, and without knowing specifics which you omitted doesn't help me to help you.
> 
> Fell free to edit your main post and add more information, and at that time, Ill have another look. But at this time, there's nothing further I can contribute.
> 
> Thank you for your understanding.

**Comment by yiranweishen** [comment]
> Hello again, Ive no idea what exactly you are doing, thereis not enough information provided in order for me to try to duplicate the issue exactly, **Ive tried, it works here**, and without knowing specifics which you omitted doesn't help me to help you.
> 
> Fell free to edit your main post and add more information, and at that time, Ill have another look. But at this time, there's nothing further I can contribute.
> 
> Thank you for your understanding.

my shelloveride is "E:\Software\Anaconda3\Scripts\ipython.exe"

**Comment by yiranweishen** [comment]
> > Hello again, Ive no idea what exactly you are doing, thereis not enough information provided in order for me to try to duplicate the issue exactly, **Ive tried, it works here**, and without knowing specifics which you omitted doesn't help me to help you.
> > Fell free to edit your main post and add more information, and at that time, Ill have another look. But at this time, there's nothing further I can contribute.
> > Thank you for your understanding.
> 
> ![problems](https://user-images.githubusercontent.com/49714033/56280958-fa322380-613d-11e9-818f-1f10f50ec99c.gif)
> My problem just act like this.

**Comment by yiranweishen** [comment]
> Also works fine here.
> 
> ![generic](https://user-images.githubusercontent.com/31389848/56278173-14500f80-6106-11e9-8d09-6e2a9a4a01f1.gif)

when I

**Comment by yiranweishen** [comment]
> Hello again, Ive no idea what exactly you are doing, thereis not enough information provided in order for me to try to duplicate the issue exactly, **Ive tried, it works here**, and without knowing specifics which you omitted doesn't help me to help you.
> 
> Fell free to edit your main post and add more information, and at that time, Ill have another look. But at this time, there's nothing further I can contribute.
> 
> Thank you for your understanding.

When I select code and want to run it by “ctrl-enter”, it doesn't run and shows the code with "^[" at the end. I just add 
'atom-text-editor':
'ctrl-enter': 'platformio-ide-terminal:insert-selected-text'
in the key map.

**Comment by yiranweishen** [comment]
> Hello again, Ive no idea what exactly you are doing, thereis not enough information provided in order for me to try to duplicate the issue exactly, **Ive tried, it works here**, and without knowing specifics which you omitted doesn't help me to help you.
> 
> Fell free to edit your main post and add more information, and at that time, Ill have another look. But at this time, there's nothing further I can contribute.
> 
> Thank you for your understanding.

I find is my shell problem.
When I use Ipython3.exe, it has the problem like this.
But When I use python.exe, it works fine. I use ipython-7.4.0

**Comment by the-j0k3r** [comment]
Thats the sort of information you could have provided, we dont read minds, but given that you found the issue, then its OK to move on to better things.

So now we know the issue is external,the only thing I can suggest is use what works.

Further reading, #543, #426 

Have a good day.

**Comment by the-j0k3r** [comment]
Also, if you Have Windows 1809, That breaks many terminals, best thing is to stick at best with Windows 10 - 1803 for the foreseeable future until MS fixes the issue causing the problems.
