### ISSUE TITLE
gsl libraries not being found

### ISSUE THREAD

**Issue by bojohnson5** [platformio/platformio-atom-ide-terminal#687]
- [x ] I have reset Atom to defaults prior to submitting report.
- [ ] I have not reset Atom to defaults prior to submitting report.
### Description

In a regular bash terminal I'm able to run a Python script with Anaconda Python which uses the GSL libraries and Swig. When run in platformio I'm not able to compile the code because it can't find the GSL libraries. I changed the shell used to /bin/bash and still didn't get any change

### Steps to reproduce

1. Open platformio terminal
2. Run Python script which pulls in C++ code using Swig
3. Get fatal error that GSL library can't be found

**Expected behavior:** 
The Python script runs like in a regular terminal

**Actual behavior:** 
Fatal error in platformio terminal that GSL library can't be found

**Reproduces how often:**  100%

### Versions

```
> atom --version
Atom    : 1.36.1
Electron: 2.0.18
Chrome  : 61.0.3163.100
Node    : 8.9.3
```
```
> apm --version
apm  2.1.3
npm  6.2.0
node 8.9.3 x64
atom 1.36.1
python 3.7.1
git 2.21.0
```
OS name and version: Fedora 29
Platformio-ide-terminal version: 2.9.1

### Additional Information

![Screenshot from 2019-04-30 17-16-53](https://user-images.githubusercontent.com/20647190/56999304-da522500-6b6b-11e9-8b2d-1365992c83a7.png)

**Comment by the-j0k3r** [comment]
Hi @bojohnson02 , thank you for reaching out with this report.

I take it you have exported paths, could you do that into your `~/.bash_profile` instead/also and see if it works?

Failing that, there's little else that can be done.

**Comment by bojohnson5** [comment]
@the-j0k3r I've seen several different ways to do this, but not sure the best way to do this in context of this problem. How would I export the path ot `~/.bash_profile`?

Actually I was able to export the path to `~/.bash_profile` but still no luck. I tried some other commands in the platformio terminal, and I can't even run commands like `sudo` or `dnf`. Is this normal?

**Comment by bojohnson5** [comment]
Ok, I think I found out the issue @the-j0k3r. I had installed Atom as a Flatpak which was causing the issues. I have removed the Flatpak version and installed the `.rpm` version, and everything is working now.

**Comment by the-j0k3r** [comment]
Yes, flatpak installs are mostly broken as documented in https://github.com/platformio/platformio-atom-ide-terminal#caveats, I think I need to update the issue templates to request info for method/type of atom install, so it be quicker to triage issues.

Im glad you reached that conclusion in the end and that its working now. =)

Thanks.
