### ISSUE TITLE
Terminal is not working

### ISSUE THREAD

**Issue by sangee14** [platformio/platformio-atom-ide-terminal#690]
- [x ] I have reset Atom to defaults prior to submitting report.
- [ ] I have not reset Atom to defaults prior to submitting report.
### Description

Terminal is not working. Only blank terminal appears and tried Install and re-install more than 10 times. But nothing works. Installed required terminal packages and tried on each and every Install and re-install process.

### Steps to reproduce

1. Terminal is not working
2. As it is not working, I am unable to work with Atom Editor, instead using some other IDE.

**Expected behavior:** 
To work efficiently with Atom Editor with proper terminal, python, Django packages.

**Actual behavior:** 
Disappointed with Atom Editor as the terminal is not working.

**Reproduces how often:** 
100%

### Versions

```
> atom --version
Version 1.37.0 x64
Electron: 2.0.18
Chrome:61.0.3163.100
Node:v8.9.3

> apm --version


OS name and version: 
Platformio-ide-terminal version: 2.9.1


### Additional Information
<!-- Add any additional information like screenshots, gif captures,
configuration, data or other Atom package lists, that might be necessary to reproduce the issue. -->

**Comment by the-j0k3r** [comment]
Please see this issue https://github.com/platformio/platformio-atom-ide-terminal/issues/668

There are several causes and workarounds for the problems you describe.

Also you dont actually porvide any actionable information like OS version or type. I can guarantee you however that #668 holds the answers you seek.
