### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by nchungdev** [platformio/platformio-atom-ide-terminal#691]
- [ ] I have reset Atom to defaults prior to submitting report.
- [ ] I have not reset Atom to defaults prior to submitting report.
### Steps to reproduce

1.
2.
3.

**Expected behavior:** 

**Actual behavior:** 

**Reproduces how often:** 

### Versions

```
> atom --version

```
```
> apm --version

```
OS name and version:
Platformio-ide-terminal version:

**Comment by the-j0k3r** [comment]
@nchungdev, thank you for rewaching out with this issue report.

Thers a couple of points I would like to raise with your report.

1) You did not fill in the issue template, so thers really no information that is actionable. You make it impossible for anyone looking into helping you Impossible.

2) Installation issues with Atom/Atom packages (such as this project) are apm https://github.com/atom/apm domain, so if you have any installation issues, [please report them to apm](https://github.com/atom/apm/issues/new)

Im closing this issue as invalid for those two reasons, but mainly for the second reason, we cannot control installation processes by 3rd party projects. I hope you understand, but if not, I'll try to clear any questions you may have.

Regards.
