### ISSUE TITLE
Python - cannot print multiple objects

### ISSUE THREAD

**Issue by hanreader** [platformio/platformio-atom-ide-terminal#705]
- [x] I have reset Atom to defaults prior to submitting report.
- [] I have not reset Atom to defaults prior to submitting report.
### Description

I am trying to print multiple objects in Python, but when I do, it comes out weird when I use the platform-ide-terminal.

### Steps to reproduce

1. Install platform-ide-terminal
2. Create a python file
3. Put in this code:
![Screen Shot 2019-07-20 at 1 05 01 PM](https://user-images.githubusercontent.com/13181961/61581650-10f66680-aaef-11e9-8bab-e2c7ffcc1536.png)

4. Run the code

**Expected behavior:** 
So it should print:
```
1. apple
2. banana
```
Note: It should just print the integers, strings, and variables.

**Actual behavior:** 
But instead, it prints:
![Screen Shot 2019-07-20 at 1 05 10 PM](https://user-images.githubusercontent.com/13181961/61581651-10f66680-aaef-11e9-8b98-65702d13da71.png)
Note: It actually prints the parenthesis, commas, and quotation marks.

**Reproduces how often:** 
I have tried the same code in different editors and it works (meaning that there is no parenthesis, comma, and quotation marks printed). 
But when I use the platform-ide-terminal, the output for ` print(1, " .", a)` I get (1, " .", a).

### Versions

```
> atom --version 1.38.2

```
```
> apm --version 2.1.7

```
OS name and version: macOS Version 10.12.6
Platformio-ide-terminal version: 2.9.1

**Comment by the-j0k3r** [comment]
Hey @hanreader thansk for reaching out to us with this issue report.

Please fill in THE FULL issue template. Your post indicates what you want to achieve, in order to try to help you, I need way more information that you chose not to provide.

>But when I use Atom, it doesn't work.

This is platformio-ide-terminal project for Atom, not Atom.

Soon as you provide all information required, Ill have another look at this.

Thanks

**Comment by hanreader** [comment]
Hi @the-j0k3r thank you for the quick response. 

I have added more information and filled out the full issue template.

**Comment by the-j0k3r** [comment]
Thanks for the extra information.

Try to export your paths to `~/.bash_profile` and see if it helps.

**Comment by hanreader** [comment]
Thank you, I realized that my error was because I was printing a tuple.
