### ISSUE TITLE
autoRunCommand with export PATH=... is added on every relaunch

### ISSUE THREAD

**Issue by urbaniak** [platformio/platformio-atom-ide-terminal#71]
I've got the platformio installed globally (using homebrew), so there's no need to update the path.

Tried removing the autoRunCommand from config, but it keeps returning on each atom relaunch.

**Comment by ivankravets** [comment]
Please move this issue here https://github.com/platformio/platformio-atom-ide/issues

PlatformIO IDE sets this option externally. Temporary solution is to set here some hook... `echo 1`.
