### ISSUE TITLE
Issue with double tabs (text not cleared)

### ISSUE THREAD

**Issue by betimer** [platformio/platformio-atom-ide-terminal#72]
When I press 'cd re' and 'tab' 'tab'
It seems the previous text has not been cleared. 

![2016-08-22 11_16_28-app js c__repo_learn-js atom](https://cloud.githubusercontent.com/assets/8111748/17990419/e56706f4-6b78-11e6-8310-ca0c81cb8ad6.png)

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0.
These type issues all so far seem fixed with this release due to using node-pty-prebuilt instead unmaintained and outdated pty.js
