### ISSUE TITLE
Updated atom and getting a build error

### ISSUE THREAD

**Issue by masonhorder** [platformio/platformio-atom-ide-terminal#720]
### Description

Today I updated atom 1.39.0 and when I opened atom again it said the following packages aren't configureable: PlatformIO IDE Terminal. So I go to packages and redownloaded PlatformIO IDE Terminal but came out with this error:

node-pty-prebuilt@0.7.6 install /private/var/folders/fp/9y6jpk6d42g0g5vt05rwzc8m0000gp/T/apm-install-dir-119624-3007-1r4p756.kwucg/node_modules/platformio-ide-terminal/node_modules/node-pty-prebuilt
prebuild-install || node scripts/install.js

prebuild-install WARN install No prebuilt binaries found (target=3.1.10 runtime=electron arch=x64 libc= platform=darwin)
No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Darwin 19.0.0
gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--build_v8_with_gn=false"
gyp ERR! cwd /private/var/folders/fp/9y6jpk6d42g0g5vt05rwzc8m0000gp/T/apm-install-dir-119624-3007-1r4p756.kwucg/node_modules/platformio-ide-terminal/node_modules/node-pty-prebuilt
gyp ERR! node -v v8.9.3
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/private/var/folders/fp/9y6jpk6d42g0g5vt05rwzc8m0000gp/T/apm-install-dir-119624-3007-1r4p756.kwucg/package.json'
npm WARN apm-install-dir-119624-3007-1r4p756.kwucg No description
npm WARN apm-install-dir-119624-3007-1r4p756.kwucg No repository field.
npm WARN apm-install-dir-119624-3007-1r4p756.kwucg No README data
npm WARN apm-install-dir-119624-3007-1r4p756.kwucg No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-pty-prebuilt@0.7.6 install: `prebuild-install || node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-pty-prebuilt@0.7.6 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/**********/.atom/.apm/_logs/2019-07-24T20_50_10_619Z-debug.log

**Expected behavior:** 
platformio-atom-ide-terminal to run normally
**Actual behavior:** 
Build error

### Versions

```
> atom --version
1.39.0
```

```
> apm --version
2.2.4
```
OS name and version: Mac OS catilina
Platformio-ide-terminal version:2.9.1

**Comment by contang0** [comment]
Same here..

**Comment by attisbarros** [comment]
Yeah, just started for me actually.

[Here's](https://gist.github.com/iBrazilian2/c6802b434c0aa5811c424fb923b920ce) my log when I tried to rebuild.

**Comment by masonhorder** [comment]
what os are you running

**Comment by masonhorder** [comment]
i was running mac os catilina

**Comment by linjialiang** [comment]
me too !
After the atom upgrade to 1.39.0, I couldn't use it either

**Comment by linjialiang** [comment]
![图片](https://user-images.githubusercontent.com/8848263/61836950-36032480-aeb5-11e9-89e0-17bb639417ff.png)

**Comment by lFaustus** [comment]
same here, after updating atom, package not working anymore

**Comment by msundeen** [comment]
I also updated atom today and this package had a error but I fixed my issue. 

How I fixed it:
Installed nodejs for windows and put C:\Program Files\nodejs\ in the enviroment path - https://nodejs.org/en/download/

then installed windows-build-tools - https://github.com/felixrieseberg/windows-build-tools

finally rebuild package and everything was fixed

**Comment by masonhorder** [comment]
is there a way to fix it on mac

**Comment by linjialiang** [comment]
https://github.com/atom/atom/issues/19695#issue-472065419

**Comment by linjialiang** [comment]
#721 
#722 
#723 
#724

**Comment by the-j0k3r** [comment]
Thanks for bring this issue to our attention.

This is a duplicate of #700 see https://github.com/platformio/platformio-atom-ide-terminal/issues/707#issuecomment-514634895 for a possible workaround
