### ISSUE TITLE
Problem in Installing Package platformio-ide-terminal@2.9.1

### ISSUE THREAD

**Issue by UAhmadSoft** [platformio/platformio-atom-ide-terminal#728]
1.I am unable to install this package "platformio-ide-terminal@2.9.1"

I wanted to install it from setting but it didn't installed....I have tried several times but not succeeded .

Error comes everytime when I try to install 

OS name and version: Windows 10 Enterprise 64-bit (10.0 Build 17763)
Platformio-ide-terminal version: 2.9.1

![atom](https://user-images.githubusercontent.com/53309523/61888623-4f3fbb80-af1d-11e9-982b-81fd3d2896db.png)

**Comment by the-j0k3r** [comment]
@dznlv thank you for reaching ou to use with this issue report.

There is a workaround, its been posted in this issue https://github.com/platformio/platformio-atom-ide-terminal/issues/707#issuecomment-514634895 < click that.

Thanks for your understanding.
