### ISSUE TITLE
platform atom ide terminal stopped working and can not reinstal 

### ISSUE THREAD

**Issue by RDCordova** [platformio/platformio-atom-ide-terminal#729]
- [x] I have reset Atom to defaults prior to submitting report.
- [ ] I have not reset Atom to defaults prior to submitting report.
### Description
Installing “platformio-ide-terminal@2.9.1” failed.Hide output…

> node-pty-prebuilt@0.7.6 install C:\Users\RODNEY~1\AppData\Local\Temp\apm-install-dir-119625-17480-6mv1cf.qaa2f\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt
> prebuild-install || node scripts/install.js

C:\Users\RODNEY~1\AppData\Local\Temp\apm-install-dir-119625-17480-6mv1cf.qaa2f\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt>if not defined npm_config_node_gyp (node "C:\Users\Rodney Cordova\AppData\Local\atom\app-1.39.0\resources\app\apm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild --build_v8_with_gn=false )  else (node "C:\Users\Rodney Cordova\AppData\Local\atom\app-1.39.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild --build_v8_with_gn=false ) 

prebuild-install WARN install No prebuilt binaries found (target=3.1.10 runtime=electron arch=x64 libc= platform=win32)
gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\Rodney Cordova\AppData\Local\atom\app-1.39.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\configure.js:492:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\Rodney Cordova\AppData\Local\atom\app-1.39.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\configure.js:517:16)
gyp ERR! stack     at C:\Users\Rodney Cordova\AppData\Local\atom\app-1.39.0\resources\app\apm\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Users\\Rodney Cordova\\AppData\\Local\\atom\\app-1.39.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Rodney Cordova\\AppData\\Local\\atom\\app-1.39.0\\resources\\app\\apm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--build_v8_with_gn=false"
gyp ERR! cwd C:\Users\RODNEY~1\AppData\Local\Temp\apm-install-dir-119625-17480-6mv1cf.qaa2f\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt
gyp ERR! node -v v8.9.3
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\RODNEY~1\AppData\Local\Temp\apm-install-dir-119625-17480-6mv1cf.qaa2f\package.json'
npm WARN apm-install-dir-119625-17480-6mv1cf.qaa2f No description
npm WARN apm-install-dir-119625-17480-6mv1cf.qaa2f No repository field.
npm WARN apm-install-dir-119625-17480-6mv1cf.qaa2f No README data
npm WARN apm-install-dir-119625-17480-6mv1cf.qaa2f No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-pty-prebuilt@0.7.6 install: `prebuild-install || node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-pty-prebuilt@0.7.6 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Rodney Cordova\.atom\.apm\_logs\2019-07-25T16_50_37_269Z-debug.log

**Comment by the-j0k3r** [comment]
@RDCordova thank you for reaching ou to use with this issue report.

There is a workaround, its been posted in this issue https://github.com/platformio/platformio-atom-ide-terminal/issues/707#issuecomment-514634895 < click that.

Thanks for your understanding.
