### ISSUE TITLE
Terminal not starting project path containing accented characters

### ISSUE THREAD

**Issue by tweetysat** [platformio/platformio-atom-ide-terminal#73]
Running on windows 10 1511, atom 1.10.2 and Platformio Ide Terminal 2.2.0.
With a project located in a folder width accented characters in the path the terminal stay black with only cursor blinking.
Works fine with a project located elsewhere.
Tried with powershell and also cmd.exe.

**Comment by the-j0k3r** [comment]
Please retry with 2.9.0
