### ISSUE TITLE
Cannot install after uninstalling to correct a bug

### ISSUE THREAD

**Issue by Chris-Hastie** [platformio/platformio-atom-ide-terminal#746]
- [x] I have reset Atom to defaults prior to submitting report.
- [ ] I have not reset Atom to defaults prior to submitting report.
### Steps to reproduce

1. Open Atom settings
2. Select "Install"
3. Find platformio-ide-terminal
4. Select install

**Expected behavior:** 
Expected the tool to install

**Actual behavior:** 
The installation button begins the installation animation, however nothing installs and the animation stops after a few seconds

**Reproduces how often:** 
Every time, I cannot install the tool

### Versions

```
> atom --version
Atom    : 1.39.1
Electron: 3.1.10
Chrome  : 66.0.3359.181
Node    : 10.2.0
```
```
> apm --version
apm  2.2.4
npm  6.2.0
node 8.9.3 x64
atom 1.39.1
python 3.7.0
git 2.20.1.windows.1
visual studio 2015
```
OS name and version: Windows 10 Pro version 1803, build 17134.885
Platformio-ide-terminal version: Unknown as cannot install

### Additional Information

I was using platformio-ide-terminal without issue until there was an Atom update which flagged the tool as having a bug and suggested reinstalling. I was able to uninstall but not install again afterwards

**Comment by the-j0k3r** [comment]
Thank you for reaching out to use with this issue report.

There is a workaround, its been posted in this issue https://github.com/platformio/platformio-atom-ide-terminal/issues/707#issuecomment-514634895 < click that.

There are other workarounds in thread (ive posted a rebuilt node-pty-prebuilt) compatible with Atom 1.39.1 zip with instructions.

Thanks for your understanding.
