### ISSUE TITLE
Ctrl+[left,right] prints characters (fish)

### ISSUE THREAD

**Issue by yajo** [platformio/platformio-atom-ide-terminal#75]
I use Fish, and with it, pressing ctrl+left or ctrl+right in a normal terminal (gnome-terminal) jumps a whole word in your currently typed command.

When doing that in this package's terminal, it prints characters `[5D` for ctrl+left, and `[5C` for ctrl+right instead.

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0 is using node-pty-prebuilt instead unmaintained and outdated pty.js

**Comment by Makerthone** [comment]
> the-j0k3r commented on 7 Feb 2019
Please retest again with platformio-atom-ide-terminal 2.9.0 is using node-pty-prebuilt instead unmaintained and outdated pty.js


Hi there! The problem still exists. Version 2.10.1

**Comment by UziTech** [comment]
This package is no longer maintained. Please uninstall platformio-ide-terminal and install either [terminus](https://atom.io/packages/terminus) or [x-terminal](https://atom.io/packages/x-terminal)
