### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by Anthomedal** [platformio/platformio-atom-ide-terminal#754]
Hello, atom has just been installed. And the installation failed. Could someone please help me?

### Steps to reproduce
`
$ sudo apm install platformio-ide-terminal
Installing platformio-ide-terminal to /root/.atom/packages ✗

> node-pty-prebuilt@0.7.6 install /tmp/apm-install-dir-11971-1437-1gpp9ll.xdwz/node_modules/platformio-ide-terminal/node_modules/node-pty-prebuilt
> prebuild-install || node scripts/install.js

sh: 1: prebuild-install: Permission denied
module.js:538
    throw err;
    ^

Error: Cannot find module '/tmp/apm-install-dir-11971-1437-1gpp9ll.xdwz/node_modules/platformio-ide-terminal/node_modules/node-pty-prebuilt/scripts/install.js'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
npm WARN enoent ENOENT: no such file or directory, open '/tmp/apm-install-dir-11971-1437-1gpp9ll.xdwz/package.json'
npm WARN apm-install-dir-11971-1437-1gpp9ll.xdwz No description
npm WARN apm-install-dir-11971-1437-1gpp9ll.xdwz No repository field.
npm WARN apm-install-dir-11971-1437-1gpp9ll.xdwz No README data
npm WARN apm-install-dir-11971-1437-1gpp9ll.xdwz No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-pty-prebuilt@0.7.6 install: `prebuild-install || node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-pty-prebuilt@0.7.6 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.atom/.apm/_logs/2019-08-01T17_18_51_453Z-debug.log
`

### Versions
Atom    : 1.39.1
Electron: 3.1.10
Chrome  : 66.0.3359.181
Node    : 10.2.0

OS name and version: Debian 10

Thank you !

**Comment by the-j0k3r** [comment]
Thank you for reaching out to use with this issue report.


There is a workaround, its been posted in this issue https://github.com/platformio/platformio-atom-ide-terminal/issues/707#issuecomment-514634895 < click that.

There are other workarounds in thread, so reading and typing more than the minimum is necessary.

You shouldnt install packages to root in any case, this should be installed userside.

Thanks for your understanding.
