### ISSUE TITLE
2.92 hangs, doesn't allow text entry

### ISSUE THREAD

**Issue by pdugan20** [platformio/platformio-atom-ide-terminal#755]
- [ ] I have reset Atom to defaults prior to submitting report.
- [x] I have not reset Atom to defaults prior to submitting report.
### Description

I upgraded to the newest version and I can't enter any text. I restarted my computer and restarted Atom with no luck.

I'm on Atom 1.39.1 x64 on the latest OSX

### Steps to reproduce

1. Open platformio-ide-terminal

**Expected behavior:** 
I can type

**Actual behavior:** 
I can't type

**Reproduces how often:** 
Every time I open the package

### Versions

```
> atom --version

```
```
> apm --version

```
OS name and version:
Platformio-ide-terminal version:

**Comment by AndyMardell** [comment]
Same problem here.

```
> atom --version
Atom    : 1.39.1
Electron: 3.1.10
Chrome  : 66.0.3359.181
Node    : 10.2.0
```

```
> apm --version
apm  2.2.4
npm  6.2.0
node 8.9.3 x64
atom 1.39.1
python 3.7.0
git 2.18.0
```

Note, 2.91 was working for me on Atom 1.39.1 with [this fix](https://github.com/platformio/platformio-atom-ide-terminal/issues/707#issuecomment-517001497)

**Comment by WolfAvenger** [comment]
When I updated terminal, it stopped to initialize, shows nothing. 2.9.1 worked perfect.

**Comment by aacassandra** [comment]
same problem here, when im update my this plugin, getting the error
mac os mojave 10.14.6
```
> atom --version
Atom    : 1.38.1
Electron: 2.0.18
Chrome  : 61.0.3163.100
Node    : 8.9.3
```

```
> apm --version
apm  2.1.7
npm  6.2.0
node 8.9.3 x64
atom 1.38.1
python 2.7.16
git 2.20.1
```

**Comment by linjialiang** [comment]
> me too !

![图片](https://user-images.githubusercontent.com/8848263/62335948-966f1300-b500-11e9-8d77-c7cdb9955697.png)

**Comment by grhitch** [comment]
Same here on: 

Ubuntu 19.04
apm  2.2.4
npm  6.2.0
node 8.9.3 x64
atom 1.39.1
python 2.7.16
git 2.20.1

Fixed by downgrading to 2.9.1

**Comment by kinojacky** [comment]
Same with me.

➜  ~ atom --version
Atom    : 1.39.1
Electron: 3.1.10
Chrome  : 66.0.3359.181
Node    : 10.2.0

➜  ~ apm --version
apm  2.2.4
npm  6.2.0
node 8.9.3 x64
atom 1.39.1
python 2.7.10
git 2.20.1
➜  ~

**Comment by xinst** [comment]
It is same for me. I did nothing but upgrade the package

Atom    : 1.39.1
Electron: 3.1.10
Chrome  : 66.0.3359.181
Node    : 10.2.0

apm  2.2.4
npm  6.2.0
node 8.9.3 x64
atom 1.39.1
python 2.7.10
git 2.16.1

**Comment by jpung** [comment]
Latest update has broken it even for downgraded atom versions. Previous fixes for mac no longer working as well once upgraded

**Comment by raels** [comment]
It looks like 2.9.2 wants node-pty-prebuilt but can't find it:  

```
<embedded>:14 Cannot find module 'node-pty-prebuilt' Error: Cannot find module 'node-pty-prebuilt'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
    at Function.Module._load (internal/modules/cjs/loader.js:528:25)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/raels/.atom/packages/platformio-ide-terminal/lib/process.coffee:1:7)
    at Object.<anonymous> (/Users/raels/.atom/packages/platformio-ide-terminal/lib/process.coffee:1:1)
    at Object.<anonymous> (/Users/raels/.atom/packages/platformio-ide-terminal/lib/process.coffee:1:1)
    at Module._compile (internal/modules/cjs/loader.js:711:30)
    at Object.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:255:23)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/task-bootstrap.js:90:17)
    at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/task-bootstrap.js:92:3)
    at Module._compile (internal/modules/cjs/loader.js:711:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:753:10)
    at startup (internal/bootstrap/node.js:241:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:579:3)
(anonymous) @ <embedded>:14
(anonymous) @ <embedded>:14
simpleDispatch @ <embedded>:11
emit @ <embedded>:11
(anonymous) @ <embedded>:14
emit @ events.js:182
emit @ internal/child_process.js:811
_tickCallback @ internal/process/next_tick.js:63

```

**Comment by raels** [comment]
But package.json says it wants node-pty-prebuilt-multiarch:

``` 
 "dependencies": {
    "atom-space-pen-views": "^2.2.0",
    "node-pty-prebuilt-multiarch": "^0.8.1",
    "term.js": "https://github.com/jeremyramin/term.js/tarball/master",
    "underscore": "^1.8.3"
  },
```

**Comment by Iseez** [comment]
Same problem on Windows 10x64.
Atom    : 1.39.0
Electron: 3.1.10
Chrome  : 66.0.3359.181
Node    : 10.2.0

apm  2.2.4
npm  6.2.0
node 8.9.3 x64
atom 1.39.0
python 3.6.7
git 2.21.0.windows.1

The terminal cursor just keeps blinking

**Comment by the-j0k3r** [comment]
Thanks guys, and Im sorry its my fault, on the upgrade PR to switch to node-pty-prebuilt-multiarch I missed the coffescript definition.

Good news is a PR is up to address this and should be fixed in 2.9.3

For more information see https://github.com/platformio/platformio-atom-ide-terminal/pull/757

**Comment by xinst** [comment]
thx for the timely fix，I changed my local code follow your PR, it works again, :)

**Comment by Borgelin** [comment]
Changed my local code in process.coffee to the one mentioned in #755 (-multiarch), but it does not help. Atom version 1.39.1 x64.
I'm fairly new to coding, could be something I'm missing?

**Comment by the-j0k3r** [comment]
@Borgelin You need to restart atom perhaps. Alsomake sure you dont have a corrupt powershell install like I did due to upgrade to Windows 1903.

**Comment by Borgelin** [comment]
@the-j0k3r 
Thanks for helping. Can't see any problems with Powershell, working fine. Restarted Atom.
Just to make sure I got this correctly, should the first five lines of process.coffee look like this?:

pty = require 'node-pty-prebuilt-multiarch'
path = require 'path'
fs = require 'fs'
_ = require 'underscore'
child = require 'child_process'

**Comment by the-j0k3r** [comment]
It looks like in the PR, best you wait until release with fix.

Also on issue please provide information contained in the issue template

Copy and paste the template located at https://raw.githubusercontent.com/platformio/platformio-atom-ide-terminal/master/.github/ISSUE_TEMPLATE.md and fill in all fields. Logs / Errors / other information should be added at the bottom in the Notes portion of the [issue template](https://raw.githubusercontent.com/platformio/platformio-atom-ide-terminal/master/.github/ISSUE_TEMPLATE.md).


Thank you for your understanding.

**Comment by ivankravets** [comment]
Please upgrade to https://github.com/platformio/platformio-atom-ide-terminal/releases/tag/v2.9.3

**Comment by the-j0k3r** [comment]
Any new issues (including me too reports) should contain full issue template details.

Copy and paste the template located at https://raw.githubusercontent.com/platformio/platformio-atom-ide-terminal/master/.github/ISSUE_TEMPLATE.md and fill in all fields. Logs / Errors / other information should be added at the bottom in the Notes portion of the [issue template](https://raw.githubusercontent.com/platformio/platformio-atom-ide-terminal/master/.github/ISSUE_TEMPLATE.md).

Thank you for your understanding.
