### ISSUE TITLE
Unable to install or update 2.9.4

### ISSUE THREAD

**Issue by smellypotato** [platformio/platformio-atom-ide-terminal#767]
- [ ] I have reset Atom to defaults prior to submitting report.
- [x] I have not reset Atom to defaults prior to submitting report.
### Description

Unable to update to 2.9.4. After uninstalling the old version, cannot install version 2.9.4. Fail to install without any error

### Steps to reproduce

1. Update using any method
2. Uninstall package, then install again using any method
3.

**Expected behavior:** 
Update/install sucessfully

**Actual behavior:** 
Update failed with warning, install failed without warning

**Reproduces how often:** 100%

### Versions

```
> atom --version
Atom v1.13.2 x64
```
```
> apm --version

```
OS name and version: MacOS High Sierra v10.13.6
Platformio-ide-terminal version:2.9.4

**Comment by the-j0k3r** [comment]
Thnaks for submitting this isse report,

1. Navigate to atpm/packages and delete the platformio-ide-terminal folder or links to it.
2. install platformio-ide-terminal@2.9.4via apm or UI.

Also you are using an unsupported version of Atom 1.13.2 requires a much older platformio-ide-terminal, both are unsupported here.

You will need minimum Atom 1.39.1 64bit

Thanks for understanding.

**Comment by smellypotato** [comment]
Updating Atom to 1.39.1 works, thanks.

Btw, it was a typo for my old atom version: 1.31.2 instead of 1.13.2

**Comment by the-j0k3r** [comment]
> Updating Atom to 1.39.1 works, thanks.

Great!

> Btw, it was a typo for my old atom version: 1.31.2 instead of 1.13.2

Same workaround though.

Glad its working.
