### ISSUE TITLE
Uncaught Channel closed

### ISSUE THREAD

**Issue by Baalkikhaal** [platformio/platformio-atom-ide-terminal#768]
Dear developers,
This is my first issue post reporting a bug on GitHub. I am very excited to be part of the development process 😄.

[Enter steps to reproduce:]

1. Open a terminal (Alt+ Shift + T). After a pause of 20 s the after mentioned-error pops up.
2. Not sure if it is repeatable. Yesterday it worked fine. However [Script](https://atom.io/packages/script) package was not installed yesterday. After installing and successfully running "Script", I tried opening terminal

**Atom**: 1.39.1 x64
**Electron**: 3.1.10
**OS**: Microsoft Windows 10 Home Insider Preview Single Language
**Thrown From**: [platformio-ide-terminal](https://github.com/platformio/platformio-atom-ide-terminal) package 2.9.4

### Stack Trace

Uncaught Channel closed

```
At events.js:167

Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed
    at ChildProcess.target.send (internal/child_process.js:627:16)
    at Task.send (~/AppData/Local/atom/app-1.39.1/resources/app/static/<embedded>:14:42428)
    at PlatformIOTerminalView.module.exports.PlatformIOTerminalView.input (/packages/platformio-ide-terminal/lib/view.coffee:271:17)
    at /packages/platformio-ide-terminal/lib/view.coffee:149:8)
    at Terminal.EventEmitter.emit (/packages/platformio-ide-terminal/node_modules/term.js/src/term.js:109:12)
    at Terminal.handler (/packages/platformio-ide-terminal/node_modules/term.js/src/term.js:3493:8)
    at /packages/platformio-ide-terminal/node_modules/term.js/src/term.js:3253:12
```

### Commands

```
     -2:08.0 core:cut (input.hidden-input)
     -2:06.7.0 editor:newline (input.hidden-input)
     -2:06.3.0 core:paste (input.hidden-input)
     -2:03.6.0 core:save (input.hidden-input)
     -2:02.2.0 script:run (input.hidden-input)
     -1:34.3.0 core:move-left (input.hidden-input)
     -1:33.5.0 core:move-down (input.hidden-input)
     -1:33.3.0 core:move-left (input.hidden-input)
     -1:33 core:move-down (input.hidden-input)
     -1:32.6.0 core:move-up (input.hidden-input)
     -1:32.1.0 core:move-down (input.hidden-input)
     -1:31.9.0 core:move-left (input.hidden-input)
     -1:19.1.0 script:run (input.hidden-input)
     -1:02.1.0 platformio-ide-terminal:new (input.hidden-input)
```

### Non-Core Packages

```
language-latex 1.2.0 
latex 0.50.2 
pdf-view 0.71.0 
platformio-ide-terminal 2.9.4 
script 3.18.1 
```

**Comment by the-j0k3r** [comment]
@Baalkikhaal Thank you for reporting this issue to us.

>This is my first issue post reporting a bug on GitHub. I am very excited to be part of the development process smile.

Thanks and welcome, we do need developers, as we have none at this time.

On your log.

>    at /packages/platformio-ide-terminal/node_modules/term.js/src/term.js:3253:12

We dont use this since node-pty-prebuilt was added in platformio-ide-terminal 2.9.0 its not even part of new installs, so if you have been upgrading until now, maybe its time to:

1.  Uninstall platformio-ide-terminal via `apm uninstall platformio-ide-terminal` 
2. Make sure its gone from `.atom/packages` directory in your user folder, and reinstall it
   `apm i platformio-ide-terminal@2.9.4`.

 > 2. Not sure if it is repeatable. Yesterday it worked fine. However Script package was not installed yesterday. After installing and successfully running "Script", I tried opening terminal

Well easy test:

3.  Remove/uninstall the **script** package **and retest**, that is after doing the step 1. and 2.  above.
If when you remove the script package the issue does not repeat itself, then you know the issue is caused by the script package or some weird interaction between the two causes the issue. Make sense?

4. Only then after you know the issue is gone try re-adding script package,
If issue returns, well I would advise you to report the issue to script repo. Usually issues are caused by external package or programs installs that affect platformio-ide-terminal.

This script package last update was over a year ago, so good luck.

Please do let me know whats happened after you tried these things.

In future dont overwrite any portions of the issue template but indeed complete them all, any additions you want to add, add it to the end of template in the relevant fields, the logs you posted were helpful but other info could shed more light on problem.

**Comment by Baalkikhaal** [comment]
> 
> 
> @Baalkikhaal Thank you for reporting this issue to us.
> 
> > This is my first issue post reporting a bug on GitHub. I am very excited to be part of the development process smile.
> 
> Thanks and welcome, we do need developers, as we have none at this time.

I am a noob programmer. However I am exploring `GitHub + Atom` ecosystem and dynamics. I will venture into more active contribution once I am confident. 😃 

> 
> On your log.
> 
> > at /packages/platformio-ide-terminal/node_modules/term.js/src/term.js:3253:12
> 
> We dont use this since node-pty-prebuilt was added in platformio-ide-terminal 2.9.0 its not even part of new installs, so if you have been upgrading until now, maybe its time to:
> 
>     1. Uninstall platformio-ide-terminal via `apm uninstall platformio-ide-terminal`
> 

Step 1 : Executed

![AtomBug1](https://user-images.githubusercontent.com/8896597/62860889-4f162d00-bd1f-11e9-8823-607b2502eba0.png)

>     2. Make sure its gone from `.atom/packages` directory in your user folder, and reinstall it
>        `apm i platformio-ide-terminal@2.9.4`.
> 

Step 2 : Executed and `platformio-ide-terminal` working fine

![AtomBug2](https://user-images.githubusercontent.com/8896597/62860996-a6b49880-bd1f-11e9-887d-ca4f231674d1.png)

> 
> > 1. Not sure if it is repeatable. Yesterday it worked fine. However Script package was not installed yesterday. After installing and successfully running "Script", I tried opening terminal
> 
> Well easy test:
> 
>     1. Remove/uninstall the **script** package **and retest**, that is after doing the step 1. and 2.  above.
>        If when you remove the script package the issue does not repeat itself, then you know the issue is caused by the script package or some weird interaction between the two causes the issue. Make sense?
> 

Step 3 
- Removed the `Script` package

![AtomBug3](https://user-images.githubusercontent.com/8896597/62861126-10cd3d80-bd20-11e9-9beb-f1124b39395f.png)

- `platformio-ide-terminal` working fine

![AtomBug4](https://user-images.githubusercontent.com/8896597/62861237-6efa2080-bd20-11e9-84ab-5463cc33484d.png)

>     2. Only then after you know the issue is gone try re-adding script package,
>        If issue returns, well I would advise you to report the issue to script repo. Usually issues are caused by external package or programs installs that affect platformio-ide-terminal.
> 

Step 4 
- Reinstalled the `Script` package

![AtomBug5](https://user-images.githubusercontent.com/8896597/62861325-ba143380-bd20-11e9-91bc-07c337c871f8.png)

- `platformio-ide-terminal` working fine

![AtomBug6](https://user-images.githubusercontent.com/8896597/62861347-ce583080-bd20-11e9-86b2-3be27b5c0b01.png)

> 
> This script package last update was over a year ago, so good luck.
> 
> Please do let me know whats happened after you tried these things.

Thank you @the-j0k3r for the detailed instructions. I hope I have executed them to the dot. That is why I put up detailed responses after each instruction as I was not sure the optimum way of reporting and responding to  bug tracking. Since the bug did not recur, I am guessing that reinstalling `platformio-ide-terminal` did the trick. From next time I will un/install packages via the command line as a safe programming practice.

> 
> In future dont overwrite any portions of the issue template but indeed complete them all, any additions you want to add, add it to the end of template in the relevant fields, the logs you posted were helpful but other info could shed more light on problem.

Sure I will keep that in mind 😊

**Comment by the-j0k3r** [comment]
Excelent and thanks for comming back with that detailed response, its appreciated =)

It could be that upgrading platformio-ide-terminal may leave remnants behind from much older versions, its possible, the `node_modules` folder is a problem in normal circumstances where upgrades are concerned, Theres nothing we can do about it but this.

Glad its working, Will close issue now.

Feel free to add any further info if situation changes.

Thanks.
