### ISSUE TITLE
After last update, terminal is not showing anything

### ISSUE THREAD

**Issue by alejandroastudillo** [platformio/platformio-atom-ide-terminal#769]
- [x] I have reset Atom to defaults prior to submitting report.
- [ ] I have not reset Atom to defaults prior to submitting report.
### Description

Terminal is not showing anything. That happened exactly after updating the platformio-ide-terminal package.

### Steps to reproduce

1. Start atom
2. Open a terminal
3.

**Expected behavior:** 
To show the usual username and text when terminal is in idle.

**Actual behavior:** 
Nothing is showing. All black.

**Reproduces how often:** 
100 %

### Versions

```
> atom --version
Atom    : 1.26.1
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0
```
```
> apm --version
apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.26.1
python 2.7.12
git 2.7.4

```
OS name and version: Ubuntu 16.04
Platformio-ide-terminal version: 2.9.4

**Comment by the-j0k3r** [comment]
@alejandroastudillo Thank you for opening this issue report and filling in the template.

I see immediately that youre using an unsupported version of Atom for platformio-ide-terminal 2.9.4
If you wish to remain with that old Atom version, please do the following.

Open an external terminal and run.

0. close all Atom Instances

1. `apm uninstall platformio-ide-terminal`

wait for process to finish then, install and older version of platformio-ide-terminal specifically. 

2. `apm install platformio-ide-terminal@2.9.0`
3. Restart Atom.
4. Test terminal

If that doesnt work you will need an even older version of platformio-ide-terminal, noe are supported anymore but you can still install much older versions, if you follow the steps above for older versions.

Alternatively upgrade Atom to the current production build 1.39.1

Please leave feedback once you tried what I just suggested.

Thanks.

**Comment by digitalcombine** [comment]
I'm getting the same issue.

**Version**
```shell
$ atom --version
Atom    : 1.33.0
Electron: 2.0.11
Chrome  : 61.0.3163.100
Node    : 8.9.3
```

```shell
$ apm --version
apm  2.1.2
npm  6.2.0
node 8.9.3 x64
atom 1.33.0
python 2.7.15+
git 2.17.1
```

Ubuntu 18.04
Platformio-ide-terminal version: 2.9.4

Downgrading to Platformio-ide-terminal version 2.9.0 as above did get the terminal working again.

Also upgrading to atom version 1.39.1 from the atom package repositories fixed the problems with Platformio-ide-terminal version 2.9.4.

**Comment by the-j0k3r** [comment]
> Downgrading to Platformio-ide-terminal version 2.9.0 as above did get the terminal working again.

> Also upgrading to atom version 1.39.1 from the atom package repositories fixed the problems with Platformio-ide-terminal version 2.9.4.

It does because the node-pty-prebuilt 2.9.0/2.9.1 and node-pty-prebuilt-mutiarch 2.9.4 binaries are specific to Atom's Electron versions, Thers no way around this and if you guys have older Atom versions with older electron versions this is what you need to do.

Atom has repositories in Linux? Are these official?

**Comment by titulebolide** [comment]
I confirm that upgrading atom fixes the issue. I was working on version 1.37 meanwhile the current version for my distribution (debian 9) is 1.39. Thanks!

**Comment by alejandroastudillo** [comment]
I solved the problem by installing the nightly version of Atom (but I suppose that v-1.39 works as well), and rebuilding the packages for that version (when asked). I think this issue can be closed.

**Comment by the-j0k3r** [comment]
> I solved the problem by installing the nightly version of Atom

Well thats very interesting, same OS and https://github.com/platformio/platformio-atom-ide-terminal/issues/766 says the contrary.

> (but I suppose that v-1.39 works as well), and rebuilding the packages for that version (when asked)

There's no need to rebuild packages for 1.39.1 with platformio-ide-terminal 2.9.4, this statement with limited information above, are you sure there is no confusion it with the nightly?

>  I think this issue can be closed.

Given that some other users are using this ticket to report same issue, I'll leave it open for now.

**Comment by the-j0k3r** [comment]
> I solved the problem by installing the nightly version of Atom

Great. At least we know Linux binaries work with Atom nightlies, Windows doesnt seem to work #766. Havent tested.

> (but I suppose that v-1.39 works as well), and rebuilding the packages for that version (when asked)

There's no need to rebuild packages for 1.39.1 with platformio-ide-terminal 2.9.4 must have been some glitch with Atom upgrade.

>  I think this issue can be closed.

Given that some other users are using this ticket to report same issue, I'll leave it open for now.

**Comment by tan-wei** [comment]
Met the same issue both under Windows and Linux with Atom 1.39.

**Comment by the-j0k3r** [comment]
@ian-wei

Please provide evidence of that claim.

**Comment by the-j0k3r** [comment]
> Met the same issue both under Windows and Linux with Atom 1.39.

Uninstall platformio-ide-terminal and reinstall.

1.  Uninstall platformio-ide-terminal via `apm uninstall platformio-ide-terminal` 
2. Make sure its gone from `.atom/packages` directory in your user folder, and reinstall it
   `apm i platformio-ide-terminal@2.9.4`.

**Comment by ghost** [comment]
Issue persist in Atom 1.40.0 not showing anything 
![Screenshot from 2019-08-14 14-30-48](https://user-images.githubusercontent.com/26399261/63009387-0470ee00-bea2-11e9-86d1-504dfedd4ee2.png)

:+1: Helpful Plugin.

**Comment by the-j0k3r** [comment]
@pranavwani @tan-wei open a new issue ticket and fill in all issue template fields. This topic is for nightlies only. Thanks.

**Comment by the-j0k3r** [comment]
@pranavwani @tan-wei open a new issue ticket and fill in all issue template fields. This topic is unrelated to your issue with 1.40.0. Thanks.
