### ISSUE TITLE
Add support for Ubuntu bash in Windows 10

### ISSUE THREAD

**Issue by 0ski** [platformio/platformio-atom-ide-terminal#77]
#24 - any workaround with PowerShell or CMD doesn't work

**Comment by bakana808** [comment]
+1 I feel like this might be an issue with Atom itself; it can't even see bash.exe

**Comment by edwingustafson** [comment]
+1 PowerShell can't see `bash.exe` inside `platformio-atom-ide-terminal` the way it can outside.

From `powershell.exe` run from the Windows 10 Start Menu:

```
PS H:\> dir C:\Windows\System32\bash.exe


    Directory: C:\Windows\System32


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----       2016-09-13     08:54          70656 bash.exe
```

From `platformio-atom-ide-terminal`'s default shell `C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe`:

```
PS H:\> dir C:\Windows\System32\bash.exe
dir : Cannot find path 'C:\Windows\System32\bash.exe' because it does not exist.
At line:1 char:1
+ dir C:\Windows\System32\bash.exe
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Windows\System32\bash.exe:String) [Get-ChildItem], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetChildItemCommand
```

**Comment by wxkuang** [comment]
+1

**Comment by JohnnyR030T** [comment]
Hey guys, I was having the same problem... Try entering this in "Settings" > "Shell Override":

```
C:\\WINDOWS\\sysnative\\bash.exe
```

It worked for me. Got the idea from Jessica Deen on Channel 9 when she did the same for Visual Studio Code... Hope this helps.
http://www.jessicadeen.com/tech/svcc-getting-started-with-bash-on-windows-10-recap-and-channel-9-video/

**Comment by 0ski** [comment]
Thanks, it works! I'm closing the issue. Btw. thanks for the video it seems interesting.

**Comment by mslinn** [comment]
This works, but does not make the project directory current. Instead, the user home directory is current.
