### ISSUE TITLE
platformio-ide-terminal installation 2.9.4 failed

### ISSUE THREAD

**Issue by tedykim11** [platformio/platformio-atom-ide-terminal#771]
- [ ] I have reset Atom to defaults prior to submitting report.
- [ ] I have not reset Atom to defaults prior to submitting report.
platformio-ide-terminal installation 2.9.4 failed on Atom 1.40.0 x64

platformio-ide-terminal installation 2.9.4 failed on Atom 1.40.0 x64
as well as any type of terminal packages install fails.

### Steps to reproduce

> node-pty-prebuilt-multiarch@0.9.0-beta21.legacy install C:\Users\AppData\Local\Temp\apm-install-dir-119715-10916-y8szjg.cdwf\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch
> prebuild-install || node scripts/install.js

C:\Users\xxxxx\AppData\Local\Temp\apm-install-dir-119715-10916-y8szjg.cdwf\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch>if not defined npm_config_node_gyp (node "C:\Users\xxxxx\AppData\Local\atom\app-1.40.0\resources\app\apm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\xxxxxx\AppData\Local\atom\app-1.40.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 

prebuild-install WARN install No prebuilt binaries found (target=3.1.10 runtime=node arch=x64 libc= platform=win32)
gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\AppData\Local\atom\app-1.40.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\configure.js:492:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\AppData\Local\atom\app-1.40.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\configure.js:517:16)
gyp ERR! stack     at C:\Users\AppData\Local\atom\app-1.40.0\resources\app\apm\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:182:21)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Users\AppData\\Local\\atom\\app-1.40.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\AppData\\Local\\atom\\app-1.40.0\\resources\\app\\apm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\AppData\Local\Temp\apm-install-dir-119715-10916-y8szjg.cdwf\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch
gyp ERR! node -v v10.2.1
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\AppData\Local\Temp\apm-install-dir-119715-10916-y8szjg.cdwf\package.json'
npm WARN apm-install-dir-119715-10916-y8szjg.cdwf No description
npm WARN apm-install-dir-119715-10916-y8szjg.cdwf No repository field.
npm WARN apm-install-dir-119715-10916-y8szjg.cdwf No README data
npm WARN apm-install-dir-119715-10916-y8szjg.cdwf No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-pty-prebuilt-multiarch@0.9.0-beta21.legacy install: `prebuild-install || node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-pty-prebuilt-multiarch@0.9.0-beta21.legacy install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\.atom\.apm\_logs\2019-08-15T19_07_41_315Z-debug.log

**Expected behavior:** 

**Actual behavior:** 

**Reproduces how often:** 

### Versions

```
> atom --1.40.0

```
```
> apm --version

```
OS name and version: Windows 7 SP1
Platformio-ide-terminal version:

**Comment by shibaPuppy** [comment]
```
> apm --version
apm  2.4.2
npm  6.2.0
node 10.2.1 x64
atom 1.40.0
python 3.7.4
git 2.22.0.windows.1
visual studio
```
OS : window10
python: 3.7.4

I haven't installed with a similar error.
The log is shown below.

```
warn enoent ENOENT: no such file or directory, open 'C:\Users\whoami\AppData\Local\Temp\apm-install-dir-119716-3400-1dpjsk9.a1bqk\package.json'
verbose enoent This is related to npm not being able to find a file.
warn apm-install-dir-119716-3400-1dpjsk9.a1bqk No description
warn apm-install-dir-119716-3400-1dpjsk9.a1bqk No repository field.
warn apm-install-dir-119716-3400-1dpjsk9.a1bqk No README data
warn apm-install-dir-119716-3400-1dpjsk9.a1bqk No license field.
verbose stack Error: node-pty-prebuilt-multiarch@0.9.0-beta21.legacy install: `prebuild-install || node scripts/install.js`
verbose stack Exit status 1
verbose stack     at EventEmitter.<anonymous> (C:\Users\whoami\AppData\Local\atom\app-1.40.0\resources\app\apm\node_modules\npm\node_modules\npm-lifecycle\index.js:304:16)
verbose stack     at EventEmitter.emit (events.js:182:13)
verbose stack     at ChildProcess.<anonymous> (C:\Users\whoami\AppData\Local\atom\app-1.40.0\resources\app\apm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
verbose stack     at ChildProcess.emit (events.js:182:13)
verbose stack     at maybeClose (internal/child_process.js:961:16)
verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
verbose pkgid node-pty-prebuilt-multiarch@0.9.0-beta21.legacy
verbose cwd C:\Users\whoami\AppData\Local\Temp\apm-install-dir-119716-3400-1dpjsk9.a1bqk
verbose Windows_NT 10.0.16299
verbose argv "C:\\Users\\whoami\\AppData\\Local\\atom\\app-1.40.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\whoami\\AppData\\Local\\atom\\app-1.40.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\whoami\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\whoami\\.atom\\.apmrc" "install" "https://www.atom.io/api/packages/platformio-ide-terminal/versions/2.9.4/tarball" "--target=3.1.10" "--disturl=https://atom.io/download/electron" "--arch=x64" "--global-style"
verbose node v10.2.1
verbose npm  v6.2.0
error code ELIFECYCLE
error errno 1
error node-pty-prebuilt-multiarch@0.9.0-beta21.legacy install: `prebuild-install || node scripts/install.js`
error Exit status 1
error Failed at the node-pty-prebuilt-multiarch@0.9.0-beta21.legacy install script.
error This is probably not a problem with npm. There is likely additional logging output above.
verbose exit [ 1, true ]
```

**Comment by the-j0k3r** [comment]
this is a duplicate of https://github.com/platformio/platformio-atom-ide-terminal/issues/770

Also see https://github.com/platformio/platformio-atom-ide-terminal/issues/770#issuecomment-521368518 for proof it works.
