### ISSUE TITLE
I have this while installing platformio -ide-terminal

### ISSUE THREAD

**Issue by NightFox-06** [platformio/platformio-atom-ide-terminal#778]
Installing “platformio-ide-terminal@2.9.4” failed.Hide output…

> node-pty-prebuilt-multiarch@0.9.0-beta21.legacy install C:\Users\WarLock\AppData\Local\Temp\apm-install-dir-119725-7496-1fdfosk.imse\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch
> prebuild-install || node scripts/install.js

C:\Users\WarLock\AppData\Local\Temp\apm-install-dir-119725-7496-1fdfosk.imse\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch>if not defined npm_config_node_gyp (node "C:\Users\WarLock\AppData\Local\atom\app-1.40.0\resources\app\apm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\WarLock\AppData\Local\atom\app-1.40.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 

prebuild-install WARN install No prebuilt binaries found (target=3.1.10 runtime=node arch=x64 libc= platform=win32)
gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "C:\Users\WarLock\Anaconda3\python.EXE", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\WarLock\AppData\Local\atom\app-1.40.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\configure.js:492:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\WarLock\AppData\Local\atom\app-1.40.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\configure.js:517:16)
gyp ERR! stack     at C:\Users\WarLock\AppData\Local\atom\app-1.40.0\resources\app\apm\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:182:21)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Users\\WarLock\\AppData\\Local\\atom\\app-1.40.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\WarLock\\AppData\\Local\\atom\\app-1.40.0\\resources\\app\\apm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\WarLock\AppData\Local\Temp\apm-install-dir-119725-7496-1fdfosk.imse\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch
gyp ERR! node -v v10.2.1
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\WarLock\AppData\Local\Temp\apm-install-dir-119725-7496-1fdfosk.imse\package.json'
npm WARN apm-install-dir-119725-7496-1fdfosk.imse No description
npm WARN apm-install-dir-119725-7496-1fdfosk.imse No repository field.
npm WARN apm-install-dir-119725-7496-1fdfosk.imse No README data
npm WARN apm-install-dir-119725-7496-1fdfosk.imse No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-pty-prebuilt-multiarch@0.9.0-beta21.legacy install: `prebuild-install || node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-pty-prebuilt-multiarch@0.9.0-beta21.legacy install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\WarLock\.atom\.apm\_logs\2019-08-25T03_58_16_239Z-debug.log

version - 1.40.0 X 64
OS - windows

**Comment by the-j0k3r** [comment]
@NightFox-06 Thanks for opening this report.

Atom 1.40.0 version of apm is buggy, see https://github.com/atom/atom/issues/19780

Upgrade to Atom 1.40.1 its all fixed.

Closing this as resolved, we also have a sticky issue that you could have read before opening this.

**Comment by the-j0k3r** [comment]
@NightFox-06 Thanks for opening this report.

Atom 1.40.0 version of apm is buggy, see https://github.com/atom/atom/issues/19780

Upgrade to Atom 1.40.1 its all fixed.

Closing this as resolved, we also have a sticky issue that you could have read before opening this and also dont ignore the issue templates, they are there for a reason.

Thanks.

**Comment by Magia19** [comment]
$ atom -v

Atom    : 1.44.0
Electron: 4.2.7
Chrome  : 69.0.3497.128
Node    : 10.11.0

$ apm install platformio-ide-terminal
Installing platformio-ide-terminal to C:\Users\eunad\.atom\packages failed

npm ERR! code Z_BUF_ERROR
npm ERR! errno -5
npm ERR! zlib: unexpected end of file

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\eunad\.atom\.apm\_logs\2020-04-09T05_34_33_856Z-debug.log

SO : Windows 10

**Comment by the-j0k3r** [comment]
@Magia19 thats npm error and missing a lot of logging to know what issue actually is.
Also unrelated to terminal or this issue.
