### ISSUE TITLE
Cannot access Danish keyboard through right alt button

### ISSUE THREAD

**Issue by Dysperen** [platformio/platformio-atom-ide-terminal#78]
I simply cannot figure out if I just don't know how to get it to work. If there is a solution, would someone point me in the right direction?
Even tried both running stable and development build of Atom.

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0 is using node-pty-prebuilt instead unmaintained and outdated pty.js
