### ISSUE TITLE
Terminal not loading Atom 1.34.0/platformio-ide-terminal 2.9.4

### ISSUE THREAD

**Issue by jessypouliot98** [platformio/platformio-atom-ide-terminal#786]
Tick the appropriate box by adding an x in between the [] to ID the status-->
- [ ] I have reset Atom to defaults prior to submitting report.
- [X] I have not reset Atom to defaults prior to submitting report.
### Description
I had this problem at my job last week on win10 after updating the package and got fix shortly after. Yesterday, I got on my Linux computer and had the same problem, but now it's the latest version and is not fixed

### Steps to reproduce
1. (+) New Terminal (open up a new terminal)

**Expected behavior: My terminal emulator should load

**Actual behavior: Nothing, blank terminal. (terminal seems not to be loading in)

**Reproduces how often: 100%

### Versions

Atom    : 1.34.0
Electron: 2.0.16
Chrome  : 61.0.3163.100
Node    : 8.9.3

apm  2.1.3
npm  6.2.0
node 8.9.3 x64
atom 1.34.0
python 2.7.15+
git 2.17.1

OS name and version: Ubuntu 18.04.3 LTS

Platformio-ide-terminal version: 2.9.4

**Comment by jessypouliot98** [comment]
Going back to 2.9.3 fixed my problem, if that help in debugging !

**Comment by the-j0k3r** [comment]
@jessypouliot98 

2.9.4 is compatible with electron 3.x, 4.x and 5.x

Your Atom version 1.34.0 is electron 2.x so if you want Atom 1.34.0 thats what you have to stick with platformio-ide-terminal 2.9.3.

There is nothing to debug really, but I do apprecciate you filling in the template with the necessary information for me to be able to explain these details.

So to sum up, to have platformio-ide-terminal 2.9.4 is to upgrade Atom to 1.40.1 <- or newer Atom version.

Ill be closing this as wontfix and outdated-versions as there is nothing else I can do here given these facts, We expect our users to Work with latest production Atom releases to our latest production releases.

Thanks you for understanding.
