### ISSUE TITLE
Cannot install on last atom 1.40.1 in ubuntu 19.04

### ISSUE THREAD

**Issue by rusikf** [platformio/platformio-atom-ide-terminal#795]
- [ ] I have reset Atom to defaults prior to submitting report.
- [ x ] I have not reset Atom to defaults prior to submitting report.
### Steps to reproduce

1.Cannot install Atom, I see the error:

```
Installing “platformio-ide-terminal@2.9.4” failed.Hide output…

> node-pty-prebuilt-multiarch@0.9.0-beta21.legacy install /tmp/apm-install-dir-119915-20948-p0ajn3.4hqvn/node_modules/platformio-ide-terminal/node_modules/node-pty-prebuilt-multiarch
> prebuild-install || node scripts/install.js


Aborted (core dumped)
Aborted (core dumped)
gyp: Call to 'node -e "require('nan')"' returned exit status 134 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Linux 5.0.0-31-generic
gyp ERR! command "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/apm-install-dir-119915-20948-p0ajn3.4hqvn/node_modules/platformio-ide-terminal/node_modules/node-pty-prebuilt-multiarch
gyp ERR! node -v v10.2.1
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
Aborted (core dumped)
Aborted (core dumped)
npm WARN enoent ENOENT: no such file or directory, open '/tmp/apm-install-dir-119915-20948-p0ajn3.4hqvn/package.json'
npm WARN apm-install-dir-119915-20948-p0ajn3.4hqvn No description
npm WARN apm-install-dir-119915-20948-p0ajn3.4hqvn No repository field.
npm WARN apm-install-dir-119915-20948-p0ajn3.4hqvn No README data
npm WARN apm-install-dir-119915-20948-p0ajn3.4hqvn No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! node-pty-prebuilt-multiarch@0.9.0-beta21.legacy install: `prebuild-install || node scripts/install.js`
npm ERR! Exit status 134
npm ERR! 
```

**Expected behavior:** Package has been installed

**Actual behavior:**  Not installed

**Reproduces how often:** Every time 

### Versions

```
atom --version
Atom    : 1.40.1
Electron: 3.1.10
Chrome  : 66.0.3359.181
Node    : 10.2.0
```
OS name and version:
```
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 19.04
Release:        19.04
Codename:       disco
```

### Additional Information
( note - before updating atom it works good )

**Comment by the-j0k3r** [comment]
OK this isnt related to platformio-ide-terminal error reads

```log
gyp: Call to 'node -e "require('nan')"' returned exit status 134 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
```

So blame gyp and report this issue to apm repo after you confirmed the following:

Make sure that you are installing platformio-ide-terminal 2.9.4 **you can not use older version of platformio-ide-terminal e.g 2.9.1 or 2.9.3 with atom 1.40.1**

platformio-ide-terminal 2.9.4 works fine with Atom 140.1 in all supported OS's

To ensure this, open a terminal and type

`apm uninstall platformio-ide-terminal`

then

`apm install platformio-ide-terminal@2.9.4`

If error persists [report issue to apm](https://github.com/atom/apm/issues/new/choose) as its the tool responsible for installling addons into atom, we cant control how that works or fails. 

Thanks for understanding.

Related to https://github.com/atom/apm/issues/860 ?

**Comment by rusikf** [comment]
Ok, thanks, looks, related to apm
```
rusik@rusik-Inspiron-5547:~/Work/plexa$ apm uninstall platformio-ide-terminal
Uninstalling platformio-ide-terminal ✗                                                                         
Failed to delete platformio-ide-terminal: No package.json found at /home/rusik/.atom/packages/platformio-ide-terminal/package.json
rusik@rusik-Inspiron-5547:~/Work/plexa$ sudo apm uninstall platformio-ide-terminal
[sudo] password for rusik:                                                            
Uninstalling platformio-ide-terminal ✗                                                            
Failed to delete platformio-ide-terminal: No package.json found at /home/rusik/.atom/packages/platformio-ide-terminal/package.json
rusik@rusik-Inspiron-5547:~/Work/plexa$ sudo apm install platformio-ide-terminal@2.9.4
Installing platformio-ide-terminal@2.9.4 to /home/rusik/.atom/packages ✗ 

> node-pty-prebuilt-multiarch@0.9.0-beta21.legacy install /tmp/apm-install-dir-119915-6333-1k1ybhj.mllr/node_modules/platformio-ide-terminal/n
ode_modules/node-pty-prebuilt-multiarch
> prebuild-install || node scripts/install.js


sh: 1: prebuild-install: Permission denied
internal/modules/cjs/loader.js:596
    throw err;
    ^

Error: Cannot find module '/tmp/apm-install-dir-119915-6333-1k1ybhj.mllr/node_modules/platformio-ide-terminal/node_modules/node-pty-prebuilt-m
ultiarch/scripts/install.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
    at Function.Module._load (internal/modules/cjs/loader.js:520:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:10)
    at startup (internal/bootstrap/node.js:238:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:572:3)
Aborted (core dumped)
npm WARN enoent ENOENT: no such file or directory, open '/tmp/apm-install-dir-119915-6333-1k1ybhj.mllr/package.json'
npm WARN apm-install-dir-119915-6333-1k1ybhj.mllr No description
npm WARN apm-install-dir-119915-6333-1k1ybhj.mllr No repository field.
npm WARN apm-install-dir-119915-6333-1k1ybhj.mllr No README data
npm WARN apm-install-dir-119915-6333-1k1ybhj.mllr No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! node-pty-prebuilt-multiarch@0.9.0-beta21.legacy install: `prebuild-install || node scripts/install.js`
npm ERR! Exit status 134
npm ERR! 
npm ERR! Failed at the node-pty-prebuilt-multiarch@0.9.0-beta21.legacy install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/rusik/.atom/.apm/_logs/2019-10-15T11_52_39_811Z-debug.log
```

**Comment by the-j0k3r** [comment]
```log
>Error: Cannot find module '/tmp/apm-install-dir-119915-6333-1k1ybhj.mllr/node_modules/platformio-ide-terminal/node_modules/node-pty-prebuilt-m
ultiarch/scripts/install.js'
```
Lets try shoving this in sideways. =)

download the platformio-ide-terminal master zip https://github.com/platformio/platformio-atom-ide-terminal/archive/master.zip

Then unzip and cd inside then run

`apm i`

then run

`apm link`

try without sudo also.

if that works you have more info to report upstream.

Thanks for feedback, feel free to update with new info and linkback to any report to apm.

**Comment by myInstagramAlternative** [comment]
I have the same issue here.. 

```
Atom    : 1.41.0
Electron: 4.2.7
Chrome  : 69.0.3497.128
Node    : 10.11.0
```

```
> node-pty-prebuilt-multiarch@0.9.0-beta21.legacy install /tmp/apm-install-dir-1191010-22825-1oabssy.j0rmk/node_modules/platformio-ide-terminal/node_modules/node-pty-prebuilt-multiarch
> prebuild-install || node scripts/install.js


sh: 1: prebuild-install: Permission denied
internal/modules/cjs/loader.js:596
    throw err;
    ^

Error: Cannot find module '/tmp/apm-install-dir-1191010-22825-1oabssy.j0rmk/node_modules/platformio-ide-terminal/node_modules/node-pty-prebuilt-multiarch/scripts/install.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
    at Function.Module._load (internal/modules/cjs/loader.js:520:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:10)
    at startup (internal/bootstrap/node.js:238:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:572:3)
Aborted (core dumped)
npm WARN enoent ENOENT: no such file or directory, open '/tmp/apm-install-dir-1191010-22825-1oabssy.j0rmk/package.json'
npm WARN apm-install-dir-1191010-22825-1oabssy.j0rmk No description
npm WARN apm-install-dir-1191010-22825-1oabssy.j0rmk No repository field.
npm WARN apm-install-dir-1191010-22825-1oabssy.j0rmk No README data
npm WARN apm-install-dir-1191010-22825-1oabssy.j0rmk No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! node-pty-prebuilt-multiarch@0.9.0-beta21.legacy install: `prebuild-install || node scripts/install.js`
npm ERR! Exit status 134
npm ERR! 
npm ERR! Failed at the node-pty-prebuilt-multiarch@0.9.0-beta21.legacy install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.atom/.apm/_logs/2019-11-10T18_44_41_078Z-debug.log
```
Also, I have tried everything from above.

**Comment by the-j0k3r** [comment]
This is the problem.

```
sh: 1: prebuild-install: Permission denied
internal/modules/cjs/loader.js:596
    throw err;
    ^
```

There's nothing to be done here, permission issues shouldn't exist when things are installed to userspace.  Here, installed Atom via the deb file they provide and it works.

Also dont use flatpak or sandboxed Atom installs, it wont work as expected.

**Comment by myInstagramAlternative** [comment]
> This is the problem.
> 
> ```
> sh: 1: prebuild-install: Permission denied
> internal/modules/cjs/loader.js:596
>     throw err;
>     ^
> ```
> 
> There's nothing to be done here, permission issues shouldn't exist when things are installed to userspace. Here, installed Atom via the deb file they provide and it works.
> 
> Also dont use flatpak or sandboxed Atom installs, it wont work as expected.

I was installed from offical site atom-amd64.deb, thanks for info I will try with apt, regards!

**Comment by HearMeWhisper** [comment]
I'm also having a similar issue.

Atom    : 1.43.0
Electron: 4.2.7
Chrome  : 69.0.3497.128
Node    : 10.11.0


Distributor ID:	Ubuntu
Description:	Ubuntu 19.10
Release:	19.10
Codename:	eoan

[2020-01-29T00_21_19_436Z-debug.log](https://github.com/platformio/platformio-atom-ide-terminal/files/4125561/2020-01-29T00_21_19_436Z-debug.log)

**Comment by the-j0k3r** [comment]
Installations failures are apm domain! Try solutions above if nothing works try [terminus](https://github.com/bus-stop/terminus). If that doesnt work please complain to apm repo.

**Comment by zipy124** [comment]
> Installations failures are apm domain! Try solutions above if nothing works try [terminus](https://github.com/bus-stop/terminus). If that doesnt work please complain to apm repo.

I've been having the same issues described here and can comment that terminus does not work either.

**Comment by the-j0k3r** [comment]
terminus works with Atom 1.41.0 and newer only

**Comment by zipy124** [comment]
> terminus works with Atom 1.41.0 and newer on

This was using atom 1.44.0

**Comment by the-j0k3r** [comment]
That may very well be, but if the errror is related to apm theres nothing to be done. Generally me too reports without any actual tangible information is of little value and nothing can be deduced from such reports.

If you feel your report has more information thus more value to offer then feel free to open a bug report and provide the information requested.

**Comment by zipy124** [comment]
Ok, I've reported it to APM asking for the relevant issue to be re-opened, it was closed but testing the latest nightly shows it is still broken.

Thank you for your prompt replies.

**Comment by the-j0k3r** [comment]
Having personally tested in Windows 10/ macOS / Linux I cant say I can reproduce the issue and all works fairly well.

Glad there's a bug report, feel free to link it here

**Comment by ivankravets** [comment]
Fixed in https://github.com/platformio/platformio-atom-ide-terminal/releases/tag/v2.10.1

Please update `platformio-ide-terminal` to the latest version.
