### ISSUE TITLE
Terminal does not close upon exit when preference is set

### ISSUE THREAD

**Issue by peterloron** [platformio/platformio-atom-ide-terminal#8]
I have the terminal installed in Atom 1.6 on OS X 10.11.4. I have the preference set to close the terminal when the session exits. This does not work. I open a terminal session, type "exit", and the terminal window is still open.
##

**Comment by the-j0k3r** [comment]
Invalid, this works and its obsolete Atom and pio-ide-terminal, @ivankravets please close
