### ISSUE TITLE
Added two new lines symbols when inserting texts in Git Bash

### ISSUE THREAD

**Issue by pingshunhuangalex** [platformio/platformio-atom-ide-terminal#80]
I found the terminal will always add two new lines symbols (= tap enter twice) which I use inserting text to command functions in Git Bash. It works fine for powershell though. Is there a way to fix it? Thanks.

**Comment by michaelvasallo** [comment]
I have this issue as well. It happens when I use the Auto Run Command to launch Cmder using [this method](http://thebar.cc/atom-editor-cmder/). Here's a [gif](http://i.imgur.com/WvuPHNR.gifv) of what it looks like.

**Comment by clayms** [comment]
same problem.

I suspect it is somehow related to the linux LF versus Windows CRLF line endings.  Where Windows is adding a carriage return + line feed `CR+LF` which the various linux shells, which only use the `LF` as line endings, interpret as a separate `CR` + `LF` as two separate `LF`'s.

Windows 10 Enterprise x64
Atom 1.25.0 x64
platformio-atom-ide-terminal 2.8.1
git version 2.14.3.windows.1

Shell Override - C:\Program Files\Git\bin\bash.exe

**Comment by clayms** [comment]
Would changing this code

https://github.com/platformio/platformio-atom-ide-terminal/blob/dcd4e41ea9939d84ce9b9526610a1b184c1f8dda/lib/input-dialog.coffee#L14

to include not just `os.EOL`, which in Windows is `CRLF`, but add an option to input `LF` as the EOL character instead.

Then you would have to add a settings option to override the default `os.EOL` character with `LF`. 
After (perhaps dependent on) this :
https://github.com/platformio/platformio-atom-ide-terminal/blob/dcd4e41ea9939d84ce9b9526610a1b184c1f8dda/lib/platformio-ide-terminal.coffee#L49

What else would need to be changed?

**Comment by clayms** [comment]
This is an issue not just for linux shells on windows, but also in Powershell when connecting to a Linux machine through ssh.

**Comment by clayms** [comment]
[Node.js docs](https://nodejs.org/api/os.html#os_os_eol) say that `os.EOL` is a "string constant defining the operating system-specific end-of-line marker:"
+ `\n` on POSIX
+ `\r\n` on Windows

**Comment by clayms** [comment]
This is what fixed it for me:
replace `os.EOL` with `'\n'` in the locations shown below in the `/lib/view.coffee` file on your system.  In my Windows system, the `/lib/view.coffee` file was located in `C:\Users\my.name\.atom\packages\platformio-ide-terminal\lib`.


https://github.com/platformio/platformio-atom-ide-terminal/blob/dcd4e41ea9939d84ce9b9526610a1b184c1f8dda/lib/view.coffee#L162

becomes: ` @input "#{autoRunCommand}#{'\n'}" if autoRunCommand `

https://github.com/platformio/platformio-atom-ide-terminal/blob/dcd4e41ea9939d84ce9b9526610a1b184c1f8dda/lib/view.coffee#L163

becomes: `@input "#{command}#{'\n'}" for command in @autoRun `

https://github.com/platformio/platformio-atom-ide-terminal/blob/dcd4e41ea9939d84ce9b9526610a1b184c1f8dda/lib/view.coffee#L462

becomes: `replace(/\$\$/, '$')}#{if runCommand then '\n' else ''}" `


Not sure if *all* of those changes are necessary, but that is what I changed and it works now.  
However, I had to switch my shell to always use git-bash. After changing the code above, the `insert-selected-text` option breaks in PowerShell, but works in PowerShell when connected to a remote Linux machine with ssh.

**Comment by clayms** [comment]
Another strange behavior after the fix I did above, is that it stops working in a python interactive mode session running on the local Windows machine in git-bash.  It partially works in an IPython session running the local Windows machine in git-bash, in that a new line is added, but the code will not run until you enter a new line after a blank line.

Running a python REPL on the remote Linux machine works fine.

**Comment by clayms** [comment]
I abandoned trying to use git-bash.  Changing the code in the `/lib/view.coffee` mentioned above to append the line with '\r' and using PowerShell works in all of my cases.  

Plus, git-bash has a bunch of other glitchy problems when using as a Shell Override.

**Comment by clayms** [comment]
Another problem cropped up.  When selecting whole blocks of code and then using `ctrl+enter` to run the code from a local Windows machine in a remote Linux terminal there is an extra line inserted in between each line of code. 

This would not be a big deal except when I am trying to run a code block that contains a python `def` function.  In that case I get an `IndentationError: unexpected indent` .

Using `ctrl+enter` on single lines of code works great after I made the changes noted above regardless of that code running in a local or remote terminal.

Now... How do I replace the `'\r\n'` end-of-line character that Windows uses locally with a `'\r'` character that seems to work in both local Windows and remote Linux terminals? 

Inserting the line `replace('\r\n', '\r').`  immediately after the line below only replaces the first occurrence.  Still searching for the `coffee` script text method to replace *all* occurrences of `'\r\n'` . 

https://github.com/platformio/platformio-atom-ide-terminal/blob/dcd4e41ea9939d84ce9b9526610a1b184c1f8dda/lib/view.coffee#L461

**Comment by clayms** [comment]
Refering to the [coffeescript cookbook](https://coffeescript-cookbook.github.io/chapters/regular_expressions/replacing-substrings) led me to:

`replace(/\r\n/g, '\r').`  

which did the trick.

Now everything works as I would expect  :-)
