### ISSUE TITLE
Unable to build marlin 2.0 firmware get Terminal Error this script only runs under python 2 

### ISSUE THREAD

**Issue by Crunch69** [platformio/platformio-atom-ide-terminal#802]
Unable to build marlin 2.0 firmware get Terminal Error this script only runs under python 2 

### Steps to reproduce

1. Windows Intel 3i Laptop install Atom using v1.41.0 executable from Atom.io and followed install with the necessary additions that the install requested packages such as, platformio ide, auto complete clang v3.9.1, palette-process, llvm etc..
2. Atom install automatically installs python version 3.7.4
3. Open project added the latest SKR v1.3 Marlin 2.0 bug fix from BigTreeTech github
4. Run Auto build / PIO Build 
5. Build fails Get the following terminal error 

**_build_type build
Working 
python version 3
This script only runs under python 2_** 

6. Tried installing Python 2.7.9 using the python-2.7.9-amd64.exe  but Platformio does not see it apparently

**Expected behavior:** Build firmware for SKR v1.3 

**Actual behavior:** Platformio does not build firmware terminal states it requires Python 2

**Reproduces how often:** Everytime

### Versions

```apm  2.4.3
npm  6.2.0
node 10.2.1 x64
atom 1.41.0
python 3.7.4
git
visual studio
> atom --version v1.41.0
build 0.70.0
clang v3.9.1
apm --version 2.4.3

atom setup manager package v0.2.4
platformio ide v2.5.0
platformio ide terminal v2.10.0
palette-process v0.17.0
OS name and version: windows 10
```

**Comment by the-j0k3r** [comment]
Make sure the python2 paths are in environment and that you installed the right bitness version for python (32-bit or 64-bit)

You also dont mention if it works in external terminal like Powershell or CMD, though my guess is a paths issue.

**Comment by Crunch69** [comment]
the-j0k3r how do I create a path in environment  for python 2?

**Comment by the-j0k3r** [comment]
> the-j0k3r how do I create a path in environment for python 2?

A search engine spat this out with same question http://www.aaronstannard.com/how-to-setup-a-proper-python-environment-on-windows/

**Comment by Crunch69** [comment]
the-j0k3r thanq I would have never figured that it was a path issue

**Comment by the-j0k3r** [comment]
So its fixed?
