### ISSUE TITLE
Blinking cursor: Terminal is not responding

### ISSUE THREAD

**Issue by markel-official** [platformio/platformio-atom-ide-terminal#819]
- [ ] I have reset Atom to defaults prior to submitting report.
- [ x] I have not reset Atom to defaults prior to submitting report.
### Description

I had installed platformio-ide-terminal and tried to open terminal. But it's just empty space with blinking cursor. I reinstalled platformio-ide-terminal, but the problem stay.

### Steps to reproduce

1. Install platform-ide-terminal
2. New Terminal

**Expected behavior:** 
Open terminal

**Actual behavior:** 
Only empty terminal with blinking cursor

**Reproduces how often:** 
Always

### Versions

```
> atom --version
1.26.1
```
```
> apm --version
1.19.0
```
OS name and version: Ubuntu 18.04.1
Platformio-ide-terminal version: 2.10.0

### Additional Information

![image](https://user-images.githubusercontent.com/55998086/72678433-ec3b7580-3ab6-11ea-9381-20de2fa98c34.png)

**Comment by ghost** [comment]
I find this problem REALLY flaky.  I have uninstalled atom (Deleting .atom directory after uninstall) and reinstalled  Atom and platformio-ide-terminal; the problem comes and goes. I 'sometimes' get it to work by disabling platformio closing Atom, reopen it and then enabling platformio.  I know this is completely unscientific.  Atom 1.43.0 / Window 10.0.17763.973 / platformio 2.10.0. --- OK worked for a couple of days then quit working and could not be revived. - this is apparently a BIG problem - see post #668

**Comment by meetaig** [comment]
Had the same problem and for now removing atom and its config files, then reinstalling worked. I hope the issue doesn't come back.
See #823 for more details about my configuration.

**Comment by harmonicus** [comment]
+1 
i have the same problem,

just a blinking cursor

System : Linux/Debian
Atom : 1.44
Platformio-ide-terminal : 2.10.0

On the other hand, i run VirtualMachine, install there Atom and platormio-ide-terminal and there it works, so i suppose that is connected to some cross dependency with other packages, like f.ex. 'Script 3.25.0' 

i am quite new to this environment, so if you want to get more get informations, like non-core packages - and you probably will - please indicate short path, how to get this info. Thanks

**Comment by ghost** [comment]
+1
Not sure regarding exact time or version where problem appeared (I not used Atom before)

Today I installed Ubuntu 18.04.4 with Atom Beta (according with https://flight-manual.atom.io/getting-started/sections/installing-atom/#debian-and-ubuntu-debapt )

Installed the terminal-plus and then platformio-ide-terminal (application said that platformio-ide-terminal built for the previous version of editor, automatic rebuild completed without issues).
Unfortunately both plugins shows the mentioned above issue: just empty space with blinking cursor.

After this I made 
```
apt purge atom-beta
rm -rf ~/.atom/
apt install atom # not atom-beta
``` 
installed platformio-ide-terminal - issue remains the same.

Additional information:
```
> atom --version
Atom    : 1.48.0
Electron: 5.0.13
Chrome  : 73.0.3683.121
Node    : 12.0.0
```
```
> apm --version
apm  2.5.0
npm  6.14.5
node 10.20.1 x64
atom 1.48.0
python 2.7.17
git 2.17.1
```
Thanks

**Comment by vatsj** [comment]
I'm having the same issue; any chance it has to do with the node.js version? I'm getting 

```
$ atom --version
Atom    : 1.51.0
Electron: 5.0.13
Chrome  : 73.0.3683.121
Node    : 12.0.0
```

but 
```
$ nodejs --version
v8.10.0
```
which makes me suspect atom is using the wrong version of nodejs. @timelapserduck you have the same nodejs versions as I do, so perhaps the error is for a similar reason?

**Comment by dvictori** [comment]
Same problem here with Ubuntu 18.04.5 LTS.

Atom was installed using the official repo. I just did:

```
apt purge atom
rm -rf ~/.atom/
apt install atom
```

Installed `plataformio-ide-terminal` and all I got was a blinking cursor in an empty screen

```sh
$ atom --version
Atom    : 1.52.0
Electron: 6.1.12
Chrome  : 76.0.3809.146
Node    : 12.4.0

$ apm --version
apm  2.5.2
npm  6.14.8
node 12.4.0 x64
atom 1.52.0
python 2.7.17
git 2.17.1
```

**Comment by ivankravets** [comment]
Fixed in https://github.com/platformio/platformio-atom-ide-terminal/releases/tag/v2.10.1

Please update `platformio-ide-terminal` to the latest version.
