### ISSUE TITLE
platformio-ide-terminal is not installed in atom.

### ISSUE THREAD

**Issue by flashlogix** [platformio/platformio-atom-ide-terminal#824]
- [ ] I have reset Atom to defaults prior to submitting report.
- [ ] I have not reset Atom to defaults prior to submitting report.
### Description

platformio-ide-terminal is not installed in atom.

### Steps to reproduce

1.
2.
3.

**Expected behavior:** 

**Actual behavior:** 

**Reproduces how often:** 

### Versions

```
> atom --version

```
```
> apm --version

```
OS name and version:
Platformio-ide-terminal version:

**Comment by gautaman8** [comment]
I'm not sure what could be the actual issue. 

But please try to install nodejs LTS 12.x version. 

I used the below command to install 12.x version and it magically started working. 

**nvm install 12.16.2 
nvm use 12.16.2**
Now using node v12.16.2 (npm v6.14.4)

Then proceed with the installation. This worked for me. It's an oddity, tbh. 

I'm not sure, if this is the issue. If it truly is, the developers should probably mention these in dependencies for non-technical persons.  

Most atom package dev are under the impression that, the users should be developers and figure things out on their own.
