### ISSUE TITLE
File Dropping

### ISSUE THREAD

**Issue by MikeyWand** [platformio/platformio-atom-ide-terminal#825]
- [x] I have reset Atom to defaults prior to submitting report.
- [ ] I have not reset Atom to defaults prior to submitting report.
### Description

At my job I am on a team of front-end developers. The first laptop they gave me was a macbook from mid 2014. Atom and Atom-beta worked fine for me. I've noticed over the years that not everyone else is able to do the file dropping from the atom left side directory. We use this function multiple times a day to change directories before running gulp. On the people's laptops who it doesn't work, we realized we could still right click, copy full path, and paste.

They swapped out my old 2014 macbook for a new model with the annoyingly large trackpad. Now I have installed only 3 packages, emmet, ide-terminal, and beautify. The file dropping doesn't work on my new laptop, a MacBook Pro (15-inch, 2018).

### Steps to reproduce

1. drag a file from the left side directory to ide-terminal
2.
3.

**Expected behavior:** 
The path would appear in the terminal

**Actual behavior:** 
nothing

**Reproduces how often:** 
100% for those of us it does not work for.

### Versions

```
> atom --version
Terminal says: `bash: atom: command not found.` 1.44.0 x64
```
```
> apm --version
Terminal says: `bash: apm: command not found.`
```
OS name and version: macOS Mojave 10.14.6
Platformio-ide-terminal version: 5.0.1

**Comment by the-j0k3r** [comment]
> Platformio-ide-terminal version: 5.0.1

5.0.1?? you must be reporting this issue from another fork

try https://github.com/bus-stop/terminus or https://github.com/bus-stop/x-terminal
