### ISSUE TITLE
Scroll

### ISSUE THREAD

**Issue by Melkhouly** [platformio/platformio-atom-ide-terminal#83]
I am trying to do vertical scroll  but I cant find any properties for that 
so how can I do scroll in terminal vertical and horizontal

**Comment by Devligue** [comment]
There is no way to scroll except of the mouse wheel. Scrollbar at least? Pretty please

**Comment by Zedsquared** [comment]
Another vote for scrollbar here ... laptop trackpad user with no mousewheel.

**Comment by ghost** [comment]
Another vote for a scrollbar

**Comment by rianneogi** [comment]
One more vote for scrollbar.

**Comment by ZCLMK** [comment]
scrollbar would be the cherry

**Comment by ZCLMK** [comment]
I just realized that ctrl+ arrow(up or down) works.. to me it's even better

**Comment by nitrocode** [comment]
@ZCLMK it doesn't work on mac but 2 finger scroll on trackpad and mouse wheel works. Thanks @Devligue and @Zedsquared .

**Comment by langley** [comment]
Hate to just jump in with a "me too", but I just ran into a situation where a scroll bar would be VERY useful. So +1 on scrollbar.

**Comment by adamskrodzki** [comment]
Also same problem

**Comment by ayenewdemeke** [comment]
Same here

**Comment by ayenewdemeke** [comment]
> I just realized that ctrl+ arrow(up or down) works.. to me it's even better

Thank you

**Comment by AhmedMohamedFathi1995** [comment]
ctrl + arrows

**Comment by the-j0k3r** [comment]
duplicate of https://github.com/platformio/platformio-atom-ide-terminal/issues/9

**Comment by ahmadshaik1106** [comment]
one more vote for scrollbar(unable to scroll with touchpad)

**Comment by the-j0k3r** [comment]
Use the arrows else youre stuck as this project is dead.

The issue is closed and is a duplicate,  will lock to prevent noise in wrong thread.
