### ISSUE TITLE
apm install platformio-ide-terminal doesn't work

### ISSUE THREAD

**Issue by FlyingApe** [platformio/platformio-atom-ide-terminal#833]
- [ ] I have reset Atom to defaults prior to submitting report.
- [x] I have not reset Atom to defaults prior to submitting report.
### Description

Atom hangs on installing dependencies so I did this:
https://github.com/platformio/platformio-atom-ide/issues/2059#issuecomment-414883209

But platformio-ide-terminal does not want to install. I get:

Installing platformio-ide-terminal to /home/user/.atom/packages ✗

\> node-pty-prebuilt-multiarch@0.9.0-beta21.legacy install /tmp/apm-install-dir-12029-2562-1ehzkq1.ef37k/node_modules/platformio-ide-terminal/node_modules/node-pty-prebuilt-multiarch     
\> prebuild-install || node scripts/install.js                                                
                                                                                    
Aborted (core dumped)                                                                        
Aborted (core dumped)                                                                        
gyp: Call to 'node -e "require('nan')"' returned exit status 134 while in binding.gyp. while trying to load binding.gyp                                                                   
gyp ERR! configure error                                                                     
gyp ERR! stack Error: `gyp` failed with exit code: 1                                         
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)                                            
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)                                   
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12) 
gyp ERR! System Linux 5.3.0-18-generic                                                       
gyp ERR! command "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"                        
gyp ERR! cwd /tmp/apm-install-dir-12029-2562-1ehzkq1.ef37k/node_modules/platformio-ide-terminal/node_modules/node-pty-prebuilt-multiarch                                                  
gyp ERR! node -v v10.2.1                                                                     
gyp ERR! node-gyp -v v3.7.0                                                                  
gyp ERR! not ok                                                                              
Aborted (core dumped)                                                                        
Aborted (core dumped)                                                                        
npm WARN enoent ENOENT: no such file or directory, open '/tmp/apm-install-dir-12029-2562-1ehzkq1.ef37k/package.json'                                                                      
npm WARN apm-install-dir-12029-2562-1ehzkq1.ef37k No description                             
npm WARN apm-install-dir-12029-2562-1ehzkq1.ef37k No repository field.                       
npm WARN apm-install-dir-12029-2562-1ehzkq1.ef37k No README data                             
npm WARN apm-install-dir-12029-2562-1ehzkq1.ef37k No license field.                          
                                                                                             
npm ERR! code ELIFECYCLE                                                                     
npm ERR! errno 134                                                                           
npm ERR! node-pty-prebuilt-multiarch@0.9.0-beta21.legacy install: `prebuild-install || node scripts/install.js`                                                                           
npm ERR! Exit status 134                                                                     
npm ERR!                                                                                     
npm ERR! Failed at the node-pty-prebuilt-multiarch@0.9.0-beta21.legacy install script.       
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.                                                                                        
                                                                                             
npm ERR! A complete log of this run can be found in:                                         
npm ERR!     /home/user/.atom/.apm/_logs/2020-03-09T10_35_26_314Z-debug.log

### Versions

```
> atom --version

Atom    : 1.44.0
Electron: 4.2.7
Chrome  : 69.0.3497.128
Node    : 10.11.0

```
> apm --version

apm  2.4.3
npm  6.2.0
node 10.2.1 x64
atom 1.44.0
python 2.7.17
git 2.20.1

```
> OS name and version: 
lubuntu-19.10

**Comment by gautaman8** [comment]
Not sure if this could be the reason for installation error. 

gyp ERR! node -v v10.2.1
gyp ERR! node-gyp -v v3.7.0

Having later versions of node and node-gyp could cause some issues due to incompatibilities? 

I've the same thing.
