### ISSUE TITLE
when selecting region in terminal window with theme=solarized-dark, I can't see selection

### ISSUE THREAD

**Issue by azuruce** [platformio/platformio-atom-ide-terminal#84]

**Comment by the-j0k3r** [comment]
I cant see any issue here with this, please post a gif or video or something that shows the issue.

![test](https://user-images.githubusercontent.com/31389848/52400401-52560500-2abf-11e9-8119-b5fb1a25b5d4.gif)


Also please retest again with platformio-atom-ide-terminal 2.9.0 is using node-pty-prebuilt instead unmaintained and outdated pty.js

**Comment by the-j0k3r** [comment]
fixed by https://github.com/platformio/platformio-atom-ide-terminal/pull/424
