### ISSUE TITLE
keyboard is not working in terminal.

### ISSUE THREAD

**Issue by hellopraveen** [platformio/platformio-atom-ide-terminal#840]
- [x ] I have reset Atom to defaults prior to submitting report.
- [ ] I have not reset Atom to defaults prior to submitting report.
### Description

I am unable to use keyboard in terminal. The cursor is only blinking and the pressed key is not visible in the terminal. The cursor is blinking at the same position even after multiple key stroke. 

### Steps to reproduce

1.Installed platformio-ide-terminal
2.click on the "+" sign in the low left corner
3.type something in the terminal.

**Expected behavior:** 
The keystroke should be visible. At least the output must be there. 

**Actual behavior:** 
Nothing is happening. Even the cursor position is not changing. 

**Reproduces how often:** 
every single time

### Versions

``
> atom --version
Atom    : 1.26.1
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0
> apm --version
apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.26.1
python 2.7.17
git 2.17.1

OS name and version:`Linux distribution " Ubuntu 18.04 "
Platformio-ide-terminal version: 2.10.0

### Additional Information

![Screenshot from 2020-03-30 23-44-14](https://user-images.githubusercontent.com/45879987/77945485-720e4500-72e0-11ea-90a8-674034bfdd1d.png)

**Comment by kygwang** [comment]
Same problem as above. Similar LInux & Atom version. Commenting to Follow.

**Comment by the-j0k3r** [comment]
Try https://github.com/bus-stop/terminus
