### ISSUE TITLE
terminal not working in my ubuntu 18.04 

### ISSUE THREAD

**Issue by aslamsk** [platformio/platformio-atom-ide-terminal#842]
- [ ] I have reset Atom to defaults prior to submitting report.
- [x] I have not reset Atom to defaults prior to submitting report.
### Steps to reproduce

1.
2.
3.

**Expected behavior:** 

**Actual behavior:** 

**Reproduces how often:** 

### Versions

```
> atom --version

```
```
> apm --version

```
OS name and version:
Platformio-ide-terminal version:

**Comment by payang04** [comment]
> 
> - [ ] I have reset Atom to defaults prior to submitting report.
> - [x] I have not reset Atom to defaults prior to submitting report.
> ### Description
> 
> 
> 
> ### Steps to reproduce
> 
> 1.
> 2.
> 3.
> 
> 
> **Expected behavior:** 
> 
> 
> **Actual behavior:** 
> 
> 
> **Reproduces how often:** 
> 
> 
> ### Versions
> 
> 
> ```
> > atom --version
> 
> ```
> ```
> > apm --version
> 
> ```
> OS name and version:
> Platformio-ide-terminal version:
> 
> 
> ### Additional Information
> 
>
