### ISSUE TITLE
spam

### ISSUE THREAD

**Issue by ritik23-coder** [platformio/platformio-atom-ide-terminal#848]
- [x] I have reset Atom to defaults prior to submitting report.
- [ ] I have not reset Atom to defaults prior to submitting report.
### Steps to reproduce

1.
2.
3.

**Expected behavior:** 

**Actual behavior:** 

**Reproduces how often:** 

### Versions

```
> atom --version

```
```
> apm --version

```
OS name and version:
Platformio-ide-terminal version:

**Comment by srilekha201created** [comment]
atom version 1.45.0
os name and version name:windows 64 bit operating system
platformio-ide-terminal version:2.10.0
![isue1](https://user-images.githubusercontent.com/63400385/79107782-a4b14680-7d92-11ea-85c4-cfdc72aa1772.PNG)

**Comment by srilekha201created** [comment]
i got this issuue how i can resolve it

**Comment by ghost** [comment]
I could not get the terminal working in Atom, either. Interesting, it would work sometimes, then finally gave up the ghost. (weird eh!) If your are doing the same course as I am you do not need the terminal window; it is convenient but not necessary. Simply use an external command prompt.

**Comment by the-j0k3r** [comment]
This is HOW **not** to report issues.
