### ISSUE TITLE
how can i set Atom to default

### ISSUE THREAD

**Issue by KingMalikFahad** [platformio/platformio-atom-ide-terminal#849]
- [ ] I have reset Atom to defaults prior to submitting report.
- [ ] I have not reset Atom to defaults prior to submitting report.
### Steps to reproduce

1.
2.
3.

**Expected behavior:** 

**Actual behavior:** 

**Reproduces how often:** 

### Versions

```
> atom --version

```
```
> apm --version

```
OS name and version:
Platformio-ide-terminal version:

**Comment by the-j0k3r** [comment]
https://flight-manual.atom.io/
