### ISSUE TITLE
 platformio-ide-terminal is not installing in atom and generated error.

### ISSUE THREAD

**Issue by 164168AhmedSohail** [platformio/platformio-atom-ide-terminal#857]
- [ ] I have reset Atom to defaults prior to submitting report.
- [ ] I have not reset Atom to defaults prior to submitting report.
### Steps to reproduce

1.
2.
3.

**Expected behavior:** 

**Actual behavior:** 

**Reproduces how often:** 

### Versions

```
> atom --version

```
```
> apm --version

```
OS name and version:
Platformio-ide-terminal version:

**Comment by Mirdhini** [comment]
I cannot reset Atom to defaults prior to submtting report.
Expected behavior: Platformio-ide-terminal is to be installed.
Actual behavior: Plaformio-ide-terminal is not installing
Atom version 1.47.0
Os name and version: Windows 10
Platformio-ide-terminal version: 2.10.0

**Comment by the-j0k3r** [comment]
use https://github.com/bus-stop/terminus or https://github.com/bus-stop/x-terminal
