### ISSUE TITLE
How to add font? 

### ISSUE THREAD

**Issue by viktor-yang** [platformio/platformio-atom-ide-terminal#86]
I need powerline font in my iTerm theme, but in atom ide terminal is't support.

And it also is't support Chinese .

Thanks for help.

**Comment by ghost** [comment]
good question, would like to know the same.

**Comment by redeemefy** [comment]
Same here.

**Comment by Betree** [comment]
Duplicate of #33 

You can change the font from the "Font Family" entry in the config. Setting this value fixed powerline for me :

> PowerlineSymbols, Monospace

**Comment by nikolaussucher** [comment]
Install the font package; Go to Packages, find Platform, click on Settings, scroll down to find Font Family,  enter:  Hack
Now all symbols show up in my powerline

**Comment by ghost** [comment]
This is how I set it up on a mac after some trial and error:

```
brew tap caskroom/fonts
brew cask install font-hack-nerd-font
```

In Atom settings: Packages / Platformio Ide Terminal

Font Family: `Hack Nerd Font, Monospace`

The icons showed up immediately without needing to relaunch the terminal

**Comment by the-j0k3r** [comment]
duplicate of #33
