### ISSUE TITLE
Terminal not working

### ISSUE THREAD

**Issue by E-Wickliffe** [platformio/platformio-atom-ide-terminal#860]
- [ ] I have reset Atom to defaults prior to submitting report.
- [x] I have not reset Atom to defaults prior to submitting report.
### Steps to reproduce

1.
2.
3.

**Expected behavior:** 

**Actual behavior:** 

**Reproduces how often:** 

### Versions

```
> atom --version

```
```
> apm --version

```
OS name and version:
Platformio-ide-terminal version:

**Comment by stutzzzz** [comment]
can install but doesn't work for me Ubuntu 20.04 Atom version 1.47.0

**Comment by josark2005** [comment]
same problem
win10, Atom version 1.47.0

**Comment by bluemalkin** [comment]
Same issue.
MacOS
Atom    : 1.47.0

**Comment by ricosandyca** [comment]
Same here...
I got a same issue when i updated atom to the latest version.
There's no significant error, but i just get blank terminal on it

**Comment by bogsanthosh** [comment]
even for me its same in windows machine, after upgrading to latest atom version i am getting blank terminal on it

**Comment by stutzzzz** [comment]
moved to atom-ide-terminal works for me looks to be a fork of this.

**Comment by bogsanthosh** [comment]
using >apm install atom-ide-terminal in windows throwing an error.Due to proxy not able to install in atom. Where as platformio is installing using apm.How can install atom-ide without issues?

**Comment by stutzzzz** [comment]
you have to uninstall the platformio one first so I uninstall platformio then use apm install for atom-ide-terminal then open atom I was able to launch a terminal This was on pop 20.04 so not sure if it works on windows.

**Comment by f9rajiv** [comment]
just uninstall and re install ,it this will fix the error in windows

**Comment by langley** [comment]
Ran into the same problem on ubuntu 16.04. I uninstalled and the installed atom-ide-terminal, which had a similar "incompatibility bug" as indicated by the little red 'bug' in the footer of atom. Once I rebuilt that atom-ide-terminal works. Note: this was the same pattern I ran into with the platform-ide-terminal, but when I rebuilt for that, the bug indicator went away, but the terminal did not work. 

One final note; I believe the incompatibility reported there was a problem either with node.js or it's 'module' capabilities. I have a v69 installed and the platform-ide-terminal wanted v70. Having said that, a rebuild with the installed v69 component resulted in a working installation.

**Comment by rpalloni** [comment]
Ubuntu 20.04
Atom 1.47
Same problem. Opens with only a blank cursor where you cannot type.
And you cannot even  **apm install platformio-ide-terminal@2.9.3**

![Screenshot from 2020-05-22 18-54-55](https://user-images.githubusercontent.com/17080117/82691198-d1902d80-9c5d-11ea-8769-9e4121932b74.png)

**Comment by ejuniorls** [comment]
it used to work but suddenly stoped working
I removed and reinstalled but the terminal does not open properly
ubuntu 20.04

![Captura de tela de 2020-05-22 14-58-15](https://user-images.githubusercontent.com/19741532/82696169-e01a1d00-9c3c-11ea-8fb3-9c22e1ded376.png)

**Comment by attisbarros** [comment]
> just uninstall and re install ,it this will fix the error in windows

Reinstalling it worked on Win 10.

**Comment by Pablo-MC** [comment]
Solution:

Uninstall and install https://atom.io/packages/platformio-ide-terminal

**Comment by FarasatN** [comment]
help me ubuntu 18.04 platformio-ide-terminal not working

**Comment by Nootaku** [comment]
> Solution:
> 
> Uninstall and install https://atom.io/packages/platformio-ide-terminal

This solution does not work on Ubuntu 18.04 Bionic Beaver.
My output is identical to @rpalloni

**Comment by Alexartur** [comment]
Ubuntu 20.04 - platformio-ide-terminal - only a blank cursor where you cannot type

~$ apm --version
apm  2.4.5
npm  6.2.0
node 10.2.1 x64
atom 1.47.0
python 2.7.18rc1
git 2.25.1

**Comment by mrM71** [comment]
same issue, atom 1.47

**Comment by Alexartur** [comment]
Can we have some updates?

**Comment by lucian777** [comment]
Doesn't work for me as well...
apm  2.4.5
npm  6.2.0
node 10.2.1 x64
atom 1.47.0
python 2.7.18rc1
git 2.25.1

**Comment by vnosis** [comment]
> you have to uninstall the platformio one first so I uninstall platformio then use apm install for atom-ide-terminal then open atom I was able to launch a terminal This was on pop 20.04 so not sure if it works on windows.

This worked for me!!!! I'm running ubuntu 18.0x

**Comment by thiagodma** [comment]
Same issues here! Any solutions?

**Comment by Alexartur** [comment]
Deleted all other terminal packages and install terminus and it's working fine.

OS Ubuntu 20.04
~$ apm --version
apm  2.4.5
npm  6.2.0
node 10.2.1 x64
atom 1.47.0
python 2.7.18rc1
git 2.25.1

**Comment by mrM71** [comment]
> Deleted all other terminal packages and install terminus and it's working fine.
> 
> OS Ubuntu 20.04
> ~$ apm --version
> apm 2.4.5
> npm 6.2.0
> node 10.2.1 x64
> atom 1.47.0
> python 2.7.18rc1
> git 2.25.1

just did, working well
thanks mate

**Comment by Alexartur** [comment]
> > Deleted all other terminal packages and install terminus and it's working fine.
> > OS Ubuntu 20.04
> > ~$ apm --version
> > apm 2.4.5
> > npm 6.2.0
> > node 10.2.1 x64
> > atom 1.47.0
> > python 2.7.18rc1
> > git 2.25.1
> 
> just did, working well
> thanks mate

not at all

**Comment by lucian777** [comment]
> Doesn't work for me as well...
> apm 2.4.5
> npm 6.2.0
> node 10.2.1 x64
> atom 1.47.0
> python 2.7.18rc1
> git 2.25.1

Fix for terminal not loading etc:
1.--Uninstall--
Terminal
which atom ( get the installation location, could be  /usr/local/bin/atom or  /usr/bin/atom)
sudo rm /usr/local/bin/atom 
sudo rm /usr/local/bin/apm
rm -rf ~/atom
rm -rf ~/.atom
rm -rf ~/.config/Atom-Shell
sudo rm -rf /usr/local/share/atom/

2.--Install--
apm install platformio-ide@2.3.1
apm install platformio-ide-debugger@1.2.6
apm install platformio-ide-terminal@2.9.1

3. Disable wifi/internet
4. Open Atom - Edit - Preferences - Disable = Automatically update
5. PlatformioIO menu -Settings - PlatformioIO IDE - Disable = Automatically update Plaformio IDE
6. Enable wif/internet
7. Open Atom

**Comment by bassamanator** [comment]
I get a blank terminal window with a blinking cursor. 
Happens everytime.
Have tried uninstalling/reinstalling from within atom.
Linux 5.6.15-1-MANJARO KDE.
Atom installed via package manager.
platformio-ide-terminal 2.10.0
```
$ atom --version
Atom    : 1.47.0
Electron: 5.0.13
Chrome  : 73.0.3683.121
Node    : 12.0.0

$ apm --version
apm  2.5.0
npm  6.14.5
node 14.3.0 x64
atom 1.47.0
python 3.8.3
git 2.27.0
```
Other terminal packages:
-terminal-plus also **not** working
-termination **working**

**Comment by Vagrantin** [comment]
Looks like duplicate of #668

**Comment by nicolaycamacho** [comment]
> > > Deleted all other terminal packages and install terminus and it's working fine.
> > > OS Ubuntu 20.04
> > > ~$ apm --version
> > > apm 2.4.5
> > > npm 6.2.0
> > > node 10.2.1 x64
> > > atom 1.47.0
> > > python 2.7.18rc1
> > > git 2.25.1
> > 
> > 
> > just did, working well
> > thanks mate
> 
> not at all

Installing terminus was the only solution for me. Thanks mate.

**Comment by the-j0k3r** [comment]
Try https://github.com/bus-stop/terminus
