### ISSUE TITLE
not working ide-terminal after update atom to 1.47.0 in Ubuntu 16.04

### ISSUE THREAD

**Issue by jxxx-oldblr** [platformio/platformio-atom-ide-terminal#862]
- [ ] I have reset Atom to defaults prior to submitting report.
- [ ] I have not reset Atom to defaults prior to submitting report.
### Description
not working ide-terminal after update atom to 1.47.0 in Ubuntu 16.04

not working ide-terminal after update atom to 1.47.0 in Ubuntu 16.04

### Steps to reproduce

1. not working ide-terminal after update atom to 1.47.0 in Ubuntu 16.04
2. not working ide-terminal after update atom to 1.47.0 in Ubuntu 16.04
3. not working ide-terminal after update atom to 1.47.0 in Ubuntu 16.04

not working ide-terminal after update atom to 1.47.0 in Ubuntu 16.04
**Expected behavior:** 

not working ide-terminal after update atom to 1.47.0 in Ubuntu 16.04
**Actual behavior:** 

not working ide-terminal after update atom to 1.47.0 in Ubuntu 16.04
**Reproduces how often:** 

not working ide-terminal after update atom to 1.47.0 in Ubuntu 16.04
### Versions

```
> atom --version

```
```
> apm --version

```
OS name and version:
Platformio-ide-terminal version:

**Comment by asiloisad** [comment]
the same problem in ms windows 10 x64

**Comment by sandeepsreedeep** [comment]
same issue for ms windows 10
everytime restart my pc I have to reinstall the package and it is taking a long time

**Comment by ffais** [comment]
Same issue for ubuntu 19.10

**Comment by jxxx-oldblr** [comment]
https://atom.io/packages/atom-ide-terminal 
atom-ide-terminal  good working )

**Comment by BaldrOdinson** [comment]
The same for Windows 10 64 and 2.10.0 version.
Started, but stay without invitation string, black field with a blinking rectangle on top left.

**Comment by RudrakshKashyap** [comment]
![Screenshot from 2020-05-22 19-02-25](https://user-images.githubusercontent.com/44721843/82673758-ea99de00-9c5f-11ea-8d71-9c99c6233524.png)
I got this same error with atom-ide-terminal and after i rebuild the package the terminal stopped working properly.
Below is the screeshot of pio ide terminal.
![Screenshot from 2020-05-22 19-15-43](https://user-images.githubusercontent.com/44721843/82674662-49ac2280-9c61-11ea-81b9-826f2a6ca9dd.png)
Ubuntu 19.10
Platformio-ide-terminal version 2.10.0
apm  2.4.5
npm  6.2.0
node 10.2.1 x64
atom 1.47.0

**Comment by OseiasMzM** [comment]
Same problem with ubuntu 18.04 and Atom 1.47.

**Comment by RudrakshKashyap** [comment]
For now i've installed terminus which is working fine. [https://atom.io/packages/terminus](url)

**Comment by chima-okwara** [comment]
Same here, running Mint 19.3 x86_64.

**Comment by jwerre** [comment]
Rebuild the Package and restart Atom. That should solve the problem.

**Comment by chima-okwara** [comment]
I already did that. I even uninstalled and reinstalled it. Nothing seemed
to change.

**Comment by stephdl** [comment]
For now I use `terminus` it works well

**Comment by OseiasMzM** [comment]
For now I'm using VSCode, but I hope platformio-terminal will work again.

**Comment by Yoshinosido** [comment]
After atom upgrade to 1.47.0 have same problem.
OS:Windows 10 1909

**Comment by chadhumphrey** [comment]
upgrade to 1.47.0, now platformio isn't working. 
Ubuntu 20.04

**Comment by getricj** [comment]
Same here problem after upgrading to 1.47.0
OS: Manjaro Gnome 20.0.2

**Comment by wurmtal868** [comment]
As long as the platformio-ide-terminal is broken, disable it and install terminus instead. The terminal will open, when you click on the bottom status bar "+" sign or use "CTRL-`" kotkeys. If you need a serial terminal you can start miniterm.py in the command line.

**Comment by christalk** [comment]
_Sorry, my answer was not about PlatformIO IDE Terminal._

**Comment by christalk** [comment]
New Version Atom 1.48.0  
v1.48.0 (2020-06-10)
https://atom.io

**Comment by wurmtal868** [comment]
Same for me, Atom 1.48.0 did not fix the terminal

**Comment by wurmtal868** [comment]
Launching atom with sudo is not a good idea. First of all it will refuse to run without "--no-sandbox".
If you use this extra option, root will take over all user configuration files that get touched during the session. When you then try to run atom without sudo you won't be able to access the files that have been touched by sudo, which can lead to strange behavior.

**Comment by christalk** [comment]
OYou are absolutely right, and I will correct or delete this reference in my description above. I totally agree that using the sudo command was absolutely not appropriate. And that indeed it will modify or create "root" rights . But it was only an attempt.

Did you try a second instance with command line without sudo, or with icon ?

**Comment by wtmatthias** [comment]
I'm on OS Catalina 10.15.3. Having the same issue with Atom 1.48.0 and platformio-ide-terminal 2.10.0.

I uninstalled 2.10.0 and rolled back to 2.9.0 and that works (for now).

`apm uninstall platformio-ide-terminal`
`apm install platformio-ide-terminal@2.9.0`

**Comment by christalk** [comment]
Thanks wtmatthias,

It sounds the good answer, nowadays (at the moment)
See what ashkanahrabi commented 4 days ago •
_I've found the fix.
Try downgrading Platformio-ide-terminal to 2.9.0_

apm uninstall platformio-ide-terminal
apm install platformio-ide-terminal@2.9.0
https://github.com/platformio/platformio-atom-ide-terminal/issues/872#issuecomment-643603517

**Comment by the-j0k3r** [comment]
Try https://github.com/bus-stop/terminus
