### ISSUE TITLE
i want to change the path directory of atom terminal by changing the drive

### ISSUE THREAD

**Issue by priyankajain111** [platformio/platformio-atom-ide-terminal#863]
- [x] I have reset Atom to defaults prior to submitting report.
- [ ] I have not reset Atom to defaults prior to submitting report.
### Steps to reproduce

1.
2.
3.

**Expected behavior:** 

**Actual behavior:** 

**Reproduces how often:** 

### Versions

```
> atom --version

```
```
> apm --version

```
OS name and version:
Platformio-ide-terminal version:

**Comment by the-j0k3r** [comment]
these tickets ignoring the issue template will be closed.
