### ISSUE TITLE
platformio-ide-terminal not installing

### ISSUE THREAD

**Issue by SeeratNissar** [platformio/platformio-atom-ide-terminal#867]
- [x] I have reset Atom to defaults prior to submitting report.
- [x] I have not reset Atom to defaults prior to submitting report.
### Description
I am not able to install platformio-ide-terminal I want to start coding with python for that I require that but its not getting installed I tried to install it more than 20 times

### Steps to reproduce

1.
2.
3.

**Expected behavior:** 

**Actual behavior:** 

**Reproduces how often:** 

### Versions

```
> atom --version

```
```
> apm --version

```
OS name and version:
Windows 10
Platformio-ide-terminal version:

**Comment by the-j0k3r** [comment]
Ignoring the details gets the issue closed
