### ISSUE TITLE
Option to use Alt/Option key as meta key

### ISSUE THREAD

**Issue by blockloop** [platformio/platformio-atom-ide-terminal#87]
In OSX terminal, and iTerm2 there is the ability to use the alt/option key as the meta key. 

From iTerm2 website:

> Q: How do I make the option/alt key act like Meta or send escape codes?
> A: Go to Preferences->Profiles tab. Select your profile on the left, and then open the Keyboard tab. At the bottom is a set of buttons that lets you select the behavior of the Option key. For most users, Esc+ will be the best choice.

Could we have this option for this package?

I would like to use ALT+B/ALT+F to move the cursor one word back/forward, respectively. Right now ESC, B and ESC, F works.

With alt I get the following characters 

![image](https://cloud.githubusercontent.com/assets/3022496/19458144/ec9ce7b4-948f-11e6-9f75-13fd38707775.png)

**Comment by mrpotatoes** [comment]
I am also used to the emacs commands and this would be an extremely useful option.

**Comment by 7AC** [comment]
Is there any workaround for this? I'm looking at [lib/view.coffee](https://github.com/platformio/platformio-atom-ide-terminal/blob/master/lib/view.coffee) but I don't see anything obvious I can use in [keymaps/platform-ide-terminal.cson](https://github.com/platformio/platformio-atom-ide-terminal/blob/master/keymaps/platformio-ide-terminal.cson).
