### ISSUE TITLE
platformio-ide-terminal package installed. It show empty console with blinking cursor... Atom is newly installed and all packages are latest version

### ISSUE THREAD

**Issue by eaakashmaurya** [platformio/platformio-atom-ide-terminal#872]
- [ ] I have reset Atom to defaults prior to submitting report.
- [ ] I have not reset Atom to defaults prior to submitting report.
### Steps to reproduce

1.
2.
3.

**Expected behavior:** 

**Actual behavior:** 

**Reproduces how often:** 

### Versions

```
> atom --version

```
```
> apm --version

```
OS name and version:
Platformio-ide-terminal version:

**Comment by christalk** [comment]
Hello,

Which OS name and version ? please.
Please see here, if it's the same (1.47.0 and now 1.48.0 on Ubuntu 16.04 LTS)

Try to launch Atom a second time, as explained in this post
https://github.com/platformio/platformio-atom-ide-terminal/issues/862

https://github.com/platformio/platformio-atom-ide-terminal/issues/862#issuecomment-642213569"

**Comment by eaakashmaurya** [comment]
OS :- Ubuntu 18.04
Atom version :- 1.48.0
Platformio-ide-terminal :- 2.10.0
Even tried vk-terminal but same error...
Tried uninstalling and reinstalling both atom and the package, but no result

**Comment by christalk** [comment]
Thanks. 
And sorry, my answer was about Atom. I don't use platformio-ide.
I would say I use "Vanilla" Atom, if you know what I mean.

Did you try to launch a second instance of Atom (sorry,  platformio-ide) in addition to the first one?
What happens next ?

**Comment by eaakashmaurya** [comment]
Yeah, I did nothing happened...
I am using VS code for the timebeing!

**Comment by ashkanahrabi** [comment]
I've found the fix.
Try downgrading Platformio-ide-terminal to 2.9.0

`apm uninstall platformio-ide-terminal`
`apm install platformio-ide-terminal@2.9.0`

**Comment by OseiasMzM** [comment]
@ashkanahrabi thank you friend, you helped me a lot :)

**Comment by PaulCoral** [comment]
> I've found the fix.
> Try downgrading Platformio-ide-terminal to 2.9.0
> 
> `apm uninstall platformio-ide-terminal`
> `apm install platformio-ide-terminal@2.9.0`

Downgrading to 2.9.0 also worked for me thanks a lot. (However I got this annoying notification to update the package)

**Comment by paulanand95** [comment]
@ashkanahrabi you are a god.

**Comment by arghyadipchak** [comment]
> I've found the fix.
> Try downgrading Platformio-ide-terminal to 2.9.0
> 
> `apm uninstall platformio-ide-terminal`
> `apm install platformio-ide-terminal@2.9.0`

Hey, that was great worked perfectly. Thank You so much.
Also I found out that platformio-ide-terminal works great upto version 2.9.3 (I found it while testing all the 2.9.x versions).
But the blinking issue happens as soon as you upgrade it to any higher version (like 2.9.4 or 2.10.0).
Is there a permanent fix?? I tried everything I found of github but nothing helped other than downgrading it.

And, here are my specs:
- OS: Parrot GNU/Linux 4.10 (x86-64)
- Kernel: Linux 5.6.0-2parrot1-amd64
- Atom: 1.48.0
- apm: 2.5.0
- npm: 6.14.5
- node: 10.20.1 x64

**Comment by ashkanahrabi** [comment]
@arghyadipchak 
As far as I know, this issue is caused by a mismatch of the electron version which Atom and platformio-ide-terminal are developed by. If this is the case, there should be no permanent fix until it is fixed by platformio-ide-terminal.

**Comment by monsoft** [comment]
> I've found the fix.
> Try downgrading Platformio-ide-terminal to 2.9.0
> 
> `apm uninstall platformio-ide-terminal`
> `apm install platformio-ide-terminal@2.9.0`

Works for me as well.

Thanks :)

**Comment by saket-sgr** [comment]
The issue can be seen from v2.9.4. Till v2.9.3, it's working fine. So downgrading it to v2.9.3 is what can be done as of now.
p.s.: sorry for bad english :`)

**Comment by arghyadipchak** [comment]
> The issue can be seen from v2.9.4. Till v2.9.3, it's working fine. So downgrading it to v2.9.3 is what can be done as of now.

Yes, exactly. But we need a permanent fix for this. Devs please look into this matter..

**Comment by pronoym99** [comment]
I currently have version 2.10.0 . I think this issue has been rectified recently and finally. 😀😀

**Comment by wurmtal868** [comment]
Did someone try atom version 1.49.0?

**Comment by pronoym99** [comment]
@wurmtal868 Yes my editor got updated today to 1.49.0 and the Platform Io terminal (v 2.10.0) is working properly

**Comment by the-j0k3r** [comment]
Try https://github.com/bus-stop/terminus

this ticket will be closed and locked because no one provides any information to help troubleshoot.
