### ISSUE TITLE
Atom terminal not working in fresh install, Ubuntu 18.04

### ISSUE THREAD

**Issue by adroitashish** [platformio/platformio-atom-ide-terminal#874]
- [ ] I have reset Atom to defaults prior to submitting report.
- [ ] I have not reset Atom to defaults prior to submitting report.
### Description

Terminal take no inputs and cursor just keep on blinking.

### Steps to reproduce

1. Install atom in your ubuntu system.
2. Open atom and navigate to preferences
3. Choose packages and install platformio-ide-terminal version 2.10.0
4. After installation observe the terminal doen't show up current directory and take no inputs from the user, Only the cursor keeps blinking.

**Expected behavior:** 
It should show my current directory.

**Actual behavior:** 
It is blank and cursor just blinks

**Reproduces how often:** 
Everytime

### Versions

```
> atom --version: 1.47.0

```
```
> apm --version: 2.4.5

```
OS name and version: Ubuntu 18.04
Platformio-ide-terminal version: 2.10.0

**Comment by freecre** [comment]
I have the same problem

**Comment by ashkanahrabi** [comment]
Same issue with me. Exactly the same versions as mentioned

**Comment by ashkanahrabi** [comment]
I've found the fix.
Try downgrading Platformio-ide-terminal to 2.9.0

`apm uninstall platformio-ide-terminal`
`apm install platformio-ide-terminal@2.9.0`

**Comment by adroitashish** [comment]
![Screenshot from 2020-06-13 17-07-27](https://user-images.githubusercontent.com/19406562/84567947-d302d080-ad99-11ea-8357-a13aba5eb651.png)
Well it didn't work for me. Can you help me? It give some error. I have attached it below.

> node-pty-prebuilt@0.7.6 install /tmp/apm-install-dir-2020513-13376-clwjo6.3wcrk/node_modules/platformio-ide-terminal/node_modules/node-pty-prebuilt
> prebuild-install || node scripts/install.js


prebuild-install WARN install No prebuilt binaries found (target=5.0.13 runtime=electron arch=x64 libc= platform=linux)
gyp ERR! configure error 
gyp ERR! stack Error: Command failed: /snap/atom/252/usr/share/atom/resources/app/apm/bin/python-interceptor.sh -c import platform; print(platform.python_version());
gyp ERR! stack /snap/atom/252/usr/share/atom/resources/app/apm/bin/python-interceptor.sh: line 40: exec: python: not found
gyp ERR! stack 
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:291:12)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:961:16)
gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:380:11)
gyp ERR! stack     at Socket.emit (events.js:182:13)
gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:596:12)
gyp ERR! System Linux 5.3.0-59-generic
gyp ERR! command "/snap/atom/252/usr/share/atom/resources/app/apm/bin/node" "/snap/atom/252/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--build_v8_with_gn=false"
gyp ERR! cwd /tmp/apm-install-dir-2020513-13376-clwjo6.3wcrk/node_modules/platformio-ide-terminal/node_modules/node-pty-prebuilt
gyp ERR! node -v v10.2.1
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/tmp/apm-install-dir-2020513-13376-clwjo6.3wcrk/package.json'
npm WARN apm-install-dir-2020513-13376-clwjo6.3wcrk No description
npm WARN apm-install-dir-2020513-13376-clwjo6.3wcrk No repository field.
npm WARN apm-install-dir-2020513-13376-clwjo6.3wcrk No README data
npm WARN apm-install-dir-2020513-13376-clwjo6.3wcrk No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-pty-prebuilt@0.7.6 install: `prebuild-install || node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-pty-prebuilt@0.7.6 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/adroitashish/.atom/.apm/_logs/2020-06-13T11_34_59_314Z-debug.log

**Comment by ashkanahrabi** [comment]
@adroitashish Just upgrade your Atom to 1.48.0 too.
This is because Atom version 1.47.0 is not compatible with the Electron version as mentioned in the error description.

Make sure that Atom version is 1.48.0 and Platformio-ide-terminal version is 2.9.0

**Comment by the-j0k3r** [comment]
See and read https://github.com/platformio/platformio-atom-ide-terminal/issues/668#issuecomment-633130699

**Comment by EvilKunt** [comment]
guys atom version 1.48.0 , and  Platformio-ide-terminal version is 2.9.0 it worked for me .. 
OS Ubuntu 18.04 . 
Thanks @ashkanahrabi

**Comment by homberghp** [comment]
It works in atom 1.54.0 and after apm install platformio-ide-terminal on ubuntu 20.04

**Comment by UziTech** [comment]
This package is no longer maintained. Please uninstall platformio-ide-terminal and install either [terminus](https://atom.io/packages/terminus) or [x-terminal](https://atom.io/packages/x-terminal)
