### ISSUE TITLE
It isn't work in my atom

### ISSUE THREAD

**Issue by ahmadrezash** [platformio/platformio-atom-ide-terminal#877]
- [ ] I have reset Atom to defaults prior to submitting report.
- [ ] I have not reset Atom to defaults prior to submitting report.
### Steps to reproduce

1. It can't work on last version of atom downloaded from atom website. It gives me just a blank pane.
It's on Ubuntu 20.4

**Expected behavior:** 

**Actual behavior:** 

**Reproduces how often:** 

### Versions

```
> atom --version

```
```
> apm --version

```
OS name and version:
Platformio-ide-terminal version:

**Comment by the-j0k3r** [comment]
@ahmadrezash see and read https://github.com/platformio/platformio-atom-ide-terminal/issues/668#issuecomment-633130699

Also this ticket contains no helpful info so closing.
