### ISSUE TITLE
Change position of terminal from bottom to right

### ISSUE THREAD

**Issue by ayushdiagarwal** [platformio/platformio-atom-ide-terminal#878]
- [x] I have reset Atom to defaults prior to submitting report.
### Description

Is there a way to change the position of terminal from bottom to right as at the bottom the teriminal gets in the view of the code.

### Versions

```
> atom --version
Atom    : 1.48.0
Electron: 5.0.13
Chrome  : 73.0.3683.121
Node    : 12.0.0
```
```
> apm --version
apm  2.5.0
npm  6.14.5
node 10.20.1 x64
atom 1.48.0
python 2.7.18rc1
git 2.25.1
```
OS name and version: Ubuntu 20.04
Platformio-ide-terminal version:2.9.0

**Comment by the-j0k3r** [comment]
Not this project its no longer developed

You want https://github.com/bus-stop/terminus and read https://github.com/bus-stop/terminus/issues/64
