### ISSUE TITLE
2.10 Version Does Not Work (Atom 1.48.0) run on Arch

### ISSUE THREAD

**Issue by ejsergeev** [platformio/platformio-atom-ide-terminal#881]
- [x] I have reset Atom to defaults prior to submitting report.
- [x] I have not reset Atom to defaults prior to submitting report.
### Description

Terminal version 2.10 does not work. 2.9 works well.

### Steps to reproduce

1. Install Atom
2. Install terminal
3. Not possible to launch

**Expected behavior:** 

I expected terminal to appear on the bottom bar with + sign as it was before or to be able to launch it with ctr+`

**Actual behavior:** 

In reality there is no more + sign and ctr+` does not launch terminal

**Reproduces how often:** 

100%

### Versions

2.10

> atom --version

Atom    : 1.48.0
Electron: 5.0.13
Chrome  : 73.0.3683.121
Node    : 12.0.0

> apm --version

apm  2.5.0
npm  6.14.5
node 10.20.1 x64
atom 1.48.0
python 3.8.3
git 2.27.0

OS name and version: Manjaro Linux 20.0.3 Lysia

Platformio-ide-terminal version: 2.10

**Comment by the-j0k3r** [comment]
Try https://github.com/bus-stop/terminus
