### ISSUE TITLE
In version 2.10 Terminal is not working

### ISSUE THREAD

**Issue by abhinavprkash** [platformio/platformio-atom-ide-terminal#882]
- [ ] I have reset Atom to defaults prior to submitting report.
- [ ] I have not reset Atom to defaults prior to submitting report.
### Description

**Expected behavior:** 

**Actual behavior:** 

**Reproduces how often:** 

### Versions

```
> atom --version

```
```
> apm --version

```
OS name and version:
Platformio-ide-terminal version:

**Comment by ijunaid8989** [comment]
@the-j0k3r You seems to be very very rude, thanks for your comments with condescending good luck.

**Comment by the-j0k3r** [comment]
Purposefully ignoring the requested information gets the ticket closed.
