### ISSUE TITLE
Platformio-ide-terminal does not work in Atom

### ISSUE THREAD

**Issue by david-roark** [platformio/platformio-atom-ide-terminal#883]
- [x] I have reset Atom to defaults prior to submitting report.
- [ ] I have not reset Atom to defaults prior to submitting report.
### Steps to reproduce

1. Open Atom
2. Open platformio-ide-terminal
3. type `cd /media`

**Expected behavior:** 
Change directory to media

**Actual behavior:** 
The interface blank and I can not type anything (can not do anything)

**Reproduces how often:** 
All the time I open Atom, it always does not work

### Versions

```
> atom --version: 
Atom    : 1.49.0
Electron: 5.0.13
Chrome  : 73.0.3683.121
Node    : 12.0.0

```
```
> apm --version
apm  2.5.0
npm  6.14.5
node 10.20.1 x64
atom 1.49.0
python 2.7.18rc1
git 2.27.0

```
OS name and version: Ubuntu 20.04 LTS
Platformio-ide-terminal version: 2.10.0

### Additional Information

![Screenshot from 2020-07-16 14-58-55](https://user-images.githubusercontent.com/67179718/87643368-fd6af380-c774-11ea-810d-1f92b9ad7025.png)

**Comment by omitrowski** [comment]
same issue here. Tried to install atom via `snap` and directly via `.deb`. Does not help; terminal does not work.

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04 LTS
Release:	20.04
Codename:	focal

$ atom --version
Atom    : 1.49.0
Electron: 5.0.13
Chrome  : 73.0.3683.121
Node    : 12.0.0

$ apm --version
apm  2.5.0
npm  6.14.5
node 10.20.1 x64
atom 1.49.0
python 2.7.18rc1
git 2.25.1
```

![image](https://user-images.githubusercontent.com/19892452/87709146-1d65db80-c7a4-11ea-9243-f45e4bff8ebd.png)
![image](https://user-images.githubusercontent.com/19892452/87709220-3a9aaa00-c7a4-11ea-9074-b446a52c1258.png)
![image](https://user-images.githubusercontent.com/19892452/87709760-07a4e600-c7a5-11ea-809a-c3e832f9d701.png)
![image](https://user-images.githubusercontent.com/19892452/87709903-45097380-c7a5-11ea-9a1f-68c36b43eba7.png)
![image](https://user-images.githubusercontent.com/19892452/87709948-5783ad00-c7a5-11ea-94e7-409cc9d30468.png)
![image](https://user-images.githubusercontent.com/19892452/87710003-7124f480-c7a5-11ea-8f2f-7017b97daafa.png)

**Comment by david-roark** [comment]
Do you have a better solution? The reason I use `.deb` instead of `snap` is because when I install via `snap` I cannot type in my native language (Vietnamese) @omitrowski

**Comment by omitrowski** [comment]
@David-Roark IMHO using snap you have always the newest version of Atom. BUT it often brakes some plugins. So I like rather to contorll the used version by myself. In fact I have found a workaroud. I downgraded atom to [1.46.0 ](https://github.com/atom/atom/releases/tag/v1.46.0). In this version platformio terminal is working fine.

**Comment by david-roark** [comment]
@omitrowski thank you very much. maybe I should use VScode and report this issue to the Atom development team.
