### ISSUE TITLE
platformio-atom-ide-terminal not working

### ISSUE THREAD

**Issue by kujurbimal** [platformio/platformio-atom-ide-terminal#884]
- [ ] I have reset Atom to defaults prior to submitting report.
- [ ] I have not reset Atom to defaults prior to submitting report.
### Steps to reproduce

1.
2.
3.

**Expected behavior:** 

**Actual behavior:** 

**Reproduces how often:** 

### Versions

```
> atom --version

```
```
> apm --version

```
OS name and version:
Platformio-ide-terminal version:

**Comment by overgara2012** [comment]
OS:Linux Ubuntu 20.04 with Deepin Desktop
same issue: platformio-ide-teminal (2.10.0) not working , just blink cursor.
platformio-ide(2.7.1)

>>apm --version  
apm  2.5.0
npm  6.14.5
node 10.20.1 x64
atom 1.49.0
python 3.7.3
git 2.25.1

I used Python 2.7 (>>conda activate py27) and not changed , same issue....

>>atom --version
atom 1.49.0 x64

electron 5.0.13
chrome 73.0.3683.121
node v12.0.0

**Comment by nazarlviv07** [comment]
I have the same issue. 
platformio-ide-teminal (2.10.0)
Ubuntu 18.04.4 LTS

**Comment by kujurbimal** [comment]
Works well in windows

**Comment by cforput77** [comment]
I have not reset defaults in Atom. I'm just learning how to use it and don't know how to reset them

Description:
Using Lubuntu 20.04, just installed Atom and platformio......... It doesn't work. Just a flashing cursor

Steps to reproduce
1. Open .py file
2. Click + sign in lower left 
Same problem. Just a flashing cursor and can't type anything

Expected behavior:
Terminal should open in a new window with a command prompt allowing to enter command line commands

Actual behavior:
Just get a flashing cursor and if you try and type, nothing happens

Reproduces how often:
Every time I try it

Versions

> atom -- 1.49.0 x64

> apm -- I don't know what this is or how to find the version

OS name and version:
Lubuntu 20.04

**Comment by black-snow** [comment]
Win10, Atom 1.49, term 2.10.0 - Window rolls up, spinning mouse wheel, nothing happens

**Comment by overgara2012** [comment]
I gave up trying to fix this issue between Atom and Platformio with Ubuntu. I don't like to use Windows 10 (even I tested it (atom-platformio) and works fine). I always use linux (Ubuntu 20.04). That I did was change to use VScode IDE and everything was fine working with platformio IDE(2.7.1) and platformio-IDE-Terminal(2.10.0) . So my advise is forget Atom by now in linux.

**Comment by cforput77** [comment]
Yeah, seems like our posts here are going unanswered. Lot's of people having the issue. I just use Idle. My main reason for trying to get Atom working is so I could run code inside a SIMPLE IDE / text editor which Idle does (F5 key and boom!).

**Comment by derykmarl** [comment]
Is this abandoned?  Is there a maintained fork?

Edit: There are hundreds of forks of this and terminal-plus, it seems, but finding one that is still maintained is another matter.  This seems to be a major downside to Atom's package repo.

**Comment by cforput77** [comment]
I don't know. I abandoned Atom and use Idle and PyCharm.

**Comment by schtangel** [comment]
Same problem.
MacOS Catalina 10.15.6 (19G73)
Atom 1.49.0
platformio-ide-terminal 2.10.0

UPD: fixed [by this method](https://github.com/platformio/platformio-atom-ide-terminal/issues/297)

**Comment by pranavwani** [comment]
Please try https://github.com/bus-stop/terminus

Fork of `platformio-atom-ide-terminal`
https://github.com/platformio/platformio-atom-ide-terminal/issues/872#issuecomment-658743370

**Comment by gustavobertolino** [comment]
Same problem here ;(

The terminal tab opens, but no shell terminal appears in the session. I checked already the bash path in the plataformio-terminal settings and it points to /bin/bash in my Atom, as it should.

Linux
Ubuntu 18.04 + i3 wm
Atom version
1.49.0
plataformio-atom-ide
2.10.0

![Selection_003](https://user-images.githubusercontent.com/25723294/89735835-9a027780-da3b-11ea-89e4-0dd3611ba229.png)

**Comment by gustavobertolino** [comment]
The solution I found was to use other terminal package, in this case, **terminus**. It works well in my machine setup (Ubuntu 18.04 + Atom 1.49.0 + plataformio 2.10.0). 

Unfortunately terminus will works as a shadow IT for platformio-terminal unless this issue get solved.

![Selection_004](https://user-images.githubusercontent.com/25723294/89736050-22354c80-da3d-11ea-9ac7-6298838596e2.png)

**Comment by ivankravets** [comment]
Fixed in https://github.com/platformio/platformio-atom-ide-terminal/releases/tag/v2.10.1

Please update `platformio-ide-terminal` to the latest version.
