### ISSUE TITLE
Version 2.10.0 does not open the terminal

### ISSUE THREAD

**Issue by lfjaimesb** [platformio/platformio-atom-ide-terminal#885]
atom: 1.49.0 x64
node: 14.6.0
npm: 6.14.7

The TERMINAL does not open and when debugging the following error appears, where apparently there is a problem with pty.node, the Debug folder does not exist, in your case this Release.

![Screenshot_20200730_010151](https://user-images.githubusercontent.com/1088753/88886894-0a6df500-d201-11ea-95d6-a0486dc51873.png)

Testing past versions, I was only able to get working up to 2.9.0

**Comment by christianbalderrama** [comment]
I have the same issue as well, I saw first the issue when installing Atom via flatpak which was my go-to then I uninstalled it and reinstalled using the `deb` file in the website but still got the same result.

I also did installed `node-gyp` globally already.

![image](https://user-images.githubusercontent.com/18398769/89320381-fff5a480-d6b3-11ea-8f72-3ee6696c55c5.png)

**Comment by pranavwani** [comment]
@lfjaimesb Please try https://github.com/bus-stop/terminus

Fork of `platformio-atom-ide-terminal`
https://github.com/platformio/platformio-atom-ide-terminal/issues/872#issuecomment-658743370

**Comment by lfjaimesb** [comment]
**@pranavwani,** 
thank you very much, **terminus** works very great.

Even so, I am on the lookout for **"platformio-atom-ide-terminal"** to see if future versions provide a solution, I have used it for many years and I have become fond of that plugin.
