### ISSUE TITLE
Version2.10.0 keyboard stops working during writing passwords in Command Prompt.

### ISSUE THREAD

**Issue by Hamato739** [platformio/platformio-atom-ide-terminal#886]
- [ ] I have reset Atom to defaults prior to submitting report.
- [ ] I have not reset Atom to defaults prior to submitting report.
### Steps to reproduce

1.
2.
3.

**Expected behavior:** 

**Actual behavior:** 

**Reproduces how often:** 

### Versions

```
> atom --version

```
```
> apm --version

```
OS name and version:
Platformio-ide-terminal version:

**Comment by the-j0k3r** [comment]
I dont accept title only issues

use https://github.com/bus-stop/terminus or https://github.com/bus-stop/x-terminal
