### ISSUE TITLE
platformio-atom-ide-terminal is not working in atom

### ISSUE THREAD

**Issue by patelanandec54132** [platformio/platformio-atom-ide-terminal#889]
platformio-atom-ide-terminal is not working in my atom editor and i can not even uninstall it, it also does not let me install atom-ide-terminal please help me

**Comment by masteryourmind** [comment]
Please share the solution if you have any...

**Comment by patelanandec54132** [comment]
deleted platformio-atom-ide-terminal folder from package folder manually than reinstalled platformio-atom-ide-terminal. now it is working fine.
folder path : C:\Users\username\.atom\packages
