### ISSUE TITLE
How to change path in terminal

### ISSUE THREAD

**Issue by MandarSant** [platformio/platformio-atom-ide-terminal#89]
@ivankravets

I want to change the path in terminal my default path is i am usin windows 8.1

> c:\users(username)\desktop

i want to change it to

> c:\users(username)\AppData\Local\atom\bin

**Comment by RomanADavis** [comment]
cd .. 
to go up a directory
cd Appdata\Local\atom\bin
to go down to the desired directory

it's easy to remember if you know cd stands for change directory.

**Comment by MandarSant** [comment]
@RomanADavis I do not want to use cd command when ever i open the terminal the default path should be  
_

> c:\users(username)\AppData\Local\atom\bin

_

**Comment by RomanADavis** [comment]
I'm pretty sure that the terminal is setup to run in the project directory. It would be cool if we could change the default behavior, though.
