### ISSUE TITLE
unable to install, 2.10

### ISSUE THREAD

**Issue by kakyadaks** [platformio/platformio-atom-ide-terminal#890]
- [x ] I have reset Atom to defaults prior to submitting report.
- [] I have not reset Atom to defaults prior to submitting report.
### Description

error message says to install latest version of python.  tried with both 3.7 and 3.8

### Steps to reproduce

1.
2.
3.

**Expected behavior:** 

**Actual behavior:** 

**Reproduces how often:** 

### Versions

```
> atom --version
1.50  x64

```
```
> apm --version

```
OS name and version:
Platformio-ide-terminal version: 2.10

### Additional Information

prebuild-install WARN install getaddrinfo ENOTFOUND github-production-release-asset-2e65be.s3.amazonaws.com github-production-release-asset-2e65be.s3.amazonaws.com:443
gyp ERR! find Python 
gyp ERR! find Python Python is not set from command line or npm configuration
gyp ERR! find Python Python is not set from environment variable PYTHON
gyp ERR! find Python checking if "python" can be used
gyp ERR! find Python - "python" is not in PATH or produced an error
gyp ERR! find Python checking if "python2" can be used
gyp ERR! find Python - "python2" is not in PATH or produced an error
gyp ERR! find Python checking if "python3" can be used
gyp ERR! find Python - "python3" is not in PATH or produced an error
gyp ERR! find Python checking if the py launcher can be used to find Python 2
gyp ERR! find Python - "py.exe" is not in PATH or produced an error
gyp ERR! find Python checking if Python is C:\Python27\python.exe
gyp ERR! find Python - "C:\Python27\python.exe" could not be run
gyp ERR! find Python checking if Python is C:\Python37\python.exe
gyp ERR! find Python - "C:\Python37\python.exe" could not be run
gyp ERR! find Python

**Comment by the-j0k3r** [comment]
this is an apm issue more specifically node-gyp dependency of apm trythe apm bug tracker
