### ISSUE TITLE
error while installing “platformio-ide-terminal

### ISSUE THREAD

**Issue by akhilsarasan** [platformio/platformio-atom-ide-terminal#893]
- [ ] I have reset Atom to defaults prior to submitting report.
- [ ] I have not reset Atom to defaults prior to submitting report.
### Description

unable to install .I was using it properly. suddenly I faced some issues with the terminal(not able to type in the terminal) so i uninstalled.after that i could not reinstall it.

### Steps to reproduce

1.Go to File --> Settings in Atom editor
2. Click on Install
3. Search for "Terminal"
4. Click on "Install" blue button under platformio-ide-terminal

**Expected behavior:** 
Install platformio-ide-terminal

**Actual behavior:** 
Gives error message after processing for a while

**Reproduces how often:** 
up to 4 times

### Versions

```
> atom --version
1.50.0
```
```
> apm --version
 2.5.0
```
OS name and version:
Platformio-ide-terminal version:2.10
windows 10.

### Additional Information
######sccreen shot
![issue platformio](https://user-images.githubusercontent.com/27654253/91216086-03200580-e733-11ea-90b0-f085b05c85db.png)

######adding log
[log.txt](https://github.com/platformio/platformio-atom-ide-terminal/files/5125770/log.txt)

######version
apm  2.5.0
npm  6.14.5
node 10.20.1 x64
atom 1.50.0
git 2.17.1.windows.2

######call stack

Installing “platformio-ide-terminal@2.10.0” failed.Hide output…

> node-pty-prebuilt-multiarch@0.9.0-beta21.legacy install C:\Users\AKHILS~1\AppData\Local\Temp\apm-install-dir-2020726-32016-1k55zjk.jchh\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch
> prebuild-install || node scripts/install.js

C:\Users\AKHILS~1\AppData\Local\Temp\apm-install-dir-2020726-32016-1k55zjk.jchh\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch>if not defined npm_config_node_gyp (node "C:\Users\akhil sarasan\AppData\Local\atom\app-1.50.0\resources\app\apm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\akhil sarasan\AppData\Local\atom\app-1.50.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 

prebuild-install WARN install unexpected end of file
gyp ERR! find VS 
gyp ERR! find VS msvs_version not set from command line or npm config
gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer
gyp ERR! find VS looking for Visual Studio 2015
gyp ERR! find VS - not found
gyp ERR! find VS looking for Visual Studio 2013
gyp ERR! find VS - not found
gyp ERR! find VS 
gyp ERR! find VS **************************************************************
gyp ERR! find VS You need to install the latest version of Visual Studio
gyp ERR! find VS including the "Desktop development with C++" workload.
gyp ERR! find VS For more information consult the documentation at:
gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
gyp ERR! find VS **************************************************************
gyp ERR! find VS 
gyp ERR! configure error 
gyp ERR! stack Error: Could not find any Visual Studio installation to use
gyp ERR! stack     at VisualStudioFinder.fail (C:\Users\akhil sarasan\AppData\Local\atom\app-1.50.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:121:47)
gyp ERR! stack     at findVisualStudio2013 (C:\Users\akhil sarasan\AppData\Local\atom\app-1.50.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:74:16)
gyp ERR! stack     at regSearchKeys (C:\Users\akhil sarasan\AppData\Local\atom\app-1.50.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:372:16)
gyp ERR! stack     at regGetValue (C:\Users\akhil sarasan\AppData\Local\atom\app-1.50.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7)
gyp ERR! stack     at C:\Users\akhil sarasan\AppData\Local\atom\app-1.50.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:301:5)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Users\\akhil sarasan\\AppData\\Local\\atom\\app-1.50.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\akhil sarasan\\AppData\\Local\\atom\\app-1.50.0\\resources\\app\\apm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\AKHILS~1\AppData\Local\Temp\apm-install-dir-2020726-32016-1k55zjk.jchh\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch
gyp ERR! node -v v10.20.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\AKHILS~1\AppData\Local\Temp\apm-install-dir-2020726-32016-1k55zjk.jchh\package.json'
npm WARN apm-install-dir-2020726-32016-1k55zjk.jchh No description
npm WARN apm-install-dir-2020726-32016-1k55zjk.jchh No repository field.
npm WARN apm-install-dir-2020726-32016-1k55zjk.jchh No README data
npm WARN apm-install-dir-2020726-32016-1k55zjk.jchh No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-pty-prebuilt-multiarch@0.9.0-beta21.legacy install: `prebuild-install || node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-pty-prebuilt-multiarch@0.9.0-beta21.legacy install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\akhil sarasan\.atom\.apm\_logs\2020-08-25T18_35_16_173Z-debug.log

**Comment by thanhttran21** [comment]
I am also having this issue on macOS Catalina 10.15.6

**Comment by akhilsarasan** [comment]
> I am also having this issue on macOS Catalina 10.15.6

I reinstalled atom.now issue is gone

**Comment by Kardiamond** [comment]
> > I am also having this issue on macOS Catalina 10.15.6
> 
> I reinstalled atom.now issue is gone

Worked for me too, nothing else worked.

**Comment by FernandoPagesy** [comment]
I am currently having issues o Windows 10 and well no luck :(

**Comment by Kvork** [comment]
on windows, uninstall atom, restart system, then instal atom then install platformio-terminal all work well

**Comment by Kardiamond** [comment]
> on windows, uninstall atom, restart system, then instal atom then install platformio-terminal all work well

It worked for me for like a day, then I got the issue again. In the last year I had this issue 4-5 times, it really annoying.

I would suggest switching to Terminus, as I'm not sure this package is still alive?

**Comment by DeyDipankar** [comment]
Checck this -https://discuss.atom.io/t/cannot-install-platformio-ide-terminal-2-9-1-on-atom/67012

**Comment by UziTech** [comment]
This package is no longer maintained. Please uninstall platformio-ide-terminal and install either [terminus](https://atom.io/packages/terminus) or [x-terminal](https://atom.io/packages/x-terminal)

**Comment by ivankravets** [comment]
Fixed in https://github.com/platformio/platformio-atom-ide-terminal/releases/tag/v2.10.1

Please update `platformio-ide-terminal` to the latest version.
