### ISSUE TITLE
platform-atom-ide-terminal" does not work

### ISSUE THREAD

**Issue by SakhHunter** [platformio/platformio-atom-ide-terminal#895]
- [+] I have reset Atom to defaults prior to submitting report.
- [ ] I have not reset Atom to defaults prior to submitting report.
### Description

**Actual behavior:** 
Just get a flashing cursor and if you try and type, nothing happens

**Reproduces how often:** 

### Versions

```
> atom --version
atom 1.50.0
```
```
> apm --version
apm  2.5.0
npm  6.14.5
node 10.20.1 x64
atom 1.50.0
python 3.6.8
git 2.18.4


```
OS name and version: CentOS Linux release 8.2.2004
Platformio-ide-terminal version: 2.10.0

### Additional Information

![Screenshot from 2020-09-08 14-56-05](https://user-images.githubusercontent.com/10120611/92473556-7457c200-f1e3-11ea-8a03-f0451ed09347.png)

**Comment by cesarpaliza** [comment]
same as @SakhHunter but i have atom --v 1.51
Platformio-ide-terminal version: 2.10.0
![terminal_bug](https://user-images.githubusercontent.com/12817746/92821998-eb7a8b00-f388-11ea-865f-2b1133e57aad.png)

**Comment by touchft** [comment]
ame as @cesarpaliza 
i have atom --v 1.51
Platformio-ide-terminal version: 2.10.0

```
> atom --version
Atom    : 1.51.0
Electron: 5.0.13
Chrome  : 73.0.3683.121
Node    : 12.0.0
```

```
>apm --version
apm  2.5.0
npm  6.14.5
node 10.20.1 x64
atom 1.51.0
python 2.7.18rc1
git 2.25.1
```

**Comment by talantasan** [comment]
Same issue here, not working properly

**Comment by MarioJose** [comment]
Same issue.

It worked for me uninstall version 2.10 of terminal and install the 2.9.3. But, after atom update to 1.51, this not working more.

Atom    : 1.52.0
Electron: 6.1.12
Chrome  : 76.0.3809.146
Node    : 12.4.0

apm  2.5.2
npm  6.14.8
node 12.4.0 x64
atom 1.52.0
python 2.7.13
git 2.11.0

Linux 4.9.0-13-amd64 #1 SMP Debian 4.9.228-1 (2020-07-05) x86_64 GNU/Linux

Pio Core 5.0.1
Pio Home 3.3.0
Pio Terminal 2.10.0 (2.9.3 and 2.9.4 not working more)

**Comment by FDmitryG** [comment]
Same issue. 

Fix with install the version 2.9.3 doesn't work from Atom version 1.52.0.

Ubuntu 16.04.7 xenial LTS

Atom    : 1.52.0
Electron: 6.1.12
Chrome  : 76.0.3809.146
Node    : 12.4.0 

But I fixed installation of the version 2.9.3. 
I rebuilt plugin with node module node-pty-prebuilt-multiarch version 0.9.0-beta21.legacy.

1) Uninstall platformio-atom-ide-terminal.
2) Install plugin from source:

`cd ~/.atom/packages/`
`wget https://github.com/platformio/platformio-atom-ide-terminal/archive/v2.9.3.zip`
`unzip v2.9.3.zip`
`rm v2.9.3.zip `
`mv platformio-atom-ide-terminal-2.9.3 platformio-atom-ide-terminal`
`cd platformio-atom-ide-terminal/`
`sed -i 's/"node-pty-prebuilt-multiarch": "^0.8.1"/"node-pty-prebuilt-multiarch": "^0.9.0-beta21.legacy"/g' package.json`
`npm i`
`apm install`
`apm rebuild`

For some reason doesn't work without `apm rebuild`.

**Comment by gautaman8** [comment]
@FDmitryG
Worked perfectly now. This answer looks very under-rated. 

There are multiple threads for this same issue. 

Everytime, atom updates terminal fails. 

I don't really understand why this solution works and why it fails with every atom update, apart from platformio updates. 

But I guess I will prevent atom auto-updates now.

**Comment by UziTech** [comment]
This package is no longer maintained. Please uninstall platformio-ide-terminal and install either [terminus](https://atom.io/packages/terminus) or [x-terminal](https://atom.io/packages/x-terminal)

**Comment by ivankravets** [comment]
Fixed in https://github.com/platformio/platformio-atom-ide-terminal/releases/tag/v2.10.1

Please update `platformio-ide-terminal` to the latest version.
