### ISSUE TITLE
unable to install

### ISSUE THREAD

**Issue by prajjawal03** [platformio/platformio-atom-ide-terminal#899]
- [x ] I have reset Atom to defaults prior to submitting report.
- [ ] I have not reset Atom to defaults prior to submitting report.
### Steps to reproduce

1.unable to install the package
2.getting following error...
3.Installing “platformio-ide-terminal@2.10.0” failed

**Expected behavior:** 
terminal get installed

**Actual behavior:** 
threw error

**Reproduces how often:** 

### Versions

```
> atom --version

```
```
> apm --version

```
OS name and version:
Platformio-ide-terminal version:

**Comment by ivankravets** [comment]
Fixed in https://github.com/platformio/platformio-atom-ide-terminal/releases/tag/v2.10.1

Please update `platformio-ide-terminal` to the latest version.
