### ISSUE TITLE
platformio-atom-ide-terminal 2.10 not working in LinuxMint 20

### ISSUE THREAD

**Issue by axelljt** [platformio/platformio-atom-ide-terminal#900]
- [ ] I have reset Atom to defaults prior to submitting report.
- [ ] I have not reset Atom to defaults prior to submitting report.
### Steps to reproduce

1.
2.
3.

**Expected behavior:** 

**Actual behavior:** 
platformio-atom-ide-terminal 2.10 not working in LinuxMint 20, the console does not respond, I enter text and nothing happens.

**Reproduces how often:** 

### Versions

```
> atom --version

Atom    : 1.50.0
Electron: 5.0.13
Chrome  : 73.0.3683.121
Node    : 12.0.0

> apm --version

apm  2.5.0
npm  6.14.5
node 10.20.1 x64
atom 1.50.0
python 
git 2.25.1

OS name and version: Linux Mint 20 Ulyana
Platformio-ide-terminal version: platformio-atom-ide-terminal 2.10.0


### Additional Information
<!-- Add any additional information like screenshots, gif captures,
configuration, data or other Atom package lists, that might be necessary to reproduce the issue. -->

**Comment by ivankravets** [comment]
Fixed in https://github.com/platformio/platformio-atom-ide-terminal/releases/tag/v2.10.1

Please update `platformio-ide-terminal` to the latest version.
