### ISSUE TITLE
platformio-atom-ide-terminal not working after installation and also refuses to uninstall

### ISSUE THREAD

**Issue by exp8589ert** [platformio/platformio-atom-ide-terminal#904]
=> Os: Windows 10 Pro. x64
=> platformio-atom-ide-terminal version: 2.10.0
=> Atom version: 1.51.0

**Comment by ivankravets** [comment]
Fixed in https://github.com/platformio/platformio-atom-ide-terminal/releases/tag/v2.10.1

Please update `platformio-ide-terminal` to the latest version.
