### ISSUE TITLE
installing paltform-ide-terminal failed

### ISSUE THREAD

**Issue by M-Rb3** [platformio/platformio-atom-ide-terminal#908]
- [ ] I have reset Atom to defaults prior to submitting report.
- [ x] I have not reset Atom to defaults prior to submitting report.
### Description

> node-pty-prebuilt-multiarch@0.9.0-beta21.legacy install C:\Users\rabea\AppData\Local\Temp\apm-install-dir-2020914-3844-bbzalm.hedvm\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch
> prebuild-install || node scripts/install.js

C:\Users\rabea\AppData\Local\Temp\apm-install-dir-2020914-3844-bbzalm.hedvm\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch>if not defined npm_config_node_gyp (node "C:\Users\rabea\AppData\Local\atom\app-1.52.0\resources\app\apm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\rabea\AppData\Local\atom\app-1.52.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )

prebuild-install WARN install No prebuilt binaries found (target=6.1.12 runtime=electron arch=x64 libc= platform=win32)
gyp ERR! find VS
gyp ERR! find VS msvs_version not set from command line or npm config
gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer
gyp ERR! find VS looking for Visual Studio 2015
gyp ERR! find VS - not found
gyp ERR! find VS looking for Visual Studio 2013
gyp ERR! find VS - not found
gyp ERR! find VS
gyp ERR! find VS **************************************************************
gyp ERR! find VS You need to install the latest version of Visual Studio
gyp ERR! find VS including the "Desktop development with C++" workload.
gyp ERR! find VS For more information consult the documentation at:
gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
gyp ERR! find VS **************************************************************
gyp ERR! find VS
gyp ERR! configure error
gyp ERR! stack Error: Could not find any Visual Studio installation to use
gyp ERR! stack     at VisualStudioFinder.fail (C:\Users\rabea\AppData\Local\atom\app-1.52.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:121:47)
gyp ERR! stack     at C:\Users\rabea\AppData\Local\atom\app-1.52.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:74:16
gyp ERR! stack     at C:\Users\rabea\AppData\Local\atom\app-1.52.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:372:16
gyp ERR! stack     at C:\Users\rabea\AppData\Local\atom\app-1.52.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7
gyp ERR! stack     at C:\Users\rabea\AppData\Local\atom\app-1.52.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:297:5)
gyp ERR! stack     at ChildProcess.emit (events.js:200:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
gyp ERR! System Windows_NT 10.0.19041
gyp ERR! command "C:\\Users\\rabea\\AppData\\Local\\atom\\app-1.52.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\rabea\\AppData\\Local\\atom\\app-1.52.0\\resources\\app\\apm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\rabea\AppData\Local\Temp\apm-install-dir-2020914-3844-bbzalm.hedvm\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch
gyp ERR! node -v v12.4.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\rabea\AppData\Local\Temp\apm-install-dir-2020914-3844-bbzalm.hedvm\package.json'
npm WARN apm-install-dir-2020914-3844-bbzalm.hedvm No description
npm WARN apm-install-dir-2020914-3844-bbzalm.hedvm No repository field.
npm WARN apm-install-dir-2020914-3844-bbzalm.hedvm No README data
npm WARN apm-install-dir-2020914-3844-bbzalm.hedvm No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-pty-prebuilt-multiarch@0.9.0-beta21.legacy install: `prebuild-install || node scripts/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-pty-prebuilt-multiarch@0.9.0-beta21.legacy install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\rabea\.atom\.apm\_logs\2020-10-13T22_08_20_349Z-debug.log

### Steps to reproduce

1.
2.
3.

**Expected behavior:** 

**Actual behavior:** 

**Reproduces how often:** 

### Versions

```
> atom --version
 Atom    : 1.52.0
Electron: 6.1.12
Chrome  : 76.0.3809.146
Node    : 12.4.0
```
```
> apm --version
apm  2.5.2
npm  6.14.8
node 12.4.0 x64
atom 1.52.0
python 3.9.0
git 2.28.0.windows.1
visual studio
```
OS name and version:
Platformio-ide-terminal version:

**Comment by il1yaz** [comment]
I have the same problem,
I found that after update atom to 1.52.0 platform-ide-terminal is not working and i desided to uninstall&install this package. And now package is not installing with the same error

**Comment by alok18-tech** [comment]
same issue i am also facing , unable to install terminal after uninstalling

**Comment by default-sameer** [comment]
Same issue for me also. Didn't  help me after uninstalling and installing.
Hope to get answer soon!

**Comment by scrouncha** [comment]
I had same issue, and solution is in error :

> gyp ERR! find VS You need to install the latest version of Visual Studio
> gyp ERR! find VS including the "Desktop development with C++" workload.
> gyp ERR! find VS For more information consult the documentation at:
> gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows

So,

> Install Visual C++ Build Environment: [Visual Studio Build Tools](https://visualstudio.microsoft.com/thank-you-downloading-visual-studio/?sku=BuildTools) (using "Visual C++ build tools" workload)

worked for me

**Comment by Kardiamond** [comment]
Same issue.

I tried 

"Install Visual C++ Build Environment: Visual Studio Build Tools (using "Visual C++ build tools" workload)"

Didn't work for me.

**Comment by M-Rb3** [comment]
I tried it too,and it did not work.

**Comment by mahmoodgb** [comment]
I tried all the above solutions and it did not work.

**Comment by Kardiamond** [comment]
I just went with Terminus.

https://atom.io/packages/terminus

**Comment by fucasfucco** [comment]
you're an angel Kardiamond, thanks!!!

**Comment by saurabhmarpadge** [comment]
Thanks @Kardiamond

**Comment by M-Rb3** [comment]
Thanks @Kardiamond

**Comment by Harsha-VardhanReddy** [comment]
Thanks man!!

**Comment by ivankravets** [comment]
Fixed in https://github.com/platformio/platformio-atom-ide-terminal/releases/tag/v2.10.1

Please update `platformio-ide-terminal` to the latest version.
