### ISSUE TITLE
Platformio-ide-terminal stopped automatically and now unable to install back

### ISSUE THREAD

**Issue by RMJacob173** [platformio/platformio-atom-ide-terminal#909]
- [ yes ] I have reset Atom to defaults prior to submitting report.
- [ ] I have not reset Atom to defaults prior to submitting report.
### Steps to reproduce

1.unistall atom on windows 10
2. tried to reinstall platformio-ide-terminal 
3.Getting the below message in error log 
2130 error code ELIFECYCLE
2131 error errno 1
2132 error node-pty-prebuilt-multiarch@0.9.0-beta21.legacy install: `prebuild-install || node scripts/install.js`
2132 error Exit status 1
2133 error Failed at the node-pty-prebuilt-multiarch@0.9.0-beta21.legacy install script.
2133 error This is probably not a problem with npm. There is likely additional logging output above.
2134 verbose exit [ 1, true ]

**Expected behavior:** 
The terminal to have install as expected

**Actual behavior:** 
Not able to install back

**Reproduces how often:** 
NA

### Versions

```
> atom --version 
 Atom    : 1.52.0
Electron: 6.1.12
Chrome  : 76.0.3809.146
Node    : 12.4.0
```
```
> apm --version
apm  2.5.2
npm  6.14.8
node 12.4.0 x64
atom 1.52.0
python 3.7.6
git 2.27.0.windows.1
visual studio
```
OS name and version: windows 10
Platformio-ide-terminal version: 2.10.0

### Additional Information

I tried to install with the master zip file in https://github.com/platformio/platformio-atom-ide-terminal/archive/master.zip
related to  https://github.com/platformio/platformio-atom-ide-terminal/issues/795.
It installed successfully but I am still not able to see the terminal from atom
I tried the command: apm install platformio-ide-terminal
I got the same message in error logs
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-pty-prebuilt-multiarch@0.9.0-beta21.legacy install: `prebuild-install || node scripts/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-pty-prebuilt-multiarch@0.9.0-beta21.legacy install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**Comment by moiristo** [comment]
+1 same on mac.

**Comment by nosoccus** [comment]
I have the same problem, also tried to reinstall, but unsuccessful

**Comment by arogic** [comment]
same here, suddenly stopped working, removed it and now I am unable to install it.

macOS Catalina 10.15.7
Atom 1.52.0

**Comment by mzunigau** [comment]
same on windows 2.10 i just get a blank terminal i can't type

**Comment by Kardiamond** [comment]
Reinstall Atom and it should work again.

**Comment by AokiYuchan** [comment]
tried it.
but not solve that problem.

**Comment by Kardiamond** [comment]
True, it worked until I rebooted, then it stopped working again.

I just went with Terminus.

https://atom.io/packages/terminus

**Comment by AokiYuchan** [comment]
oh!! thank you!!
The package solved my all the problems.

**Comment by RMJacob173** [comment]
I reinstalled atom and it didnt work. It seems to be the package issue. The necessary files are not getting installed. I have stared using Terminus for the time being

**Comment by moiristo** [comment]
This package seems to be terminal

**Comment by ivankravets** [comment]
Fixed in https://github.com/platformio/platformio-atom-ide-terminal/releases/tag/v2.10.1

Please update `platformio-ide-terminal` to the latest version.
