### ISSUE TITLE
Not able to install

### ISSUE THREAD

**Issue by Novak-maker** [platformio/platformio-atom-ide-terminal#919]
- [x] I have reset Atom to defaults prior to submitting report.
- [ ] I have not reset Atom to defaults prior to submitting report.
### Description

there is something weird happening when I try to download it. Here is the log-
> node-pty-prebuilt-multiarch@0.9.0-beta21.legacy install C:\Users\susheel\AppData\Local\Temp\apm-install-dir-2020916-7008-sc856q.ykhc\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch
> prebuild-install || node scripts/install.js

C:\Users\susheel\AppData\Local\Temp\apm-install-dir-2020916-7008-sc856q.ykhc\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch>if not defined npm_config_node_gyp (node "C:\Users\susheel\AppData\Local\atom\app-1.52.0\resources\app\apm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\susheel\AppData\Local\atom\app-1.52.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 

prebuild-install WARN install No prebuilt binaries found (target=6.1.12 runtime=electron arch=x64 libc= platform=win32)
gyp ERR! find VS 
gyp ERR! find VS msvs_version not set from command line or npm config
gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
gyp ERR! find VS checking VS2019 (16.7.30611.23) found at:
gyp ERR! find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community"
gyp ERR! find VS - found "Visual Studio C++ core features"
gyp ERR! find VS - found VC++ toolset: v142
gyp ERR! find VS - missing any Windows SDK
gyp ERR! find VS could not find a version of Visual Studio 2017 or newer to use
gyp ERR! find VS looking for Visual Studio 2015
gyp ERR! find VS - not found
gyp ERR! find VS looking for Visual Studio 2013
gyp ERR! find VS - not found
gyp ERR! find VS 
gyp ERR! find VS **************************************************************
gyp ERR! find VS You need to install the latest version of Visual Studio
gyp ERR! find VS including the "Desktop development with C++" workload.
gyp ERR! find VS For more information consult the documentation at:
gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
gyp ERR! find VS **************************************************************
gyp ERR! find VS 
gyp ERR! configure error 
gyp ERR! stack Error: Could not find any Visual Studio installation to use
gyp ERR! stack     at VisualStudioFinder.fail (C:\Users\susheel\AppData\Local\atom\app-1.52.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:121:47)
gyp ERR! stack     at C:\Users\susheel\AppData\Local\atom\app-1.52.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:74:16
gyp ERR! stack     at C:\Users\susheel\AppData\Local\atom\app-1.52.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:372:16
gyp ERR! stack     at C:\Users\susheel\AppData\Local\atom\app-1.52.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7
gyp ERR! stack     at C:\Users\susheel\AppData\Local\atom\app-1.52.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:297:5)
gyp ERR! stack     at ChildProcess.emit (events.js:200:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Users\\susheel\\AppData\\Local\\atom\\app-1.52.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\susheel\\AppData\\Local\\atom\\app-1.52.0\\resources\\app\\apm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\susheel\AppData\Local\Temp\apm-install-dir-2020916-7008-sc856q.ykhc\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch
gyp ERR! node -v v12.4.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\susheel\AppData\Local\Temp\apm-install-dir-2020916-7008-sc856q.ykhc\package.json'
npm WARN apm-install-dir-2020916-7008-sc856q.ykhc No description
npm WARN apm-install-dir-2020916-7008-sc856q.ykhc No repository field.
npm WARN apm-install-dir-2020916-7008-sc856q.ykhc No README data
npm WARN apm-install-dir-2020916-7008-sc856q.ykhc No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-pty-prebuilt-multiarch@0.9.0-beta21.legacy install: `prebuild-install || node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-pty-prebuilt-multiarch@0.9.0-beta21.legacy install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\susheel\.atom\.apm\_logs\2020-10-16T11_46_21_928Z-debug.log

**Reproduces how often:** 

100%
### Versions

```
> atom --version
 Atom    : 1.52.0
Electron: 6.1.12
Chrome  : 76.0.3809.146
Node    : 12.4.0

```
```

**Comment by jdaehne** [comment]
+1 (same for me)

**Comment by StanNaum** [comment]
I have the same issue. 

It was working just fine yesterday, but today I tried opening the terminal inside Atom and it seemed frozen (just a little blinking bar). I restarted the computer thinking that it might have been some thread blocking the call, but it did not resolve the issue. I uninstalled the package and cannot install it anymore. Error is saying that I do not have Visual Studio with C++ Toolkit, while I actually have Visual Studio 2019 with all the modules.

I read other old posts with such issue and it might be due to an Atom autoupdate (I cannot prove if this is really the case) and people suggest downgrading Atom to an older version (I have not done it). So if anyone could please test it and tell if it works?

**Comment by guicuton** [comment]
I"ve changed the `Shell override` default to CMD.EXE path (windows 10) and back to work

**Comment by jonoyuan** [comment]
I'm getting the same issue. Previously, I had the error about Visual Studio (nearly identical to OP's). After installing Visual Studio including the "Desktop development with C++" workload, this is the error that appears instead.

> Installing "platformio-ide-terminal@2.10.0" failed.
> 
> ```
> > node-pty-prebuilt-multiarch@0.9.0-beta21.legacy install C:\Users\jyuan\AppData\Local\Temp\apm-install-dir-2020916-276-1tmrbje.w0w0f\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch
> > prebuild-install || node scripts/install.js
> 
> 
> C:\Users\jyuan\AppData\Local\Temp\apm-install-dir-2020916-276-1tmrbje.w0w0f\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch>if not defined npm_config_node_gyp (node "C:\Users\jyuan\AppData\Local\atom\app-1.52.0\resources\app\apm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\jyuan\AppData\Local\atom\app-1.52.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 
> Building the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
> C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(499,5): warning MSB8029: The Intermediate directory or Output directory cannot reside under the Temporary directory as it could lead to issues with incremental build. [C:\Users\jyuan\AppData\Local\Temp\apm-install-dir-2020916-276-1tmrbje.w0w0f\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\conpty.vcxproj]
>   conpty.cc
>   path_util.cc
>   win_delay_load_hook.cc
> C:\Users\jyuan\AppData\Local\node-gyp\Cache\6.1.12\include\node\v8.h(8205,1): warning C4996: 'v8::MicrotasksCompletedCallback': was declared deprecated (compiling source file ..\src\win\path_util.cc) [C:\Users\jyuan\AppData\Local\Temp\apm-install-dir-2020916-276-1tmrbje.w0w0f\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\conpty.vcxproj]
> C:\Users\jyuan\AppData\Local\node-gyp\Cache\6.1.12\include\node\v8.h(8214,1): warning C4996: 'v8::MicrotasksCompletedCallback': was declared deprecated (compiling source file ..\src\win\path_util.cc) [C:\Users\jyuan\AppData\Local\Temp\apm-install-dir-2020916-276-1tmrbje.w0w0f\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\conpty.vcxproj]
> C:\Users\jyuan\AppData\Local\node-gyp\Cache\6.1.12\include\node\v8.h(8205,1): warning C4996: 'v8::MicrotasksCompletedCallback': was declared deprecated (compiling source file ..\src\win\conpty.cc) [C:\Users\jyuan\AppData\Local\Temp\apm-install-dir-2020916-276-1tmrbje.w0w0f\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\conpty.vcxproj]
> C:\Users\jyuan\AppData\Local\node-gyp\Cache\6.1.12\include\node\v8.h(8214,1): warning C4996: 'v8::MicrotasksCompletedCallback': was declared deprecated (compiling source file ..\src\win\conpty.cc) [C:\Users\jyuan\AppData\Local\Temp\apm-install-dir-2020916-276-1tmrbje.w0w0f\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\conpty.vcxproj]
>      Creating library C:\Users\jyuan\AppData\Local\Temp\apm-install-dir-2020916-276-1tmrbje.w0w0f\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\Release\conpty.lib and object C:\Users\jyuan\AppData\Local\Temp\apm-install-dir-2020916-276-1tmrbje.w0w0f\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\Release\conpty.exp
>   Generating code
>   Previous IPDB not found, fall back to full compilation.
>   All 951 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.
>   Finished generating code
>   conpty.vcxproj -> C:\Users\jyuan\AppData\Local\Temp\apm-install-dir-2020916-276-1tmrbje.w0w0f\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\Release\\conpty.node
> C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(499,5): warning MSB8029: The Intermediate directory or Output directory cannot reside under the Temporary directory as it could lead to issues with incremental build. [C:\Users\jyuan\AppData\Local\Temp\apm-install-dir-2020916-276-1tmrbje.w0w0f\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\conpty_console_list.vcxproj]
>   conpty_console_list.cc
>   win_delay_load_hook.cc
> C:\Users\jyuan\AppData\Local\node-gyp\Cache\6.1.12\include\node\v8.h(8205,1): warning C4996: 'v8::MicrotasksCompletedCallback': was declared deprecated (compiling source file ..\src\win\conpty_console_list.cc) [C:\Users\jyuan\AppData\Local\Temp\apm-install-dir-2020916-276-1tmrbje.w0w0f\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\conpty_console_list.vcxproj]
> C:\Users\jyuan\AppData\Local\node-gyp\Cache\6.1.12\include\node\v8.h(8214,1): warning C4996: 'v8::MicrotasksCompletedCallback': was declared deprecated (compiling source file ..\src\win\conpty_console_list.cc) [C:\Users\jyuan\AppData\Local\Temp\apm-install-dir-2020916-276-1tmrbje.w0w0f\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\conpty_console_list.vcxproj]
>      Creating library C:\Users\jyuan\AppData\Local\Temp\apm-install-dir-2020916-276-1tmrbje.w0w0f\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\Release\conpty_console_list.lib and object C:\Users\jyuan\AppData\Local\Temp\apm-install-dir-2020916-276-1tmrbje.w0w0f\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\Release\conpty_console_list.exp
>   Generating code
>   Previous IPDB not found, fall back to full compilation.
>   All 167 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.
>   Finished generating code
>   conpty_console_list.vcxproj -> C:\Users\jyuan\AppData\Local\Temp\apm-install-dir-2020916-276-1tmrbje.w0w0f\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\Release\\conpty_console_list.node
> C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(499,5): warning MSB8029: The Intermediate directory or Output directory cannot reside under the Temporary directory as it could lead to issues with incremental build. [C:\Users\jyuan\AppData\Local\Temp\apm-install-dir-2020916-276-1tmrbje.w0w0f\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\deps\winpty\src\winpty.vcxproj]
>   AgentLocation.cc
>   winpty.cc
>   BackgroundDesktop.cc
>   Buffer.cc
>   DebugClient.cc
>   GenRandom.cc
>   OwnedHandle.cc
>   StringUtil.cc
>   WindowsSecurity.cc
>   WindowsVersion.cc
>   WinptyAssert.cc
>   WinptyException.cc
>   WinptyVersion.cc
>   win_delay_load_hook.cc
>      Creating library C:\Users\jyuan\AppData\Local\Temp\apm-install-dir-2020916-276-1tmrbje.w0w0f\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\Release\winpty.lib and object C:\Users\jyuan\AppData\Local\Temp\apm-install-dir-2020916-276-1tmrbje.w0w0f\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\Release\winpty.exp
>   Generating code
>   Previous IPDB not found, fall back to full compilation.
>   All 1034 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.
>   Finished generating code
>   winpty.vcxproj -> C:\Users\jyuan\AppData\Local\Temp\apm-install-dir-2020916-276-1tmrbje.w0w0f\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\Release\\winpty.dll
> C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(499,5): warning MSB8029: The Intermediate directory or Output directory cannot reside under the Temporary directory as it could lead to issues with incremental build. [C:\Users\jyuan\AppData\Local\Temp\apm-install-dir-2020916-276-1tmrbje.w0w0f\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\deps\winpty\src\winpty-agent.vcxproj]
>   Agent.cc
>   AgentCreateDesktop.cc
>   ConsoleFont.cc
>   ConsoleInput.cc
>   ConsoleInputReencoding.cc
>   ConsoleLine.cc
>   DebugShowInput.cc
>   DefaultInputMap.cc
>   EventLoop.cc
>   InputMap.cc
>   LargeConsoleRead.cc
>   NamedPipe.cc
>   Scraper.cc
>   Terminal.cc
>   Win32Console.cc
>   Win32ConsoleBuffer.cc
>   main.cc
>   BackgroundDesktop.cc
>   Buffer.cc
>   DebugClient.cc
>   GenRandom.cc
>   OwnedHandle.cc
>   StringUtil.cc
>   WindowsSecurity.cc
>   WindowsVersion.cc
>   WinptyAssert.cc
>   WinptyException.cc
>   WinptyVersion.cc
>   win_delay_load_hook.cc
>   Generating code
>   Previous IPDB not found, fall back to full compilation.
> C:\Users\jyuan\AppData\Local\Temp\apm-install-dir-2020916-276-1tmrbje.w0w0f\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\deps\winpty\src\agent\Agent.cc(231): warning C4722: 'Agent::~Agent': destructor never returns, potential memory leak [C:\Users\jyuan\AppData\Local\Temp\apm-install-dir-2020916-276-1tmrbje.w0w0f\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\deps\winpty\src\winpty-agent.vcxproj]
>   All 1725 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.
>   Finished generating code
> C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(876,5): error MSB6003: The specified task executable "link.exe" could not be run. System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\jyuan\AppData\Local\Temp\apm-install-dir-2020916-276-1tmrbje.w0w0f\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\deps\winpty\src\Release\obj\winpty-agent\winpty-agent.tlog'. [C:\Users\jyuan\AppData\Local\Temp\apm-install-dir-2020916-276-1tmrbje.w0w0f\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\deps\winpty\src\winpty-agent.vcxproj]
> C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(876,5): error MSB6003:    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath) [C:\Users\jyuan\AppData\Local\Temp\apm-install-dir-2020916-276-1tmrbje.w0w0f\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\deps\winpty\src\winpty-agent.vcxproj]
> C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(876,5): error MSB6003:    at System.IO.FileSystemEnumerableIterator`1.CommonInit() [C:\Users\jyuan\AppData\Local\Temp\apm-install-dir-2020916-276-1tmrbje.w0w0f\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\deps\winpty\src\winpty-agent.vcxproj]
> C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(876,5): error MSB6003:    at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost) [C:\Users\jyuan\AppData\Local\Temp\apm-install-dir-2020916-276-1tmrbje.w0w0f\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\deps\winpty\src\winpty-agent.vcxproj]
> C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(876,5): error MSB6003:    at System.IO.Directory.GetFiles(String path, String searchPattern) [C:\Users\jyuan\AppData\Local\Temp\apm-install-dir-2020916-276-1tmrbje.w0w0f\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\deps\winpty\src\winpty-agent.vcxproj]
> C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(876,5): error MSB6003:    at Microsoft.Build.Utilities.TrackedDependencies.ExpandWildcards(ITaskItem[] expand) [C:\Users\jyuan\AppData\Local\Temp\apm-install-dir-2020916-276-1tmrbje.w0w0f\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\deps\winpty\src\winpty-agent.vcxproj]
> C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(876,5): error MSB6003:    at Microsoft.Build.Utilities.CanonicalTrackedOutputFiles.InternalConstruct(ITask ownerTask, ITaskItem[] tlogFiles, Boolean constructOutputsFromTLogs) [C:\Users\jyuan\AppData\Local\Temp\apm-install-dir-2020916-276-1tmrbje.w0w0f\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\deps\winpty\src\winpty-agent.vcxproj]
> C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(876,5): error MSB6003:    at Microsoft.Build.CPPTasks.TrackedVCToolTask.PostExecuteTool(Int32 exitCode) [C:\Users\jyuan\AppData\Local\Temp\apm-install-dir-2020916-276-1tmrbje.w0w0f\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\deps\winpty\src\winpty-agent.vcxproj]
> C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(876,5): error MSB6003:    at Microsoft.Build.CPPTasks.TrackedVCToolTask.ExecuteTool(String pathToTool, String responseFileCommands, String commandLineCommands) [C:\Users\jyuan\AppData\Local\Temp\apm-install-dir-2020916-276-1tmrbje.w0w0f\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\deps\winpty\src\winpty-agent.vcxproj]
> C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(876,5): error MSB6003:    at Microsoft.Build.Utilities.ToolTask.Execute() [C:\Users\jyuan\AppData\Local\Temp\apm-install-dir-2020916-276-1tmrbje.w0w0f\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\deps\winpty\src\winpty-agent.vcxproj]
> 
> prebuild-install WARN install No prebuilt binaries found (target=6.1.12 runtime=electron arch=x64 libc= platform=win32)
> gyp ERR! build error 
> gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
> gyp ERR! stack     at ChildProcess.onExit (C:\Users\jyuan\AppData\Local\atom\app-1.52.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
> gyp ERR! stack     at ChildProcess.emit (events.js:200:13)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
> gyp ERR! System Windows_NT 10.0.18363
> gyp ERR! command "C:\\Users\\jyuan\\AppData\\Local\\atom\\app-1.52.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\jyuan\\AppData\\Local\\atom\\app-1.52.0\\resources\\app\\apm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
> gyp ERR! cwd C:\Users\jyuan\AppData\Local\Temp\apm-install-dir-2020916-276-1tmrbje.w0w0f\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch
> gyp ERR! node -v v12.4.0
> gyp ERR! node-gyp -v v5.1.0
> gyp ERR! not ok 
> npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\jyuan\AppData\Local\Temp\apm-install-dir-2020916-276-1tmrbje.w0w0f\package.json'
> npm WARN apm-install-dir-2020916-276-1tmrbje.w0w0f No description
> npm WARN apm-install-dir-2020916-276-1tmrbje.w0w0f No repository field.
> npm WARN apm-install-dir-2020916-276-1tmrbje.w0w0f No README data
> npm WARN apm-install-dir-2020916-276-1tmrbje.w0w0f No license field.
> 
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! node-pty-prebuilt-multiarch@0.9.0-beta21.legacy install: `prebuild-install || node scripts/install.js`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the node-pty-prebuilt-multiarch@0.9.0-beta21.legacy install script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\jyuan\.atom\.apm\_logs\2020-10-16T17_11_45_504Z-debug.log
> ```

**Comment by iatecookies** [comment]
Using the package terminus instead works for me

**Comment by Novak-maker** [comment]
I just uninstalled Atom and downloaded Pycharm instead. Works better.

**Comment by tenaciouslyantediluvian** [comment]
I'm getting the same issue since upgrading Atom to 1.52 on macOS 10.15.7. Package no longer works and cannot be reinstalled.

**Comment by jnewblanc** [comment]
+1

Same issue, same stack trace, same comment as @StanNaum

**Comment by olafthiele** [comment]
+1

**Comment by mariusgronli** [comment]
+1 same issue as @Novak-maker

**Comment by ivankravets** [comment]
Fixed in https://github.com/platformio/platformio-atom-ide-terminal/releases/tag/v2.10.1

Please update `platformio-ide-terminal` to the latest version.
