### ISSUE TITLE
terminal is not working also terminal is not installed when I tried to install

### ISSUE THREAD

**Issue by PolAditya** [platformio/platformio-atom-ide-terminal#922]
- [ ] I have reset Atom to defaults prior to submitting report.
- [ ] I have not reset Atom to defaults prior to submitting report.
### Steps to reproduce

1.
2.
3.

**Expected behavior:** 

**Actual behavior:** 

**Reproduces how often:** 

### Versions

```
> atom --version

```
```
> apm --version

```
OS name and version:
Platformio-ide-terminal version:

**Comment by ayanezcloud** [comment]
Same here. My favorite terminal stopped working a few days ago and cannot be reinstalled. Any news or clues to solve it?

**Comment by PolAditya** [comment]
> Same here. My favorite terminal stopped working a few days ago and cannot be reinstalled. Any news or clues to solve it?

it is  also my favourite terminal but I am unable to install it

**Comment by PolAditya** [comment]
> Same here. My favorite terminal stopped working a few days ago and cannot be reinstalled. Any news or clues to solve it?

install "terminus"

**Comment by EricEsajian** [comment]
Had the same issue with the install Platformio IDE Terminal on Atom. I installed the package: 'terminus' , and that works for me.

**Comment by ivankravets** [comment]
Fixed in https://github.com/platformio/platformio-atom-ide-terminal/releases/tag/v2.10.1

Please update `platformio-ide-terminal` to the latest version.
