### ISSUE TITLE
Unable to install this package. I reset a number of times. I even uninstalled Atom 3 times and re-installed and tried to install the package but with no success.

### ISSUE THREAD

**Issue by Bibisho** [platformio/platformio-atom-ide-terminal#923]
- [x] I have reset Atom to defaults prior to submitting report.
- [x] I have not reset Atom to defaults prior to submitting report.
### Steps to reproduce

1.
2.
3.

**Expected behavior:** 

**Actual behavior:** 

**Reproduces how often:** 

### Versions

```
> atom --version

```
```
> apm --version

```
OS name and version:
Platformio-ide-terminal version:

**Comment by XandermanGG** [comment]
I am not sure what OS you are using but I had to install XCode and it finally installed and working with no problems.

**Comment by ayanezcloud** [comment]
Same here. My favorite terminal stopped working a few days ago and cannot be reinstalled. Any news or clues to solve it? 
Windows 10.

**Comment by EricEsajian** [comment]
Had the same issue with the install Platformio IDE Terminal on Atom. I installed the package: 'terminus' , and that works for me.

**Comment by ivankravets** [comment]
Fixed in https://github.com/platformio/platformio-atom-ide-terminal/releases/tag/v2.10.1

Please update `platformio-ide-terminal` to the latest version.
