### ISSUE TITLE
Installation Failure platformio-atom-ide-terminal

### ISSUE THREAD

**Issue by peet7969** [platformio/platformio-atom-ide-terminal#925]
- [x] I have reset Atom to defaults prior to submitting report.
- [ ] I have not reset Atom to defaults prior to submitting report.
### Steps to reproduce

1.
2.
3.

**Expected behavior:** 

**Actual behavior:** 

**Reproduces how often:** 

### Versions

```
> atom --version

```
```
> apm --version

```
OS name and version:
Platformio-ide-terminal version:

**Comment by PolAditya** [comment]
try to install "terminus" it is a fork of platformio-ide-terminal

**Comment by EricEsajian** [comment]
Had the same issue with the install Platformio IDE Terminal on Atom. I installed the package: 'terminus' , and that works for me.

**Comment by bigdatavik** [comment]
same

**Comment by joranson** [comment]
same

**Comment by peet7969** [comment]
Thanks, that helped.

**Comment by ivankravets** [comment]
Fixed in https://github.com/platformio/platformio-atom-ide-terminal/releases/tag/v2.10.1

Please update `platformio-ide-terminal` to the latest version.
