### ISSUE TITLE
Not able to install terminal

### ISSUE THREAD

**Issue by Priyanka9496** [platformio/platformio-atom-ide-terminal#927]
- [x] I have reset Atom to defaults prior to submitting report.
- [ ] I have not reset Atom to defaults prior to submitting report.
### Steps to reproduce

1.
2.
3.

**Expected behavior:** 

**Actual behavior:** 

**Reproduces how often:** 

### Versions

```
> atom --version

```
```
> apm --version

```
OS name and version:
Platformio-ide-terminal version:

**Comment by Priyanka9496** [comment]
Installing “platformio-ide-terminal@2.10.0” failed.Hide output…

> node-pty-prebuilt-multiarch@0.9.0-beta21.legacy install C:\Users\Priyanka\AppData\Local\Temp\apm-install-dir-2020922-3304-11rftjx.mko7\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch
> prebuild-install || node scripts/install.js


C:\Users\Priyanka\AppData\Local\Temp\apm-install-dir-2020922-3304-11rftjx.mko7\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch>if not defined npm_config_node_gyp (node "C:\Users\Priyanka\AppData\Local\atom\app-1.52.0\resources\app\apm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\Priyanka\AppData\Local\atom\app-1.52.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 
Building the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(475,5): warning MSB8029: The Intermediate directory or Output directory cannot reside under the Temporary directory as it could lead to issues with incremental build. [C:\Users\Priyanka\AppData\Local\Temp\apm-install-dir-2020922-3304-11rftjx.mko7\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\conpty.vcxproj]
  conpty.cc
  path_util.cc
  win_delay_load_hook.cc
C:\Users\Priyanka\AppData\Local\node-gyp\Cache\6.1.12\include\node\v8.h(8205,1): warning C4996: 'v8::MicrotasksCompletedCallback': was declared deprecated (compiling source file ..\src\win\path_util.cc) [C:\Users\Priyanka\AppData\Local\Temp\apm-install-dir-2020922-3304-11rftjx.mko7\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\conpty.vcxproj]
C:\Users\Priyanka\AppData\Local\node-gyp\Cache\6.1.12\include\node\v8.h(8214,1): warning C4996: 'v8::MicrotasksCompletedCallback': was declared deprecated (compiling source file ..\src\win\path_util.cc) [C:\Users\Priyanka\AppData\Local\Temp\apm-install-dir-2020922-3304-11rftjx.mko7\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\conpty.vcxproj]
C:\Users\Priyanka\AppData\Local\node-gyp\Cache\6.1.12\include\node\v8.h(8205,1): warning C4996: 'v8::MicrotasksCompletedCallback': was declared deprecated (compiling source file ..\src\win\conpty.cc) [C:\Users\Priyanka\AppData\Local\Temp\apm-install-dir-2020922-3304-11rftjx.mko7\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\conpty.vcxproj]
C:\Users\Priyanka\AppData\Local\node-gyp\Cache\6.1.12\include\node\v8.h(8214,1): warning C4996: 'v8::MicrotasksCompletedCallback': was declared deprecated (compiling source file ..\src\win\conpty.cc) [C:\Users\Priyanka\AppData\Local\Temp\apm-install-dir-2020922-3304-11rftjx.mko7\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\conpty.vcxproj]
     Creating library C:\Users\Priyanka\AppData\Local\Temp\apm-install-dir-2020922-3304-11rftjx.mko7\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\Release\conpty.lib and object C:\Users\Priyanka\AppData\Local\Temp\apm-install-dir-2020922-3304-11rftjx.mko7\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\Release\conpty.exp
  Generating code
  Previous IPDB not found, fall back to full compilation.
  All 950 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.
  Finished generating code
  conpty.vcxproj -> C:\Users\Priyanka\AppData\Local\Temp\apm-install-dir-2020922-3304-11rftjx.mko7\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\Release\\conpty.node
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(475,5): warning MSB8029: The Intermediate directory or Output directory cannot reside under the Temporary directory as it could lead to issues with incremental build. [C:\Users\Priyanka\AppData\Local\Temp\apm-install-dir-2020922-3304-11rftjx.mko7\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\conpty_console_list.vcxproj]
  conpty_console_list.cc
  win_delay_load_hook.cc
C:\Users\Priyanka\AppData\Local\node-gyp\Cache\6.1.12\include\node\v8.h(8205,1): warning C4996: 'v8::MicrotasksCompletedCallback': was declared deprecated (compiling source file ..\src\win\conpty_console_list.cc) [C:\Users\Priyanka\AppData\Local\Temp\apm-install-dir-2020922-3304-11rftjx.mko7\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\conpty_console_list.vcxproj]
C:\Users\Priyanka\AppData\Local\node-gyp\Cache\6.1.12\include\node\v8.h(8214,1): warning C4996: 'v8::MicrotasksCompletedCallback': was declared deprecated (compiling source file ..\src\win\conpty_console_list.cc) [C:\Users\Priyanka\AppData\Local\Temp\apm-install-dir-2020922-3304-11rftjx.mko7\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\conpty_console_list.vcxproj]
     Creating library C:\Users\Priyanka\AppData\Local\Temp\apm-install-dir-2020922-3304-11rftjx.mko7\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\Release\conpty_console_list.lib and object C:\Users\Priyanka\AppData\Local\Temp\apm-install-dir-2020922-3304-11rftjx.mko7\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\Release\conpty_console_list.exp
  Generating code
  Previous IPDB not found, fall back to full compilation.
  All 167 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.
  Finished generating code
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(861,5): error MSB6003: The specified task executable "link.exe" could not be run. System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Priyanka\AppData\Local\Temp\apm-install-dir-2020922-3304-11rftjx.mko7\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\Release\obj\conpty_console_list\conpty_c.B9CB3515.tlog'. [C:\Users\Priyanka\AppData\Local\Temp\apm-install-dir-2020922-3304-11rftjx.mko7\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\conpty_console_list.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(861,5): error MSB6003:    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath) [C:\Users\Priyanka\AppData\Local\Temp\apm-install-dir-2020922-3304-11rftjx.mko7\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\conpty_console_list.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(861,5): error MSB6003:    at System.IO.FileSystemEnumerableIterator`1.CommonInit() [C:\Users\Priyanka\AppData\Local\Temp\apm-install-dir-2020922-3304-11rftjx.mko7\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\conpty_console_list.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(861,5): error MSB6003:    at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost) [C:\Users\Priyanka\AppData\Local\Temp\apm-install-dir-2020922-3304-11rftjx.mko7\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\conpty_console_list.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(861,5): error MSB6003:    at System.IO.Directory.GetFiles(String path, String searchPattern) [C:\Users\Priyanka\AppData\Local\Temp\apm-install-dir-2020922-3304-11rftjx.mko7\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\conpty_console_list.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(861,5): error MSB6003:    at Microsoft.Build.Utilities.TrackedDependencies.ExpandWildcards(ITaskItem[] expand) [C:\Users\Priyanka\AppData\Local\Temp\apm-install-dir-2020922-3304-11rftjx.mko7\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\conpty_console_list.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(861,5): error MSB6003:    at Microsoft.Build.Utilities.CanonicalTrackedOutputFiles.InternalConstruct(ITask ownerTask, ITaskItem[] tlogFiles, Boolean constructOutputsFromTLogs) [C:\Users\Priyanka\AppData\Local\Temp\apm-install-dir-2020922-3304-11rftjx.mko7\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\conpty_console_list.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(861,5): error MSB6003:    at Microsoft.Build.CPPTasks.TrackedVCToolTask.PostExecuteTool(Int32 exitCode) [C:\Users\Priyanka\AppData\Local\Temp\apm-install-dir-2020922-3304-11rftjx.mko7\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\conpty_console_list.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(861,5): error MSB6003:    at Microsoft.Build.CPPTasks.TrackedVCToolTask.ExecuteTool(String pathToTool, String responseFileCommands, String commandLineCommands) [C:\Users\Priyanka\AppData\Local\Temp\apm-install-dir-2020922-3304-11rftjx.mko7\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\conpty_console_list.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(861,5): error MSB6003:    at Microsoft.Build.Utilities.ToolTask.Execute() [C:\Users\Priyanka\AppData\Local\Temp\apm-install-dir-2020922-3304-11rftjx.mko7\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\conpty_console_list.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(475,5): warning MSB8029: The Intermediate directory or Output directory cannot reside under the Temporary directory as it could lead to issues with incremental build. [C:\Users\Priyanka\AppData\Local\Temp\apm-install-dir-2020922-3304-11rftjx.mko7\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\deps\winpty\src\winpty.vcxproj]
  AgentLocation.cc
  winpty.cc
  BackgroundDesktop.cc
  Buffer.cc
  DebugClient.cc
  GenRandom.cc
  OwnedHandle.cc
  StringUtil.cc
  WindowsSecurity.cc
  WindowsVersion.cc
  WinptyAssert.cc
  WinptyException.cc
  WinptyVersion.cc
  win_delay_load_hook.cc
     Creating library C:\Users\Priyanka\AppData\Local\Temp\apm-install-dir-2020922-3304-11rftjx.mko7\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\Release\winpty.lib and object C:\Users\Priyanka\AppData\Local\Temp\apm-install-dir-2020922-3304-11rftjx.mko7\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\Release\winpty.exp
  Generating code
  Previous IPDB not found, fall back to full compilation.
  All 1033 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.
  Finished generating code
  winpty.vcxproj -> C:\Users\Priyanka\AppData\Local\Temp\apm-install-dir-2020922-3304-11rftjx.mko7\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\Release\\winpty.dll
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(475,5): warning MSB8029: The Intermediate directory or Output directory cannot reside under the Temporary directory as it could lead to issues with incremental build. [C:\Users\Priyanka\AppData\Local\Temp\apm-install-dir-2020922-3304-11rftjx.mko7\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\deps\winpty\src\winpty-agent.vcxproj]
  Agent.cc
  AgentCreateDesktop.cc
  ConsoleFont.cc
  ConsoleInput.cc
  ConsoleInputReencoding.cc
  ConsoleLine.cc
  DebugShowInput.cc
  DefaultInputMap.cc
  EventLoop.cc
  InputMap.cc
  LargeConsoleRead.cc
  NamedPipe.cc
  Scraper.cc
  Terminal.cc
  Win32Console.cc
  Win32ConsoleBuffer.cc
  main.cc
  BackgroundDesktop.cc
  Buffer.cc
  DebugClient.cc
  GenRandom.cc
  OwnedHandle.cc
  StringUtil.cc
  WindowsSecurity.cc
  WindowsVersion.cc
  WinptyAssert.cc
  WinptyException.cc
  WinptyVersion.cc
  win_delay_load_hook.cc
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(514,5): error MSB6003: The specified task executable "CL.exe" could not be run. System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Priyanka\AppData\Local\Temp\apm-install-dir-2020922-3304-11rftjx.mko7\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\deps\winpty\src\Release\obj\winpty-agent\winpty-agent.tlog'. [C:\Users\Priyanka\AppData\Local\Temp\apm-install-dir-2020922-3304-11rftjx.mko7\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\deps\winpty\src\winpty-agent.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(514,5): error MSB6003:    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath) [C:\Users\Priyanka\AppData\Local\Temp\apm-install-dir-2020922-3304-11rftjx.mko7\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\deps\winpty\src\winpty-agent.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(514,5): error MSB6003:    at System.IO.FileSystemEnumerableIterator`1.CommonInit() [C:\Users\Priyanka\AppData\Local\Temp\apm-install-dir-2020922-3304-11rftjx.mko7\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\deps\winpty\src\winpty-agent.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(514,5): error MSB6003:    at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost) [C:\Users\Priyanka\AppData\Local\Temp\apm-install-dir-2020922-3304-11rftjx.mko7\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\deps\winpty\src\winpty-agent.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(514,5): error MSB6003:    at System.IO.Directory.GetFiles(String path, String searchPattern) [C:\Users\Priyanka\AppData\Local\Temp\apm-install-dir-2020922-3304-11rftjx.mko7\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\deps\winpty\src\winpty-agent.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(514,5): error MSB6003:    at Microsoft.Build.Utilities.TrackedDependencies.ExpandWildcards(ITaskItem[] expand) [C:\Users\Priyanka\AppData\Local\Temp\apm-install-dir-2020922-3304-11rftjx.mko7\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\deps\winpty\src\winpty-agent.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(514,5): error MSB6003:    at Microsoft.Build.Utilities.CanonicalTrackedOutputFiles.InternalConstruct(ITask ownerTask, ITaskItem[] tlogFiles, Boolean constructOutputsFromTLogs) [C:\Users\Priyanka\AppData\Local\Temp\apm-install-dir-2020922-3304-11rftjx.mko7\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\deps\winpty\src\winpty-agent.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(514,5): error MSB6003:    at Microsoft.Build.Utilities.CanonicalTrackedOutputFiles..ctor(ITaskItem[] tlogFiles) [C:\Users\Priyanka\AppData\Local\Temp\apm-install-dir-2020922-3304-11rftjx.mko7\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\deps\winpty\src\winpty-agent.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(514,5): error MSB6003:    at Microsoft.Build.CPPTasks.CL.PostExecuteTool(Int32 exitCode) [C:\Users\Priyanka\AppData\Local\Temp\apm-install-dir-2020922-3304-11rftjx.mko7\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\deps\winpty\src\winpty-agent.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(514,5): error MSB6003:    at Microsoft.Build.CPPTasks.TrackedVCToolTask.ExecuteTool(String pathToTool, String responseFileCommands, String commandLineCommands) [C:\Users\Priyanka\AppData\Local\Temp\apm-install-dir-2020922-3304-11rftjx.mko7\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\deps\winpty\src\winpty-agent.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(514,5): error MSB6003:    at Microsoft.Build.Utilities.ToolTask.Execute() [C:\Users\Priyanka\AppData\Local\Temp\apm-install-dir-2020922-3304-11rftjx.mko7\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\deps\winpty\src\winpty-agent.vcxproj]

prebuild-install WARN install No prebuilt binaries found (target=6.1.12 runtime=electron arch=x64 libc= platform=win32)
gyp ERR! build error 
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Priyanka\AppData\Local\atom\app-1.52.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:200:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Users\\Priyanka\\AppData\\Local\\atom\\app-1.52.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Priyanka\\AppData\\Local\\atom\\app-1.52.0\\resources\\app\\apm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Priyanka\AppData\Local\Temp\apm-install-dir-2020922-3304-11rftjx.mko7\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch
gyp ERR! node -v v12.4.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\Priyanka\AppData\Local\Temp\apm-install-dir-2020922-3304-11rftjx.mko7\package.json'
npm WARN apm-install-dir-2020922-3304-11rftjx.mko7 No description
npm WARN apm-install-dir-2020922-3304-11rftjx.mko7 No repository field.
npm WARN apm-install-dir-2020922-3304-11rftjx.mko7 No README data
npm WARN apm-install-dir-2020922-3304-11rftjx.mko7 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-pty-prebuilt-multiarch@0.9.0-beta21.legacy install: `prebuild-install || node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-pty-prebuilt-multiarch@0.9.0-beta21.legacy install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Priyanka\.atom\.apm\_logs\2020-10-22T11_31_46_668Z-debug.log

**Comment by ryanxu168** [comment]
Same here. It threw errors so I uninstalled it. Then it's unable to install. 

apm  v2.5.2
Atom v1.52.0
macOS Catalina v10.15.7

**Comment by the-j0k3r** [comment]
https://atom.io/packages/terminus
