### ISSUE TITLE
cant install the package in atom 

### ISSUE THREAD

**Issue by ajsharma76** [platformio/platformio-atom-ide-terminal#929]
- [x ] I have reset Atom to defaults prior to submitting report.
- [ ] I have not reset Atom to defaults prior to submitting report.
### Description

error outs. doesnt install the package

### Steps to reproduce

1.
2.
3.

**Expected behavior:** 

download package 
**Actual behavior:** 
errors out. doesnt install

**Reproduces how often:** 

### Versions

```
> atom --version

```1.52.0
```
> apm --version

```sorry, dont know what it is.

OS name and version: windows 365
Platformio-ide-terminal version:
10.2.0

### Additional Information
<!-- Add any additional information like screenshots, gif captures,
configuration, data or other Atom package lists, that might be necessary to reproduce the issue. -->

**Comment by the-j0k3r** [comment]
https://atom.io/packages/terminus

**Comment by ivankravets** [comment]
Fixed in https://github.com/platformio/platformio-atom-ide-terminal/releases/tag/v2.10.1

Please update `platformio-ide-terminal` to the latest version.
