### ISSUE TITLE
Pushed files/folder colour in tree-view

### ISSUE THREAD

**Issue by Austinrea** [platformio/platformio-atom-ide-terminal#93]
A small feature that doesn't seem to be working:

When I push my files through this built in terminal, my files in Atom's tree-view are still coloured orange as if they haven't been pushed.

When I use my "external" terminal, atom automatically recognises this and reverts the files/folders to original colours.

**Comment by the-j0k3r** [comment]
Please retest again with platformio-atom-ide-terminal 2.9.0 is using node-pty-prebuilt instead unmaintained and outdated pty.js
