### ISSUE TITLE
Current version incompatible when upgrading to Atom 1.52.0 on MacOS 10.15.7 

### ISSUE THREAD

**Issue by bill-tulskie** [platformio/platformio-atom-ide-terminal#932]
- [ X] I have reset Atom to defaults prior to submitting report.
- [ ] I have not reset Atom to defaults prior to submitting report.
### Description

After upgrading to Atom 1.52.0 on Mac, platformio-atom-ide-terminal shows up as a bug. The error indicates that it was compiled for a prior version.  Compilation fails. Uninstall works.  Reinstall fails.

OS name and version:
macOS Catalina 10.15.7

Platformio-ide-terminal version: 2.10.0

**Comment by the-j0k3r** [comment]
reinstall package else try https://atom.io/packages/terminus
