### ISSUE TITLE
I am currently unable to install platformio-ide-terminal on atom

### ISSUE THREAD

**Issue by abdulmalikadebayo** [platformio/platformio-atom-ide-terminal#933]
- [ x] I have reset Atom to defaults prior to submitting report.
- [ x] I have not reset Atom to defaults prior to submitting report.
<I am currently unable to install platformio-ide-terminal on atom because it is showing:

 npm ERR! code Z_BUF_ERROR
npm ERR! errno -5
npm ERR! zlib: unexpected end of file

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Dell\.atom\.apm\_logs\2020-10-24T04_38_55_927Z-debug.log>
```

> atom --version:atom 1.52.0

```
![Screenshot (25)](https://user-images.githubusercontent.com/65060993/97068093-50e2ae00-15bc-11eb-9d81-1657b94449fc.png)

```
> apm --version: apm  2.5.2

```
OS name and version: windows 10
Platformio-ide-terminal version:

**Comment by ivankravets** [comment]
Fixed in https://github.com/platformio/platformio-atom-ide-terminal/releases/tag/v2.10.1

Please update `platformio-ide-terminal` to the latest version.
