### ISSUE TITLE
platformio-ide-terminal won't install

### ISSUE THREAD

**Issue by Sha-byte** [platformio/platformio-atom-ide-terminal#942]
- [ x] I have reset Atom to defaults prior to submitting report.
- [ ] I have not reset Atom to defaults prior to submitting report.
### Description

I am clicking on install but nothing happens and the error "Installing “platformio-ide-terminal@2.10.0” failed comes up in atom

### Steps to reproduce

1.
2.
3.

**Expected behavior:** 

**Actual behavior:** 

**Reproduces how often:** 

### Versions

```
> atom --version

```
```
> apm --version

```
OS name and version: macOS Catalina 10.15.6

Platformio-ide-terminal version: 2.10.0

### Additional Information

<img width="1280" alt="Skärmavbild 2020-10-28 kl  15 55 52" src="https://user-images.githubusercontent.com/73599622/97453494-15d2d880-1936-11eb-8d18-85a50cb9373f.png">

**Comment by derickmoncado** [comment]
Having the same issue

**Comment by giipark** [comment]
It was not installed in the latest version, so I received the 1.49 version. It installs well.

**Comment by the-j0k3r** [comment]
try https://atom.io/packages/terminus

**Comment by ivankravets** [comment]
Fixed in https://github.com/platformio/platformio-atom-ide-terminal/releases/tag/v2.10.1

Please update `platformio-ide-terminal` to the latest version.
