### ISSUE TITLE
platformio-ide-terminal 2.10.0 won't download on my windows hp

### ISSUE THREAD

**Issue by wizcudi** [platformio/platformio-atom-ide-terminal#943]
- [ x] I have reset Atom to defaults prior to submitting report.
- [ ] I have not reset Atom to defaults prior to submitting report.
### Description

When I type install,  a red circular stop sign appears.  The install button starts to load but then it stops.

### Steps to reproduce

1. open atom
2. search for 
3.download platformio-ide-terminal 2.10.0

**Expected behavior:** 
I expected the program to download so i can start using python

**Actual behavior:** 
When I type install,  a red circular stop sign appears.  The install button starts to load but then it stops.

**Reproduces how often:** 
What do you mean? this is the first time that i am trying to download this.

### Versions

```
> atom --version
AtomSetup-x64
```
```
> apm --version
platformio-ide-terminal 2.10.0
```
OS name and version:
Platformio-ide-terminal version:
Windows

**Comment by the-j0k3r** [comment]
Nothing to do with the package, Atom addons server issues at best.
