### ISSUE TITLE
terminal installation failed 

### ISSUE THREAD

**Issue by meghanalaxmi** [platformio/platformio-atom-ide-terminal#950]
- [ ] I have reset Atom to defaults prior to submitting report.
- [x] I have not reset Atom to defaults prior to submitting report.
### Description

i have just installed atom and trying to install ide terminal to learn python
ide terminal is not getting installed by showing the following message. plz help me out thank you.
![Screenshot (1)](https://user-images.githubusercontent.com/21291119/97803087-c827da00-1c6d-11eb-999c-bcb60bedb69b.png)

### Steps to reproduce

1.
2.
3.

**Expected behavior:** 

**Actual behavior:** 

**Reproduces how often:** 

### Versions

```
> atom --version 1.52.0

```
```
> apm --version

```
OS name and version: windows 10 
Platformio-ide-terminal version: 2.10.0

**Comment by trymeouteh** [comment]
I am having the same issue with a fresh install of Atom on Windows 10

**Comment by UziTech** [comment]
This package is no longer maintained. Please uninstall platformio-ide-terminal and install either [terminus](https://atom.io/packages/terminus) or [x-terminal](https://atom.io/packages/x-terminal)

**Comment by ivankravets** [comment]
Fixed in https://github.com/platformio/platformio-atom-ide-terminal/releases/tag/v2.10.1

Please update `platformio-ide-terminal` to the latest version.
