### ISSUE TITLE
not able to install platformio-ide-terminal

### ISSUE THREAD

**Issue by RAHUL6109736** [platformio/platformio-atom-ide-terminal#951]
- [ ] I have reset Atom to defaults prior to submitting report.
- [ x] I have not reset Atom to defaults prior to submitting report.
### Steps to reproduce

1.
2.
3.

**Expected behavior:**  to install platformio-ide-terminal

**Actual behavior:** but it did not install

**Reproduces how often:** 

### Versions

```
> atom --version

```
```
> apm --version

```
OS name and version:
Platformio-ide-terminal version: window 10 ,8Gen,dell G3 15

**Comment by trymeouteh** [comment]
I am having the same issue with a fresh install of Atom on Windows 10

**Comment by UziTech** [comment]
This package is no longer maintained. Please uninstall platformio-ide-terminal and install either [terminus](https://atom.io/packages/terminus) or [x-terminal](https://atom.io/packages/x-terminal)

**Comment by ivankravets** [comment]
Fixed in https://github.com/platformio/platformio-atom-ide-terminal/releases/tag/v2.10.1

Please update `platformio-ide-terminal` to the latest version.
