### ISSUE TITLE
Packages installation

### ISSUE THREAD

**Issue by Debasish2590** [platformio/platformio-atom-ide-terminal#952]
Respected sir,
                     I could not install platform-ide-terminal packages. when i install atom , it does not show in my laptop all programs. i 
                     think that is the reason for packages not install  properly.

Please help me. I am waiting for your response.

**Comment by ivankravets** [comment]
Fixed in https://github.com/platformio/platformio-atom-ide-terminal/releases/tag/v2.10.1

Please update `platformio-ide-terminal` to the latest version.
