### ISSUE TITLE
BUG in the installation of (platformio-ide-terminal)

### ISSUE THREAD

**Issue by samfreitasxs** [platformio/platformio-atom-ide-terminal#966]
![bug na instalação do pacote](https://user-images.githubusercontent.com/37847692/98861954-dda6bc00-2444-11eb-9396-3aed2229e944.png)

**Comment by UziTech** [comment]
This package is no longer maintained. Please uninstall platformio-ide-terminal and install either [terminus](https://atom.io/packages/terminus) or [x-terminal](https://atom.io/packages/x-terminal)

**Comment by ivankravets** [comment]
Fixed in https://github.com/platformio/platformio-atom-ide-terminal/releases/tag/v2.10.1

Please update `platformio-ide-terminal` to the latest version.
