### ISSUE TITLE
not installing on Big Sur MacOs

### ISSUE THREAD

**Issue by dxbFORCE** [platformio/platformio-atom-ide-terminal#967]
- [ ] I have reset Atom to defaults prior to submitting report.
- [ ] I have not reset Atom to defaults prior to submitting report.
### Steps to reproduce

1.
2.
3.

**Expected behavior:** 

**Actual behavior:** 

**Reproduces how often:** 

### Versions

```
> atom --version

```
```
> apm --version

```
OS name and version:
Platformio-ide-terminal version:

**Comment by legato0** [comment]
https://allanphilipbarku.medium.com/gyp-no-xcode-or-clt-version-detected-macos-big-sur-anansewaa-com-7fe936ee1623
The "Second" solution worked for me.
(You need rebuild package after that)

**Comment by UziTech** [comment]
see https://github.com/platformio/platformio-atom-ide-terminal/issues/543#issuecomment-678979080

**Comment by ivankravets** [comment]
Fixed in https://github.com/platformio/platformio-atom-ide-terminal/releases/tag/v2.10.1

Please update `platformio-ide-terminal` to the latest version.
