### ISSUE TITLE
hello i am facing problem while installing platform ide terminal in my package

### ISSUE THREAD

**Issue by Suraj4931** [platformio/platformio-atom-ide-terminal#973]
- [ ] I have reset Atom to defaults prior to submitting report.
- [x] I have not reset Atom to defaults prior to submitting report.
### Steps to reproduce

1.
2.
3.

**Expected behavior:** 

**Actual behavior:** 

**Reproduces how often:** 

### Versions

```
> atom --version

```
```
> apm --version

```
OS name and version:
Platformio-ide-terminal version:

**Comment by Suraj4931** [comment]
![Desktop Screenshot 2020 11 21 - 19 27 49 99](https://user-images.githubusercontent.com/74195930/99892985-004c8800-2c30-11eb-8593-887e9ef3b506.png)
its failing every time

**Comment by UziTech** [comment]
This package is not maintained see https://github.com/platformio/platformio-atom-ide-terminal/issues/543#issuecomment-678979080

**Comment by Suraj4931** [comment]
So what should I do

**Comment by UziTech** [comment]
install a different terminal as mentioned in https://github.com/platformio/platformio-atom-ide-terminal/issues/543#issuecomment-678979080

**Comment by shavalibadvel** [comment]
but that terminal doesn't providing new terminal

**Comment by UziTech** [comment]
which one?

**Comment by ivankravets** [comment]
Fixed in https://github.com/platformio/platformio-atom-ide-terminal/releases/tag/v2.10.1

Please update `platformio-ide-terminal` to the latest version.
