### ISSUE TITLE
Unable to install on atom 1.53 and OSX Big Sur

### ISSUE THREAD

**Issue by mattbellme** [platformio/platformio-atom-ide-terminal#982]
- [ x] I have reset Atom to defaults prior to submitting report.
- [ ] I have not reset Atom to defaults prior to submitting report.
### Description

Cant install after updating to big sur

> node-pty-prebuilt-multiarch@0.9.0-beta21.legacy install /private/var/folders/_s/635yymmd0p1gtbrjwlzv7wlw0000gp/T/apm-install-dir-20201027-8704-1mns91n.hw14m/node_modules/platformio-ide-terminal/node_modules/node-pty-prebuilt-multiarch
> prebuild-install || node scripts/install.js

prebuild-install WARN install No prebuilt binaries found (target=6.1.12 runtime=electron arch=x64 libc= platform=darwin)
No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:200:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 20.1.0
gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/var/folders/_s/635yymmd0p1gtbrjwlzv7wlw0000gp/T/apm-install-dir-20201027-8704-1mns91n.hw14m/node_modules/platformio-ide-terminal/node_modules/node-pty-prebuilt-multiarch
gyp ERR! node -v v12.4.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/private/var/folders/_s/635yymmd0p1gtbrjwlzv7wlw0000gp/T/apm-install-dir-20201027-8704-1mns91n.hw14m/package.json'
npm WARN apm-install-dir-20201027-8704-1mns91n.hw14m No description
npm WARN apm-install-dir-20201027-8704-1mns91n.hw14m No repository field.
npm WARN apm-install-dir-20201027-8704-1mns91n.hw14m No README data
npm WARN apm-install-dir-20201027-8704-1mns91n.hw14m No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-pty-prebuilt-multiarch@0.9.0-beta21.legacy install: `prebuild-install || node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-pty-prebuilt-multiarch@0.9.0-beta21.legacy install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/matt/.atom/.apm/_logs/2020-11-26T20_45_16_601Z-debug.log

### Steps to reproduce

1.
2.
3.

**Expected behavior:** 
install sucessful

**Actual behavior:** 
eroor message

**Reproduces how often:** 
100%

### Versions

```
> atom --version
1.53.0
```
```
> apm --version
2.5.2
```
OS name and version:big sur 11.0.1
Platformio-ide-terminal version:n/a trying latestinstall

**Comment by UziTech** [comment]
This package is no longer maintained. Please uninstall platformio-ide-terminal and install either [terminus](https://atom.io/packages/terminus) or [x-terminal](https://atom.io/packages/x-terminal)

**Comment by ivankravets** [comment]
Fixed in https://github.com/platformio/platformio-atom-ide-terminal/releases/tag/v2.10.1

Please update to the latest version.
