### ISSUE TITLE
platformio-ide-terminal unable to install

### ISSUE THREAD

**Issue by Devanand-Vadlapudi** [platformio/platformio-atom-ide-terminal#983]
- [x] I have reset Atom to defaults prior to submitting report.
- [ ] I have not reset Atom to defaults prior to submitting report.
### Description

First my terminal was not opening so I've re-installed entire Atom again but now I'm even unable to install platformio-ide-terminal and is showing a huge error.

### Steps to reproduce

1.
2.
3.

**Expected behavior:** 

**Actual behavior:** 

**Reproduces how often:** 

### Versions

```
> atom --version

```
```
> apm --version

```
OS name and version:
Platformio-ide-terminal version:

**Comment by UziTech** [comment]
This package is no longer maintained. Please uninstall platformio-ide-terminal and install either [terminus](https://atom.io/packages/terminus) or [x-terminal](https://atom.io/packages/x-terminal)

**Comment by Devanand-Vadlapudi** [comment]
> This package is no longer maintained. Please uninstall platformio-ide-terminal and install either [terminus](https://atom.io/packages/terminus) or [x-terminal](https://atom.io/packages/x-terminal)

Thanks!!! Now it works:)

**Comment by ivankravets** [comment]
Fixed in https://github.com/platformio/platformio-atom-ide-terminal/releases/tag/v2.10.1

Please update to the latest version.
