### ISSUE TITLE
No installatino possible without VS (???) which I don't want or need and even after it is not finding 

### ISSUE THREAD

**Issue by JuliaS-L1** [platformio/platformio-atom-ide-terminal#984]
- [X] I have reset Atom to defaults prior to submitting report.
- [ ] I have not reset Atom to defaults prior to submitting report.
### Steps to reproduce

1. install atom
2. install platformio-ide-terminal through settings -> install

**Expected behavior:** 
package to be installed

**Actual behavior:** 
error

**Reproduces how often:** 
100%, 7-8 attempts

### Versions

```
> atom --version

```
```
> apm --version

```
OS name and version:
Platformio-ide-terminal version:

### Additional Information

Installing “platformio-ide-terminal@2.10.0” failed.Hide output…

> node-pty-prebuilt-multiarch@0.9.0-beta21.legacy install C:\Users\JULIA~1.SCH\AppData\Local\Temp\apm-install-dir-20201027-14136-1gq2x70.k6ksh\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch
> prebuild-install || node scripts/install.js

C:\Users\JULIA~1.SCH\AppData\Local\Temp\apm-install-dir-20201027-14136-1gq2x70.k6ksh\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch>if not defined npm_config_node_gyp (node "C:\Users\julia.schmidt\AppData\Local\atom\app-1.53.0\resources\app\apm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\julia.schmidt\AppData\Local\atom\app-1.53.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 
Building the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(495,5): warning MSB8029: The Intermediate directory or Output directory cannot reside under the Temporary directory as it could lead to issues with incremental build. [C:\Users\JULIA~1.SCH\AppData\Local\Temp\apm-install-dir-20201027-14136-1gq2x70.k6ksh\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\conpty.vcxproj]
  conpty.cc
  path_util.cc
  win_delay_load_hook.cc
C:\Users\julia.schmidt\AppData\Local\node-gyp\Cache\6.1.12\include\node\v8.h(8205,1): warning C4996: 'v8::MicrotasksCompletedCallback': was declared deprecated (compiling source file ..\src\win\path_util.cc) [C:\Users\JULIA~1.SCH\AppData\Local\Temp\apm-install-dir-20201027-14136-1gq2x70.k6ksh\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\conpty.vcxproj]
C:\Users\julia.schmidt\AppData\Local\node-gyp\Cache\6.1.12\include\node\v8.h(8214,1): warning C4996: 'v8::MicrotasksCompletedCallback': was declared deprecated (compiling source file ..\src\win\path_util.cc) [C:\Users\JULIA~1.SCH\AppData\Local\Temp\apm-install-dir-20201027-14136-1gq2x70.k6ksh\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\conpty.vcxproj]
C:\Users\julia.schmidt\AppData\Local\node-gyp\Cache\6.1.12\include\node\v8.h(8205,1): warning C4996: 'v8::MicrotasksCompletedCallback': was declared deprecated (compiling source file ..\src\win\conpty.cc) [C:\Users\JULIA~1.SCH\AppData\Local\Temp\apm-install-dir-20201027-14136-1gq2x70.k6ksh\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\conpty.vcxproj]
C:\Users\julia.schmidt\AppData\Local\node-gyp\Cache\6.1.12\include\node\v8.h(8214,1): warning C4996: 'v8::MicrotasksCompletedCallback': was declared deprecated (compiling source file ..\src\win\conpty.cc) [C:\Users\JULIA~1.SCH\AppData\Local\Temp\apm-install-dir-20201027-14136-1gq2x70.k6ksh\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\conpty.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(1341,5): warning MSB8012: TargetPath(C:\Users\JULIA~1.SCH\AppData\Local\Temp\apm-install-dir-20201027-14136-1gq2x70.k6ksh\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\Release\\conpty.node) does not match the Linker's OutputFile property value (C:\Users\JULIA~1.SCH\AppData\Local\Temp\apm-install-dir-20201027-14136-1gq2x70.k6ksh\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\Release\conpty.node). This may cause your project to build incorrectly. To correct this, please make sure that $(OutDir), $(TargetName) and $(TargetExt) property values match the value specified in %(Link.OutputFile). [C:\Users\JULIA~1.SCH\AppData\Local\Temp\apm-install-dir-20201027-14136-1gq2x70.k6ksh\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\conpty.vcxproj]
     Creating library C:\Users\JULIA~1.SCH\AppData\Local\Temp\apm-install-dir-20201027-14136-1gq2x70.k6ksh\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\Release\conpty.lib and object C:\Users\JULIA~1.SCH\AppData\Local\Temp\apm-install-dir-20201027-14136-1gq2x70.k6ksh\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\Release\conpty.exp
  Generating code
  Previous IPDB not found, fall back to full compilation.
  All 942 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.
  Finished generating code
  conpty.vcxproj -> C:\Users\JULIA~1.SCH\AppData\Local\Temp\apm-install-dir-20201027-14136-1gq2x70.k6ksh\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\Release\\conpty.node
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(495,5): warning MSB8029: The Intermediate directory or Output directory cannot reside under the Temporary directory as it could lead to issues with incremental build. [C:\Users\JULIA~1.SCH\AppData\Local\Temp\apm-install-dir-20201027-14136-1gq2x70.k6ksh\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\conpty_console_list.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(354,5): error MSB3491: Could not write lines to file "Release\obj\conpty_console_list\conpty_c.0D0AC6CE.tlog\conpty_console_list.lastbuildstate". Could not find a part of the path 'C:\Users\julia.schmidt\AppData\Local\Temp\apm-install-dir-20201027-14136-1gq2x70.k6ksh\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\Release\obj\conpty_console_list\conpty_c.0D0AC6CE.tlog\conpty_console_list.lastbuildstate'. [C:\Users\JULIA~1.SCH\AppData\Local\Temp\apm-install-dir-20201027-14136-1gq2x70.k6ksh\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\conpty_console_list.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(495,5): warning MSB8029: The Intermediate directory or Output directory cannot reside under the Temporary directory as it could lead to issues with incremental build. [C:\Users\JULIA~1.SCH\AppData\Local\Temp\apm-install-dir-20201027-14136-1gq2x70.k6ksh\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\deps\winpty\src\winpty.vcxproj]
  AgentLocation.cc
  winpty.cc
  BackgroundDesktop.cc
  Buffer.cc
  DebugClient.cc
  GenRandom.cc
  OwnedHandle.cc
  StringUtil.cc
  WindowsSecurity.cc
  WindowsVersion.cc
  WinptyAssert.cc
  WinptyException.cc
  WinptyVersion.cc
  win_delay_load_hook.cc
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(1341,5): warning MSB8012: TargetPath(C:\Users\JULIA~1.SCH\AppData\Local\Temp\apm-install-dir-20201027-14136-1gq2x70.k6ksh\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\Release\\winpty.dll) does not match the Linker's OutputFile property value (C:\Users\JULIA~1.SCH\AppData\Local\Temp\apm-install-dir-20201027-14136-1gq2x70.k6ksh\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\Release\winpty.dll). This may cause your project to build incorrectly. To correct this, please make sure that $(OutDir), $(TargetName) and $(TargetExt) property values match the value specified in %(Link.OutputFile). [C:\Users\JULIA~1.SCH\AppData\Local\Temp\apm-install-dir-20201027-14136-1gq2x70.k6ksh\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\deps\winpty\src\winpty.vcxproj]
     Creating library C:\Users\JULIA~1.SCH\AppData\Local\Temp\apm-install-dir-20201027-14136-1gq2x70.k6ksh\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\Release\winpty.lib and object C:\Users\JULIA~1.SCH\AppData\Local\Temp\apm-install-dir-20201027-14136-1gq2x70.k6ksh\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\Release\winpty.exp
  Generating code
  Previous IPDB not found, fall back to full compilation.
  All 1032 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.
  Finished generating code
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(1010,5): error MSB6003: The specified task executable "link.exe" could not be run. System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\julia.schmidt\AppData\Local\Temp\apm-install-dir-20201027-14136-1gq2x70.k6ksh\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\deps\winpty\src\Release\obj\winpty\winpty.tlog'. [C:\Users\JULIA~1.SCH\AppData\Local\Temp\apm-install-dir-20201027-14136-1gq2x70.k6ksh\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\deps\winpty\src\winpty.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(1010,5): error MSB6003:    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath) [C:\Users\JULIA~1.SCH\AppData\Local\Temp\apm-install-dir-20201027-14136-1gq2x70.k6ksh\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\deps\winpty\src\winpty.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(1010,5): error MSB6003:    at System.IO.FileSystemEnumerableIterator`1.CommonInit() [C:\Users\JULIA~1.SCH\AppData\Local\Temp\apm-install-dir-20201027-14136-1gq2x70.k6ksh\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\deps\winpty\src\winpty.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(1010,5): error MSB6003:    at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost) [C:\Users\JULIA~1.SCH\AppData\Local\Temp\apm-install-dir-20201027-14136-1gq2x70.k6ksh\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\deps\winpty\src\winpty.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(1010,5): error MSB6003:    at System.IO.Directory.GetFiles(String path, String searchPattern) [C:\Users\JULIA~1.SCH\AppData\Local\Temp\apm-install-dir-20201027-14136-1gq2x70.k6ksh\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\deps\winpty\src\winpty.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(1010,5): error MSB6003:    at Microsoft.Build.Utilities.TrackedDependencies.ExpandWildcards(ITaskItem[] expand) [C:\Users\JULIA~1.SCH\AppData\Local\Temp\apm-install-dir-20201027-14136-1gq2x70.k6ksh\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\deps\winpty\src\winpty.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(1010,5): error MSB6003:    at Microsoft.Build.Utilities.CanonicalTrackedOutputFiles.InternalConstruct(ITask ownerTask, ITaskItem[] tlogFiles, Boolean constructOutputsFromTLogs) [C:\Users\JULIA~1.SCH\AppData\Local\Temp\apm-install-dir-20201027-14136-1gq2x70.k6ksh\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\deps\winpty\src\winpty.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(1010,5): error MSB6003:    at Microsoft.Build.CPPTasks.TrackedVCToolTask.PostExecuteTool(Int32 exitCode) [C:\Users\JULIA~1.SCH\AppData\Local\Temp\apm-install-dir-20201027-14136-1gq2x70.k6ksh\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\deps\winpty\src\winpty.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(1010,5): error MSB6003:    at Microsoft.Build.CPPTasks.TrackedVCToolTask.ExecuteTool(String pathToTool, String responseFileCommands, String commandLineCommands) [C:\Users\JULIA~1.SCH\AppData\Local\Temp\apm-install-dir-20201027-14136-1gq2x70.k6ksh\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\deps\winpty\src\winpty.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(1010,5): error MSB6003:    at Microsoft.Build.Utilities.ToolTask.Execute() [C:\Users\JULIA~1.SCH\AppData\Local\Temp\apm-install-dir-20201027-14136-1gq2x70.k6ksh\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\deps\winpty\src\winpty.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(495,5): warning MSB8029: The Intermediate directory or Output directory cannot reside under the Temporary directory as it could lead to issues with incremental build. [C:\Users\JULIA~1.SCH\AppData\Local\Temp\apm-install-dir-20201027-14136-1gq2x70.k6ksh\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\deps\winpty\src\winpty-agent.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(190,5): error MSB4018: The "GetOutOfDateItems" task failed unexpectedly. [C:\Users\JULIA~1.SCH\AppData\Local\Temp\apm-install-dir-20201027-14136-1gq2x70.k6ksh\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\deps\winpty\src\winpty-agent.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(190,5): error MSB4018: System.InvalidOperationException: The item metadata "%(FullPath)" cannot be applied to the path "Release\obj\winpty-agent\winpty-agent.tlog\ParallelCustomBuild.write.1.tlog". Path: Release\obj\winpty-agent\winpty-agent.tlog\ParallelCustomBuild.write.1.tlog exceeds the OS max path limit. The fully qualified file name must be less than 260 characters. [C:\Users\JULIA~1.SCH\AppData\Local\Temp\apm-install-dir-20201027-14136-1gq2x70.k6ksh\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\deps\winpty\src\winpty-agent.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(190,5): error MSB4018:    at Microsoft.Build.Shared.ErrorUtilities.ThrowInvalidOperation(String resourceName, Object[] args) [C:\Users\JULIA~1.SCH\AppData\Local\Temp\apm-install-dir-20201027-14136-1gq2x70.k6ksh\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\deps\winpty\src\winpty-agent.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(190,5): error MSB4018:    at Microsoft.Build.Shared.FileUtilities.ItemSpecModifiers.GetItemSpecModifier(String currentDirectory, String itemSpec, String definingProjectEscaped, String modifier, String& fullPath) [C:\Users\JULIA~1.SCH\AppData\Local\Temp\apm-install-dir-20201027-14136-1gq2x70.k6ksh\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\deps\winpty\src\winpty-agent.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(190,5): error MSB4018:    at Microsoft.Build.Utilities.TaskItem.Microsoft.Build.Framework.ITaskItem2.GetMetadataValueEscaped(String metadataName) [C:\Users\JULIA~1.SCH\AppData\Local\Temp\apm-install-dir-20201027-14136-1gq2x70.k6ksh\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\deps\winpty\src\winpty-agent.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(190,5): error MSB4018:    at Microsoft.Build.Utilities.TaskItem.GetMetadata(String metadataName) [C:\Users\JULIA~1.SCH\AppData\Local\Temp\apm-install-dir-20201027-14136-1gq2x70.k6ksh\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\deps\winpty\src\winpty-agent.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(190,5): error MSB4018:    at Microsoft.Build.CPPTasks.GetOutOfDateItems.Execute() [C:\Users\JULIA~1.SCH\AppData\Local\Temp\apm-install-dir-20201027-14136-1gq2x70.k6ksh\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\deps\winpty\src\winpty-agent.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(190,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [C:\Users\JULIA~1.SCH\AppData\Local\Temp\apm-install-dir-20201027-14136-1gq2x70.k6ksh\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\deps\winpty\src\winpty-agent.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(190,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext() [C:\Users\JULIA~1.SCH\AppData\Local\Temp\apm-install-dir-20201027-14136-1gq2x70.k6ksh\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\deps\winpty\src\winpty-agent.vcxproj]

prebuild-install WARN install No prebuilt binaries found (target=6.1.12 runtime=electron arch=x64 libc= platform=win32)
gyp ERR! build error 
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\julia.schmidt\AppData\Local\atom\app-1.53.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:200:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Windows_NT 10.0.19041
gyp ERR! command "C:\\Users\\julia.schmidt\\AppData\\Local\\atom\\app-1.53.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\julia.schmidt\\AppData\\Local\\atom\\app-1.53.0\\resources\\app\\apm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\JULIA~1.SCH\AppData\Local\Temp\apm-install-dir-20201027-14136-1gq2x70.k6ksh\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch
gyp ERR! node -v v12.4.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\JULIA~1.SCH\AppData\Local\Temp\apm-install-dir-20201027-14136-1gq2x70.k6ksh\package.json'
npm WARN apm-install-dir-20201027-14136-1gq2x70.k6ksh No description
npm WARN apm-install-dir-20201027-14136-1gq2x70.k6ksh No repository field.
npm WARN apm-install-dir-20201027-14136-1gq2x70.k6ksh No README data
npm WARN apm-install-dir-20201027-14136-1gq2x70.k6ksh No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-pty-prebuilt-multiarch@0.9.0-beta21.legacy install: `prebuild-install || node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-pty-prebuilt-multiarch@0.9.0-beta21.legacy install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\julia.schmidt\.atom\.apm\_logs\2020-11-27T19_33_30_605Z-debug.log

**Comment by UziTech** [comment]
This package is no longer maintained. Please uninstall platformio-ide-terminal and install either [terminus](https://atom.io/packages/terminus) or [x-terminal](https://atom.io/packages/x-terminal)
