### ISSUE TITLE
Installing “platformio-ide-terminal produces the error message below.

### ISSUE THREAD

**Issue by ask4soteria** [platformio/platformio-atom-ide-terminal#988]
- [ x] I have reset Atom to defaults prior to submitting report.
- [ ] I have not reset Atom to defaults prior to submitting report.
### Description

Installing “platformio-ide-terminal produces the error message below.

Installing “platformio-ide-terminal@2.10.0” failed.Hide output…

> node-pty-prebuilt-multiarch@0.9.0-beta21.legacy install /private/var/folders/20/pgllz42x5rn7tpqdn_k16pfr0000gp/T/apm-install-dir-2020114-87864-e1eqd3.xxw2/node_modules/platformio-ide-terminal/node_modules/node-pty-prebuilt-multiarch
> prebuild-install || node scripts/install.js

prebuild-install WARN install No prebuilt binaries found (target=6.1.12 runtime=electron arch=x64 libc= platform=darwin)
No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:200:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 19.6.0
gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/var/folders/20/pgllz42x5rn7tpqdn_k16pfr0000gp/T/apm-install-dir-2020114-87864-e1eqd3.xxw2/node_modules/platformio-ide-terminal/node_modules/node-pty-prebuilt-multiarch
gyp ERR! node -v v12.4.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/private/var/folders/20/pgllz42x5rn7tpqdn_k16pfr0000gp/T/apm-install-dir-2020114-87864-e1eqd3.xxw2/package.json'
npm WARN apm-install-dir-2020114-87864-e1eqd3.xxw2 No description
npm WARN apm-install-dir-2020114-87864-e1eqd3.xxw2 No repository field.
npm WARN apm-install-dir-2020114-87864-e1eqd3.xxw2 No README data
npm WARN apm-install-dir-2020114-87864-e1eqd3.xxw2 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-pty-prebuilt-multiarch@0.9.0-beta21.legacy install: `prebuild-install || node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-pty-prebuilt-multiarch@0.9.0-beta21.legacy install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Uju/.atom/.apm/_logs/2020-12-04T17_14_38_466Z-debug.log

### Steps to reproduce

1.
2.
3.

**Expected behavior:** 

**Actual behavior:** 

**Reproduces how often:** 

### Versions

```
> atom --version 
Atom    : 1.53.0
```
```
> apm --version
apm  2.5.2
```
OS name and version: macOS Catalina version 10.15.7
Platformio-ide-terminal version:
2.7.2

**Comment by UziTech** [comment]
This package is no longer maintained. Please uninstall platformio-ide-terminal and install either [terminus](https://atom.io/packages/terminus) or [x-terminal](https://atom.io/packages/x-terminal)

**Comment by ask4soteria** [comment]
Thank you so much!

**Comment by ivankravets** [comment]
Fixed in https://github.com/platformio/platformio-atom-ide-terminal/releases/tag/v2.10.1

Please update to the latest version.
