### ISSUE TITLE
Upgrade this package!!!

### ISSUE THREAD

**Issue by Nazmulho71** [platformio/platformio-atom-ide-terminal#997]
I can't install it on Atom. Plz, upgrade this package!

**Comment by UziTech** [comment]
This package is no longer maintained. Please uninstall platformio-ide-terminal and install either [terminus](https://atom.io/packages/terminus) or [x-terminal](https://atom.io/packages/x-terminal)

**Comment by Nazmulho71** [comment]
> This package is no longer maintained. Please uninstall platformio-ide-terminal and install either [terminus](https://atom.io/packages/terminus) or [x-terminal](https://atom.io/packages/x-terminal)

I tried this too but it's not working!

**Comment by UziTech** [comment]
If [terminus](https://github.com/bus-stop/terminus) or [x-terminal](https://github.com/bus-stop/x-terminal) are not working you should create issues on those repos.

**Comment by Nazmulho71** [comment]
Ok. Thank you for your reply!
